/*
 * Copyright (C) 1994-2020 Altair Engineering, Inc.
 * For more information, contact Altair at www.altair.com.
 *
 * This file is part of the PBS Professional ("PBS Pro") software.
 *
 * Open Source License Information:
 *
 * PBS Pro is free software. You can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * PBS Pro is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Commercial License Information:
 *
 * For a copy of the commercial license terms and conditions,
 * go to: (http://www.pbspro.com/UserArea/agreement.html)
 * or contact the Altair Legal Department.
 *
 * Altair’s dual-license business model allows companies, individuals, and
 * organizations to create proprietary derivative works of PBS Pro and
 * distribute them - whether embedded or bundled with other software -
 * under a commercial license agreement.
 *
 * Use of Altair’s trademarks, including but not limited to "PBS™",
 * "PBS Professional®", and "PBS Pro™" and Altair’s logos is subject to Altair's
 * trademark licensing policies.
 *
 */
/**
 * dis_read.c - contains function to read and decode the DIS
 *	encoded requests and replies.
 *
 *	Included public functions are:
 *
 *	decode_wire_CopyFiles
 *	decode_wire_replySvr_inner
 *	decode_wire_replySvr
 *	decode_wire_replySvrTPP
 *	wire_request_read
 *	wire_reply_read
 */

#include <pbs_config.h>   /* the master config generated by configure */

#include <sys/types.h>
#include <stdlib.h>
#include <errno.h>
#include <string.h>
#include <stdio.h>
#include "pbs_transport.h"
#include "libpbs.h"
#include "ifl_internal.h"
#include "list_link.h"
#include "server_limits.h"
#include "attribute.h"
#include "log.h"
#include "pbs_error.h"
#include "credential.h"
#include "batch_request.h"
#include "net_connect.h"


static int decode_wire_CopyFiles(ns(CopyFile_table_t) B, struct rq_cpyfile *pcf);

/* External Global Data */

extern char	*msg_nosupport;

/**
 * @brief
 * 	decode_wire_CopyFiles() - decode a Copy Files Dependency Batch Request
 *
 *	This request is used by the server ONLY.
 *	The rq_cpyfile structure pointed to by pcf must already exist.
 *
 * @param[in] B - copy file table ref from flatbuffer
 * @param[in] pcf - pointer to rq_cpyfile structure
 *
 * @return int
 * @retval 0 - success
 * @retval !0 - error
 */
static int
decode_wire_CopyFiles(ns(CopyFile_table_t) B, struct rq_cpyfile *pcf)
{
	int pair_ct = 0;
	struct rqfpair *ppair = NULL;
	ns(FilePair_vec_t) pairs;
	int i = 0;

	CLEAR_HEAD(pcf->rq_pair);

	strncpy(pcf->rq_jobid, (char *)ns(CopyFile_jobId(B)), PBS_MAXSVRJOBID);
	pcf->rq_jobid[PBS_MAXSVRJOBID + 1] = '\0';

	strncpy(pcf->rq_owner, (char *)ns(CopyFile_owner(B)), PBS_MAXUSER);
	pcf->rq_owner[PBS_MAXUSER + 1] = '\0';

	strncpy(pcf->rq_user, (char *)ns(CopyFile_user(B)), PBS_MAXUSER);
	pcf->rq_user[PBS_MAXUSER + 1] = '\0';

	strncpy(pcf->rq_group, (char *)ns(CopyFile_group(B)), PBS_MAXGRPN);
	pcf->rq_group[PBS_MAXGRPN + 1] = '\0';

	pcf->rq_dir = (int) ns(CopyFile_flags(B));

	pairs = ns(CopyFile_pairs(B));
	pair_ct = (int) ns(FilePair_vec_len(pairs));

	for (i = 0; i < pair_ct; i++) {
		ns(FilePair_table_t) pair = ns(FilePair_vec_at(pairs, i));

		ppair = (struct rqfpair *) calloc(sizeof(struct rqfpair), 1);
		if (ppair == NULL)
			return PBSE_SYSTEM;

		CLEAR_LINK(ppair->fp_link);

		ppair->fp_flag = (int) ns(FilePair_flag(pair));

		ppair->fp_rmt = strdup((char *) ns(FilePair_remote(pair)));
		if (ppair->fp_rmt == NULL) {
			free(ppair);
			return PBSE_SYSTEM;
		}

		ppair->fp_local = strdup((char *) ns(FilePair_local(pair)));
		if (ppair->fp_local == NULL) {
			free(ppair->fp_rmt);
			free(ppair);
			return PBSE_SYSTEM;
		}

		append_link(&(pcf->rq_pair), &(ppair->fp_link), ppair);
	}
	return 0;
}

/**
 * @brief
 * 		decode_wire_replySvr_inner() - decode a Batch Protocol Reply Structure for Server
 *
 *		This routine decodes a batch reply into the form used by server.
 *		The only difference between this and the command version is on status
 *		replies.  For the server,  the attributes are decoded into a list of
 *		server svrattrl structures rather than a commands's attrl.
 *
 * @see
 * 		decode_wire_replySvrTPP
 *
 * @param[in] sock - socket connection from which to read reply
 * @param[in,out] reply - batch_reply structure defined in libpbs.h, it must be allocated
 *					  by the caller.
 *
 * @return int
 * @retval 0 - success
 * @retval -1 - if brp_choice is wrong
 * @retval non-zero - decode failure error from a DIS routine
 */

static int
decode_wire_replySvr_inner(int sock, struct batch_reply *reply)
{
	int		      ct;
	struct brp_select    *psel;
	struct brp_select   **pselx;
	struct brp_status    *pstsvr;
	int		      rc = 0;
	size_t		      txtlen;

	/* next decode code, auxcode and choice (union type identifier) */

	reply->brp_code    = disrsi(sock, &rc);
	if (rc) return rc;
	reply->brp_auxcode = disrsi(sock, &rc);
	if (rc) return rc;
	reply->brp_choice  = disrui(sock, &rc);
	if (rc) return rc;


	switch (reply->brp_choice) {

		case BATCH_REPLY_CHOICE_NULL:
			break;	/* no more to do */

		case BATCH_REPLY_CHOICE_Queue:
		case BATCH_REPLY_CHOICE_RdytoCom:
		case BATCH_REPLY_CHOICE_Commit:
			rc = disrfst(sock, PBS_MAXSVRJOBID+1, reply->brp_un.brp_jid);
			if (rc)
				return (rc);
			break;

		case BATCH_REPLY_CHOICE_Select:

			/* have to get count of number of strings first */

			reply->brp_un.brp_select = NULL;
			pselx = &reply->brp_un.brp_select;
			ct = disrui(sock, &rc);
			if (rc) return rc;

			while (ct--) {
				psel = (struct brp_select *)malloc(sizeof(struct brp_select));
				if (psel == 0) return DIS_NOMALLOC;
				psel->brp_next = NULL;
				psel->brp_jobid[0] = '\0';
				rc = disrfst(sock, PBS_MAXSVRJOBID+1, psel->brp_jobid);
				if (rc) {
					(void)free(psel);
					return rc;
				}
				*pselx = psel;
				pselx = &psel->brp_next;
			}
			break;

		case BATCH_REPLY_CHOICE_Status:

			/* have to get count of number of status objects first */

			CLEAR_HEAD(reply->brp_un.brp_status);
			ct = disrui(sock, &rc);
			if (rc) return rc;

			while (ct--) {
				pstsvr = (struct brp_status *)malloc(sizeof(struct brp_status));
				if (pstsvr == 0) return DIS_NOMALLOC;

				CLEAR_LINK(pstsvr->brp_stlink);
				pstsvr->brp_objname[0] = '\0';
				CLEAR_HEAD(pstsvr->brp_attr);

				pstsvr->brp_objtype = disrui(sock, &rc);
				if (rc == 0) {
					rc = disrfst(sock, PBS_MAXSVRJOBID+1,
						pstsvr->brp_objname);
				}
				if (rc) {
					(void)free(pstsvr);
					return rc;
				}
				append_link(&reply->brp_un.brp_status,
					&pstsvr->brp_stlink, pstsvr);
				rc = decode_wire_svrattrl(sock, &pstsvr->brp_attr);
			}
			break;

		case BATCH_REPLY_CHOICE_Text:

			/* text reply */

		  	reply->brp_un.brp_txt.brp_str = disrcs(sock, &txtlen, &rc);
			reply->brp_un.brp_txt.brp_txtlen = txtlen;
			break;

		case BATCH_REPLY_CHOICE_Locate:

			/* Locate Job Reply */

			rc = disrfst(sock, PBS_MAXDEST+1, reply->brp_un.brp_locate);
			break;

		default:
			return -1;
	}

	return rc;
}

/**
 * @brief
 * 		decode a Batch Protocol Reply Structure for Server
 *
 *  	This routine reads reply over TCP by calling decode_wire_replySvr_inner()
 * 		to read the reply to a batch request. This routine reads the protocol type
 * 		and version before calling decode_wire_replySvr_inner() to read the rest of
 * 		the reply structure.
 *
 * @see
 *		wire_reply_read
 *
 * @param[in] sock - socket connection from which to read reply
 * @param[out] reply - The reply structure to be returned
 *
 * @return Error code
 * @retval 0 - Success
 * @retval !DIS_SUCCESS   - Failure (see pbs_transport.h)
 */
int
decode_wire_replySvr(int sock, struct batch_reply *reply)
{
	int		      rc = 0;
	int		      i;
	/* first decode "header" consisting of protocol type and version */

	i = disrui(sock, &rc);
	if (rc != 0) return rc;
	if (i != PBS_BATCH_PROT_TYPE) return DIS_PROTO;
	i = disrui(sock, &rc);
	if (rc != 0) return rc;
	if (i != PBS_BATCH_PROT_VER) return DIS_PROTO;

	return (decode_wire_replySvr_inner(sock, reply));
}

/**
 * @brief
 *	decode a Batch Protocol Reply Structure for Server over TPP
 *
 *	This routine reads data over TPP by calling decode_wire_replySvr_inner()
 *	to read the reply to a batch request. This routine reads the protocol type
 *	and version before calling decode_wire_replySvr_inner() to read the rest of
 *	the reply structure.
 *
 * @see
 *	wire_reply_read
 *
 * @param[in] sock - socket connection from which to read reply
 * @param[out] reply - The reply structure to be returned
 *
 * @return Error code
 * @retval 0 - Success
 * @retval !DIS_SUCCESS   - Failure (see pbs_transport.h)
 */
int
decode_wire_replySvrTPP(int sock, struct batch_reply *reply)
{
	/* for tpp header has already been read */
	return (decode_wire_replySvr_inner(sock, reply));
}

/**
 * @brief
 * 		Read in an DIS encoded request from the network
 * 		and decodes it:
 *		Read and decode the request into the request structures
 *
 * @see
 * 		process_request and read_fo_request
 *
 * @param[in]		sfds	- the socket descriptor
 * @param[in,out]	request - will contain the decoded request
 *
 * @return int
 * @retval 0 	if request read ok, batch_request pointed to by request is
 *		   updated.
 * @retval -1 	if EOF (no request but no error)
 * @retval >0 	if errors ( a PBSE_ number)
 */

int
wire_request_read(int sfds, struct batch_request *request)
{
	int rc = 0;
	void *buf = NULL;
	size_t bufsz = 0;
	ns(Req_table_t) req;
	ns(Header_table_t) hdr;
	uint16_t proto;

	if (request->istpp)
		set_transport_to_tpp();
	else
		set_transport_to_tcp();

	//FIXME: get loaded buf with size here
	rc = ns(Req_verify_as_root(buf, bufsz));
	if (rc != 0) {
		log_eventf(PBSEVENT_DEBUG, PBS_EVENTCLASS_REQUEST, LOG_DEBUG, __func__,
				"Bad request, errno %d, wire error %d", errno, rc);
		return PBSE_PROTOCOL;
	}

	req = ns(Req_as_root(buf));
	hdr = ns(Req_hdr(req));
	proto = ns(Header_protType(hdr));

	request->rq_type = (int)ns(Header_batchId(hdr));

	strncpy(request->rq_user, (char *)ns(Header_user(hdr)), PBS_MAXUSER);
	request->rq_user[PBS_MAXUSER + 1] = '\0';

	/* Decode the Request Body based on the type */
	switch (request->rq_type) {
		case PBS_BATCH_Connect:
			break;

		case PBS_BATCH_Disconnect:
			return (-1); /* set EOF return */

		case PBS_BATCH_QueueJob:
		case PBS_BATCH_SubmitResv:
			ns(Qjob_table_t) B = (ns(Qjob_table_t)) ns(Req_body(req));

			CLEAR_HEAD(request->rq_ind.rq_queuejob.rq_attr);

			strncpy(request->rq_ind.rq_queuejob.rq_jid, (char *)ns(Qjob_jobId(B)), PBS_MAXSVRJOBID);
			request->rq_ind.rq_queuejob.rq_jid[PBS_MAXSVRJOBID + 1] = '\0';

			strncpy(request->rq_ind.rq_queuejob.rq_destin, (char *)ns(Qjob_destin(B)), PBS_MAXDEST);
			request->rq_ind.rq_queuejob.rq_destin[PBS_MAXDEST + 1] = '\0';

			rc = decode_wire_svrattrl(ns(Qjob_attrs(B)), &(request->rq_ind.rq_queuejob.rq_attr));
			break;

		case PBS_BATCH_JobCred:
			ns(Cred_table_t) B = (ns(Cred_table_t)) ns(Req_body(req));

			request->rq_ind.rq_jobcred.rq_type = (int) ns(Cred_type(B));
			request->rq_ind.rq_jobcred.rq_size = (int) ns(Cred_size(B));

			request->rq_ind.rq_jobcred.rq_data = (char *)malloc(request->rq_ind.rq_jobcred.rq_size + 1);
			if (request->rq_ind.rq_jobcred.rq_data == NULL)
				return PBSE_SYSTEM;
			memcpy(request->rq_ind.rq_jobcred.rq_data, (char *)(ns(Cred_cred(B))), request->rq_ind.rq_jobcred.rq_size);
			request->rq_ind.rq_jobcred.rq_data[request->rq_ind.rq_jobcred.rq_size + 1] = '\0';

			break;

		case PBS_BATCH_UserCred:
			ns(Cred_table_t) B = (ns(Cred_table_t)) ns(Req_body(req));

			request->rq_ind.rq_usercred.rq_type = (int) ns(Cred_type(B));
			request->rq_ind.rq_usercred.rq_size = (int) ns(Cred_size(B));

			strncpy(request->rq_ind.rq_usercred.rq_user, (char *)ns(Cred_user(B)), PBS_MAXUSER);
			request->rq_ind.rq_usercred.rq_user[PBS_MAXUSER + 1] = '\0';

			request->rq_ind.rq_usercred.rq_data = (char *)malloc(request->rq_ind.rq_usercred.rq_size + 1);
			if (request->rq_ind.rq_usercred.rq_data == NULL)
				return PBSE_SYSTEM;
			memcpy(request->rq_ind.rq_usercred.rq_data, (char *)(ns(Cred_data(B))), request->rq_ind.rq_usercred.rq_size);
			request->rq_ind.rq_usercred.rq_data[request->rq_ind.rq_usercred.rq_size + 1] = '\0';

			break;

		case PBS_BATCH_UserMigrate:
			ns(UserMigrate_table_t) B = (ns(UserMigrate_table_t)) ns(Req_body(req));

			strncpy(request->rq_ind.rq_user_migrate.rq_tohost, (char *)ns(UserMigrate_tohost(B)), PBS_MAXHOSTNAME);
			request->rq_ind.rq_user_migrate.rq_tohost[PBS_MAXHOSTNAME + 1] = '\0';
			break;

		case PBS_BATCH_jobscript:
		case PBS_BATCH_MvJobFile:
			ns(JobFile_table_t) B = (ns(JobFile_table_t)) ns(Req_body(req));

			request->rq_ind.rq_jobfile.rq_sequence = (int) ns(JobFile_seq(B));
			request->rq_ind.rq_jobfile.rq_type = (int) ns(JobFile_type(B));
			request->rq_ind.rq_jobfile.rq_size = (long) ns(JobFile_size(B));

			strncpy(request->rq_ind.rq_jobfile.rq_jobid, (char *)ns(JobFile_jobId(B)), PBS_MAXSVRJOBID);
			request->rq_ind.rq_jobfile.rq_jobid[PBS_MAXSVRJOBID + 1] = '\0';

			request->rq_ind.rq_jobfile.rq_data = (char *)malloc(request->rq_ind.rq_jobfile.rq_size + 1);
			if (request->rq_ind.rq_jobfile.rq_data == NULL)
				return PBSE_SYSTEM;
			memcpy(request->rq_ind.rq_jobfile.rq_data, (char *)(ns(Cred_data(B))), request->rq_ind.rq_jobfile.rq_size);
			request->rq_ind.rq_jobfile.rq_data[request->rq_ind.rq_jobfile.rq_size + 1] = '\0';

			break;

		case PBS_BATCH_RdytoCommit:
		case PBS_BATCH_Commit:
		case PBS_BATCH_Rerun:
#ifndef MOM
		case PBS_BATCH_LocateJob:
#endif
			ns(JobId_table_t) B = (ns(JobId_table_t)) ns(Req_body(req));

			strncpy(request->rq_ind.rq_commit, (char *)ns(JobFile_jobId(B)), PBS_MAXSVRJOBID);
			request->rq_ind.rq_commit[PBS_MAXSVRJOBID + 1] = '\0';

			break;

		case PBS_BATCH_DeleteJob:
		case PBS_BATCH_DeleteResv:
		case PBS_BATCH_ResvOccurEnd:
		case PBS_BATCH_HoldJob:
		case PBS_BATCH_ModifyJob:
#ifndef MOM
		case PBS_BATCH_Manager:
		case PBS_BATCH_ReleaseJob:
		case PBS_BATCH_ModifyResv:
#endif
			ns(Manage_table_t) B = (ns(Manage_table_t)) ns(Req_body(req));

			CLEAR_HEAD(request->rq_ind.rq_manager.rq_attr);

			request->rq_ind.rq_manager.rq_cmd = (int) ns(Manage_cmd(B));
			request->rq_ind.rq_manager.rq_objtype = (int) ns(Manage_objType(B));

			strncpy(request->rq_ind.rq_manager.rq_objname, (char *)ns(Manager_objName(B)), PBS_MAXSVRJOBID);
			request->rq_ind.rq_manager.rq_objname[PBS_MAXSVRJOBID + 1] = '\0';

			rc = decode_wire_svrattrl(ns(Manager_attrs(B)), &(request->rq_ind.rq_manager.rq_attr));

			break;

		case PBS_BATCH_MessJob:
			ns(Msg_table_t) B = (ns(Msg_table_t)) ns(Req_body(req));

			request->rq_ind.rq_message.rq_file = (int) ns(Msg_FileInd(B));

			strncpy(request->rq_ind.rq_message.rq_jid, (char *) ns(Msg_jobId(B)), PBS_MAXSVRJOBID);
			request->rq_ind.rq_message.rq_jid[PBS_MAXSVRJOBID + 1] = '\0';

			request->rq_ind.rq_message.rq_text = strdup((char *) ns(Msg_text(B)));
			if (request->rq_ind.rq_message.rq_text == NULL)
				return PBSE_SYSTEM;

			break;

		case PBS_BATCH_Shutdown:
		case PBS_BATCH_FailOver:
			ns(DmnCmd_table_t) B = (ns(DmnCmd_table_t)) ns(Req_body(req));

			request->rq_ind.rq_shutdown = ns(DmnCmd_cmd(B));
			break;

		case PBS_BATCH_SignalJob:
			ns(Signal_table_t) B = (ns(Signal_table_t)) ns(Req_body(req));

			strncpy(request->rq_ind.rq_signal.rq_jid, (char *) ns(Signal_jobId(B)), PBS_MAXSVRJOBID);
			request->rq_ind.rq_signal.rq_jid[PBS_MAXSVRJOBID + 1] = '\0';

			strncpy(request->rq_ind.rq_signal.rq_signame, (char *) ns(Signal_sigName(B)), PBS_SIGNAMESZ);
			request->rq_ind.rq_signal.rq_signame[PBS_SIGNAMESZ + 1] = '\0';

			break;

		case PBS_BATCH_StatusJob:
#ifndef MOM
		case PBS_BATCH_StatusNode:
		case PBS_BATCH_StatusResv:
		case PBS_BATCH_StatusQue:
		case PBS_BATCH_StatusSvr:
		case PBS_BATCH_StatusSched:
		case PBS_BATCH_StatusRsc:
		case PBS_BATCH_StatusHook:
#endif
			ns(Stat_table_t) B = (ns(Stat_table_t)) ns(Req_body(req));

			CLEAR_HEAD(request->rq_ind.rq_status.rq_attr);

			request->rq_ind.rq_status.rq_id = strdup((char *) ns(Stat_jobIds(B)));
			if (request->rq_ind.rq_status.rq_id == NULL)
				return PBSE_SYSTEM;

			rc = decode_wire_svrattrl(ns(Stat_attrs(B)), &(request->rq_ind.rq_status.rq_attr));

			break;

		case PBS_BATCH_PySpawn:
			ns(Spawn_table_t) B = (ns(Spawn_table_t)) ns(Req_body(req));
			int i = 0;
			size_t len = 0;
			flatbuffers_string_vec_t strs;

			strncpy(request->rq_ind.rq_py_spawn.rq_jid, (char *) ns(Signal_jobId(B)), PBS_MAXSVRJOBID);
			request->rq_ind.rq_py_spawn.rq_jid[PBS_MAXSVRJOBID + 1] = '\0';

			request->rq_ind.rq_py_spawn.rq_argv = NULL;
			request->rq_ind.rq_py_spawn.rq_envp = NULL;

			strs = ns(Spawn_argv(B));
			len = flatbuffers_string_vec_len(strs);
			request->rq_ind.rq_py_spawn.rq_argv = (char **)calloc(sizeof(char **), len + 1);
			if (request->rq_ind.rq_py_spawn.rq_argv == NULL)
				return PBSE_SYSTEM;
			for (i = 0; i < len; i++) {
				request->rq_ind.rq_py_spawn.rq_argv[i] = strdup(flatbuffers_string_vec_at(strs, i));
				if (request->rq_ind.rq_py_spawn.rq_argv[i] == NULL)
					return PBSE_SYSTEM;
			}
			request->rq_ind.rq_py_spawn.rq_argv[++i] = NULL;

			strs = ns(Spawn_envp(B));
			len = flatbuffers_string_vec_len(strs);
			request->rq_ind.rq_py_spawn.rq_envp = (char **)calloc(sizeof(char **), len + 1);
			if (request->rq_ind.rq_py_spawn.rq_envp == NULL)
				return PBSE_SYSTEM;
			for (i = 0; i < len; i++) {
				request->rq_ind.rq_py_spawn.rq_envp[i] = strdup(flatbuffers_string_vec_at(strs, i));
				if (request->rq_ind.rq_py_spawn.rq_envp[i] == NULL)
					return PBSE_SYSTEM;
			}
			request->rq_ind.rq_py_spawn.rq_envp[++i] = NULL;

			break;

		case PBS_BATCH_AuthExternal:
			ns(Auth_table_t) B = (ns(Auth_table_t)) ns(Req_body(req));

			request->rq_ind.rq_auth_ext.rq_auth_type = ns(Auth_type(B));
			if (request->rq_ind.rq_auth_ext.rq_auth_type == AUTH_MUNGE) {
				ns(AuthMunge_table_t) B1 = (ns(AuthMunge_table_t)) ns(Auth_info(B));
				strncpy(request->rq_ind.rq_auth_ext.rq_authen_un.rq_munge.rq_authkey, (char *)ns(AuthMunge_key(B1)), PBS_AUTH_KEY_LEN);
				request->rq_ind.rq_auth_ext.rq_authen_un.rq_munge.rq_authkey[PBS_AUTH_KEY_LEN + 1] = '\0';
			}

			break;

#ifndef PBS_MOM
		case PBS_BATCH_RelnodesJob:
			ns(RelNodes_table_t) B = (ns(RelNodes_table_t)) ns(Req_body(req));

			strncpy(request->rq_ind.rq_relnodes.rq_jid, (char *) ns(RelNodes_jobId(B)), PBS_MAXSVRJOBID);
			request->rq_ind.rq_relnodes.rq_jid[PBS_MAXSVRJOBID + 1] = '\0';

			request->rq_ind.rq_relnodes.rq_node_list = strdup(ns(RelNodes_nodes(B)));
			if (request->rq_ind.rq_relnodes.rq_node_list == NULL)
				return PBSE_SYSTEM;

			break;

		case PBS_BATCH_MoveJob:
		case PBS_BATCH_OrderJob:
			ns(Move_table_t) B = (ns(Move_table_t)) ns(Req_body(req));

			strncpy(request->rq_ind.rq_move.rq_jid, (char *) ns(Move_jobId(B)), PBS_MAXSVRJOBID);
			request->rq_ind.rq_move.rq_jid[PBS_MAXSVRJOBID + 1] = '\0';

			strncpy(request->rq_ind.rq_move.rq_destin, (char *) ns(Move_dest(B)), PBS_MAXDEST);
			request->rq_ind.rq_move.rq_destin[PBS_MAXDEST + 1] = '\0';

			break;

		case PBS_BATCH_RunJob:
		case PBS_BATCH_AsyrunJob:
		case PBS_BATCH_StageIn:
		case PBS_BATCH_ConfirmResv:
			ns(Run_table_t) B = (ns(Run_table_t)) ns(Req_body(req));

			request->rq_ind.rq_run.rq_resch = (unsigned long) ns(Run_resch(B));

			strncpy(request->rq_ind.rq_run.rq_jid, (char *) ns(Run_jobId(B)), PBS_MAXSVRJOBID);
			request->rq_ind.rq_relnodes.rq_jid[PBS_MAXSVRJOBID + 1] = '\0';

			request->rq_ind.rq_run.rq_destin = strdup(ns(Run_dest(B)));
			if (request->rq_ind.rq_run.rq_destin == NULL)
				return PBSE_SYSTEM;

			break;

		case PBS_BATCH_DefSchReply:
			ns(SchedDefRep_table_t) B = (ns(SchedDefRep_table_t)) ns(Req_body(req));

			request->rq_ind.rq_defrpy.rq_cmd = (int) ns(SchedDefRep_cmd(B));
			request->rq_ind.rq_defrpy.rq_err = (int) ns(SchedDefRep_err(B));

			request->rq_ind.rq_defrpy.rq_txt = NULL;
			request->rq_ind.rq_defrpy.rq_id = NULL;

			request->rq_ind.rq_defrpy.rq_id = strdup(ns(SchedDefRep_id(B)));
			if (request->rq_ind.rq_defrpy.rq_id == NULL)
				return PBSE_SYSTEM;

			if (SchedDefRep_txt_is_present(B)) {
				request->rq_ind.rq_defrpy.rq_txt = strdup(ns(SchedDefResp_txt(B)));
				if (request->rq_ind.rq_defrpy.rq_txt == NULL)
					return PBSE_SYSTEM;

			break;

		case PBS_BATCH_SelectJobs:
		case PBS_BATCH_SelStat:
			ns(Select_table_t) B = (ns(Select_table_t)) ns(Req_body(req));

			CLEAR_HEAD(request->rq_ind.rq_select.rq_selattr);
			CLEAR_HEAD(request->rq_ind.rq_select.rq_rtnattr);

			rc = decode_wire_svrattrl(ns(Select_selAttrs(B)), &(request->rq_ind.rq_select.rq_selattr));
			if (rc == 0)
				rc = decode_wire_svrattrl(ns(Select_rtnAttrs(B)), &(request->rq_ind.rq_select.rq_rtnattr));

			break;

		case PBS_BATCH_TrackJob:
			ns(Track_table_t) B = (ns(Track_table_t)) ns(Req_body(req));

			request->rq_ind.rq_track.rq_hopcount = (int) ns(Track_hops(B));
			request->rq_ind.rq_track.rq_state[0] = (char) ns(Track_state(B));

			strncpy(request->rq_ind.rq_track.rq_jid, (char *) ns(Track_jobId(B)), PBS_MAXSVRJOBID);
			request->rq_ind.rq_track.rq_jid[PBS_MAXSVRJOBID + 1] = '\0';

			strncpy(request->rq_ind.rq_track.rq_location, (char *) ns(Track_location(B)), PBS_MAXDEST);
			request->rq_ind.rq_track.rq_location[PBS_MAXDEST + 1] = '\0';

			break;

		case PBS_BATCH_Rescq:
		case PBS_BATCH_ReserveResc:
		case PBS_BATCH_ReleaseResc:
			ns(RescQuery_table_t) B = (ns(RescQuery_table_t)) ns(Req_body(req));
			int i = 0;
			size_t len = 0;
			flatbuffers_string_vec_t strs;

			request->rq_ind.rq_rescq.rq_rhandle = (int) ns(RescQuery_handle(B));


			strs = ns(RescQuery_queries(B));
			len = flatbuffers_string_vec_len(strs);
			request->rq_ind.rq_rescq.rq_num = (int) len;

			request->rq_ind.rq_rescq.rq_list = NULL;
			request->rq_ind.rq_rescq.rq_list = (char **)calloc(sizeof(char **), len);
			if (request->rq_ind.rq_rescq.rq_list == NULL)
				return PBSE_SYSTEM;
			for (i = 0; i < len; i++) {
				request->rq_ind.rq_rescq.rq_list[i] = strdup(flatbuffers_string_vec_at(strs, i));
				if (request->rq_ind.rq_rescq.rq_list[i] == NULL)
					return PBSE_SYSTEM;
			}

			break;

		case PBS_BATCH_RegistDep:
			ns(Register_table_t) B = (ns(Register_table_t)) ns(Req_body(req));

			request->rq_ind.rq_register.rq_op = (int) ns(Register_op(B));
			request->rq_ind.rq_register.rq_dependtype = (int) ns(Register_type(B));
			request->rq_ind.rq_register.rq_cost = (long) ns(Register_cost(B));

			strncpy(request->rq_ind.rq_register.rq_child, (char *) ns(Register_child(B)), PBS_MAXCLTJOBID);
			request->rq_ind.rq_register.rq_child[PBS_MAXCLTJOBID + 1] = '\0';

			strncpy(request->rq_ind.rq_register.rq_parent, (char *) ns(Register_parent(B)), PBS_MAXSVRJOBID);
			request->rq_ind.rq_register.rq_parent[PBS_MAXSVRJOBID + 1] = '\0';

			strncpy(request->rq_ind.rq_register.rq_owner, (char *) ns(Register_owner(B)), PBS_MAXUSER);
			request->rq_ind.rq_register.rq_owner[PBS_MAXUSER + 1] = '\0';

			strncpy(request->rq_ind.rq_register.rq_svr, (char *) ns(Register_server(B)), PBS_MAXSERVERNAME);
			request->rq_ind.rq_register.rq_svr[PBS_MAXSERVERNAME + 1] = '\0';

			break;

		case PBS_BATCH_AuthenResvPort:
			ns(Auth_table_t) B = (ns(Auth_table_t)) ns(Req_body(req));

			request->rq_ind.rq_authen_resvport.rq_port = ns(AuthResvPort_port(ns(Auth_info(B))));

			break;

		case PBS_BATCH_PreemptJobs:
			ns(Preempt_table_t) B = (ns(Preempt_table_t)) ns(Req_body(req));

			int i = 0;
			size_t len = 0;
			flatbuffers_string_vec_t strs;

			strs = ns(Preempt_infos(B));
			len = flatbuffers_string_vec_len(strs);
			request->rq_ind.rq_preempt.count = (int) len;

			request->rq_ind.rq_preempt.ppj_list = NULL;
			request->rq_ind.rq_preempt.ppj_list = (preempt_job_info *)calloc(sizeof(struct preempt_job_info), len);
			if (request->rq_ind.rq_preempt.ppj_list == NULL)
				return PBSE_SYSTEM;
			for (i = 0; i < len; i++) {
				strncpy(request->rq_ind.rq_preempt.ppj_list[i].job_id, flatbuffers_string_vec_at(strs, i), PBS_MAXSVRJOBID);
				request->rq_ind.rq_preempt.ppj_list[i].job_id[PBS_MAXSVRJOBID + 1] = '\0';
			}

			break;

#else	/* yes PBS_MOM */

		case PBS_BATCH_CopyHookFile:
			ns(CopyHook_table_t) B = (ns(CopyHook_table_t)) ns(Req_body(req));

			request->rq_ind.rq_hookfile.rq_sequence = (int) ns(CopyHook_seq(B));
			request->rq_ind.rq_hookfile.rq_size = (int) ns(CopyHook_size(B));

			strncpy(request->rq_ind.rq_hookfile.rq_filename, (char *)ns(CopyHook_filename(B)), MAXPATHLEN);
			request->rq_ind.rq_hookfile.rq_filename[MAXPATHLEN + 1] = '\0';

			request->rq_ind.rq_hookfile.rq_data = strdup((char *)ns(CopyHook_data(B)));
			if (request->rq_ind.rq_hookfile.rq_data == NULL)
				return PBSE_SYSTEM;

			if (strlen(request->rq_ind.rq_hookfile.rq_data) != request->rq_ind.rq_hookfile.rq_size) {
				free(request->rq_ind.rq_hookfile.rq_data);
				return PBSE_SYSTEM;
			}

			break;

		case PBS_BATCH_DelHookFile:
			ns(CopyHook_table_t) B = (ns(CopyHook_table_t)) ns(Req_body(req));

			strncpy(request->rq_ind.rq_hookfile.rq_filename, (char *)ns(CopyHook_filename(B)), MAXPATHLEN);
			request->rq_ind.rq_hookfile.rq_filename[MAXPATHLEN + 1] = '\0';

			break;

		case PBS_BATCH_CopyFiles:
		case PBS_BATCH_DelFiles:
			rc = decode_wire_CopyFiles(sfds, request);
			break;

		case PBS_BATCH_CopyFiles_Cred:
		case PBS_BATCH_DelFiles_Cred:
			flatbuffers_string_t cred;
			ns(CopyFileCred_table_t) B = (ns(CopyFileCred_table_t)) ns(Req_body(req));
			struct rq_cpyfile *files = &(request->rq_ind.rq_cpyfile_cred.rq_copyfile);

			CLEAR_HEAD(files->rq_pair);
			request->rq_ind.rq_cpyfile_cred.rq_pcred = NULL;

			request->rq_ind.rq_cpyfile_cred.rq_credtype = (int) ns(CopyFileCred_type(B));

			cred = ns(CopyFileCred_cred(B));
			request->rq_ind.rq_cpyfile_cred.rq_credlen = flatbuffers_string_len(cred);
			request->rq_ind.rq_cpyfile_cred.rq_pcred = (char *)malloc(request->rq_ind.rq_cpyfile_cred.rq_credlen + 1);
			if (request->rq_ind.rq_cpyfile_cred.rq_pcred == NULL)
				return PBSE_SYSTEM;

			memcpy(request->rq_ind.rq_cpyfile_cred.rq_pcred, (char *)cred, request->rq_ind.rq_cpyfile_cred.rq_credlen);
			request->rq_ind.rq_cpyfile_cred.rq_pcred[request->rq_ind.rq_cpyfile_cred.rq_credlen + 1] = '\0';

			rc = decode_wire_CopyFiles(ns(CopyFileCred_files(B)), files);

			break;

		case PBS_BATCH_Cred:
			ns(Cred_table_t) B = (ns(Cred_table_t)) ns(Req_body(req));

			request->rq_ind.rq_cred.rq_data = NULL;
			request->rq_ind.rq_cred.rq_type = (int) ns(Cred_type(B));
			request->rq_ind.rq_cred.rq_size = (size_t) ns(Cred_size(B));
			request->rq_ind.rq_cred.rq_validity = (long) ns(Cred_validity(B));

			strncpy(request->rq_ind.rq_cred.rq_jobid, (char *)ns(Cred_jobId(B)), PBS_MAXSVRJOBID);
			request->rq_ind.rq_cred.rq_jobid[PBS_MAXSVRJOBID + 1] = '\0';

			strncpy(request->rq_ind.rq_cred.rq_credid, (char *)ns(Cred_jobId(B)), PBS_MAXUSER);
			request->rq_ind.rq_cred.rq_credid[PBS_MAXUSER + 1] = '\0';

			request->rq_ind.rq_cred.rq_data = (char *)malloc(request->rq_ind.rq_cred.rq_size + 1);
			if (request->rq_ind.rq_cred.rq_data == NULL)
				return PBSE_SYSTEM;
			memcpy(request->rq_ind.rq_cred.rq_data, (char *)(ns(Cred_cred(B))), request->rq_ind.rq_cred.rq_size);
			request->rq_ind.rq_cred.rq_data[request->rq_ind.rq_cred.rq_size + 1] = '\0';

			break;

#endif	/* PBS_MOM */

		default:
			log_eventf(PBSEVENT_ERROR, PBS_EVENTCLASS_REQUEST, LOG_ERR,
				__func__, "%s: %d from %s", msg_nosupport,
				request->rq_type, request->rq_user);
			rc = PBSE_UNKREQ;
			break;
	}

	if (rc == 0) {
		/* Decode the Request Extension, if present */
		if (ns(Req_extend_is_present(req))) {
			request->rq_extend = strdup((char *) ns(Req_extend(req)));
			if (request->rq_extend == NULL)
				rc = PBSE_SYSTEM;
		}
	} else if (rc != PBSE_UNKREQ) {
		log_eventf(PBSEVENT_ERROR, PBS_EVENTCLASS_REQUEST, LOG_ERR, __func__,
				"Req Body bad, type %d", request->rq_type);
		rc = PBSE_PROTOCOL;
	}

	return (rc);
}


/**
 * @brief
 *	top level function to read and decode DIS based batch reply
 *
 *	Calls decode_wire_replySvrTPP in case of TPP and decode_wire_replySvr
 *	in case of TCP to read the reply
 *
 * @see
 *	read_reg_reply, process_Dreply and process_DreplyTPP.
 *
 * @param[in] sock - socket connection from which to read reply
 * @param[out] reply - The reply structure to be returned
 * @param[in] prot - PROT_TCP pr PROT_TPP
 *
 * @return int
 * @retval 0 - success
 * @retval !0- error
 */
int
wire_reply_read(int sock, struct batch_reply *preply, int prot)
{
	if (prot == PROT_TPP)
		return (decode_wire_replySvrTPP(sock, preply));

	set_transport_to_tcp();
	return  (decode_wire_replySvr(sock, preply));
}
