/*
 * Copyright (C) 1994-2020 Altair Engineering, Inc.
 * For more information, contact Altair at www.altair.com.
 *
 * This file is part of the PBS Professional ("PBS Pro") software.
 *
 * Open Source License Information:
 *
 * PBS Pro is free software. You can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * PBS Pro is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Commercial License Information:
 *
 * For a copy of the commercial license terms and conditions,
 * go to: (http://www.pbspro.com/UserArea/agreement.html)
 * or contact the Altair Legal Department.
 *
 * Altair’s dual-license business model allows companies, individuals, and
 * organizations to create proprietary derivative works of PBS Pro and
 * distribute them - whether embedded or bundled with other software -
 * under a commercial license agreement.
 *
 * Use of Altair’s trademarks, including but not limited to "PBS™",
 * "PBS Professional®", and "PBS Pro™" and Altair’s logos is subject to Altair's
 * trademark licensing policies.
 *
 */
#include <pbs_config.h>   /* the master config generated by configure */

#include <sys/types.h>
#include <stdlib.h>
#include <errno.h>
#include <string.h>
#include <stdio.h>
#include "pbs_transport.h"
#include "libpbs.h"
#include "ifl_internal.h"
#include "list_link.h"
#include "server_limits.h"
#include "attribute.h"
#include "log.h"
#include "pbs_error.h"
#include "credential.h"
#include "batch_request.h"
#include "net_connect.h"


static int decode_wire_CopyFiles(ns(CopyFile_table_t) B, struct rq_cpyfile *pcf);
static int decode_wire_attrl(ns(Attribute_vec_t) attrs, struct attrl **ppatt);

/* External Global Data */

extern char	*msg_nosupport;

/**
 * @brief
 *	decode into a list of PBS API "attropl" structures from given flatbuffer
 *	The space for the attrl structures is allocated as needed.
 *
 * @param[in] attrs - flatbuffer attrs vec
 * @param[in] ppatt - pointer to list of attributes
 *
 * @return int
 * @retval 0 on SUCCESS
 * @retval >0 on failure
 */
static int
decode_wire_attropl(ns(Attribute_vec_t) attrs, struct attropl **ppatt)
{
	int i = 0;
	struct attropl *patprior = NULL;
	struct attropl *pat = NULL;
	size_t attrs_len = ns(Attribute_vec_len(attrs));

	for (i = 0; i < attrs_len; i++) {
		ns(Attribute_table_t) attr = ns(Attribute_vec_at(attrs, i));
		pat = new_attrl();
		if (pat == NULL)
			return PBSE_SYSTEM;

		pat->name = strdup((char *) ns(Attribute_name(attr)));
		if (pat->name != NULL)
			goto err;

		if (ns(Attribute_resc_is_present(attr))) {
			pat->resource = strdup((char *) ns(Attribute_resc(attr)));
			if (pat->resource != NULL)
				goto err;
		}

		pat->value = strdup((char *) ns(Attribute_value(attr)));
		if (pat->value != NULL)
			goto err;
		pat->op = (enum batch_op) ns(Attribute_op(attr));
		if (i == 0) {
			/* first one, link to passing in pointer */
			*ppatt = pat;
		} else {
			patprior->next = pat;
		}
		patprior = pat;
	}

err:
	PBS_free_aopl(pat);
	return PBSE_SYSTEM;
}

/**
 * @brief
 * 	decode_wire_CopyFiles() - decode a Copy Files Dependency Batch Request
 *
 *	This request is used by the server ONLY.
 *	The rq_cpyfile structure pointed to by pcf must already exist.
 *
 * @param[in] B - copy file table ref from flatbuffer
 * @param[in] pcf - pointer to rq_cpyfile structure
 *
 * @return int
 * @retval 0 - success
 * @retval !0 - error
 */
static int
decode_wire_CopyFiles(ns(CopyFile_table_t) B, struct rq_cpyfile *pcf)
{
	int pair_ct = 0;
	struct rqfpair *ppair = NULL;
	ns(FilePair_vec_t) pairs;
	int i = 0;

	CLEAR_HEAD(pcf->rq_pair);

	strncpy(pcf->rq_jobid, (char *)ns(CopyFile_jobId(B)), PBS_MAXSVRJOBID);
	pcf->rq_jobid[PBS_MAXSVRJOBID + 1] = '\0';

	strncpy(pcf->rq_owner, (char *)ns(CopyFile_owner(B)), PBS_MAXUSER);
	pcf->rq_owner[PBS_MAXUSER + 1] = '\0';

	strncpy(pcf->rq_user, (char *)ns(CopyFile_user(B)), PBS_MAXUSER);
	pcf->rq_user[PBS_MAXUSER + 1] = '\0';

	strncpy(pcf->rq_group, (char *)ns(CopyFile_group(B)), PBS_MAXGRPN);
	pcf->rq_group[PBS_MAXGRPN + 1] = '\0';

	pcf->rq_dir = (int) ns(CopyFile_flags(B));

	pairs = ns(CopyFile_pairs(B));
	pair_ct = (int) ns(FilePair_vec_len(pairs));

	for (i = 0; i < pair_ct; i++) {
		ns(FilePair_table_t) pair = ns(FilePair_vec_at(pairs, i));

		ppair = (struct rqfpair *) calloc(sizeof(struct rqfpair), 1);
		if (ppair == NULL)
			return PBSE_SYSTEM;

		CLEAR_LINK(ppair->fp_link);

		ppair->fp_flag = (int) ns(FilePair_flag(pair));

		ppair->fp_rmt = strdup((char *) ns(FilePair_remote(pair)));
		if (ppair->fp_rmt == NULL) {
			free(ppair);
			return PBSE_SYSTEM;
		}

		ppair->fp_local = strdup((char *) ns(FilePair_local(pair)));
		if (ppair->fp_local == NULL) {
			free(ppair->fp_rmt);
			free(ppair);
			return PBSE_SYSTEM;
		}

		append_link(&(pcf->rq_pair), &(ppair->fp_link), ppair);
	}
	return 0;
}

/**
 * @brief
 *	decode into a list of svrattrl structures from given flatbuffer
 *	The space for the svrattrl structures is allocated as needed.
 *
 * @param[in] attrs - flatbuffer attrs vec
 * @param[in] phead - pointer to list of attributes
 *
 * @return int
 * @retval 0 on SUCCESS
 * @retval >0 on failure
 */
int
decode_wire_svrattrl(ns(Attribute_vec_t) attrs, pbs_list_head *phead)
{
	int		i;
	unsigned int	hasresc;
	size_t		ls;
	unsigned int	data_len;
	unsigned int	numattr;

	int		rc;
	size_t		tsize;

	int i = 0;
	size_t attrs_len = ns(Attribute_vec_len(attrs));

	CLEAR_HEAD((*phead));

	for (i = 0; i < attrs_len; i++) {
		ns(Attribute_table_t) attr = ns(Attribute_vec_at(attrs, i));
		svrattrl *psvrat = NULL;
		char *name = (char *) ns(Attribute_name(attr));
		size_t nlen = strlen(name) + 1;
		char *value = (char *) ns(Attribute_value(attr));
		size_t vlen = strlen(value) + 1;
		char *resc = NULL;
		size_t rlen = 0;
		size_t tsize = sizeof(svrattrl) + nlen + vlen;

		if (ns(Attribute_resc_is_present(attr))) {
			resc = (char *) ns(Attribute_resc(attr));
			rlen = strlen(resc) + 1;
			tsize += rlen;
		}

		if ((psvrat = (svrattrl *)malloc(tsize)) == NULL)
			return PBSE_SYSTEM;

		CLEAR_LINK(psvrat->al_link);
		psvrat->al_sister = NULL;
		psvrat->al_atopl.next = NULL;
		psvrat->al_tsize = tsize;
		psvrat->al_name = (char *)psvrat + sizeof(svrattrl);
		psvrat->al_resc = psvrat->al_name + nlen;
		psvrat->al_value = psvrat->al_resc + rlen;
		psvrat->al_nameln = nlen;
		psvrat->al_rescln = rlen;
		psvrat->al_valln = vlen;
		psvrat->al_flags = 0;
		psvrat->al_refct = 1;
		psvrat->al_op = (enum batch_op) ns(Attribute_op(attr));

		strncpy(psvrat->al_name, name, nlen - 1);
		psvrat->al_name[nlen] = '\0';

		if (rlen > 0) {
			strncpy(psvrat->al_resc, resc, rlen - 1);
			psvrat->al_resc[rlen] = '\0';
		}

		strncpy(psvrat->al_value, value, vlen - 1);
		psvrat->al_value[vlen] = '\0';

		append_link(phead, &(psvrat->al_link), psvrat);
	}
	return 0;
}

/**
 * @brief
 *	Read in an PBS Batch reply from the network
 *
 * @param[in] sock - socket connection from which to read reply
 * @param[out] reply - The reply structure to be returned
 * @param[in] prot - PROT_TCP pr PROT_TPP
 *
 * @return int
 * @retval 0 - success
 * @retval !0 - error
 */
int
wire_reply_read(int sock, struct batch_reply *reply, int prot, int forsvr)
{
	int i = 0;
	size_t len = 0;
	int rc = 0;
	void *buf = NULL;
	size_t bufsz = 0;
	ns(Resp_table_t) resp;

	if (prot == PROT_TCP)
		set_transport_to_tcp();
	else
		set_transport_to_tpp();

	//FIXME: get loaded buf for read with size here
	rc = ns(Resp_verify_as_root(buf, bufsz));
	if (rc != 0) {
		log_eventf(PBSEVENT_ERROR, PBS_EVENTCLASS_REQUEST, LOG_ERR, __func__,
				"Bad reply, errno %d, wire error %d", errno, rc);
		return PBSE_PROTOCOL;
	}

	resp = ns(Resp_as_root(buf));

	reply->brp_code = ns(Resp_code(resp));
	reply->brp_auxcode = ns(Resp_auxCode(resp));
	reply->brp_choice = ns(Resp_choice(resp));

	switch (reply->brp_choice) {

		case BATCH_REPLY_CHOICE_NULL:
			break;	/* no more to do */

		case BATCH_REPLY_CHOICE_Queue:
		case BATCH_REPLY_CHOICE_RdytoCom:
		case BATCH_REPLY_CHOICE_Commit:
			ns(TextResp_table_t) B = (ns(TextResp_table_t)) ns(Resp_body(resp));

			strncpy(reply->brp_un.brp_jid, (char *) ns(TextResp_txt(B)), PBS_MAXSVRJOBID);
			reply->brp_un.brp_jid[PBS_MAXSVRJOBID + 1] = '\0';

			break;

		case BATCH_REPLY_CHOICE_Select:
			ns(SelectResp_table_t) B = (ns(SelectResp_table_t)) ns(Resp_body(resp));
			flatbuffers_string_vec_t ids = ns(SelectResp_ids(B));
			struct brp_select **pselx = &(reply->brp_un.brp_select);

			*pselx = NULL;
			len = flatbuffers_string_vec_len(ids);

			for (i = 0; i < len; i++) {
				struct brp_select *psel = (struct brp_select *)malloc(sizeof(struct brp_select));
				if (psel == NULL)
					return PBSE_SYSTEM;

				psel->brp_next = NULL;
				strncpy(psel->brp_jobid, (char *) flatbuffers_string_vec_at(ids, i), PBS_MAXSVRJOBID);
				psel->brp_jobid[PBS_MAXSVRJOBID + 1] = '\0';

				*pselx = psel;
				pselx = &(psel->brp_next);
			}

			break;

		case BATCH_REPLY_CHOICE_Status:
			ns(StatResp_table_t) B = (ns(StatResp_table_t)) ns(Resp_body(resp));
			ns(StatRespStat_vec_t) stats = ns(StatResp_stats(B));

			CLEAR_HEAD(reply->brp_un.brp_status);

			len = ns(StatRespStat_vec_len(stats));
			rc = 0;
			for (i = 0; i < len && rc == 0; i++) {
				ns(StatRespStat_table_t) stat = ns(StatRespStat_vec_at(stats, i));
				struct brp_status *pstsvr = (struct brp_status *)malloc(sizeof(struct brp_status));

				if (pstsvr == NULL)
					return PBSE_SYSTEM;

				CLEAR_LINK(pstsvr->brp_stlink);
				CLEAR_HEAD(pstsvr->brp_attr);

				pstsvr->brp_objtype = ns(StatRespStat_type(stat));

				strncpy(pstsvr->brp_objname, (char *) ns(StatRespStat_name(stat)), PBS_MAXSVRJOBID);
				pstsvr->brp_objname[PBS_MAXSVRJOBID + 1] = '\0';

				append_link(&(reply->brp_un.brp_status), &(pstsvr->brp_stlink), pstsvr);
				if (forsvr)
					rc = decode_wire_svrattrl(ns(StatRespStat_attrs(stat)), &pstsvr->brp_attr);
				else
					rc = decode_wire_attropl(ns(StatRespStat_attrs(stat)), &pstsvr->brp_attr);
			}

			break;

		case BATCH_REPLY_CHOICE_Text:
			ns(TextResp_table_t) B = (ns(TextResp_table_t)) ns(Resp_body(resp));

			reply->brp_un.brp_txt.brp_str = strdup((char *) ns(TextResp_txt(B)));
			if (reply->brp_un.brp_txt.brp_str == NULL)
				return PBSE_SYSTEM;
			reply->brp_un.brp_txt.brp_txtlen = strlen(reply->brp_un.brp_txt.brp_str);

			break;

		case BATCH_REPLY_CHOICE_Locate:
			ns(TextResp_table_t) B = (ns(TextResp_table_t)) ns(Resp_body(resp));

			strncpy(reply->brp_un.brp_locate, (char *) ns(TextResp_txt(B)), PBS_MAXDEST);
			reply->brp_un.brp_locate[PBS_MAXDEST + 1] = '\0';

			break;

		case BATCH_REPLY_CHOICE_RescQuery:
			ns(RescQueryResp_table_t) B = (ns (RescQueryResp_table_t)) ns(Resp_body(resp));
			flatbuffers_int16_vec_t avails = ns(RescQueryResp_avail(B));
			flatbuffers_int16_vec_t allocs = ns(RescQueryResp_alloc(B));
			flatbuffers_int16_vec_t resvds = ns(RescQueryResp_resvd(B));
			flatbuffers_int16_vec_t downs = ns(RescQueryResp_down(B));

			reply->brp_un.brp_rescq.brq_avail = NULL;
			reply->brp_un.brp_rescq.brq_alloc = NULL;
			reply->brp_un.brp_rescq.brq_resvd = NULL;
			reply->brp_un.brp_rescq.brq_down  = NULL;

			len = flatbuffers_int16_vec_len(avails);
			reply->brp_un.brp_rescq.brq_number = len;

			reply->brp_un.brp_rescq.brq_avail = (int *)malloc(sizeof(int) * len);
			if (reply->brp_un.brp_rescq.brq_avail == NULL)
				return PBSE_SYSTEM;

			reply->brp_un.brp_rescq.brq_alloc = (int *)malloc(sizeof(int) * len);
			if (reply->brp_un.brp_rescq.brq_alloc == NULL) {
				free(reply->brp_un.brp_rescq.brq_avail);
				reply->brp_un.brp_rescq.brq_avail = NULL;
				return PBSE_SYSTEM;
			}

			reply->brp_un.brp_rescq.brq_resvd = (int *)malloc(sizeof(int) * len);
			if (reply->brp_un.brp_rescq.brq_resvd == NULL) {
				free(reply->brp_un.brp_rescq.brq_alloc);
				free(reply->brp_un.brp_rescq.brq_avail);
				reply->brp_un.brp_rescq.brq_alloc = NULL;
				reply->brp_un.brp_rescq.brq_avail = NULL;
				return PBSE_SYSTEM;
			}

			reply->brp_un.brp_rescq.brq_down = (int *)malloc(sizeof(int) * len);
			if (reply->brp_un.brp_rescq.brq_down == NULL) {
				free(reply->brp_un.brp_rescq.brq_alloc);
				free(reply->brp_un.brp_rescq.brq_avail);
				free(reply->brp_un.brp_rescq.brq_resvd);
				reply->brp_un.brp_rescq.brq_alloc = NULL;
				reply->brp_un.brp_rescq.brq_avail = NULL;
				reply->brp_un.brp_rescq.brq_resvd = NULL;
				return PBSE_SYSTEM;
			}

			for (i = 0; i < len; i++) {
				*(reply->brp_un.brp_rescq.brq_avail + i) = (int) flatbuffers_int16_vec_at(avails, i);
				*(reply->brp_un.brp_rescq.brq_alloc + i) = (int) flatbuffers_int16_vec_at(allocs, i);
				*(reply->brp_un.brp_rescq.brq_resvd + i) = (int) flatbuffers_int16_vec_at(resvds, i);
				*(reply->brp_un.brp_rescq.brq_down + i) = (int) flatbuffers_int16_vec_at(downs, i);
			}

			break;

		case BATCH_REPLY_CHOICE_PreemptJobs:
			ns(Preempt_table_t) B = (ns(Preempt_table_t)) ns(Resp_body(resp));
			ns(PreemptJob_vec_t) preempts = ns(Preempt_infos(B));

			len = ns(PreemptJob_vec_len(preempts));
			reply->brp_un.brp_preempt_jobs.count = (int) len;

			reply->brp_un.brp_preempt_jobs.ppj_list = NULL;
			reply->brp_un.brp_preempt_jobs.ppj_list = (preempt_job_info *)calloc(sizeof(struct preempt_job_info), len);
			if (reply->brp_un.brp_preempt_jobs.ppj_list == NULL)
				return PBSE_SYSTEM;

			for (i = 0; i < len; i++) {
				ns(PreemptJob_table_t) p = (ns(PreemptJob_table_t)) flatbuffers_string_vec_at(preempts, i);

				strncpy(reply->brp_un.brp_preempt_jobs.ppj_list[i].job_id, (char *) ns(PreemptJob_jid(p)), PBS_MAXSVRJOBID);
				reply->brp_un.brp_preempt_jobs.ppj_list[i].job_id[PBS_MAXSVRJOBID + 1] = '\0';

				strncpy(reply->brp_un.brp_preempt_jobs.ppj_list[i].order, (char *) ns(PreemptJob_order(p)), PREEMPT_METHOD_HIGH);
				reply->brp_un.brp_preempt_jobs.ppj_list[i].order[PREEMPT_METHOD_HIGH + 1] = '\0';
			}

			break;

		default:
			return -1;
	}

	return rc;
}


/**
 * @brief
 *	Read in an PBS Batch request from the network
 *
 * @param[in]		sfds	- the socket descriptor
 * @param[in,out]	request - will contain the decoded request
 *
 * @return int
 * @retval 0	if request read ok, batch_request pointed to by request is updated.
 * @retval >0	if errors ( a PBSE_ number)
 */
int
wire_request_read(int sfds, struct batch_request *request)
{
	int rc = 0;
	void *buf = NULL;
	size_t bufsz = 0;
	ns(Req_table_t) req;
	ns(Header_table_t) hdr;
	uint16_t proto;
	uint16_t version;

	if (request->istpp)
		set_transport_to_tpp();
	else
		set_transport_to_tcp();

	//FIXME: get loaded buf for read with size here
	rc = ns(Req_verify_as_root(buf, bufsz));
	if (rc != 0) {
		log_eventf(PBSEVENT_DEBUG, PBS_EVENTCLASS_REQUEST, LOG_DEBUG, __func__,
				"Bad request, errno %d, wire error %d", errno, rc);
		return PBSE_PROTOCOL;
	}

	req = (ns(Req_table_t)) ns(Req_as_root(buf));
	hdr = (ns(Header_table_t)) ns(Req_hdr(req));
	proto = (uint16_t) ns(Header_protType(hdr));
	version = (uint16_t) ns(Header_version(hdr));

	if (proto != ns(ProtType_Batch) || version > PBS_BATCH_PROT_VER)
		return PBSE_PROTOCOL;

	request->rq_type = (int)ns(Header_reqId(hdr));

	strncpy(request->rq_user, (char *)ns(Header_user(hdr)), PBS_MAXUSER);
	request->rq_user[PBS_MAXUSER + 1] = '\0';

	/* Decode the Request Body based on the type */
	switch (request->rq_type) {
		case PBS_BATCH_Connect:
			break;

		case PBS_BATCH_Disconnect:
			return (-1); /* set EOF return */

		case PBS_BATCH_QueueJob:
		case PBS_BATCH_SubmitResv:
			ns(Qjob_table_t) B = (ns(Qjob_table_t)) ns(Req_body(req));

			CLEAR_HEAD(request->rq_ind.rq_queuejob.rq_attr);

			strncpy(request->rq_ind.rq_queuejob.rq_jid, (char *)ns(Qjob_jobId(B)), PBS_MAXSVRJOBID);
			request->rq_ind.rq_queuejob.rq_jid[PBS_MAXSVRJOBID + 1] = '\0';

			strncpy(request->rq_ind.rq_queuejob.rq_destin, (char *)ns(Qjob_destin(B)), PBS_MAXDEST);
			request->rq_ind.rq_queuejob.rq_destin[PBS_MAXDEST + 1] = '\0';

			rc = decode_wire_svrattrl(ns(Qjob_attrs(B)), &(request->rq_ind.rq_queuejob.rq_attr));
			break;

		case PBS_BATCH_JobCred:
			ns(Cred_table_t) B = (ns(Cred_table_t)) ns(Req_body(req));

			request->rq_ind.rq_jobcred.rq_type = (int) ns(Cred_type(B));
			request->rq_ind.rq_jobcred.rq_size = (int) ns(Cred_size(B));

			request->rq_ind.rq_jobcred.rq_data = (char *)malloc(request->rq_ind.rq_jobcred.rq_size + 1);
			if (request->rq_ind.rq_jobcred.rq_data == NULL)
				return PBSE_SYSTEM;
			memcpy(request->rq_ind.rq_jobcred.rq_data, (char *)(ns(Cred_cred(B))), request->rq_ind.rq_jobcred.rq_size);
			request->rq_ind.rq_jobcred.rq_data[request->rq_ind.rq_jobcred.rq_size + 1] = '\0';

			break;

		case PBS_BATCH_UserCred:
			ns(Cred_table_t) B = (ns(Cred_table_t)) ns(Req_body(req));

			request->rq_ind.rq_usercred.rq_type = (int) ns(Cred_type(B));
			request->rq_ind.rq_usercred.rq_size = (int) ns(Cred_size(B));

			strncpy(request->rq_ind.rq_usercred.rq_user, (char *)ns(Cred_user(B)), PBS_MAXUSER);
			request->rq_ind.rq_usercred.rq_user[PBS_MAXUSER + 1] = '\0';

			request->rq_ind.rq_usercred.rq_data = (char *)malloc(request->rq_ind.rq_usercred.rq_size + 1);
			if (request->rq_ind.rq_usercred.rq_data == NULL)
				return PBSE_SYSTEM;
			memcpy(request->rq_ind.rq_usercred.rq_data, (char *)(ns(Cred_data(B))), request->rq_ind.rq_usercred.rq_size);
			request->rq_ind.rq_usercred.rq_data[request->rq_ind.rq_usercred.rq_size + 1] = '\0';

			break;

		case PBS_BATCH_UserMigrate:
			ns(UserMigrate_table_t) B = (ns(UserMigrate_table_t)) ns(Req_body(req));

			strncpy(request->rq_ind.rq_user_migrate.rq_tohost, (char *)ns(UserMigrate_tohost(B)), PBS_MAXHOSTNAME);
			request->rq_ind.rq_user_migrate.rq_tohost[PBS_MAXHOSTNAME + 1] = '\0';
			break;

		case PBS_BATCH_jobscript:
		case PBS_BATCH_MvJobFile:
			ns(JobFile_table_t) B = (ns(JobFile_table_t)) ns(Req_body(req));

			request->rq_ind.rq_jobfile.rq_sequence = (int) ns(JobFile_seq(B));
			request->rq_ind.rq_jobfile.rq_type = (int) ns(JobFile_type(B));
			request->rq_ind.rq_jobfile.rq_size = (long) ns(JobFile_size(B));

			strncpy(request->rq_ind.rq_jobfile.rq_jobid, (char *)ns(JobFile_jobId(B)), PBS_MAXSVRJOBID);
			request->rq_ind.rq_jobfile.rq_jobid[PBS_MAXSVRJOBID + 1] = '\0';

			request->rq_ind.rq_jobfile.rq_data = (char *)malloc(request->rq_ind.rq_jobfile.rq_size + 1);
			if (request->rq_ind.rq_jobfile.rq_data == NULL)
				return PBSE_SYSTEM;
			memcpy(request->rq_ind.rq_jobfile.rq_data, (char *)(ns(Cred_data(B))), request->rq_ind.rq_jobfile.rq_size);
			request->rq_ind.rq_jobfile.rq_data[request->rq_ind.rq_jobfile.rq_size + 1] = '\0';

			break;

		case PBS_BATCH_RdytoCommit:
		case PBS_BATCH_Commit:
		case PBS_BATCH_Rerun:
#ifndef MOM
		case PBS_BATCH_LocateJob:
#endif
			ns(JobId_table_t) B = (ns(JobId_table_t)) ns(Req_body(req));

			strncpy(request->rq_ind.rq_commit, (char *)ns(JobFile_jobId(B)), PBS_MAXSVRJOBID);
			request->rq_ind.rq_commit[PBS_MAXSVRJOBID + 1] = '\0';

			break;

		case PBS_BATCH_DeleteJob:
		case PBS_BATCH_DeleteResv:
		case PBS_BATCH_ResvOccurEnd:
		case PBS_BATCH_HoldJob:
		case PBS_BATCH_ModifyJob:
#ifndef MOM
		case PBS_BATCH_Manager:
		case PBS_BATCH_ReleaseJob:
		case PBS_BATCH_ModifyResv:
#endif
			ns(Manage_table_t) B = (ns(Manage_table_t)) ns(Req_body(req));

			CLEAR_HEAD(request->rq_ind.rq_manager.rq_attr);

			request->rq_ind.rq_manager.rq_cmd = (int) ns(Manage_cmd(B));
			request->rq_ind.rq_manager.rq_objtype = (int) ns(Manage_objType(B));

			strncpy(request->rq_ind.rq_manager.rq_objname, (char *)ns(Manager_objName(B)), PBS_MAXSVRJOBID);
			request->rq_ind.rq_manager.rq_objname[PBS_MAXSVRJOBID + 1] = '\0';

			rc = decode_wire_svrattrl(ns(Manager_attrs(B)), &(request->rq_ind.rq_manager.rq_attr));

			break;

		case PBS_BATCH_MessJob:
			ns(Msg_table_t) B = (ns(Msg_table_t)) ns(Req_body(req));

			request->rq_ind.rq_message.rq_file = (int) ns(Msg_FileInd(B));

			strncpy(request->rq_ind.rq_message.rq_jid, (char *) ns(Msg_jobId(B)), PBS_MAXSVRJOBID);
			request->rq_ind.rq_message.rq_jid[PBS_MAXSVRJOBID + 1] = '\0';

			request->rq_ind.rq_message.rq_text = strdup((char *) ns(Msg_text(B)));
			if (request->rq_ind.rq_message.rq_text == NULL)
				return PBSE_SYSTEM;

			break;

		case PBS_BATCH_Shutdown:
		case PBS_BATCH_FailOver:
			ns(DmnCmd_table_t) B = (ns(DmnCmd_table_t)) ns(Req_body(req));

			request->rq_ind.rq_shutdown = ns(DmnCmd_cmd(B));
			break;

		case PBS_BATCH_SignalJob:
			ns(Signal_table_t) B = (ns(Signal_table_t)) ns(Req_body(req));

			strncpy(request->rq_ind.rq_signal.rq_jid, (char *) ns(Signal_jobId(B)), PBS_MAXSVRJOBID);
			request->rq_ind.rq_signal.rq_jid[PBS_MAXSVRJOBID + 1] = '\0';

			strncpy(request->rq_ind.rq_signal.rq_signame, (char *) ns(Signal_sigName(B)), PBS_SIGNAMESZ);
			request->rq_ind.rq_signal.rq_signame[PBS_SIGNAMESZ + 1] = '\0';

			break;

		case PBS_BATCH_StatusJob:
#ifndef MOM
		case PBS_BATCH_StatusNode:
		case PBS_BATCH_StatusResv:
		case PBS_BATCH_StatusQue:
		case PBS_BATCH_StatusSvr:
		case PBS_BATCH_StatusSched:
		case PBS_BATCH_StatusRsc:
		case PBS_BATCH_StatusHook:
#endif
			ns(Stat_table_t) B = (ns(Stat_table_t)) ns(Req_body(req));

			CLEAR_HEAD(request->rq_ind.rq_status.rq_attr);

			request->rq_ind.rq_status.rq_id = strdup((char *) ns(Stat_jobIds(B)));
			if (request->rq_ind.rq_status.rq_id == NULL)
				return PBSE_SYSTEM;

			rc = decode_wire_svrattrl(ns(Stat_attrs(B)), &(request->rq_ind.rq_status.rq_attr));

			break;

		case PBS_BATCH_PySpawn:
			ns(Spawn_table_t) B = (ns(Spawn_table_t)) ns(Req_body(req));
			int i = 0;
			size_t len = 0;
			flatbuffers_string_vec_t strs;

			strncpy(request->rq_ind.rq_py_spawn.rq_jid, (char *) ns(Signal_jobId(B)), PBS_MAXSVRJOBID);
			request->rq_ind.rq_py_spawn.rq_jid[PBS_MAXSVRJOBID + 1] = '\0';

			request->rq_ind.rq_py_spawn.rq_argv = NULL;
			request->rq_ind.rq_py_spawn.rq_envp = NULL;

			strs = ns(Spawn_argv(B));
			len = flatbuffers_string_vec_len(strs);
			request->rq_ind.rq_py_spawn.rq_argv = (char **)calloc(sizeof(char **), len + 1);
			if (request->rq_ind.rq_py_spawn.rq_argv == NULL)
				return PBSE_SYSTEM;
			for (i = 0; i < len; i++) {
				request->rq_ind.rq_py_spawn.rq_argv[i] = strdup(flatbuffers_string_vec_at(strs, i));
				if (request->rq_ind.rq_py_spawn.rq_argv[i] == NULL)
					return PBSE_SYSTEM;
			}
			request->rq_ind.rq_py_spawn.rq_argv[++i] = NULL;

			strs = ns(Spawn_envp(B));
			len = flatbuffers_string_vec_len(strs);
			request->rq_ind.rq_py_spawn.rq_envp = (char **)calloc(sizeof(char **), len + 1);
			if (request->rq_ind.rq_py_spawn.rq_envp == NULL)
				return PBSE_SYSTEM;
			for (i = 0; i < len; i++) {
				request->rq_ind.rq_py_spawn.rq_envp[i] = strdup(flatbuffers_string_vec_at(strs, i));
				if (request->rq_ind.rq_py_spawn.rq_envp[i] == NULL)
					return PBSE_SYSTEM;
			}
			request->rq_ind.rq_py_spawn.rq_envp[++i] = NULL;

			break;

		case PBS_BATCH_AuthExternal:
			ns(Auth_table_t) B = (ns(Auth_table_t)) ns(Req_body(req));

			request->rq_ind.rq_auth_ext.rq_auth_type = ns(Auth_type(B));
			if (request->rq_ind.rq_auth_ext.rq_auth_type == AUTH_MUNGE) {
				ns(AuthMunge_table_t) B1 = (ns(AuthMunge_table_t)) ns(Auth_info(B));
				strncpy(request->rq_ind.rq_auth_ext.rq_authen_un.rq_munge.rq_authkey, (char *)ns(AuthMunge_key(B1)), PBS_AUTH_KEY_LEN);
				request->rq_ind.rq_auth_ext.rq_authen_un.rq_munge.rq_authkey[PBS_AUTH_KEY_LEN + 1] = '\0';
			}

			break;

#ifndef PBS_MOM
		case PBS_BATCH_RelnodesJob:
			ns(RelNodes_table_t) B = (ns(RelNodes_table_t)) ns(Req_body(req));

			strncpy(request->rq_ind.rq_relnodes.rq_jid, (char *) ns(RelNodes_jobId(B)), PBS_MAXSVRJOBID);
			request->rq_ind.rq_relnodes.rq_jid[PBS_MAXSVRJOBID + 1] = '\0';

			request->rq_ind.rq_relnodes.rq_node_list = strdup(ns(RelNodes_nodes(B)));
			if (request->rq_ind.rq_relnodes.rq_node_list == NULL)
				return PBSE_SYSTEM;

			break;

		case PBS_BATCH_MoveJob:
		case PBS_BATCH_OrderJob:
			ns(Move_table_t) B = (ns(Move_table_t)) ns(Req_body(req));

			strncpy(request->rq_ind.rq_move.rq_jid, (char *) ns(Move_jobId(B)), PBS_MAXSVRJOBID);
			request->rq_ind.rq_move.rq_jid[PBS_MAXSVRJOBID + 1] = '\0';

			strncpy(request->rq_ind.rq_move.rq_destin, (char *) ns(Move_dest(B)), PBS_MAXDEST);
			request->rq_ind.rq_move.rq_destin[PBS_MAXDEST + 1] = '\0';

			break;

		case PBS_BATCH_RunJob:
		case PBS_BATCH_AsyrunJob:
		case PBS_BATCH_StageIn:
		case PBS_BATCH_ConfirmResv:
			ns(Run_table_t) B = (ns(Run_table_t)) ns(Req_body(req));

			request->rq_ind.rq_run.rq_resch = (unsigned long) ns(Run_resch(B));

			strncpy(request->rq_ind.rq_run.rq_jid, (char *) ns(Run_jobId(B)), PBS_MAXSVRJOBID);
			request->rq_ind.rq_relnodes.rq_jid[PBS_MAXSVRJOBID + 1] = '\0';

			request->rq_ind.rq_run.rq_destin = strdup(ns(Run_dest(B)));
			if (request->rq_ind.rq_run.rq_destin == NULL)
				return PBSE_SYSTEM;

			break;

		case PBS_BATCH_DefSchReply:
			ns(SchedDefRep_table_t) B = (ns(SchedDefRep_table_t)) ns(Req_body(req));

			request->rq_ind.rq_defrpy.rq_cmd = (int) ns(SchedDefRep_cmd(B));
			request->rq_ind.rq_defrpy.rq_err = (int) ns(SchedDefRep_err(B));

			request->rq_ind.rq_defrpy.rq_txt = NULL;
			request->rq_ind.rq_defrpy.rq_id = NULL;

			request->rq_ind.rq_defrpy.rq_id = strdup(ns(SchedDefRep_id(B)));
			if (request->rq_ind.rq_defrpy.rq_id == NULL)
				return PBSE_SYSTEM;

			if (SchedDefRep_txt_is_present(B)) {
				request->rq_ind.rq_defrpy.rq_txt = strdup(ns(SchedDefResp_txt(B)));
				if (request->rq_ind.rq_defrpy.rq_txt == NULL)
					return PBSE_SYSTEM;

			break;

		case PBS_BATCH_SelectJobs:
		case PBS_BATCH_SelStat:
			ns(Select_table_t) B = (ns(Select_table_t)) ns(Req_body(req));

			CLEAR_HEAD(request->rq_ind.rq_select.rq_selattr);
			CLEAR_HEAD(request->rq_ind.rq_select.rq_rtnattr);

			rc = decode_wire_svrattrl(ns(Select_selAttrs(B)), &(request->rq_ind.rq_select.rq_selattr));
			if (rc == 0)
				rc = decode_wire_svrattrl(ns(Select_rtnAttrs(B)), &(request->rq_ind.rq_select.rq_rtnattr));

			break;

		case PBS_BATCH_TrackJob:
			ns(Track_table_t) B = (ns(Track_table_t)) ns(Req_body(req));

			request->rq_ind.rq_track.rq_hopcount = (int) ns(Track_hops(B));
			request->rq_ind.rq_track.rq_state[0] = (char) ns(Track_state(B));

			strncpy(request->rq_ind.rq_track.rq_jid, (char *) ns(Track_jobId(B)), PBS_MAXSVRJOBID);
			request->rq_ind.rq_track.rq_jid[PBS_MAXSVRJOBID + 1] = '\0';

			strncpy(request->rq_ind.rq_track.rq_location, (char *) ns(Track_location(B)), PBS_MAXDEST);
			request->rq_ind.rq_track.rq_location[PBS_MAXDEST + 1] = '\0';

			break;

		case PBS_BATCH_Rescq:
		case PBS_BATCH_ReserveResc:
		case PBS_BATCH_ReleaseResc:
			ns(RescQuery_table_t) B = (ns(RescQuery_table_t)) ns(Req_body(req));
			int i = 0;
			size_t len = 0;
			flatbuffers_string_vec_t strs;

			request->rq_ind.rq_rescq.rq_rhandle = (int) ns(RescQuery_handle(B));


			strs = ns(RescQuery_queries(B));
			len = flatbuffers_string_vec_len(strs);
			request->rq_ind.rq_rescq.rq_num = (int) len;

			request->rq_ind.rq_rescq.rq_list = NULL;
			request->rq_ind.rq_rescq.rq_list = (char **)calloc(sizeof(char **), len);
			if (request->rq_ind.rq_rescq.rq_list == NULL)
				return PBSE_SYSTEM;
			for (i = 0; i < len; i++) {
				request->rq_ind.rq_rescq.rq_list[i] = strdup(flatbuffers_string_vec_at(strs, i));
				if (request->rq_ind.rq_rescq.rq_list[i] == NULL)
					return PBSE_SYSTEM;
			}

			break;

		case PBS_BATCH_RegistDep:
			ns(Register_table_t) B = (ns(Register_table_t)) ns(Req_body(req));

			request->rq_ind.rq_register.rq_op = (int) ns(Register_op(B));
			request->rq_ind.rq_register.rq_dependtype = (int) ns(Register_type(B));
			request->rq_ind.rq_register.rq_cost = (long) ns(Register_cost(B));

			strncpy(request->rq_ind.rq_register.rq_child, (char *) ns(Register_child(B)), PBS_MAXCLTJOBID);
			request->rq_ind.rq_register.rq_child[PBS_MAXCLTJOBID + 1] = '\0';

			strncpy(request->rq_ind.rq_register.rq_parent, (char *) ns(Register_parent(B)), PBS_MAXSVRJOBID);
			request->rq_ind.rq_register.rq_parent[PBS_MAXSVRJOBID + 1] = '\0';

			strncpy(request->rq_ind.rq_register.rq_owner, (char *) ns(Register_owner(B)), PBS_MAXUSER);
			request->rq_ind.rq_register.rq_owner[PBS_MAXUSER + 1] = '\0';

			strncpy(request->rq_ind.rq_register.rq_svr, (char *) ns(Register_server(B)), PBS_MAXSERVERNAME);
			request->rq_ind.rq_register.rq_svr[PBS_MAXSERVERNAME + 1] = '\0';

			break;

		case PBS_BATCH_AuthenResvPort:
			ns(Auth_table_t) B = (ns(Auth_table_t)) ns(Req_body(req));

			request->rq_ind.rq_authen_resvport.rq_port = ns(AuthResvPort_port(ns(Auth_info(B))));

			break;

		case PBS_BATCH_PreemptJobs:
			ns(Preempt_table_t) B = (ns(Preempt_table_t)) ns(Req_body(req));
			ns(PreemptJob_vec_t) preempts = ns(Preempt_infos(B));

			len = ns(PreemptJob_vec_len(preempts));
			request->rq_ind.rq_preempt.count = (int) len;

			request->rq_ind.rq_preempt.ppj_list = NULL;
			request->rq_ind.rq_preempt.ppj_list = (preempt_job_info *)calloc(sizeof(struct preempt_job_info), len);
			if (request->rq_ind.rq_preempt.ppj_list == NULL)
				return PBSE_SYSTEM;

			for (i = 0; i < len; i++) {
				ns(PreemptJob_table_t) p = (ns(PreemptJob_table_t)) flatbuffers_string_vec_at(preempts, i);

				strncpy(request->rq_ind.rq_preempt.ppj_list[i].job_id, (char *) ns(PreemptJob_jid(p)), PBS_MAXSVRJOBID);
				request->rq_ind.rq_preempt.ppj_list[i].job_id[PBS_MAXSVRJOBID + 1] = '\0';
			}

			break;

#else	/* yes PBS_MOM */

		case PBS_BATCH_CopyHookFile:
			ns(CopyHook_table_t) B = (ns(CopyHook_table_t)) ns(Req_body(req));

			request->rq_ind.rq_hookfile.rq_sequence = (int) ns(CopyHook_seq(B));
			request->rq_ind.rq_hookfile.rq_size = (int) ns(CopyHook_size(B));

			strncpy(request->rq_ind.rq_hookfile.rq_filename, (char *)ns(CopyHook_filename(B)), MAXPATHLEN);
			request->rq_ind.rq_hookfile.rq_filename[MAXPATHLEN + 1] = '\0';

			request->rq_ind.rq_hookfile.rq_data = strdup((char *)ns(CopyHook_data(B)));
			if (request->rq_ind.rq_hookfile.rq_data == NULL)
				return PBSE_SYSTEM;

			if (strlen(request->rq_ind.rq_hookfile.rq_data) != request->rq_ind.rq_hookfile.rq_size) {
				free(request->rq_ind.rq_hookfile.rq_data);
				return PBSE_SYSTEM;
			}

			break;

		case PBS_BATCH_DelHookFile:
			ns(CopyHook_table_t) B = (ns(CopyHook_table_t)) ns(Req_body(req));

			strncpy(request->rq_ind.rq_hookfile.rq_filename, (char *)ns(CopyHook_filename(B)), MAXPATHLEN);
			request->rq_ind.rq_hookfile.rq_filename[MAXPATHLEN + 1] = '\0';

			break;

		case PBS_BATCH_CopyFiles:
		case PBS_BATCH_DelFiles:
			rc = decode_wire_CopyFiles(sfds, request);
			break;

		case PBS_BATCH_CopyFiles_Cred:
		case PBS_BATCH_DelFiles_Cred:
			flatbuffers_string_t cred;
			ns(CopyFileCred_table_t) B = (ns(CopyFileCred_table_t)) ns(Req_body(req));
			struct rq_cpyfile *files = &(request->rq_ind.rq_cpyfile_cred.rq_copyfile);

			CLEAR_HEAD(files->rq_pair);
			request->rq_ind.rq_cpyfile_cred.rq_pcred = NULL;

			request->rq_ind.rq_cpyfile_cred.rq_credtype = (int) ns(CopyFileCred_type(B));

			cred = ns(CopyFileCred_cred(B));
			request->rq_ind.rq_cpyfile_cred.rq_credlen = flatbuffers_string_len(cred);
			request->rq_ind.rq_cpyfile_cred.rq_pcred = (char *)malloc(request->rq_ind.rq_cpyfile_cred.rq_credlen + 1);
			if (request->rq_ind.rq_cpyfile_cred.rq_pcred == NULL)
				return PBSE_SYSTEM;

			memcpy(request->rq_ind.rq_cpyfile_cred.rq_pcred, (char *)cred, request->rq_ind.rq_cpyfile_cred.rq_credlen);
			request->rq_ind.rq_cpyfile_cred.rq_pcred[request->rq_ind.rq_cpyfile_cred.rq_credlen + 1] = '\0';

			rc = decode_wire_CopyFiles(ns(CopyFileCred_files(B)), files);

			break;

		case PBS_BATCH_Cred:
			ns(Cred_table_t) B = (ns(Cred_table_t)) ns(Req_body(req));

			request->rq_ind.rq_cred.rq_data = NULL;
			request->rq_ind.rq_cred.rq_type = (int) ns(Cred_type(B));
			request->rq_ind.rq_cred.rq_size = (size_t) ns(Cred_size(B));
			request->rq_ind.rq_cred.rq_validity = (long) ns(Cred_validity(B));

			strncpy(request->rq_ind.rq_cred.rq_jobid, (char *)ns(Cred_jobId(B)), PBS_MAXSVRJOBID);
			request->rq_ind.rq_cred.rq_jobid[PBS_MAXSVRJOBID + 1] = '\0';

			strncpy(request->rq_ind.rq_cred.rq_credid, (char *)ns(Cred_jobId(B)), PBS_MAXUSER);
			request->rq_ind.rq_cred.rq_credid[PBS_MAXUSER + 1] = '\0';

			request->rq_ind.rq_cred.rq_data = (char *)malloc(request->rq_ind.rq_cred.rq_size + 1);
			if (request->rq_ind.rq_cred.rq_data == NULL)
				return PBSE_SYSTEM;
			memcpy(request->rq_ind.rq_cred.rq_data, (char *)(ns(Cred_cred(B))), request->rq_ind.rq_cred.rq_size);
			request->rq_ind.rq_cred.rq_data[request->rq_ind.rq_cred.rq_size + 1] = '\0';

			break;

#endif	/* PBS_MOM */

		default:
			log_eventf(PBSEVENT_ERROR, PBS_EVENTCLASS_REQUEST, LOG_ERR,
				__func__, "%s: %d from %s", msg_nosupport,
				request->rq_type, request->rq_user);
			rc = PBSE_UNKREQ;
			break;
	}

	if (rc == 0) {
		/* Decode the Request Extension, if present */
		if (ns(Req_extend_is_present(req))) {
			request->rq_extend = strdup((char *) ns(Req_extend(req)));
			if (request->rq_extend == NULL)
				rc = PBSE_SYSTEM;
		}
	} else if (rc != PBSE_UNKREQ) {
		log_eventf(PBSEVENT_ERROR, PBS_EVENTCLASS_REQUEST, LOG_ERR, __func__,
				"Req Body bad, type %d", request->rq_type);
		rc = PBSE_PROTOCOL;
	}

	return (rc);
}
