/*
 * Copyright (C) 1994-2021 Altair Engineering, Inc.
 * For more information, contact Altair at www.altair.com.
 *
 * This file is part of both the OpenPBS software ("OpenPBS")
 * and the PBS Professional ("PBS Pro") software.
 *
 * Open Source License Information:
 *
 * OpenPBS is free software. You can redistribute it and/or modify it under
 * the terms of the GNU Affero General Public License as published by the
 * Free Software Foundation, either version 3 of the License, or (at your
 * option) any later version.
 *
 * OpenPBS is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
 * FITNESS FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public
 * License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Commercial License Information:
 *
 * PBS Pro is commercially licensed software that shares a common core with
 * the OpenPBS software.  For a copy of the commercial license terms and
 * conditions, go to: (http://www.pbspro.com/agreement.html) or contact the
 * Altair Legal Department.
 *
 * Altair's dual-license business model allows companies, individuals, and
 * organizations to create proprietary derivative works of OpenPBS and
 * distribute them - whether embedded or bundled with other software -
 * under a commercial license agreement.
 *
 * Use of Altair's trademarks, including but not limited to "PBS™",
 * "OpenPBS®", "PBS Professional®", and "PBS Pro™" and Altair's logos is
 * subject to Altair's trademark licensing policies.
 */


/**
 * @file    pbsd_db_func.c
 *
 * @brief
 * pbsd_db_func.c - contains functions to initialize several pbs data structures.
 *
 */
#include <pbs_config.h>   /* the master config generated by configure */

#include <sys/types.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <errno.h>
#include <fcntl.h>
#include <memory.h>
#include <signal.h>
#include <time.h>
#include <sys/stat.h>
#include <libutil.h>

#include <dirent.h>
#include <grp.h>
#include <netdb.h>
#include <pwd.h>
#include <unistd.h>
#include <sys/param.h>
#include <sys/resource.h>
#include <sys/time.h>

#include "libpbs.h"
#include "pbs_ifl.h"
#include "net_connect.h"
#include "log.h"
#include "list_link.h"
#include "attribute.h"
#include "server_limits.h"
#include "server.h"
#include "credential.h"
#include "ticket.h"
#include "batch_request.h"
#include "work_task.h"
#include "resv_node.h"
#include "job.h"
#include "queue.h"
#include "reservation.h"
#include "pbs_db.h"
#include "pbs_nodes.h"
#include "tracking.h"
#include "provision.h"
#include "avltree.h"
#include "svrfunc.h"
#include "acct.h"
#include "pbs_version.h"
#include "pbs_license.h"
#include "resource.h"
#include "pbs_python.h"
#include "hook.h"
#include "hook_func.h"
#include "pbs_share.h"
#include "pbs_undolr.h"

#ifndef SIGKILL
/* there is some weid stuff in gcc include files signal.h & sys/params.h */
#include <signal.h>
#endif

extern pid_t go_to_background();
void *svr_db_conn = NULL; /* server's global database connection pointer */

/**
 * @brief
 *	Attempt to mail a message to "mail_from" (administrator), shut down
 *	the database, close the log and exit the Server. Called when a database save fails.
 *	Panic shutdown of server due to database error. Closing database and log system.
 *
 */
void
panic_stop_db()
{
	char panic_stop_txt[] = "Panic shutdown of Server on database error. Please check PBS_HOME file system for no space condition.";

	log_err(-1, __func__, panic_stop_txt);
	svr_mailowner(0, 0, 0, panic_stop_txt);
	pbs_db_disconnect(svr_db_conn);
	log_close(1);
	exit(1);
}

/**
 * @brief
 * 		connect_to_db	- Try and continue forever till a successful database connection is made.
 *
 * @param[in]	background	- Process can attempt to connect in the background.
 * @return	int
 * @retval	0	- Success
 * @retval	Non-Zero	- Failure
 */
int
connect_to_db(int background)
{
	int rc;
	int db_delay;
	char *db_host;
	char *db_errmsg = NULL;
	int try_db = 0;
	void *conn = NULL;

	fprintf(stdout, "Connecting to PBS dataservice.");
	db_host = pbs_conf.pbs_data_service_host != NULL ? pbs_conf.pbs_data_service_host : pbs_default();

	while (1) {
#ifndef DEBUG
		fprintf(stdout, ".");
#endif
		pbs_db_disconnect(conn);
		rc = pbs_db_connect(&conn, db_host, pbs_conf.pbs_data_service_port, 0);
		if (!conn) {
			pbs_db_get_errmsg(rc, &db_errmsg);
			if (db_errmsg)
				log_event(PBSEVENT_SYSTEM | PBSEVENT_FORCE, PBS_EVENTCLASS_SERVER, LOG_CRIT, msg_daemonname, db_errmsg);
		}
		if (conn && rc == 0)
			break;

		db_delay = 2 + try_db;
		sleep(db_delay);
		update_svrlive();
#ifndef DEBUG
		if (background && try_db >= 5) {
			fprintf(stdout, "continuing in background.\n");
			if (go_to_background() == -1)
				return (2);
			background = 0;
		}
#endif
		try_db++;

		if (try_db >= 5) {
			sprintf(log_buffer, "Not able to connect to PBS data service, please ensure its running");
			log_errf(-1, msg_daemonname, log_buffer);
			svr_mailowner(0, 0, 1, log_buffer);
			try_db = 0;
		}
	}

	sprintf(log_buffer, "connected to PBS dataservice@%s", db_host);
	log_event(PBSEVENT_SYSTEM | PBSEVENT_FORCE, PBS_EVENTCLASS_SERVER, LOG_CRIT, msg_daemonname, log_buffer);
	fprintf(stdout, "%s\n", log_buffer);
	svr_db_conn = conn; /* use this connection */
	conn = NULL; /* ensure conn does not point to svr_db_conn any more */
	return 0;
}

/**
 * @brief
 *	Frees attribute list memory
 *
 * @param[in]	attr_list - List of pbs_db_attr_list_t objects
 *
 * @return      None
 *
 */
void
free_db_attr_list(pbs_db_attr_list_t *attr_list)
{
	if (attr_list->attr_count > 0) {
		free_attrlist(&attr_list->attrs);
		attr_list->attr_count = 0;
	}
}
