#!/bin/bash

# Copyright (C) 1994-2016 Altair Engineering, Inc.
# For more information, contact Altair at www.altair.com.
#
# This file is part of the PBS Professional ("PBS Pro") software.
#
# Open Source License Information:
#
# PBS Pro is free software. You can redistribute it and/or modify it under the
# terms of the GNU Affero General Public License as published by the Free 
# Software Foundation, either version 3 of the License, or (at your option) any 
# later version.
#
# PBS Pro is distributed in the hope that it will be useful, but WITHOUT ANY 
# WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.
# 
# You should have received a copy of the GNU Affero General Public License along 
# with this program.  If not, see <http://www.gnu.org/licenses/>.
# 
# Commercial License Information: 
#
# The PBS Pro software is licensed under the terms of the GNU Affero General 
# Public License agreement ("AGPL"), except where a separate commercial license 
# agreement for PBS Pro version 14 or later has been executed in writing with Altair.
#
# Altair’s dual-license business model allows companies, individuals, and 
# organizations to create proprietary derivative works of PBS Pro and distribute 
# them - whether embedded or bundled with other software - under a commercial 
# license agreement.
#
# Use of Altair’s trademarks, including but not limited to "PBS™", 
# "PBS Professional®", and "PBS Pro™" and Altair’s logos is subject to Altair's 
# trademark licensing policies.
#
# Terms of use for the software are available online at
# http://www.pbspro.com/UserArea/agreement.html, and are also
# included in our PBS Professional Administrator's Guide and 
# PBS Professional User's Guide


if [ "${TRAVIS_PULL_REQUEST}" == "false" ]; then
    echo "This is not pull request, exiting"
    exit 0
fi

cat >get_contributor.rb <<-EOF
require 'octokit'
client = Octokit::Client.new :access_token => ENV['GH_TOKEN']
puts client.pull_request(ENV['TRAVIS_REPO_SLUG'], ENV['TRAVIS_PULL_REQUEST'])[:user][:login]

EOF
contributor=$(ruby get_contributor.rb)
if [ "x${contributor}" == "x" ]; then
    echo "Failed to find github username"
    exit 1
fi

COMMENT_DATA="Hi @${contributor}, thanks for choosing to contribute to pbspro. 

In order to ensure the integrity of the repository, kindly sign your commit.
Please follow the instructions mentioned [here](https://pbspro.atlassian.net/wiki/display/DG/Signing+Your+Git+Commits)
"

cat >check_sign.rb <<-EOF
require 'octokit'
client = Octokit::Client.new :access_token => ENV['GH_TOKEN']
commits = client.pull_request_commits(ENV['TRAVIS_REPO_SLUG'], ENV['TRAVIS_PULL_REQUEST'], :accept => "application/vnd.github.cryptographer-preview")
is_verified = true
commits.each do |commit|
    unless commit[:commit][:verification][:verified]
        is_verified = false
    end
end

unless is_verified
    client.add_comment(ENV['TRAVIS_REPO_SLUG'], ENV['TRAVIS_PULL_REQUEST'], ENV['COMMENT_DATA'])
    exit 1
end
exit 0

EOF
ruby check_sign.rb

if [ $? -ne 0 ]; then
    echo "There are un-signed commits, so marking this build as failed."
    exit 1
else
    exit 0
fi
