language: c
sudo: required
services:
    - docker
env:
  matrix:
    - OS_TYPE=centos:7
    - OS_TYPE=opensuse:13.2
  global:
    secure: WoA8zIUe84QvZIWo0QFKJFdoeXmMnrBErcgYKQJSHwUj9mtzZECVb7vfTiRBBTkBjaJ/6rX4Pt4XN+QkxbahHd93yTCUpdgRIYWVtlhJ0Fr1CjmGDRQT+NUw6eGeC5oc9ksoBASWblS7kdvISEGcD0Riq23H79K7m1a4kNmbnzfsKK0BxT6EVhtgmXnosobv56ykJyc04kaKhgcGapSOB9fyatrjoSX/enNIrQrzf9r37ZVBatKDgChQ/J6n/ugV65HOw0MWN4TeNwLNEkX0zS7e2c9eBITJpZYk1gG4RVPh4WxPdT4JsFv3tuOb+0bh7YHmKFnYRAq3IhkQ7viQ5YMjHCJPxFrrV/Lg0RzkeVI6ZZ6SbLMQcKHRuu2SdEUyYvHMbiWTNTnd/kWtFsmHQInSkFzvShQTxvKsOFO0eHMBxnvkeCYMXeeuWKHcjpg64TiRyDJQaQItWiFdbnVg+MHZD8adB8+F59FwmpuJ4xMYYVVXPJSh4B4RN/1VbTuGUsPao/M1tvvMkT/MFmEExGkvcKrF2WXUSHbrM9/T0cUVv85Nf/IosoSrmUoGTDC2gTcSCJFjF9UT3xvJfQtBCYmZNGYVPJEc50mtP1q/SWawI/E4m3sFLfmBP9vyUU5akBZryjquvA3xu+ZopQcYNwhat1iWHh5KdX2sCP0MbqQ=
before_install:
    - .github/runchecks
    - docker pull ${OS_TYPE}
    - docker run -it -d -h testdev.pbspro.com --name testdev -v `pwd`:`pwd` --privileged -w `pwd` ${OS_TYPE} /bin/bash
    - docker ps -a
    - export DOCKER_EXEC="docker exec -it testdev"
install:
    - '[ "${OS_TYPE}" == "centos:7" ] && travis_retry ${DOCKER_EXEC} yum -y update || true'
    - '[ "${OS_TYPE}" == "centos:7" ] && travis_retry ${DOCKER_EXEC} yum -y install yum-utils epel-release rpmdevtools || true'
    - '[ "${OS_TYPE}" == "opensuse:13.2" ] && travis_retry ${DOCKER_EXEC} zypper -n ar -f -G http://download.opensuse.org/repositories/devel:/tools/openSUSE_13.2/devel:tools.repo || true'
    - '[ "${OS_TYPE}" == "opensuse:13.2" ] && travis_retry ${DOCKER_EXEC} zypper -n ref || true'
    - '[ "${OS_TYPE}" == "opensuse:13.2" ] && travis_retry ${DOCKER_EXEC} zypper -n install rpmdevtools || true'
    - ${DOCKER_EXEC} rpmdev-setuptree
    - '[ "${OS_TYPE}" == "centos:7" ] && travis_retry ${DOCKER_EXEC} yum-builddep -y ./pbspro.spec || true'
    - '[ "${OS_TYPE}" == "opensuse:13.2" ] && travis_retry ${DOCKER_EXEC} /bin/bash -c "zypper -n install \$(rpmspec --buildrequires -q pbspro.spec)" || true'
    - ${DOCKER_EXEC} ./autogen.sh
    - ${DOCKER_EXEC} ./configure
    - ${DOCKER_EXEC} make dist
    - ${DOCKER_EXEC} /bin/bash -c "cp pbspro-*.tar.gz /root/rpmbuild/SOURCES/"
    - ${DOCKER_EXEC} rpmbuild -bb pbspro.spec
    - '[ "${OS_TYPE}" == "centos:7" ] && travis_retry ${DOCKER_EXEC} /bin/bash -c "yum -y install /root/rpmbuild/RPMS/x86_64/pbspro-server-*.x86_64.rpm" || true'
    - '[ "${OS_TYPE}" == "opensuse:13.2" ] && travis_retry ${DOCKER_EXEC} /bin/bash -c "zypper -n install /root/rpmbuild/RPMS/x86_64/pbspro-server-*.x86_64.rpm" || true'
    - ${DOCKER_EXEC} /etc/init.d/pbs start
    - '[ "${OS_TYPE}" == "centos:7" ] && travis_retry ${DOCKER_EXEC} yum -y install python-pip sudo which net-tools || true'
    - '[ "${OS_TYPE}" == "opensuse:13.2" ] && travis_retry ${DOCKER_EXEC} zypper -n install python-pip sudo which net-tools || true'
    - ${DOCKER_EXEC} /bin/bash -c "cd test/fw; pip install -r requirements.txt ."
    - ${DOCKER_EXEC} pbs_config --make-ug
    - ${DOCKER_EXEC} /bin/bash -c "cd test/tests; pbs_benchpress -l INFOCLI2 -o ../../ptl.txt"
script: true

