/*
 * Copyright (C) 1994-2020 Altair Engineering, Inc.
 * For more information, contact Altair at www.altair.com.
 *
 * This file is part of the PBS Professional ("PBS Pro") software.
 *
 * Open Source License Information:
 *
 * PBS Pro is free software. You can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * PBS Pro is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Commercial License Information:
 *
 * For a copy of the commercial license terms and conditions,
 * go to: (http://www.pbspro.com/UserArea/agreement.html)
 * or contact the Altair Legal Department.
 *
 * Altair’s dual-license business model allows companies, individuals, and
 * organizations to create proprietary derivative works of PBS Pro and
 * distribute them - whether embedded or bundled with other software -
 * under a commercial license agreement.
 *
 * Use of Altair’s trademarks, including but not limited to "PBS™",
 * "PBS Professional®", and "PBS Pro™" and Altair’s logos is subject to Altair's
 * trademark licensing policies.
 *
 */
#include <pbs_config.h>   /* the master config generated by configure */
#include <errno.h>
#include "pbs_ifl.h"
#include "libpbs.h"
#include "log.h"
#include "placementsets.h"

extern char *msg_nosupport;

static int wire_decode_attropl(ns(Attribute_vec_t), struct attropl **);
static int wire_decode_CopyFiles(ns(CopyFile_table_t), struct rq_cpyfile *);

#define COPYSTR(dest, src, len) { \
	memset(dest, '\0', len); \
	strncpy(dest, (char *)src, len - 1); \
}

#define COPYSTR_B(dest, src) COPYSTR(dest, src, sizeof(dest))

#define COPYSTR_M(dest, src, len) { \
	dest = (char *)malloc(len); \
	if (dest == NULL) \
		return PBSE_SYSTEM; \
	memcpy(dest, src, len); \
}

#define COPYSTR_S(dest, src) { \
	dest = strdup((char *)src); \
	if (dest == NULL) \
		return PBSE_SYSTEM; \
}

/**
 * @brief
 *	decode a list of PBS API "attropl" structures from given flatbuffer
 *	The space for the attrl structures is allocated as needed.
 *
 * @param[in] attrs - flatbuffer attrs vec
 * @param[in] ppatt - pointer to list of attributes to be filled
 *
 * @return int
 * @retval PBS_NONE  - Success
 * @retval !PBS_NONE - Failure
 */
static int
wire_decode_attropl(ns(Attribute_vec_t) attrs, struct attropl **ppatt)
{
	int i = 0;
	struct attropl *patprior = NULL;
	struct attropl *pat = NULL;
	size_t attrs_len = ns(Attribute_vec_len(attrs));

	for (i = 0; i < attrs_len; i++) {
		ns(Attribute_table_t) attr = ns(Attribute_vec_at(attrs, i));
		pat = malloc(sizeof(struct attropl));
		if (pat == 0)
			return PBSE_SYSTEM;

		pat->name = strdup((char *) ns(Attribute_name(attr)));
		if (pat->name != NULL)
			goto dwa_err;

		if (ns(Attribute_resc_is_present(attr))) {
			pat->resource = strdup((char *) ns(Attribute_resc(attr)));
			if (pat->resource != NULL)
				goto dwa_err;
		}

		pat->value = strdup((char *) ns(Attribute_value(attr)));
		if (pat->value != NULL)
			goto dwa_err;
		pat->op = (enum batch_op) ns(Attribute_op(attr));
		if (i == 0) {
			*ppatt = pat;
		} else {
			patprior->next = pat;
		}
		patprior = pat;
	}

	return PBSE_NONE;

dwa_err:
	// FIXME: rename this to small case
	PBS_free_aopl(pat);
	return PBSE_SYSTEM;
}

/**
 * @brief
 *	decode a list of svrattrl structures from given flatbuffer
 *	The space for the svrattrl structures is allocated as needed.
 *
 * @param[in] attrs - flatbuffer attrs vec
 * @param[in] phead - pointer to list of attributes to be filled
 *
 * @return int
 * @retval PBS_NONE  - Success
 * @retval !PBS_NONE - Failure
 */
int
wire_decode_svrattrl(ns(Attribute_vec_t) attrs, pbs_list_head *phead)
{
	unsigned int hasresc;
	size_t ls;
	unsigned int data_len;
	unsigned int numattr;
	int rc;
	size_t tsize;
	int i = 0;
	size_t attrs_len = ns(Attribute_vec_len(attrs));

	CLEAR_HEAD((*phead));

	for (i = 0; i < attrs_len; i++) {
		ns(Attribute_table_t) attr = ns(Attribute_vec_at(attrs, i));
		svrattrl *psvrat = NULL;
		char *name = (char *) ns(Attribute_name(attr));
		size_t nlen = strlen(name) + 1;
		char *value = (char *) ns(Attribute_value(attr));
		size_t vlen = strlen(value) + 1;
		char *resc = NULL;
		size_t rlen = 0;
		size_t tsize = sizeof(svrattrl) + nlen + vlen;

		if (ns(Attribute_resc_is_present(attr))) {
			resc = (char *) ns(Attribute_resc(attr));
			rlen = strlen(resc) + 1;
			tsize += rlen;
		}

		if ((psvrat = (svrattrl *)malloc(tsize)) == NULL)
			return PBSE_SYSTEM;

		CLEAR_LINK(psvrat->al_link);
		psvrat->al_sister = NULL;
		psvrat->al_atopl.next = NULL;
		psvrat->al_tsize = tsize;
		psvrat->al_name = (char *)psvrat + sizeof(svrattrl);
		psvrat->al_resc = psvrat->al_name + nlen;
		psvrat->al_value = psvrat->al_resc + rlen;
		psvrat->al_nameln = nlen;
		psvrat->al_rescln = rlen;
		psvrat->al_valln = vlen;
		psvrat->al_flags = 0;
		psvrat->al_refct = 1;
		psvrat->al_op = (enum batch_op) ns(Attribute_op(attr));

		COPYSTR(psvrat->al_name, name, nlen);

		if (rlen > 0) {
			COPYSTR(psvrat->al_resc, resc, rlen);
		}

		COPYSTR(psvrat->al_value, value, vlen);

		append_link(phead, &(psvrat->al_link), psvrat);
	}
	return PBSE_NONE;
}

/**
 * @brief
 * 	decode a Copy Files Dependency Batch Request
 *
 *	This request is used by the server ONLY.
 *	The rq_cpyfile structure pointed to by pcf must already exist.
 *
 * @param[in] B - copy file table ref from flatbuffer
 * @param[in] pcf - pointer to rq_cpyfile structure
 *
 * @return int
 * @retval 0 - success
 * @retval !0 - error
 */
static int
wire_decode_CopyFiles(ns(CopyFile_table_t) B, struct rq_cpyfile *pcf)
{
	int pair_ct = 0;
	struct rqfpair *ppair = NULL;
	ns(FilePair_vec_t) pairs;
	int i = 0;

	CLEAR_HEAD(pcf->rq_pair);

	COPYSTR_B(pcf->rq_jobid, ns(CopyFile_jobId(B)));
	COPYSTR_B(pcf->rq_owner, ns(CopyFile_owner(B)));
	COPYSTR_B(pcf->rq_user, ns(CopyFile_user(B)));
	COPYSTR(pcf->rq_group, ns(CopyFile_group(B)), sizeof(pcf->rq_group));

	pcf->rq_dir = (int) ns(CopyFile_flags(B));

	pairs = ns(CopyFile_pairs(B));
	pair_ct = (int) ns(FilePair_vec_len(pairs));

	for (i = 0; i < pair_ct; i++) {
		ns(FilePair_table_t) pair = ns(FilePair_vec_at(pairs, i));

		ppair = (struct rqfpair *) calloc(sizeof(struct rqfpair), 1);
		if (ppair == NULL)
			return PBSE_SYSTEM;

		CLEAR_LINK(ppair->fp_link);

		ppair->fp_flag = (int) ns(FilePair_flag(pair));

		ppair->fp_rmt = strdup((char *) ns(FilePair_remote(pair)));
		if (ppair->fp_rmt == NULL) {
			free(ppair);
			return PBSE_SYSTEM;
		}

		ppair->fp_local = strdup((char *) ns(FilePair_local(pair)));
		if (ppair->fp_local == NULL) {
			free(ppair->fp_rmt);
			free(ppair);
			return PBSE_SYSTEM;
		}

		append_link(&(pcf->rq_pair), &(ppair->fp_link), ppair);
	}
	return 0;
}

/**
 * @brief
 *      Decode PBS batch request to authenticate based on external (non-resv-port) mechanisms.
 *      The batch request contains type and the auth data.
 *
 * @param [in] sock socket connection
 * @param [in] preq PBS bath request
 * @return in
 * @retval 0 on success
 * @retval > 0 on failure
 */
int
decode_DIS_Authenticate(int sock, struct batch_request *preq)
{
	int rc;
	int len = 0;


	len = disrsi(sock, &rc);
	if (rc != DIS_SUCCESS)
		return (rc);
	if (len <= 0) {
		return DIS_PROTO;
	}
	rc = disrfst(sock, len, preq->rq_ind.rq_auth.rq_auth_method);
	if (rc != DIS_SUCCESS)
		return (rc);
	preq->rq_ind.rq_auth.rq_auth_method[MAXAUTHNAME] = '\0';

	preq->rq_ind.rq_auth.rq_encrypt_mode = disrui(sock, &rc);
	if (rc != DIS_SUCCESS)
		return (rc);

	if (preq->rq_ind.rq_auth.rq_encrypt_mode != ENCRYPT_DISABLE) {
		len = disrsi(sock, &rc);
		if (rc != DIS_SUCCESS)
			return (rc);
		if (len <= 0) {
			return DIS_PROTO;
		}
		rc = disrfst(sock, len, preq->rq_ind.rq_auth.rq_encrypt_method);
		if (rc != DIS_SUCCESS)
			return (rc);
		preq->rq_ind.rq_auth.rq_encrypt_method[MAXAUTHNAME] = '\0';
	} else {
		preq->rq_ind.rq_auth.rq_encrypt_method[0] = '\0';
	}

	preq->rq_ind.rq_auth.rq_port = disrui(sock, &rc);
	if (rc != DIS_SUCCESS)
		return (rc);

	return (rc);
}

/**
 * @brief
 * 	Read in an DIS encoded request from the network
 * 	and decodes it:
 *	Read and decode the request into the request structures
 *
 * @see
 * 	process_request and read_fo_request
 *
 * @param[in] sfds	- the socket descriptor
 * @param[in,out] request - will contain the decoded request
 *
 * @return int
 * @retval 0 	if request read ok, batch_request pointed to by request is updated.
 * @retval -1 	if EOF (no request but no error)
 * @retval >0 	if errors ( a PBSE_ number)
 */
// FIXME: Move this to wire_decode_batch_request.c
int
dis_request_read(int sfds, struct batch_request *request)
{
	int rc = 0;
	void *buf = NULL;
	size_t bufsz = 0;
	ns(Req_table_t) req;
	ns(Header_table_t) hdr;
	uint16_t proto;
	uint16_t version;

	if (request->prot == PROT_TPP)
		DIS_tpp_funcs();
	else
		DIS_tcp_funcs();

	//FIXME: get loaded buf for read with size here
	rc = ns(Req_verify_as_root(buf, bufsz));
	if (rc != 0) {
		log_eventf(PBSEVENT_DEBUG, PBS_EVENTCLASS_REQUEST, LOG_DEBUG, __func__,
				"Bad request, errno %d, wire error %d", errno, rc);
		return PBSE_PROTOCOL;
	}

	req = (ns(Req_table_t)) ns(Req_as_root(buf));
	hdr = (ns(Header_table_t)) ns(Req_hdr(req));
	proto = (uint16_t) ns(Header_protType(hdr));
	version = (uint16_t) ns(Header_version(hdr));

	if (proto != ns(ProtType_Batch) || version > PBS_BATCH_PROT_VER)
		return PBSE_PROTOCOL;

	request->rq_type = (int)ns(Header_reqId(hdr));

	COPYSTR_B(request->rq_user, ns(Header_user(hdr)));

	/* Decode the Request Body based on the type */
	switch (request->rq_type) {
		case PBS_BATCH_Connect:
			break;

		case PBS_BATCH_Disconnect:
			return (-1); /* set EOF return */

		case PBS_BATCH_QueueJob:
		case PBS_BATCH_SubmitResv:
			ns(Qjob_table_t) B = (ns(Qjob_table_t)) ns(Req_body(req));

			COPYSTR_B(request->rq_ind.rq_queuejob.rq_jid, ns(Qjob_jobId(B)));
			COPYSTR_B(request->rq_ind.rq_queuejob.rq_destin, ns(Qjob_destin(B)));
			rc = wire_decode_svrattrl(ns(Qjob_attrs(B)), &(request->rq_ind.rq_queuejob.rq_attr));
			break;

		case PBS_BATCH_JobCred:
			ns(Cred_table_t) B = (ns(Cred_table_t)) ns(Req_body(req));

			request->rq_ind.rq_jobcred.rq_type = (int) ns(Cred_type(B));
			request->rq_ind.rq_jobcred.rq_size = (int) ns(Cred_size(B));
			COPYSTR_M(request->rq_ind.rq_jobcred.rq_data, (char *)(ns(Cred_cred(B))), request->rq_ind.rq_jobcred.rq_size);

			break;

		case PBS_BATCH_UserCred:
			ns(Cred_table_t) B = (ns(Cred_table_t)) ns(Req_body(req));

			request->rq_ind.rq_usercred.rq_type = (int) ns(Cred_type(B));
			request->rq_ind.rq_usercred.rq_size = (int) ns(Cred_size(B));
			COPYSTR_B(request->rq_ind.rq_usercred.rq_user, ns(Cred_user(B)));
			COPYSTR_M(request->rq_ind.rq_usercred.rq_data, (char *)(ns(Cred_data(B))), request->rq_ind.rq_usercred.rq_size);

			break;

		case PBS_BATCH_UserMigrate:
			ns(UserMigrate_table_t) B = (ns(UserMigrate_table_t)) ns(Req_body(req));

			COPYSTR_B(request->rq_ind.rq_user_migrate.rq_tohost, ns(UserMigrate_tohost(B)));

			break;

		case PBS_BATCH_jobscript:
		case PBS_BATCH_MvJobFile:
			ns(JobFile_table_t) B = (ns(JobFile_table_t)) ns(Req_body(req));

			request->rq_ind.rq_jobfile.rq_sequence = (int) ns(JobFile_seq(B));
			request->rq_ind.rq_jobfile.rq_type = (int) ns(JobFile_type(B));
			request->rq_ind.rq_jobfile.rq_size = (long) ns(JobFile_size(B));
			COPYSTR_B(request->rq_ind.rq_jobfile.rq_jobid, ns(JobFile_jobId(B)));
			COPYSTR_M(request->rq_ind.rq_jobfile.rq_data, (char *)(ns(Cred_data(B))), request->rq_ind.rq_jobfile.rq_size);

			break;

		case PBS_BATCH_RdytoCommit:
		case PBS_BATCH_Commit:
		case PBS_BATCH_Rerun:
#ifndef MOM
		case PBS_BATCH_LocateJob:
#endif
			ns(JobId_table_t) B = (ns(JobId_table_t)) ns(Req_body(req));

			COPYSTR_B(request->rq_ind.rq_commit, ns(JobFile_jobId(B)));

			break;

		case PBS_BATCH_DeleteJob:
		case PBS_BATCH_DeleteResv:
		case PBS_BATCH_ResvOccurEnd:
		case PBS_BATCH_HoldJob:
		case PBS_BATCH_ModifyJob:
#ifndef MOM
		case PBS_BATCH_Manager:
		case PBS_BATCH_ReleaseJob:
		case PBS_BATCH_ModifyResv:
#endif
			ns(Manage_table_t) B = (ns(Manage_table_t)) ns(Req_body(req));

			request->rq_ind.rq_manager.rq_cmd = (int) ns(strncpyManage_cmd(B));
			request->rq_ind.rq_manager.rq_objtype = (int) ns(Manage_objType(B));
			COPYSTR_B(request->rq_ind.rq_manager.rq_objname, ns(Manager_objName(B)));
			rc = wire_decode_svrattrl(ns(Manager_attrs(B)), &(request->rq_ind.rq_manager.rq_attr));

			break;

		case PBS_BATCH_MessJob:
			ns(Msg_table_t) B = (ns(Msg_table_t)) ns(Req_body(req));

			request->rq_ind.rq_message.rq_file = (int) ns(Msg_FileInd(B));
			COPYSTR_B(request->rq_ind.rq_message.rq_jid, ns(Msg_jobId(B)));
			COPYSTR_S(request->rq_ind.rq_message.rq_text, ns(Msg_text(B)));

			break;

		case PBS_BATCH_Shutdown:
		case PBS_BATCH_FailOver:
			ns(DmnCmd_table_t) B = (ns(DmnCmd_table_t)) ns(Req_body(req));

			request->rq_ind.rq_shutdown = (int) ns(DmnCmd_cmd(B));

			break;

		case PBS_BATCH_SignalJob:
			ns(Signal_table_t) B = (ns(Signal_table_t)) ns(Req_body(req));

			COPYSTR_B(request->rq_ind.rq_signal.rq_jid, ns(Signal_jobId(B)));
			COPYSTR_B(request->rq_ind.rq_signal.rq_signame, ns(Signal_sigName(B)));

			break;

		case PBS_BATCH_StatusJob:
#ifndef MOM
		case PBS_BATCH_StatusNode:
		case PBS_BATCH_StatusResv:
		case PBS_BATCH_StatusQue:
		case PBS_BATCH_StatusSvr:
		case PBS_BATCH_StatusSched:
		case PBS_BATCH_StatusRsc:
		case PBS_BATCH_StatusHook:
#endif
			ns(Stat_table_t) B = (ns(Stat_table_t)) ns(Req_body(req));

			COPYSTR_S(request->rq_ind.rq_status.rq_id, ns(Stat_jobIds(B)));
			rc = wire_decode_svrattrl(ns(Stat_attrs(B)), &(request->rq_ind.rq_status.rq_attr));

			break;

		case PBS_BATCH_PySpawn:
			ns(Spawn_table_t) B = (ns(Spawn_table_t)) ns(Req_body(req));
			int i = 0;
			size_t len = 0;
			flatbuffers_string_vec_t strs;

			COPYSTR_B(request->rq_ind.rq_py_spawn.rq_jid, ns(Signal_jobId(B)));

			request->rq_ind.rq_py_spawn.rq_argv = NULL;
			request->rq_ind.rq_py_spawn.rq_envp = NULL;

			strs = ns(Spawn_argv(B));
			len = flatbuffers_string_vec_len(strs);
			request->rq_ind.rq_py_spawn.rq_argv = (char **)calloc(sizeof(char **), len + 1);
			if (request->rq_ind.rq_py_spawn.rq_argv == NULL)
				return PBSE_SYSTEM;
			for (i = 0; i < len; i++) {
				COPYSTR_S(request->rq_ind.rq_py_spawn.rq_argv[i], flatbuffers_string_vec_at(strs, i))
			}

			strs = ns(Spawn_envp(B));
			len = flatbuffers_string_vec_len(strs);
			request->rq_ind.rq_py_spawn.rq_envp = (char **)calloc(sizeof(char **), len + 1);
			if (request->rq_ind.rq_py_spawn.rq_envp == NULL)
				return PBSE_SYSTEM;
			for (i = 0; i < len; i++) {
				COPYSTR_S(request->rq_ind.rq_py_spawn.rq_envp[i], flatbuffers_string_vec_at(strs, i))
			}

			break;
		// FIXME: Add PBS_BATCH_Authenticate

#ifndef PBS_MOM
		case PBS_BATCH_RelnodesJob:
			ns(RelNodes_table_t) B = (ns(RelNodes_table_t)) ns(Req_body(req));

			COPYSTR_B(request->rq_ind.rq_relnodes.rq_jid, ns(RelNodes_jobId(B)));
			COPYSTR_S(request->rq_ind.rq_relnodes.rq_node_list, ns(RelNodes_nodes(B)));

			break;

		case PBS_BATCH_MoveJob:
		case PBS_BATCH_OrderJob:
			ns(Move_table_t) B = (ns(Move_table_t)) ns(Req_body(req));

			COPYSTR_B(request->rq_ind.rq_move.rq_jid, ns(Move_jobId(B)));
			COPYSTR_B(request->rq_ind.rq_move.rq_destin, ns(Move_dest(B)));

			break;

		case PBS_BATCH_RunJob:
		case PBS_BATCH_AsyrunJob:
		case PBS_BATCH_StageIn:
		case PBS_BATCH_ConfirmResv:
			ns(Run_table_t) B = (ns(Run_table_t)) ns(Req_body(req));

			request->rq_ind.rq_run.rq_resch = (unsigned long) ns(Run_resch(B));
			COPYSTR_B(request->rq_ind.rq_run.rq_jid, ns(Run_jobId(B)));
			COPYSTR_S(request->rq_ind.rq_run.rq_destin, ns(Run_dest(B)));

			break;

		case PBS_BATCH_DefSchReply:
			ns(SchedDefRep_table_t) B = (ns(SchedDefRep_table_t)) ns(Req_body(req));

			request->rq_ind.rq_defrpy.rq_cmd = (int) ns(SchedDefRep_cmd(B));
			request->rq_ind.rq_defrpy.rq_err = (int) ns(SchedDefRep_err(B));
			request->rq_ind.rq_defrpy.rq_txt = NULL;
			COPYSTR_S(request->rq_ind.rq_defrpy.rq_id, ns(SchedDefRep_id(B)));
			if (SchedDefRep_txt_is_present(B))
				COPYSTR_S(request->rq_ind.rq_defrpy.rq_txt, ns(SchedDefResp_txt(B)));

			break;

		case PBS_BATCH_SelectJobs:
		case PBS_BATCH_SelStat:
			ns(Select_table_t) B = (ns(Select_table_t)) ns(Req_body(req));

			rc = wire_decode_svrattrl(ns(Select_selAttrs(B)), &(request->rq_ind.rq_select.rq_selattr));
			if (rc == PBSE_NONE)
				rc = wire_decode_svrattrl(ns(Select_rtnAttrs(B)), &(request->rq_ind.rq_select.rq_rtnattr));

			break;

		case PBS_BATCH_TrackJob:
			ns(Track_table_t) B = (ns(Track_table_t)) ns(Req_body(req));

			request->rq_ind.rq_track.rq_hopcount = (int) ns(Track_hops(B));
			request->rq_ind.rq_track.rq_state[0] = (char) ns(Track_state(B));
			COPYSTR_B(request->rq_ind.rq_track.rq_jid, ns(Track_jobId(B)));
			COPYSTR_B(request->rq_ind.rq_track.rq_location, ns(Track_location(B)));

			break;

		case PBS_BATCH_Rescq:
		case PBS_BATCH_ReserveResc:
		case PBS_BATCH_ReleaseResc:
			ns(RescQuery_table_t) B = (ns(RescQuery_table_t)) ns(Req_body(req));
			int i = 0;
			flatbuffers_string_vec_t strs = ns(RescQuery_queries(B));
			size_t len = flatbuffers_string_vec_len(strs);

			request->rq_ind.rq_rescq.rq_num = (int) len;
			request->rq_ind.rq_rescq.rq_rhandle = (int) ns(RescQuery_handle(B));
			request->rq_ind.rq_rescq.rq_list = (char **)calloc(sizeof(char **), len);
			if (request->rq_ind.rq_rescq.rq_list == NULL)
				return PBSE_SYSTEM;
			for (i = 0; i < len; i++) {
				COPYSTR_S(request->rq_ind.rq_rescq.rq_list[i], flatbuffers_string_vec_at(strs, i));
			}

			break;

		case PBS_BATCH_RegistDep:
			ns(Register_table_t) B = (ns(Register_table_t)) ns(Req_body(req));

			request->rq_ind.rq_register.rq_op = (int) ns(Register_op(B));
			request->rq_ind.rq_register.rq_dependtype = (int) ns(Register_type(B));
			request->rq_ind.rq_register.rq_cost = (long) ns(Register_cost(B));
			COPYSTR_B(request->rq_ind.rq_register.rq_child, ns(Register_child(B)));
			COPYSTR_B(request->rq_ind.rq_register.rq_parent, ns(Register_parent(B)));
			COPYSTR_B(request->rq_ind.rq_register.rq_owner, ns(Register_owner(B)));
			COPYSTR_B(request->rq_ind.rq_register.rq_svr, ns(Register_server(B)));

			break;

		case PBS_BATCH_PreemptJobs:
			ns(Preempt_table_t) B = (ns(Preempt_table_t)) ns(Req_body(req));
			ns(PreemptJob_vec_t) preempts = ns(Preempt_infos(B));

			len = ns(PreemptJob_vec_len(preempts));
			request->rq_ind.rq_preempt.count = (int) len;
			request->rq_ind.rq_preempt.ppj_list = (preempt_job_info *)calloc(sizeof(struct preempt_job_info), len);
			if (request->rq_ind.rq_preempt.ppj_list == NULL)
				return PBSE_SYSTEM;

			for (i = 0; i < len; i++) {
				// FIXME: below
				ns(PreemptJob_table_t) p = (ns(PreemptJob_table_t)) flatbuffers_string_vec_at(preempts, i);

				COPYSTR_B(request->rq_ind.rq_preempt.ppj_list[i].job_id, ns(PreemptJob_jid(p)));
			}

			break;

#else	/* yes PBS_MOM */

		case PBS_BATCH_CopyHookFile:
			ns(CopyHook_table_t) B = (ns(CopyHook_table_t)) ns(Req_body(req));

			request->rq_ind.rq_hookfile.rq_sequence = (int) ns(CopyHook_seq(B));
			request->rq_ind.rq_hookfile.rq_size = (int) ns(CopyHook_size(B));
			COPYSTR_B(request->rq_ind.rq_hookfile.rq_filename, ns(CopyHook_filename(B)));
			COPYSTR_S(request->rq_ind.rq_hookfile.rq_data, ns(CopyHook_data(B)));

			break;

		case PBS_BATCH_DelHookFile:
			ns(CopyHook_table_t) B = (ns(CopyHook_table_t)) ns(Req_body(req));

			COPYSTR_B(request->rq_ind.rq_hookfile.rq_filename, ns(CopyHook_filename(B)));

			break;

		case PBS_BATCH_CopyFiles:
		case PBS_BATCH_DelFiles:
			rc = wire_decode_CopyFiles(sfds, request);
			break;

		case PBS_BATCH_CopyFiles_Cred:
		case PBS_BATCH_DelFiles_Cred:
			flatbuffers_string_t cred;
			ns(CopyFileCred_table_t) B = (ns(CopyFileCred_table_t)) ns(Req_body(req));
			struct rq_cpyfile *files = &(request->rq_ind.rq_cpyfile_cred.rq_copyfile);

			request->rq_ind.rq_cpyfile_cred.rq_credtype = (int) ns(CopyFileCred_type(B));
			cred = ns(CopyFileCred_cred(B));
			request->rq_ind.rq_cpyfile_cred.rq_credlen = flatbuffers_string_len(cred);
			COPYSTR_M(request->rq_ind.rq_cpyfile_cred.rq_pcred, ns(CopyFileCred_cred(B)), request->rq_ind.rq_cpyfile_cred.rq_credlen);
			rc = wire_decode_CopyFiles(ns(CopyFileCred_files(B)), files);

			break;

		case PBS_BATCH_Cred:
			ns(Cred_table_t) B = (ns(Cred_table_t)) ns(Req_body(req));

			request->rq_ind.rq_cred.rq_data = NULL;
			request->rq_ind.rq_cred.rq_type = (int) ns(Cred_type(B));
			request->rq_ind.rq_cred.rq_size = (size_t) ns(Cred_size(B));
			request->rq_ind.rq_cred.rq_validity = (long) ns(Cred_validity(B));
			COPYSTR_B(request->rq_ind.rq_cred.rq_jobid, ns(Cred_jobId(B)));
			COPYSTR_B(request->rq_ind.rq_cred.rq_credid, ns(Cred_jobId(B)));
			COPYSTR_M(request->rq_ind.rq_cred.rq_data, ns(Cred_cred(B)), request->rq_ind.rq_cred.rq_size);

			break;

#endif	/* PBS_MOM */

		default:
			log_eventf(PBSEVENT_ERROR, PBS_EVENTCLASS_REQUEST, LOG_ERR,
				__func__, "%s: %d from %s", msg_nosupport,
				request->rq_type, request->rq_user);
			rc = PBSE_UNKREQ;
			break;
	}

	if (rc == 0) {
		/* Decode the Request Extension, if present */
		if (ns(Req_extend_is_present(req))) {
			COPYSTR_S(request->rq_extend, ns(Req_extend(req)));
		}
	} else if (rc != PBSE_UNKREQ) {
		log_eventf(PBSEVENT_ERROR, PBS_EVENTCLASS_REQUEST, LOG_ERR, __func__,
				"Req Body bad, type %d", request->rq_type);
		rc = PBSE_PROTOCOL;
	}

	return (rc);
}

// FIXME: move this to wire_decode_im/is_request.c
static vnl_t	*vn_decode_DIS_V3(int, int *);
static vnl_t	*vn_decode_DIS_V4(int, int *);
static int	vn_encode_DIS_V4(int, vnl_t *);
static vnl_t	*free_and_return(vnl_t *);	/* expedient error function */
/**
 * @file	ps_dis.c
 */
/**
 * @brief
 *	vn_decode_DIS - read verison 3 or 4 vnode definition information from
 * Mom.
 * @par Functionality:
 *	The V4 over-the-wire representation of a placement set list (vnl_t) is
 *	a superset of V3.  V4 adds the ability to specify the type of an
 *	attribute/resource (and reserves a place in the protocol for flags).
 *	The V3 over-the-wire representation of a placement set list (vnl_t) is
 *
 *	version		unsigned integer	the version of the following
 *						information
 *
 *	Version PS_DIS_V3 consists of
 *
 *	vnl_modtime	signed long		this OTW format could be
 *						problematic:   the Open Group
 *						Base Specifications Issue 6
 *						says that time_t ``shall be
 *						integer or real-floating''
 *
 *	vnl_used	unsigned integer	number of entries in the vnal_t
 *						array to follow
 *
 *
 *	There follows, for each element of the vnal_t array,
 *
 *	vnal_id		string
 *
 *	vnal_used	unsigned integer	number of entries in the vna_t
 *						array to follow
 *
 *	vna_name	string			name of resource
 *	vna_val		string			value of resource
 *		Following added in V4
 *	vna_type	int			type of attribute/resource
 *	vna_flag	int			flag of attribute/resource (-h)
 *
 *
 * @param[in]	fd  - file (socket) descriptor from which to read
 * @param[out]	rcp - pointer to int into which to return the error value,
 *			either DIS_SUCCESS or some DIS_* error.
 *
 * @return	vnl_t *
 * @retval	pointer to decoded vnode information which has been malloc-ed.
 * @retval	NULL on error, see rcp value
 *
 * @par Side Effects: None
 *
 * @par MT-safe: yes
 *
 */
vnl_t *
vn_decode_DIS(int fd, int *rcp)
{
	unsigned int	vers;

	vers = disrui(fd, rcp);
	if (*rcp != DIS_SUCCESS)
		return NULL;

	switch (vers) {
		case PS_DIS_V3:
			return (vn_decode_DIS_V3(fd, rcp));
		case PS_DIS_V4:
			return (vn_decode_DIS_V4(fd, rcp));

		default:
			*rcp = DIS_PROTO;
			return NULL;
	}
}

/**
 * @brief
 *	vn_decode_DIS_V4 - decode version 4 vnode information from Mom
 *
 * @par Functionality:
 *	See vn_decode_DIS() above, This is called from there to decode
 *	V4 information.
 *
 * @param[in]	fd  -     socket descriptor from which to read
 * @param[out]	rcp -     pointer to place to return error code if error.
 *
 * @return	vnl_t *
 * @retval	pointer to decoded vnode information which has been malloc-ed.
 * @retval	NULL on error, see rcp value
 *
 * @par Side Effects: None
 *
 * @par MT-safe: yes
 *
 */
static vnl_t *
vn_decode_DIS_V4(int fd, int *rcp)
{
	unsigned int	i, j;
	unsigned int	size;
	time_t		t;
	vnl_t		*vnlp;

	if ((vnlp = calloc(1, sizeof(vnl_t))) == NULL) {
		*rcp = DIS_NOMALLOC;
		return NULL;
	}

	t = (time_t) disrsl(fd, rcp);
	if (*rcp != DIS_SUCCESS) {
		free(vnlp);
		return NULL;
	} else {
		vnlp->vnl_modtime = t;
	}
	size = disrui(fd, rcp);
	if (*rcp != DIS_SUCCESS) {
		free(vnlp);
		return NULL;
	} else {
		vnlp->vnl_nelem = vnlp->vnl_used = size;
	}

	if ((vnlp->vnl_list = calloc(vnlp->vnl_nelem,
		sizeof(vnal_t))) == NULL) {
		free(vnlp);
		*rcp = DIS_NOMALLOC;
		return NULL;
	}

	for (i = 0; i < vnlp->vnl_used; i++) {
		vnal_t		*curreslist = VNL_NODENUM(vnlp, i);

		/*
		 *	In case an error occurs and we need to free
		 *	whatever's been allocated so far, we use the
		 *	vnl_cur entry to record the number of vnal_t
		 *	entries to free.
		 */
		vnlp->vnl_cur = i;

		curreslist->vnal_id = disrst(fd, rcp);
		if (*rcp != DIS_SUCCESS)
			return (free_and_return(vnlp));

		size = disrui(fd, rcp);
		if (*rcp != DIS_SUCCESS)
			return (free_and_return(vnlp));
		else
			curreslist->vnal_nelem = curreslist->vnal_used = size;
		if ((curreslist->vnal_list = calloc(curreslist->vnal_nelem,
			sizeof(vna_t))) == NULL)
			return (free_and_return(vnlp));

		for (j = 0; j < size; j++) {
			vna_t	*curres = VNAL_NODENUM(curreslist, j);

			/*
			 *	In case an error occurs and we need to free
			 *	whatever's been allocated so far, we use the
			 *	vnal_cur entry to record the number of vna_t
			 *	entries to free.
			 */
			curreslist->vnal_cur = j;

			curres->vna_name = disrst(fd, rcp);
			if (*rcp != DIS_SUCCESS)
				return (free_and_return(vnlp));
			curres->vna_val = disrst(fd, rcp);
			if (*rcp != DIS_SUCCESS)
				return (free_and_return(vnlp));
			curres->vna_type = disrsi(fd, rcp);
			if (*rcp != DIS_SUCCESS)
				return (free_and_return(vnlp));
			curres->vna_flag = disrsi(fd, rcp);
			if (*rcp != DIS_SUCCESS)
				return (free_and_return(vnlp));
		}
	}

	*rcp = DIS_SUCCESS;
	return (vnlp);
}

/**
 * @brief
 *	vn_decode_DIS_V3 - decode version 3 vnode information from Mom
 *
 * @par Functionality:
 *	See vn_decode_DIS() above, This is called from there to decode
 *	V3 information.
 *
 * @param[in]	fd  -     socket descriptor from which to read
 * @param[out]	rcp -     pointer to place to return error code if error.
 *
 * @return	vnl_t *
 * @retval	pointer to decoded vnode information which has been malloc-ed.
 * @retval	NULL on error, see rcp value
 *
 * @par Side Effects: None
 *
 * @par MT-safe: yes
 *
 */
static vnl_t *
vn_decode_DIS_V3(int fd, int *rcp)
{
	unsigned int	i, j;
	unsigned int	size;
	time_t		t;
	vnl_t		*vnlp;

	if ((vnlp = calloc(1, sizeof(vnl_t))) == NULL) {
		*rcp = DIS_NOMALLOC;
		return NULL;
	}

	t = (time_t) disrsl(fd, rcp);
	if (*rcp != DIS_SUCCESS) {
		free(vnlp);
		return NULL;
	}
	else
		vnlp->vnl_modtime = t;
	size = disrui(fd, rcp);
	if (*rcp != DIS_SUCCESS) {
		free(vnlp);
		return NULL;
	}
	else
		vnlp->vnl_nelem = vnlp->vnl_used = size;

	if ((vnlp->vnl_list = calloc(vnlp->vnl_nelem,
		sizeof(vnal_t))) == NULL) {
		free(vnlp);
		*rcp = DIS_NOMALLOC;
		return NULL;
	}

	for (i = 0; i < vnlp->vnl_used; i++) {
		vnal_t		*curreslist = VNL_NODENUM(vnlp, i);

		/*
		 *	In case an error occurs and we need to free
		 *	whatever's been allocated so far, we use the
		 *	vnal_cur entry to record the number of vnal_t
		 *	entries to free.
		 */
		vnlp->vnl_cur = i;

		curreslist->vnal_id = disrst(fd, rcp);
		if (*rcp != DIS_SUCCESS)
			return (free_and_return(vnlp));

		size = disrui(fd, rcp);
		if (*rcp != DIS_SUCCESS)
			return (free_and_return(vnlp));
		else
			curreslist->vnal_nelem = curreslist->vnal_used = size;
		if ((curreslist->vnal_list = calloc(curreslist->vnal_nelem,
			sizeof(vna_t))) == NULL)
			return (free_and_return(vnlp));

		for (j = 0; j < size; j++) {
			vna_t	*curres = VNAL_NODENUM(curreslist, j);

			/*
			 *	In case an error occurs and we need to free
			 *	whatever's been allocated so far, we use the
			 *	vnal_cur entry to record the number of vna_t
			 *	entries to free.
			 */
			curreslist->vnal_cur = j;

			curres->vna_name = disrst(fd, rcp);
			if (*rcp != DIS_SUCCESS)
				return (free_and_return(vnlp));
			curres->vna_val = disrst(fd, rcp);
			if (*rcp != DIS_SUCCESS)
				return (free_and_return(vnlp));
		}
	}

	*rcp = DIS_SUCCESS;
	return (vnlp);
}

/**
 * @brief
 *	vn_encode_DIS - encode vnode information, used by Mom.
 *
 * @par Functionality:
 *	Used to encode vnode information.  See vn_decode_DIS() above for a
 *	description of the information encoded/decoded.  Only the latest
 *	version of information is currently supported for encode.
 *
 * @param[in]	fd   - socket descriptor to which to write the encode info.
 * @param[in]	vnlp - structure to encode and send.
 *
 * @return	int
 * @retval	DIS_SUCCESS (0) on success
 * @retval	DIS_* on error.
 *
 * @par Side Effects: None
 *
 * @par MT-safe: No, the structure pointed to by vnlp needs to be locked
 *
 */
int
vn_encode_DIS(int fd, vnl_t *vnlp)
{
	switch (PS_DIS_CURVERSION) {
		case PS_DIS_V4:
			return (vn_encode_DIS_V4(fd, vnlp));

		default:
			return (DIS_PROTO);
	}
}

/**
 * @brief
 *	vn_encode_DIS_V4 - encode version 4 vnode information, used by Mom.
 *
 * @par Functionality:
 *	Used to encode vnode information.  See vn_encode_DIS() above for a
 *	description of the information.  Supports version 4 only.
 *
 * @param[in]	fd   - socket descriptor to which to write the encode info.
 * @param[in]	vnlp - structure to encode and send.
 *
 * @return	int
 * @retval	DIS_SUCCESS (0) on success
 * @retval	DIS_* on error.
 *
 * @par Side Effects: None
 *
 * @par MT-safe: No, the structure pointed to by vnlp needs to be locked
 *
 */
static int
vn_encode_DIS_V4(int fd, vnl_t *vnlp)
{
	int		rc;
	unsigned int	i, j;

	if (((rc = diswui(fd, PS_DIS_V4)) != 0) ||
		((rc = diswsl(fd, (long) vnlp->vnl_modtime)) != 0) ||
		((rc = diswui(fd, vnlp->vnl_used)) != 0))
			return (rc);

	for (i = 0; i < vnlp->vnl_used; i++) {
		vnal_t	*curreslist = VNL_NODENUM(vnlp, i);

		if ((rc = diswst(fd, curreslist->vnal_id)) != 0)
			return (rc);
		if ((rc = diswui(fd, curreslist->vnal_used)) != 0)
			return (rc);

		for (j = 0; j < curreslist->vnal_used; j++) {
			vna_t	*curres = VNAL_NODENUM(curreslist, j);

			if ((rc = diswst(fd, curres->vna_name)) != 0)
				return (rc);
			if ((rc = diswst(fd, curres->vna_val)) != 0)
				return (rc);
			if ((rc = diswsi(fd, curres->vna_type)) != 0)
				return (rc);
			if ((rc = diswsi(fd, curres->vna_flag)) != 0)
				return (rc);
		}
	}

	return (DIS_SUCCESS);
}

/**
 * @brief
 *	free_and_return - free a vnl_t data structure.
 *
 * @par Functionality:
 *	Note that this function is nearly identical to vnl_free() (q.v.),
 *	with the exception of using the *_cur values to free partially-
 *
 * @param[in]	vnlp - pointer to structure to free
 *
 * @return	vnl_t *
 * @retval	NULL
 *
 * @par Side Effects: None
 *
 * @par MT-safe: No, vnlp needs to be locked.
 *
 */
static vnl_t *
free_and_return(vnl_t *vnlp)
{
	unsigned int	i, j;

	/* N.B. <=, not < because we may have a partially-allocated ith one */
	for (i = 0; i <= vnlp->vnl_cur; i++) {
		vnal_t	*vnrlp = VNL_NODENUM(vnlp, i);

		/* N.B. <=, not < (as above) for partially-allocated jth one */
		for (j = 0; j <= vnrlp->vnal_cur; j++) {
			vna_t	*vnrp = VNAL_NODENUM(vnrlp, j);
			free(vnrp->vna_name);
			free(vnrp->vna_val);
		}
		free(vnrlp->vnal_list);
		free(vnrlp->vnal_id);
	}
	free(vnlp->vnl_list);
	free(vnlp);

	return NULL;
}
