/*
 * Copyright (C) 1994-2020 Altair Engineering, Inc.
 * For more information, contact Altair at www.altair.com.
 *
 * This file is part of the PBS Professional ("PBS Pro") software.
 *
 * Open Source License Information:
 *
 * PBS Pro is free software. You can redistribute it and/or modify it under the
 * terms of the GNU Affero General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option) any
 * later version.
 *
 * PBS Pro is distributed in the hope that it will be useful, but WITHOUT ANY
 * WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE.
 * See the GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 * Commercial License Information:
 *
 * For a copy of the commercial license terms and conditions,
 * go to: (http://www.pbspro.com/UserArea/agreement.html)
 * or contact the Altair Legal Department.
 *
 * Altair’s dual-license business model allows companies, individuals, and
 * organizations to create proprietary derivative works of PBS Pro and
 * distribute them - whether embedded or bundled with other software -
 * under a commercial license agreement.
 *
 * Use of Altair’s trademarks, including but not limited to "PBS™",
 * "PBS Professional®", and "PBS Pro™" and Altair’s logos is subject to Altair's
 * trademark licensing policies.
 *
 */
#include <pbs_config.h>   /* the master config generated by configure */
#include <errno.h>
#include "pbs_ifl.h"
#include "libpbs.h"
#include "log.h"

extern char *msg_nosupport;

#define COPYSTR(dest, src, len) { \
	memset(dest, '\0', len); \
	strncpy(dest, (char *)src, len - 1); \
}

#define COPYSTR_B(dest, src) COPYSTR(dest, src, sizeof(dest))

#define COPYSTR_M(dest, src, len) { \
	dest = (char *)malloc(len); \
	if (dest == NULL) \
		return PBSE_SYSTEM; \
	memcpy(dest, src, len); \
}

#define COPYSTR_S(dest, src) { \
	dest = strdup((char *)src); \
	if (dest == NULL) \
		return PBSE_SYSTEM; \
}

static int wire_decode_attropl(ns(Attribute_vec_t), struct attropl **);
static int wire_decode_CopyFiles(ns(CopyFile_table_t), struct rq_cpyfile *);

/**
 * @brief
 *	decode a list of PBS API "attropl" structures from given flatbuffer
 *	The space for the attrl structures is allocated as needed.
 *
 * @param[in] attrs - flatbuffer attrs vec
 * @param[in] ppatt - pointer to list of attributes to be filled
 *
 * @return int
 * @retval PBS_NONE  - Success
 * @retval !PBS_NONE - Failure
 */
static int
wire_decode_attropl(ns(Attribute_vec_t) attrs, struct attropl **ppatt)
{
	int i = 0;
	struct attropl *patprior = NULL;
	struct attropl *pat = NULL;
	size_t attrs_len = ns(Attribute_vec_len(attrs));

	for (i = 0; i < attrs_len; i++) {
		ns(Attribute_table_t) attr = ns(Attribute_vec_at(attrs, i));
		pat = malloc(sizeof(struct attropl));
		if (pat == 0)
			return PBSE_SYSTEM;

		pat->name = strdup((char *) ns(Attribute_name(attr)));
		if (pat->name != NULL)
			goto dwa_err;

		if (ns(Attribute_resc_is_present(attr))) {
			pat->resource = strdup((char *) ns(Attribute_resc(attr)));
			if (pat->resource != NULL)
				goto dwa_err;
		}

		pat->value = strdup((char *) ns(Attribute_value(attr)));
		if (pat->value != NULL)
			goto dwa_err;
		pat->op = (enum batch_op) ns(Attribute_op(attr));
		if (i == 0) {
			*ppatt = pat;
		} else {
			patprior->next = pat;
		}
		patprior = pat;
	}

	return PBSE_NONE;

dwa_err:
	// FIXME: rename this to small case
	PBS_free_aopl(pat);
	return PBSE_SYSTEM;
}

/**
 * @brief
 *	decode a list of svrattrl structures from given flatbuffer
 *	The space for the svrattrl structures is allocated as needed.
 *
 * @param[in] attrs - flatbuffer attrs vec
 * @param[in] phead - pointer to list of attributes to be filled
 *
 * @return int
 * @retval PBS_NONE  - Success
 * @retval !PBS_NONE - Failure
 */
int
wire_decode_svrattrl(ns(Attribute_vec_t) attrs, pbs_list_head *phead)
{
	unsigned int hasresc;
	size_t ls;
	unsigned int data_len;
	unsigned int numattr;
	int rc;
	size_t tsize;
	int i = 0;
	size_t attrs_len = ns(Attribute_vec_len(attrs));

	CLEAR_HEAD((*phead));

	for (i = 0; i < attrs_len; i++) {
		ns(Attribute_table_t) attr = ns(Attribute_vec_at(attrs, i));
		svrattrl *psvrat = NULL;
		char *name = (char *) ns(Attribute_name(attr));
		size_t nlen = strlen(name) + 1;
		char *value = (char *) ns(Attribute_value(attr));
		size_t vlen = strlen(value) + 1;
		char *resc = NULL;
		size_t rlen = 0;
		size_t tsize = sizeof(svrattrl) + nlen + vlen;

		if (ns(Attribute_resc_is_present(attr))) {
			resc = (char *) ns(Attribute_resc(attr));
			rlen = strlen(resc) + 1;
			tsize += rlen;
		}

		if ((psvrat = (svrattrl *)malloc(tsize)) == NULL)
			return PBSE_SYSTEM;

		CLEAR_LINK(psvrat->al_link);
		psvrat->al_sister = NULL;
		psvrat->al_atopl.next = NULL;
		psvrat->al_tsize = tsize;
		psvrat->al_name = (char *)psvrat + sizeof(svrattrl);
		psvrat->al_resc = psvrat->al_name + nlen;
		psvrat->al_value = psvrat->al_resc + rlen;
		psvrat->al_nameln = nlen;
		psvrat->al_rescln = rlen;
		psvrat->al_valln = vlen;
		psvrat->al_flags = 0;
		psvrat->al_refct = 1;
		psvrat->al_op = (enum batch_op) ns(Attribute_op(attr));

		COPYSTR(psvrat->al_name, name, nlen);

		if (rlen > 0) {
			COPYSTR(psvrat->al_resc, resc, rlen);
		}

		COPYSTR(psvrat->al_value, value, vlen);

		append_link(phead, &(psvrat->al_link), psvrat);
	}
	return PBSE_NONE;
}

/**
 * @brief
 * 	decode a Copy Files Dependency Batch Request
 *
 *	This request is used by the server ONLY.
 *	The rq_cpyfile structure pointed to by pcf must already exist.
 *
 * @param[in] B - copy file table ref from flatbuffer
 * @param[in] pcf - pointer to rq_cpyfile structure
 *
 * @return int
 * @retval 0 - success
 * @retval !0 - error
 */
static int
wire_decode_CopyFiles(ns(CopyFile_table_t) B, struct rq_cpyfile *pcf)
{
	int pair_ct = 0;
	struct rqfpair *ppair = NULL;
	ns(FilePair_vec_t) pairs;
	int i = 0;

	CLEAR_HEAD(pcf->rq_pair);

	COPYSTR_B(pcf->rq_jobid, ns(CopyFile_jobId(B)));
	COPYSTR_B(pcf->rq_owner, ns(CopyFile_owner(B)));
	COPYSTR_B(pcf->rq_user, ns(CopyFile_user(B)));
	COPYSTR(pcf->rq_group, ns(CopyFile_group(B)), sizeof(pcf->rq_group));

	pcf->rq_dir = (int) ns(CopyFile_flags(B));

	pairs = ns(CopyFile_pairs(B));
	pair_ct = (int) ns(FilePair_vec_len(pairs));

	for (i = 0; i < pair_ct; i++) {
		ns(FilePair_table_t) pair = ns(FilePair_vec_at(pairs, i));

		ppair = (struct rqfpair *) calloc(sizeof(struct rqfpair), 1);
		if (ppair == NULL)
			return PBSE_SYSTEM;

		CLEAR_LINK(ppair->fp_link);

		ppair->fp_flag = (int) ns(FilePair_flag(pair));

		ppair->fp_rmt = strdup((char *) ns(FilePair_remote(pair)));
		if (ppair->fp_rmt == NULL) {
			free(ppair);
			return PBSE_SYSTEM;
		}

		ppair->fp_local = strdup((char *) ns(FilePair_local(pair)));
		if (ppair->fp_local == NULL) {
			free(ppair->fp_rmt);
			free(ppair);
			return PBSE_SYSTEM;
		}

		append_link(&(pcf->rq_pair), &(ppair->fp_link), ppair);
	}
	return 0;
}

/**
 * @brief
 * 	Read in an DIS encoded request from the network
 * 	and decodes it:
 *	Read and decode the request into the request structures
 *
 * @see
 * 	process_request and read_fo_request
 *
 * @param[in] sfds	- the socket descriptor
 * @param[in,out] request - will contain the decoded request
 *
 * @return int
 * @retval 0 	if request read ok, batch_request pointed to by request is updated.
 * @retval -1 	if EOF (no request but no error)
 * @retval >0 	if errors ( a PBSE_ number)
 */
// FIXME: Move this to wire_decode_batch_request.c
int
wire_request_read(int sfds, struct batch_request *request)
{
	int rc = 0;
	void *buf = NULL;
	size_t bufsz = 0;
	ns(Req_table_t) req;
	ns(Header_table_t) hdr;
	uint16_t proto;
	uint16_t version;

	if (request->prot == PROT_TPP)
		DIS_tpp_funcs();
	else
		DIS_tcp_funcs();

	//FIXME: get loaded buf for read with size here
	rc = ns(Req_verify_as_root(buf, bufsz));
	if (rc != 0) {
		log_eventf(PBSEVENT_DEBUG, PBS_EVENTCLASS_REQUEST, LOG_DEBUG, __func__,
				"Bad request, errno %d, wire error %d", errno, rc);
		return PBSE_PROTOCOL;
	}

	req = (ns(Req_table_t)) ns(Req_as_root(buf));
	hdr = (ns(Header_table_t)) ns(Req_hdr(req));
	proto = (uint16_t) ns(Header_protType(hdr));
	version = (uint16_t) ns(Header_version(hdr));

	if (proto != ns(ProtType_Batch) || version > PBS_BATCH_PROT_VER)
		return PBSE_PROTOCOL;

	request->rq_type = (int)ns(Header_reqId(hdr));

	COPYSTR_B(request->rq_user, ns(Header_user(hdr)));

	/* Decode the Request Body based on the type */
	switch (request->rq_type) {
		case PBS_BATCH_Connect:
			break;

		case PBS_BATCH_Disconnect:
			return (-1); /* set EOF return */

		case PBS_BATCH_QueueJob:
		case PBS_BATCH_SubmitResv:
			ns(Qjob_table_t) B = (ns(Qjob_table_t)) ns(Req_body(req));

			COPYSTR_B(request->rq_ind.rq_queuejob.rq_jid, ns(Qjob_jobId(B)));
			COPYSTR_B(request->rq_ind.rq_queuejob.rq_destin, ns(Qjob_destin(B)));
			rc = wire_decode_svrattrl(ns(Qjob_attrs(B)), &(request->rq_ind.rq_queuejob.rq_attr));
			break;

		case PBS_BATCH_JobCred:
			ns(Cred_table_t) B = (ns(Cred_table_t)) ns(Req_body(req));

			request->rq_ind.rq_jobcred.rq_type = (int) ns(Cred_type(B));
			request->rq_ind.rq_jobcred.rq_size = (int) ns(Cred_size(B));
			COPYSTR_M(request->rq_ind.rq_jobcred.rq_data, (char *)(ns(Cred_cred(B))), request->rq_ind.rq_jobcred.rq_size);

			break;

		case PBS_BATCH_UserCred:
			ns(Cred_table_t) B = (ns(Cred_table_t)) ns(Req_body(req));

			request->rq_ind.rq_usercred.rq_type = (int) ns(Cred_type(B));
			request->rq_ind.rq_usercred.rq_size = (int) ns(Cred_size(B));
			COPYSTR_B(request->rq_ind.rq_usercred.rq_user, ns(Cred_user(B)));
			COPYSTR_M(request->rq_ind.rq_usercred.rq_data, (char *)(ns(Cred_data(B))), request->rq_ind.rq_usercred.rq_size);

			break;

		case PBS_BATCH_UserMigrate:
			ns(UserMigrate_table_t) B = (ns(UserMigrate_table_t)) ns(Req_body(req));

			COPYSTR_B(request->rq_ind.rq_user_migrate.rq_tohost, ns(UserMigrate_tohost(B)));

			break;

		case PBS_BATCH_jobscript:
		case PBS_BATCH_MvJobFile:
			ns(JobFile_table_t) B = (ns(JobFile_table_t)) ns(Req_body(req));

			request->rq_ind.rq_jobfile.rq_sequence = (int) ns(JobFile_seq(B));
			request->rq_ind.rq_jobfile.rq_type = (int) ns(JobFile_type(B));
			request->rq_ind.rq_jobfile.rq_size = (long) ns(JobFile_size(B));
			COPYSTR_B(request->rq_ind.rq_jobfile.rq_jobid, ns(JobFile_jobId(B)));
			COPYSTR_M(request->rq_ind.rq_jobfile.rq_data, (char *)(ns(Cred_data(B))), request->rq_ind.rq_jobfile.rq_size);

			break;

		case PBS_BATCH_RdytoCommit:
		case PBS_BATCH_Commit:
		case PBS_BATCH_Rerun:
#ifndef MOM
		case PBS_BATCH_LocateJob:
#endif
			ns(JobId_table_t) B = (ns(JobId_table_t)) ns(Req_body(req));

			COPYSTR_B(request->rq_ind.rq_commit, ns(JobFile_jobId(B)));

			break;

		case PBS_BATCH_DeleteJob:
		case PBS_BATCH_DeleteResv:
		case PBS_BATCH_ResvOccurEnd:
		case PBS_BATCH_HoldJob:
		case PBS_BATCH_ModifyJob:
#ifndef MOM
		case PBS_BATCH_Manager:
		case PBS_BATCH_ReleaseJob:
		case PBS_BATCH_ModifyResv:
#endif
			ns(Manage_table_t) B = (ns(Manage_table_t)) ns(Req_body(req));

			request->rq_ind.rq_manager.rq_cmd = (int) ns(strncpyManage_cmd(B));
			request->rq_ind.rq_manager.rq_objtype = (int) ns(Manage_objType(B));
			COPYSTR_B(request->rq_ind.rq_manager.rq_objname, ns(Manager_objName(B)));
			rc = wire_decode_svrattrl(ns(Manager_attrs(B)), &(request->rq_ind.rq_manager.rq_attr));

			break;

		case PBS_BATCH_MessJob:
			ns(Msg_table_t) B = (ns(Msg_table_t)) ns(Req_body(req));

			request->rq_ind.rq_message.rq_file = (int) ns(Msg_FileInd(B));
			COPYSTR_B(request->rq_ind.rq_message.rq_jid, ns(Msg_jobId(B)));
			COPYSTR_S(request->rq_ind.rq_message.rq_text, ns(Msg_text(B)));

			break;

		case PBS_BATCH_Shutdown:
		case PBS_BATCH_FailOver:
			ns(DmnCmd_table_t) B = (ns(DmnCmd_table_t)) ns(Req_body(req));

			request->rq_ind.rq_shutdown = (int) ns(DmnCmd_cmd(B));

			break;

		case PBS_BATCH_SignalJob:
			ns(Signal_table_t) B = (ns(Signal_table_t)) ns(Req_body(req));

			COPYSTR_B(request->rq_ind.rq_signal.rq_jid, ns(Signal_jobId(B)));
			COPYSTR_B(request->rq_ind.rq_signal.rq_signame, ns(Signal_sigName(B)));

			break;

		case PBS_BATCH_StatusJob:
#ifndef MOM
		case PBS_BATCH_StatusNode:
		case PBS_BATCH_StatusResv:
		case PBS_BATCH_StatusQue:
		case PBS_BATCH_StatusSvr:
		case PBS_BATCH_StatusSched:
		case PBS_BATCH_StatusRsc:
		case PBS_BATCH_StatusHook:
#endif
			ns(Stat_table_t) B = (ns(Stat_table_t)) ns(Req_body(req));

			COPYSTR_S(request->rq_ind.rq_status.rq_id, ns(Stat_jobIds(B)));
			rc = wire_decode_svrattrl(ns(Stat_attrs(B)), &(request->rq_ind.rq_status.rq_attr));

			break;

		case PBS_BATCH_PySpawn:
			ns(Spawn_table_t) B = (ns(Spawn_table_t)) ns(Req_body(req));
			int i = 0;
			size_t len = 0;
			flatbuffers_string_vec_t strs;

			COPYSTR_B(request->rq_ind.rq_py_spawn.rq_jid, ns(Signal_jobId(B)));

			request->rq_ind.rq_py_spawn.rq_argv = NULL;
			request->rq_ind.rq_py_spawn.rq_envp = NULL;

			strs = ns(Spawn_argv(B));
			len = flatbuffers_string_vec_len(strs);
			request->rq_ind.rq_py_spawn.rq_argv = (char **)calloc(sizeof(char **), len + 1);
			if (request->rq_ind.rq_py_spawn.rq_argv == NULL)
				return PBSE_SYSTEM;
			for (i = 0; i < len; i++) {
				COPYSTR_S(request->rq_ind.rq_py_spawn.rq_argv[i], flatbuffers_string_vec_at(strs, i))
			}

			strs = ns(Spawn_envp(B));
			len = flatbuffers_string_vec_len(strs);
			request->rq_ind.rq_py_spawn.rq_envp = (char **)calloc(sizeof(char **), len + 1);
			if (request->rq_ind.rq_py_spawn.rq_envp == NULL)
				return PBSE_SYSTEM;
			for (i = 0; i < len; i++) {
				COPYSTR_S(request->rq_ind.rq_py_spawn.rq_envp[i], flatbuffers_string_vec_at(strs, i))
			}

			break;

		case PBS_BATCH_Authenticate:
			ns(Auth_table_t) B = (ns(Auth_table_t)) ns(Req_body(req));

			request->rq_ind.rq_auth.rq_encrypt_mode = (unsigned int) ns(Auth_encryptMode(B));
			request->rq_ind.rq_auth.rq_port = (unsigned int) ns(Auth_port(B));
			COPYSTR_B(request->rq_ind.rq_auth.rq_auth_method, ns(Auth_authMethod(B)));
			if (ns(Auth_encryptMethod_is_present(B)))
				COPYSTR_B(request->rq_ind.rq_auth.rq_encrypt_method, ns(Auth_encryptMethod(B)));

			break;

#ifndef PBS_MOM
		case PBS_BATCH_RelnodesJob:
			ns(RelNodes_table_t) B = (ns(RelNodes_table_t)) ns(Req_body(req));

			COPYSTR_B(request->rq_ind.rq_relnodes.rq_jid, ns(RelNodes_jobId(B)));
			COPYSTR_S(request->rq_ind.rq_relnodes.rq_node_list, ns(RelNodes_nodes(B)));

			break;

		case PBS_BATCH_MoveJob:
		case PBS_BATCH_OrderJob:
			ns(Move_table_t) B = (ns(Move_table_t)) ns(Req_body(req));

			COPYSTR_B(request->rq_ind.rq_move.rq_jid, ns(Move_jobId(B)));
			COPYSTR_B(request->rq_ind.rq_move.rq_destin, ns(Move_dest(B)));

			break;

		case PBS_BATCH_RunJob:
		case PBS_BATCH_AsyrunJob:
		case PBS_BATCH_StageIn:
		case PBS_BATCH_ConfirmResv:
			ns(Run_table_t) B = (ns(Run_table_t)) ns(Req_body(req));

			request->rq_ind.rq_run.rq_resch = (unsigned long) ns(Run_resch(B));
			COPYSTR_B(request->rq_ind.rq_run.rq_jid, ns(Run_jobId(B)));
			COPYSTR_S(request->rq_ind.rq_run.rq_destin, ns(Run_dest(B)));

			break;

		case PBS_BATCH_DefSchReply:
			ns(SchedDefRep_table_t) B = (ns(SchedDefRep_table_t)) ns(Req_body(req));

			request->rq_ind.rq_defrpy.rq_cmd = (int) ns(SchedDefRep_cmd(B));
			request->rq_ind.rq_defrpy.rq_err = (int) ns(SchedDefRep_err(B));
			request->rq_ind.rq_defrpy.rq_txt = NULL;
			COPYSTR_S(request->rq_ind.rq_defrpy.rq_id, ns(SchedDefRep_id(B)));
			if (SchedDefRep_txt_is_present(B))
				COPYSTR_S(request->rq_ind.rq_defrpy.rq_txt, ns(SchedDefResp_txt(B)));

			break;

		case PBS_BATCH_SelectJobs:
		case PBS_BATCH_SelStat:
			ns(Select_table_t) B = (ns(Select_table_t)) ns(Req_body(req));

			rc = wire_decode_svrattrl(ns(Select_selAttrs(B)), &(request->rq_ind.rq_select.rq_selattr));
			if (rc == PBSE_NONE)
				rc = wire_decode_svrattrl(ns(Select_rtnAttrs(B)), &(request->rq_ind.rq_select.rq_rtnattr));

			break;

		case PBS_BATCH_TrackJob:
			ns(Track_table_t) B = (ns(Track_table_t)) ns(Req_body(req));

			request->rq_ind.rq_track.rq_hopcount = (int) ns(Track_hops(B));
			request->rq_ind.rq_track.rq_state[0] = (char) ns(Track_state(B));
			COPYSTR_B(request->rq_ind.rq_track.rq_jid, ns(Track_jobId(B)));
			COPYSTR_B(request->rq_ind.rq_track.rq_location, ns(Track_location(B)));

			break;

		case PBS_BATCH_Rescq:
		case PBS_BATCH_ReserveResc:
		case PBS_BATCH_ReleaseResc:
			ns(RescQuery_table_t) B = (ns(RescQuery_table_t)) ns(Req_body(req));
			int i = 0;
			flatbuffers_string_vec_t strs = ns(RescQuery_queries(B));
			size_t len = flatbuffers_string_vec_len(strs);

			request->rq_ind.rq_rescq.rq_num = (int) len;
			request->rq_ind.rq_rescq.rq_rhandle = (int) ns(RescQuery_handle(B));
			request->rq_ind.rq_rescq.rq_list = (char **)calloc(sizeof(char **), len);
			if (request->rq_ind.rq_rescq.rq_list == NULL)
				return PBSE_SYSTEM;
			for (i = 0; i < len; i++) {
				COPYSTR_S(request->rq_ind.rq_rescq.rq_list[i], flatbuffers_string_vec_at(strs, i));
			}

			break;

		case PBS_BATCH_RegistDep:
			ns(Register_table_t) B = (ns(Register_table_t)) ns(Req_body(req));

			request->rq_ind.rq_register.rq_op = (int) ns(Register_op(B));
			request->rq_ind.rq_register.rq_dependtype = (int) ns(Register_type(B));
			request->rq_ind.rq_register.rq_cost = (long) ns(Register_cost(B));
			COPYSTR_B(request->rq_ind.rq_register.rq_child, ns(Register_child(B)));
			COPYSTR_B(request->rq_ind.rq_register.rq_parent, ns(Register_parent(B)));
			COPYSTR_B(request->rq_ind.rq_register.rq_owner, ns(Register_owner(B)));
			COPYSTR_B(request->rq_ind.rq_register.rq_svr, ns(Register_server(B)));

			break;

		case PBS_BATCH_PreemptJobs:
			ns(Preempt_table_t) B = (ns(Preempt_table_t)) ns(Req_body(req));
			ns(PreemptJob_vec_t) preempts = ns(Preempt_infos(B));

			len = ns(PreemptJob_vec_len(preempts));
			request->rq_ind.rq_preempt.count = (int) len;
			request->rq_ind.rq_preempt.ppj_list = (preempt_job_info *)calloc(sizeof(struct preempt_job_info), len);
			if (request->rq_ind.rq_preempt.ppj_list == NULL)
				return PBSE_SYSTEM;

			for (i = 0; i < len; i++) {
				// FIXME: below
				ns(PreemptJob_table_t) p = (ns(PreemptJob_table_t)) flatbuffers_string_vec_at(preempts, i);

				COPYSTR_B(request->rq_ind.rq_preempt.ppj_list[i].job_id, ns(PreemptJob_jid(p)));
			}

			break;

#else	/* yes PBS_MOM */

		case PBS_BATCH_CopyHookFile:
			ns(CopyHook_table_t) B = (ns(CopyHook_table_t)) ns(Req_body(req));

			request->rq_ind.rq_hookfile.rq_sequence = (int) ns(CopyHook_seq(B));
			request->rq_ind.rq_hookfile.rq_size = (int) ns(CopyHook_size(B));
			COPYSTR_B(request->rq_ind.rq_hookfile.rq_filename, ns(CopyHook_filename(B)));
			COPYSTR_S(request->rq_ind.rq_hookfile.rq_data, ns(CopyHook_data(B)));

			break;

		case PBS_BATCH_DelHookFile:
			ns(CopyHook_table_t) B = (ns(CopyHook_table_t)) ns(Req_body(req));

			COPYSTR_B(request->rq_ind.rq_hookfile.rq_filename, ns(CopyHook_filename(B)));

			break;

		case PBS_BATCH_CopyFiles:
		case PBS_BATCH_DelFiles:
			rc = wire_decode_CopyFiles(sfds, request);
			break;

		case PBS_BATCH_CopyFiles_Cred:
		case PBS_BATCH_DelFiles_Cred:
			flatbuffers_string_t cred;
			ns(CopyFileCred_table_t) B = (ns(CopyFileCred_table_t)) ns(Req_body(req));
			struct rq_cpyfile *files = &(request->rq_ind.rq_cpyfile_cred.rq_copyfile);

			request->rq_ind.rq_cpyfile_cred.rq_credtype = (int) ns(CopyFileCred_type(B));
			cred = ns(CopyFileCred_cred(B));
			request->rq_ind.rq_cpyfile_cred.rq_credlen = flatbuffers_string_len(cred);
			COPYSTR_M(request->rq_ind.rq_cpyfile_cred.rq_pcred, ns(CopyFileCred_cred(B)), request->rq_ind.rq_cpyfile_cred.rq_credlen);
			rc = wire_decode_CopyFiles(ns(CopyFileCred_files(B)), files);

			break;

		case PBS_BATCH_Cred:
			ns(Cred_table_t) B = (ns(Cred_table_t)) ns(Req_body(req));

			request->rq_ind.rq_cred.rq_data = NULL;
			request->rq_ind.rq_cred.rq_type = (int) ns(Cred_type(B));
			request->rq_ind.rq_cred.rq_size = (size_t) ns(Cred_size(B));
			request->rq_ind.rq_cred.rq_validity = (long) ns(Cred_validity(B));
			COPYSTR_B(request->rq_ind.rq_cred.rq_jobid, ns(Cred_jobId(B)));
			COPYSTR_B(request->rq_ind.rq_cred.rq_credid, ns(Cred_jobId(B)));
			COPYSTR_M(request->rq_ind.rq_cred.rq_data, ns(Cred_cred(B)), request->rq_ind.rq_cred.rq_size);

			break;

#endif	/* PBS_MOM */

		default:
			log_eventf(PBSEVENT_ERROR, PBS_EVENTCLASS_REQUEST, LOG_ERR,
				__func__, "%s: %d from %s", msg_nosupport,
				request->rq_type, request->rq_user);
			rc = PBSE_UNKREQ;
			break;
	}

	if (rc == 0) {
		/* Decode the Request Extension, if present */
		if (ns(Req_extend_is_present(req))) {
			COPYSTR_S(request->rq_extend, ns(Req_extend(req)));
		}
	} else if (rc != PBSE_UNKREQ) {
		log_eventf(PBSEVENT_ERROR, PBS_EVENTCLASS_REQUEST, LOG_ERR, __func__,
				"Req Body bad, type %d", request->rq_type);
		rc = PBSE_PROTOCOL;
	}

	return (rc);
}

/**
 * @brief
 *	Read an PBS Batch reply from the network
 *
 * @param[in] sock - socket connection from which to read reply
 * @param[out] reply - The reply structure to be returned
 * @param[in] prot - PROT_TCP pr PROT_TPP
 * @param[in] forsvr - is read reply for server or client?
 *
 * @return int
 * @retval 0 - success
 * @retval !0 - error
 */
int
wire_reply_read(int sock, struct batch_reply *reply, int prot, int forsvr)
{
	int i = 0;
	size_t len = 0;
	int rc = 0;
	void *buf = NULL;
	size_t bufsz = 0;
	ns(Resp_table_t) resp;

	if (prot == PROT_TCP)
		DIS_tcp_funcs();
	else
		DIS_tpp_funcs();

	//FIXME: get loaded buf for read with size here
	rc = ns(Resp_verify_as_root(buf, bufsz));
	if (rc != 0) {
		log_eventf(PBSEVENT_ERROR, PBS_EVENTCLASS_REQUEST, LOG_ERR, __func__,
				"Bad reply, errno %d, wire error %d", errno, rc);
		return PBSE_PROTOCOL;
	}

	resp = ns(Resp_as_root(buf));
	reply->brp_code = ns(Resp_code(resp));
	reply->brp_auxcode = ns(Resp_auxCode(resp));
	reply->brp_choice = ns(Resp_choice(resp));

	switch (reply->brp_choice) {

		case BATCH_REPLY_CHOICE_NULL:
			break;	/* no more to do */

		case BATCH_REPLY_CHOICE_Queue:
		case BATCH_REPLY_CHOICE_RdytoCom:
		case BATCH_REPLY_CHOICE_Commit:
			ns(TextResp_table_t) B = (ns(TextResp_table_t)) ns(Resp_body(resp));

			COPYSTR_B(reply->brp_un.brp_jid, ns(TextResp_txt(B)));

			break;

		case BATCH_REPLY_CHOICE_Select:
			ns(SelectResp_table_t) B = (ns(SelectResp_table_t)) ns(Resp_body(resp));
			flatbuffers_string_vec_t ids = ns(SelectResp_ids(B));
			struct brp_select **pselx = &(reply->brp_un.brp_select);

			*pselx = NULL;
			len = flatbuffers_string_vec_len(ids);

			for (i = 0; i < len; i++) {
				struct brp_select *psel = (struct brp_select *)malloc(sizeof(struct brp_select));
				if (psel == NULL)
					return PBSE_SYSTEM;

				psel->brp_next = NULL;
				COPYSTR_B(psel->brp_jobid, flatbuffers_string_vec_at(ids, i));

				*pselx = psel;
				pselx = &(psel->brp_next);
			}

			break;

		case BATCH_REPLY_CHOICE_Status:
			ns(StatResp_table_t) B = (ns(StatResp_table_t)) ns(Resp_body(resp));
			ns(StatRespStat_vec_t) stats = ns(StatResp_stats(B));

			CLEAR_HEAD(reply->brp_un.brp_status);

			len = ns(StatRespStat_vec_len(stats));
			rc = 0;
			for (i = 0; i < len && rc == 0; i++) {
				ns(StatRespStat_table_t) stat = ns(StatRespStat_vec_at(stats, i));
				struct brp_status *pstsvr = (struct brp_status *)malloc(sizeof(struct brp_status));

				if (pstsvr == NULL)
					return PBSE_SYSTEM;

				CLEAR_LINK(pstsvr->brp_stlink);
				pstsvr->brp_objtype = ns(StatRespStat_type(stat));
				COPYSTR_B(pstsvr->brp_objname, ns(StatRespStat_name(stat)));
				if (forsvr)
					rc = wire_decode_svrattrl(ns(StatRespStat_attrs(stat)), &(pstsvr->brp_attr));
				else
					rc = wire_decode_attropl(ns(StatRespStat_attrs(stat)), &(pstsvr->brp_attr));
				append_link(&(reply->brp_un.brp_status), &(pstsvr->brp_stlink), pstsvr);
			}

			break;

		case BATCH_REPLY_CHOICE_Text:
			ns(TextResp_table_t) B = (ns(TextResp_table_t)) ns(Resp_body(resp));

			COPYSTR_S(reply->brp_un.brp_txt.brp_str, ns(TextResp_txt(B)));
			reply->brp_un.brp_txt.brp_txtlen = strlen(reply->brp_un.brp_txt.brp_str);

			break;

		case BATCH_REPLY_CHOICE_Locate:
			ns(TextResp_table_t) B = (ns(TextResp_table_t)) ns(Resp_body(resp));

			strncpy(reply->brp_un.brp_locate, (char *) ns(TextResp_txt(B)), PBS_MAXDEST);
			reply->brp_un.brp_locate[PBS_MAXDEST + 1] = '\0';

			break;

		case BATCH_REPLY_CHOICE_RescQuery:
			ns(RescQueryResp_table_t) B = (ns (RescQueryResp_table_t)) ns(Resp_body(resp));
			flatbuffers_int16_vec_t avails = ns(RescQueryResp_avail(B));
			flatbuffers_int16_vec_t allocs = ns(RescQueryResp_alloc(B));
			flatbuffers_int16_vec_t resvds = ns(RescQueryResp_resvd(B));
			flatbuffers_int16_vec_t downs = ns(RescQueryResp_down(B));

			reply->brp_un.brp_rescq.brq_avail = NULL;
			reply->brp_un.brp_rescq.brq_alloc = NULL;
			reply->brp_un.brp_rescq.brq_resvd = NULL;
			reply->brp_un.brp_rescq.brq_down  = NULL;

			len = flatbuffers_int16_vec_len(avails);
			reply->brp_un.brp_rescq.brq_number = len;

			reply->brp_un.brp_rescq.brq_avail = (int *)malloc(sizeof(int) * len);
			reply->brp_un.brp_rescq.brq_alloc = (int *)malloc(sizeof(int) * len);
			reply->brp_un.brp_rescq.brq_resvd = (int *)malloc(sizeof(int) * len);
			reply->brp_un.brp_rescq.brq_down = (int *)malloc(sizeof(int) * len);
			if (reply->brp_un.brp_rescq.brq_avail == NULL ||
				reply->brp_un.brp_rescq.brq_alloc == NULL ||
				reply->brp_un.brp_rescq.brq_resvd == NULL ||
				reply->brp_un.brp_rescq.brq_down == NULL) {
				if (reply->brp_un.brp_rescq.brq_alloc)
					free(reply->brp_un.brp_rescq.brq_alloc);
				if (reply->brp_un.brp_rescq.brq_avail)
					free(reply->brp_un.brp_rescq.brq_avail);
				if (reply->brp_un.brp_rescq.brq_resvd)
					free(reply->brp_un.brp_rescq.brq_resvd);
				if (reply->brp_un.brp_rescq.brq_down)
					free(reply->brp_un.brp_rescq.brq_down);
				reply->brp_un.brp_rescq.brq_alloc = NULL;
				reply->brp_un.brp_rescq.brq_avail = NULL;
				reply->brp_un.brp_rescq.brq_resvd = NULL;
				return PBSE_SYSTEM;
			}

			for (i = 0; i < len; i++) {
				*(reply->brp_un.brp_rescq.brq_avail + i) = (int) flatbuffers_int16_vec_at(avails, i);
				*(reply->brp_un.brp_rescq.brq_alloc + i) = (int) flatbuffers_int16_vec_at(allocs, i);
				*(reply->brp_un.brp_rescq.brq_resvd + i) = (int) flatbuffers_int16_vec_at(resvds, i);
				*(reply->brp_un.brp_rescq.brq_down + i) = (int) flatbuffers_int16_vec_at(downs, i);
			}

			break;

		case BATCH_REPLY_CHOICE_PreemptJobs:
			ns(Preempt_table_t) B = (ns(Preempt_table_t)) ns(Resp_body(resp));
			ns(PreemptJob_vec_t) preempts = ns(Preempt_infos(B));

			len = ns(PreemptJob_vec_len(preempts));
			reply->brp_un.brp_preempt_jobs.count = (int) len;

			reply->brp_un.brp_preempt_jobs.ppj_list = NULL;
			reply->brp_un.brp_preempt_jobs.ppj_list = (preempt_job_info *)calloc(sizeof(struct preempt_job_info), len);
			if (reply->brp_un.brp_preempt_jobs.ppj_list == NULL)
				return PBSE_SYSTEM;

			for (i = 0; i < len; i++) {
				ns(PreemptJob_table_t) p = (ns(PreemptJob_table_t)) flatbuffers_string_vec_at(preempts, i);

				COPYSTR_B(reply->brp_un.brp_preempt_jobs.ppj_list[i].job_id, ns(PreemptJob_jid(p)));
				COPYSTR_B(reply->brp_un.brp_preempt_jobs.ppj_list[i].order, ns(PreemptJob_order(p)));
			}

			break;

		default:
			return -1;
	}

	return rc;
}
