#ifndef PBS_IFL_BUILDER_H
#define PBS_IFL_BUILDER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef PBS_IFL_READER_H
#include "pbs_ifl_reader.h"
#endif
#ifndef FLATBUFFERS_COMMON_BUILDER_H
#include "flatbuffers_common_builder.h"
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif

#define __PBS_ifl_ProtType_formal_args , PBS_ifl_ProtType_enum_t v0
#define __PBS_ifl_ProtType_call_args , v0
__flatbuffers_build_scalar(flatbuffers_, PBS_ifl_ProtType, PBS_ifl_ProtType_enum_t)
#define __PBS_ifl_batch_op_formal_args , PBS_ifl_batch_op_enum_t v0
#define __PBS_ifl_batch_op_call_args , v0
__flatbuffers_build_scalar(flatbuffers_, PBS_ifl_batch_op, PBS_ifl_batch_op_enum_t)

typedef flatbuffers_union_ref_t PBS_ifl_ReqBody_union_ref_t;
typedef flatbuffers_union_vec_ref_t PBS_ifl_ReqBody_union_vec_ref_t;
static PBS_ifl_ReqBody_union_ref_t PBS_ifl_ReqBody_clone(flatbuffers_builder_t *B, PBS_ifl_ReqBody_union_t t);
typedef flatbuffers_union_ref_t PBS_ifl_RespBody_union_ref_t;
typedef flatbuffers_union_vec_ref_t PBS_ifl_RespBody_union_vec_ref_t;
static PBS_ifl_RespBody_union_ref_t PBS_ifl_RespBody_clone(flatbuffers_builder_t *B, PBS_ifl_RespBody_union_t t);
typedef flatbuffers_union_ref_t PBS_ifl_TmBody_union_ref_t;
typedef flatbuffers_union_vec_ref_t PBS_ifl_TmBody_union_vec_ref_t;
static PBS_ifl_TmBody_union_ref_t PBS_ifl_TmBody_clone(flatbuffers_builder_t *B, PBS_ifl_TmBody_union_t t);

static const flatbuffers_voffset_t __PBS_ifl_Header_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_Header_ref_t;
static PBS_ifl_Header_ref_t PBS_ifl_Header_clone(flatbuffers_builder_t *B, PBS_ifl_Header_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_Header, 4)

static const flatbuffers_voffset_t __PBS_ifl_Attribute_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_Attribute_ref_t;
static PBS_ifl_Attribute_ref_t PBS_ifl_Attribute_clone(flatbuffers_builder_t *B, PBS_ifl_Attribute_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_Attribute, 4)

static const flatbuffers_voffset_t __PBS_ifl_Qjob_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_Qjob_ref_t;
static PBS_ifl_Qjob_ref_t PBS_ifl_Qjob_clone(flatbuffers_builder_t *B, PBS_ifl_Qjob_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_Qjob, 3)

static const flatbuffers_voffset_t __PBS_ifl_JobFile_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_JobFile_ref_t;
static PBS_ifl_JobFile_ref_t PBS_ifl_JobFile_clone(flatbuffers_builder_t *B, PBS_ifl_JobFile_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_JobFile, 5)

static const flatbuffers_voffset_t __PBS_ifl_JobId_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_JobId_ref_t;
static PBS_ifl_JobId_ref_t PBS_ifl_JobId_clone(flatbuffers_builder_t *B, PBS_ifl_JobId_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_JobId, 1)

static const flatbuffers_voffset_t __PBS_ifl_Manage_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_Manage_ref_t;
static PBS_ifl_Manage_ref_t PBS_ifl_Manage_clone(flatbuffers_builder_t *B, PBS_ifl_Manage_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_Manage, 4)

static const flatbuffers_voffset_t __PBS_ifl_Msg_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_Msg_ref_t;
static PBS_ifl_Msg_ref_t PBS_ifl_Msg_clone(flatbuffers_builder_t *B, PBS_ifl_Msg_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_Msg, 3)

static const flatbuffers_voffset_t __PBS_ifl_Move_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_Move_ref_t;
static PBS_ifl_Move_ref_t PBS_ifl_Move_clone(flatbuffers_builder_t *B, PBS_ifl_Move_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_Move, 2)

static const flatbuffers_voffset_t __PBS_ifl_Run_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_Run_ref_t;
static PBS_ifl_Run_ref_t PBS_ifl_Run_clone(flatbuffers_builder_t *B, PBS_ifl_Run_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_Run, 3)

static const flatbuffers_voffset_t __PBS_ifl_Select_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_Select_ref_t;
static PBS_ifl_Select_ref_t PBS_ifl_Select_clone(flatbuffers_builder_t *B, PBS_ifl_Select_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_Select, 2)

static const flatbuffers_voffset_t __PBS_ifl_DmnCmd_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_DmnCmd_ref_t;
static PBS_ifl_DmnCmd_ref_t PBS_ifl_DmnCmd_clone(flatbuffers_builder_t *B, PBS_ifl_DmnCmd_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_DmnCmd, 1)

static const flatbuffers_voffset_t __PBS_ifl_Signal_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_Signal_ref_t;
static PBS_ifl_Signal_ref_t PBS_ifl_Signal_clone(flatbuffers_builder_t *B, PBS_ifl_Signal_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_Signal, 2)

static const flatbuffers_voffset_t __PBS_ifl_Stat_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_Stat_ref_t;
static PBS_ifl_Stat_ref_t PBS_ifl_Stat_clone(flatbuffers_builder_t *B, PBS_ifl_Stat_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_Stat, 2)

static const flatbuffers_voffset_t __PBS_ifl_Track_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_Track_ref_t;
static PBS_ifl_Track_ref_t PBS_ifl_Track_clone(flatbuffers_builder_t *B, PBS_ifl_Track_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_Track, 4)

static const flatbuffers_voffset_t __PBS_ifl_RescQuery_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_RescQuery_ref_t;
static PBS_ifl_RescQuery_ref_t PBS_ifl_RescQuery_clone(flatbuffers_builder_t *B, PBS_ifl_RescQuery_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_RescQuery, 2)

static const flatbuffers_voffset_t __PBS_ifl_Register_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_Register_ref_t;
static PBS_ifl_Register_ref_t PBS_ifl_Register_clone(flatbuffers_builder_t *B, PBS_ifl_Register_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_Register, 6)

static const flatbuffers_voffset_t __PBS_ifl_FilePair_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_FilePair_ref_t;
static PBS_ifl_FilePair_ref_t PBS_ifl_FilePair_clone(flatbuffers_builder_t *B, PBS_ifl_FilePair_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_FilePair, 3)

static const flatbuffers_voffset_t __PBS_ifl_CopyFile_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_CopyFile_ref_t;
static PBS_ifl_CopyFile_ref_t PBS_ifl_CopyFile_clone(flatbuffers_builder_t *B, PBS_ifl_CopyFile_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_CopyFile, 6)

static const flatbuffers_voffset_t __PBS_ifl_Cred_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_Cred_ref_t;
static PBS_ifl_Cred_ref_t PBS_ifl_Cred_clone(flatbuffers_builder_t *B, PBS_ifl_Cred_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_Cred, 6)

static const flatbuffers_voffset_t __PBS_ifl_CopyFileCred_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_CopyFileCred_ref_t;
static PBS_ifl_CopyFileCred_ref_t PBS_ifl_CopyFileCred_clone(flatbuffers_builder_t *B, PBS_ifl_CopyFileCred_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_CopyFileCred, 3)

static const flatbuffers_voffset_t __PBS_ifl_UserMigrate_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_UserMigrate_ref_t;
static PBS_ifl_UserMigrate_ref_t PBS_ifl_UserMigrate_clone(flatbuffers_builder_t *B, PBS_ifl_UserMigrate_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_UserMigrate, 1)

static const flatbuffers_voffset_t __PBS_ifl_SchedDefRep_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_SchedDefRep_ref_t;
static PBS_ifl_SchedDefRep_ref_t PBS_ifl_SchedDefRep_clone(flatbuffers_builder_t *B, PBS_ifl_SchedDefRep_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_SchedDefRep, 4)

static const flatbuffers_voffset_t __PBS_ifl_Spawn_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_Spawn_ref_t;
static PBS_ifl_Spawn_ref_t PBS_ifl_Spawn_clone(flatbuffers_builder_t *B, PBS_ifl_Spawn_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_Spawn, 3)

static const flatbuffers_voffset_t __PBS_ifl_CopyHook_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_CopyHook_ref_t;
static PBS_ifl_CopyHook_ref_t PBS_ifl_CopyHook_clone(flatbuffers_builder_t *B, PBS_ifl_CopyHook_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_CopyHook, 4)

static const flatbuffers_voffset_t __PBS_ifl_RelNodes_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_RelNodes_ref_t;
static PBS_ifl_RelNodes_ref_t PBS_ifl_RelNodes_clone(flatbuffers_builder_t *B, PBS_ifl_RelNodes_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_RelNodes, 2)

static const flatbuffers_voffset_t __PBS_ifl_PreemptJob_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_PreemptJob_ref_t;
static PBS_ifl_PreemptJob_ref_t PBS_ifl_PreemptJob_clone(flatbuffers_builder_t *B, PBS_ifl_PreemptJob_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_PreemptJob, 2)

static const flatbuffers_voffset_t __PBS_ifl_Preempt_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_Preempt_ref_t;
static PBS_ifl_Preempt_ref_t PBS_ifl_Preempt_clone(flatbuffers_builder_t *B, PBS_ifl_Preempt_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_Preempt, 1)

static const flatbuffers_voffset_t __PBS_ifl_Auth_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_Auth_ref_t;
static PBS_ifl_Auth_ref_t PBS_ifl_Auth_clone(flatbuffers_builder_t *B, PBS_ifl_Auth_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_Auth, 4)

static const flatbuffers_voffset_t __PBS_ifl_Req_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_Req_ref_t;
static PBS_ifl_Req_ref_t PBS_ifl_Req_clone(flatbuffers_builder_t *B, PBS_ifl_Req_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_Req, 4)

static const flatbuffers_voffset_t __PBS_ifl_StatRespStat_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_StatRespStat_ref_t;
static PBS_ifl_StatRespStat_ref_t PBS_ifl_StatRespStat_clone(flatbuffers_builder_t *B, PBS_ifl_StatRespStat_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_StatRespStat, 3)

static const flatbuffers_voffset_t __PBS_ifl_StatResp_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_StatResp_ref_t;
static PBS_ifl_StatResp_ref_t PBS_ifl_StatResp_clone(flatbuffers_builder_t *B, PBS_ifl_StatResp_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_StatResp, 1)

static const flatbuffers_voffset_t __PBS_ifl_SelectResp_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_SelectResp_ref_t;
static PBS_ifl_SelectResp_ref_t PBS_ifl_SelectResp_clone(flatbuffers_builder_t *B, PBS_ifl_SelectResp_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_SelectResp, 1)

static const flatbuffers_voffset_t __PBS_ifl_RescQueryResp_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_RescQueryResp_ref_t;
static PBS_ifl_RescQueryResp_ref_t PBS_ifl_RescQueryResp_clone(flatbuffers_builder_t *B, PBS_ifl_RescQueryResp_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_RescQueryResp, 4)

static const flatbuffers_voffset_t __PBS_ifl_TextResp_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_TextResp_ref_t;
static PBS_ifl_TextResp_ref_t PBS_ifl_TextResp_clone(flatbuffers_builder_t *B, PBS_ifl_TextResp_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_TextResp, 1)

static const flatbuffers_voffset_t __PBS_ifl_Resp_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_Resp_ref_t;
static PBS_ifl_Resp_ref_t PBS_ifl_Resp_clone(flatbuffers_builder_t *B, PBS_ifl_Resp_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_Resp, 5)

static const flatbuffers_voffset_t __PBS_ifl_RmReq_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_RmReq_ref_t;
static PBS_ifl_RmReq_ref_t PBS_ifl_RmReq_clone(flatbuffers_builder_t *B, PBS_ifl_RmReq_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_RmReq, 2)

static const flatbuffers_voffset_t __PBS_ifl_RmResp_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_RmResp_ref_t;
static PBS_ifl_RmResp_ref_t PBS_ifl_RmResp_clone(flatbuffers_builder_t *B, PBS_ifl_RmResp_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_RmResp, 2)

static const flatbuffers_voffset_t __PBS_ifl_TmAttach_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_TmAttach_ref_t;
static PBS_ifl_TmAttach_ref_t PBS_ifl_TmAttach_clone(flatbuffers_builder_t *B, PBS_ifl_TmAttach_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_TmAttach, 3)

static const flatbuffers_voffset_t __PBS_ifl_TmSpawn_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_TmSpawn_ref_t;
static PBS_ifl_TmSpawn_ref_t PBS_ifl_TmSpawn_clone(flatbuffers_builder_t *B, PBS_ifl_TmSpawn_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_TmSpawn, 3)

static const flatbuffers_voffset_t __PBS_ifl_TmSignal_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_TmSignal_ref_t;
static PBS_ifl_TmSignal_ref_t PBS_ifl_TmSignal_clone(flatbuffers_builder_t *B, PBS_ifl_TmSignal_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_TmSignal, 3)

static const flatbuffers_voffset_t __PBS_ifl_TmObit_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_TmObit_ref_t;
static PBS_ifl_TmObit_ref_t PBS_ifl_TmObit_clone(flatbuffers_builder_t *B, PBS_ifl_TmObit_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_TmObit, 2)

static const flatbuffers_voffset_t __PBS_ifl_TmInfo_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_TmInfo_ref_t;
static PBS_ifl_TmInfo_ref_t PBS_ifl_TmInfo_clone(flatbuffers_builder_t *B, PBS_ifl_TmInfo_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_TmInfo, 1)

static const flatbuffers_voffset_t __PBS_ifl_TmPublish_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_TmPublish_ref_t;
static PBS_ifl_TmPublish_ref_t PBS_ifl_TmPublish_clone(flatbuffers_builder_t *B, PBS_ifl_TmPublish_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_TmPublish, 2)

static const flatbuffers_voffset_t __PBS_ifl_TmSubscribe_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_TmSubscribe_ref_t;
static PBS_ifl_TmSubscribe_ref_t PBS_ifl_TmSubscribe_clone(flatbuffers_builder_t *B, PBS_ifl_TmSubscribe_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_TmSubscribe, 3)

static const flatbuffers_voffset_t __PBS_ifl_TmReq_required[] = { 0 };
typedef flatbuffers_ref_t PBS_ifl_TmReq_ref_t;
static PBS_ifl_TmReq_ref_t PBS_ifl_TmReq_clone(flatbuffers_builder_t *B, PBS_ifl_TmReq_table_t t);
__flatbuffers_build_table(flatbuffers_, PBS_ifl_TmReq, 7)

#define __PBS_ifl_Header_formal_args , PBS_ifl_ProtType_enum_t v0, int16_t v1, int16_t v2, flatbuffers_string_ref_t v3
#define __PBS_ifl_Header_call_args , v0, v1, v2, v3
static inline PBS_ifl_Header_ref_t PBS_ifl_Header_create(flatbuffers_builder_t *B __PBS_ifl_Header_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_Header, PBS_ifl_Header_file_identifier, PBS_ifl_Header_type_identifier)

#define __PBS_ifl_Attribute_formal_args , flatbuffers_string_ref_t v0, flatbuffers_string_ref_t v1, flatbuffers_string_ref_t v2, PBS_ifl_batch_op_enum_t v3
#define __PBS_ifl_Attribute_call_args , v0, v1, v2, v3
static inline PBS_ifl_Attribute_ref_t PBS_ifl_Attribute_create(flatbuffers_builder_t *B __PBS_ifl_Attribute_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_Attribute, PBS_ifl_Attribute_file_identifier, PBS_ifl_Attribute_type_identifier)

#define __PBS_ifl_Qjob_formal_args , flatbuffers_string_ref_t v0, flatbuffers_string_ref_t v1, PBS_ifl_Attribute_vec_ref_t v2
#define __PBS_ifl_Qjob_call_args , v0, v1, v2
static inline PBS_ifl_Qjob_ref_t PBS_ifl_Qjob_create(flatbuffers_builder_t *B __PBS_ifl_Qjob_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_Qjob, PBS_ifl_Qjob_file_identifier, PBS_ifl_Qjob_type_identifier)

#define __PBS_ifl_JobFile_formal_args ,\
  int64_t v0, int16_t v1, int64_t v2, flatbuffers_string_ref_t v3, flatbuffers_string_ref_t v4
#define __PBS_ifl_JobFile_call_args ,\
  v0, v1, v2, v3, v4
static inline PBS_ifl_JobFile_ref_t PBS_ifl_JobFile_create(flatbuffers_builder_t *B __PBS_ifl_JobFile_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_JobFile, PBS_ifl_JobFile_file_identifier, PBS_ifl_JobFile_type_identifier)

#define __PBS_ifl_JobId_formal_args , flatbuffers_string_ref_t v0
#define __PBS_ifl_JobId_call_args , v0
static inline PBS_ifl_JobId_ref_t PBS_ifl_JobId_create(flatbuffers_builder_t *B __PBS_ifl_JobId_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_JobId, PBS_ifl_JobId_file_identifier, PBS_ifl_JobId_type_identifier)

#define __PBS_ifl_Manage_formal_args , int16_t v0, int16_t v1, flatbuffers_string_ref_t v2, PBS_ifl_Attribute_vec_ref_t v3
#define __PBS_ifl_Manage_call_args , v0, v1, v2, v3
static inline PBS_ifl_Manage_ref_t PBS_ifl_Manage_create(flatbuffers_builder_t *B __PBS_ifl_Manage_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_Manage, PBS_ifl_Manage_file_identifier, PBS_ifl_Manage_type_identifier)

#define __PBS_ifl_Msg_formal_args , int16_t v0, flatbuffers_string_ref_t v1, flatbuffers_string_ref_t v2
#define __PBS_ifl_Msg_call_args , v0, v1, v2
static inline PBS_ifl_Msg_ref_t PBS_ifl_Msg_create(flatbuffers_builder_t *B __PBS_ifl_Msg_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_Msg, PBS_ifl_Msg_file_identifier, PBS_ifl_Msg_type_identifier)

#define __PBS_ifl_Move_formal_args , flatbuffers_string_ref_t v0, flatbuffers_string_ref_t v1
#define __PBS_ifl_Move_call_args , v0, v1
static inline PBS_ifl_Move_ref_t PBS_ifl_Move_create(flatbuffers_builder_t *B __PBS_ifl_Move_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_Move, PBS_ifl_Move_file_identifier, PBS_ifl_Move_type_identifier)

#define __PBS_ifl_Run_formal_args , flatbuffers_string_ref_t v0, flatbuffers_string_ref_t v1, int64_t v2
#define __PBS_ifl_Run_call_args , v0, v1, v2
static inline PBS_ifl_Run_ref_t PBS_ifl_Run_create(flatbuffers_builder_t *B __PBS_ifl_Run_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_Run, PBS_ifl_Run_file_identifier, PBS_ifl_Run_type_identifier)

#define __PBS_ifl_Select_formal_args , PBS_ifl_Attribute_vec_ref_t v0, PBS_ifl_Attribute_vec_ref_t v1
#define __PBS_ifl_Select_call_args , v0, v1
static inline PBS_ifl_Select_ref_t PBS_ifl_Select_create(flatbuffers_builder_t *B __PBS_ifl_Select_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_Select, PBS_ifl_Select_file_identifier, PBS_ifl_Select_type_identifier)

#define __PBS_ifl_DmnCmd_formal_args , int16_t v0
#define __PBS_ifl_DmnCmd_call_args , v0
static inline PBS_ifl_DmnCmd_ref_t PBS_ifl_DmnCmd_create(flatbuffers_builder_t *B __PBS_ifl_DmnCmd_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_DmnCmd, PBS_ifl_DmnCmd_file_identifier, PBS_ifl_DmnCmd_type_identifier)

#define __PBS_ifl_Signal_formal_args , flatbuffers_string_ref_t v0, flatbuffers_string_ref_t v1
#define __PBS_ifl_Signal_call_args , v0, v1
static inline PBS_ifl_Signal_ref_t PBS_ifl_Signal_create(flatbuffers_builder_t *B __PBS_ifl_Signal_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_Signal, PBS_ifl_Signal_file_identifier, PBS_ifl_Signal_type_identifier)

#define __PBS_ifl_Stat_formal_args , flatbuffers_string_ref_t v0, PBS_ifl_Attribute_vec_ref_t v1
#define __PBS_ifl_Stat_call_args , v0, v1
static inline PBS_ifl_Stat_ref_t PBS_ifl_Stat_create(flatbuffers_builder_t *B __PBS_ifl_Stat_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_Stat, PBS_ifl_Stat_file_identifier, PBS_ifl_Stat_type_identifier)

#define __PBS_ifl_Track_formal_args , int16_t v0, flatbuffers_string_ref_t v1, flatbuffers_string_ref_t v2, int8_t v3
#define __PBS_ifl_Track_call_args , v0, v1, v2, v3
static inline PBS_ifl_Track_ref_t PBS_ifl_Track_create(flatbuffers_builder_t *B __PBS_ifl_Track_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_Track, PBS_ifl_Track_file_identifier, PBS_ifl_Track_type_identifier)

#define __PBS_ifl_RescQuery_formal_args , int16_t v0, flatbuffers_string_vec_ref_t v1
#define __PBS_ifl_RescQuery_call_args , v0, v1
static inline PBS_ifl_RescQuery_ref_t PBS_ifl_RescQuery_create(flatbuffers_builder_t *B __PBS_ifl_RescQuery_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_RescQuery, PBS_ifl_RescQuery_file_identifier, PBS_ifl_RescQuery_type_identifier)

#define __PBS_ifl_Register_formal_args ,\
  flatbuffers_string_ref_t v0, flatbuffers_string_ref_t v1, flatbuffers_string_ref_t v2, int16_t v3, int16_t v4, int64_t v5
#define __PBS_ifl_Register_call_args ,\
  v0, v1, v2, v3, v4, v5
static inline PBS_ifl_Register_ref_t PBS_ifl_Register_create(flatbuffers_builder_t *B __PBS_ifl_Register_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_Register, PBS_ifl_Register_file_identifier, PBS_ifl_Register_type_identifier)

#define __PBS_ifl_FilePair_formal_args , flatbuffers_string_ref_t v0, flatbuffers_string_ref_t v1, int16_t v2
#define __PBS_ifl_FilePair_call_args , v0, v1, v2
static inline PBS_ifl_FilePair_ref_t PBS_ifl_FilePair_create(flatbuffers_builder_t *B __PBS_ifl_FilePair_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_FilePair, PBS_ifl_FilePair_file_identifier, PBS_ifl_FilePair_type_identifier)

#define __PBS_ifl_CopyFile_formal_args ,\
  flatbuffers_string_ref_t v0, flatbuffers_string_ref_t v1, flatbuffers_string_ref_t v2, flatbuffers_string_ref_t v3, int16_t v4, PBS_ifl_FilePair_vec_ref_t v5
#define __PBS_ifl_CopyFile_call_args ,\
  v0, v1, v2, v3, v4, v5
static inline PBS_ifl_CopyFile_ref_t PBS_ifl_CopyFile_create(flatbuffers_builder_t *B __PBS_ifl_CopyFile_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_CopyFile, PBS_ifl_CopyFile_file_identifier, PBS_ifl_CopyFile_type_identifier)

#define __PBS_ifl_Cred_formal_args ,\
  flatbuffers_string_ref_t v0, flatbuffers_string_ref_t v1, int64_t v2, int16_t v3, int16_t v4, flatbuffers_string_ref_t v5
#define __PBS_ifl_Cred_call_args ,\
  v0, v1, v2, v3, v4, v5
static inline PBS_ifl_Cred_ref_t PBS_ifl_Cred_create(flatbuffers_builder_t *B __PBS_ifl_Cred_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_Cred, PBS_ifl_Cred_file_identifier, PBS_ifl_Cred_type_identifier)

#define __PBS_ifl_CopyFileCred_formal_args , PBS_ifl_CopyFile_ref_t v0, int16_t v1, flatbuffers_string_ref_t v2
#define __PBS_ifl_CopyFileCred_call_args , v0, v1, v2
static inline PBS_ifl_CopyFileCred_ref_t PBS_ifl_CopyFileCred_create(flatbuffers_builder_t *B __PBS_ifl_CopyFileCred_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_CopyFileCred, PBS_ifl_CopyFileCred_file_identifier, PBS_ifl_CopyFileCred_type_identifier)

#define __PBS_ifl_UserMigrate_formal_args , flatbuffers_string_ref_t v0
#define __PBS_ifl_UserMigrate_call_args , v0
static inline PBS_ifl_UserMigrate_ref_t PBS_ifl_UserMigrate_create(flatbuffers_builder_t *B __PBS_ifl_UserMigrate_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_UserMigrate, PBS_ifl_UserMigrate_file_identifier, PBS_ifl_UserMigrate_type_identifier)

#define __PBS_ifl_SchedDefRep_formal_args , int16_t v0, flatbuffers_string_ref_t v1, int16_t v2, flatbuffers_string_ref_t v3
#define __PBS_ifl_SchedDefRep_call_args , v0, v1, v2, v3
static inline PBS_ifl_SchedDefRep_ref_t PBS_ifl_SchedDefRep_create(flatbuffers_builder_t *B __PBS_ifl_SchedDefRep_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_SchedDefRep, PBS_ifl_SchedDefRep_file_identifier, PBS_ifl_SchedDefRep_type_identifier)

#define __PBS_ifl_Spawn_formal_args , flatbuffers_string_ref_t v0, flatbuffers_string_vec_ref_t v1, flatbuffers_string_vec_ref_t v2
#define __PBS_ifl_Spawn_call_args , v0, v1, v2
static inline PBS_ifl_Spawn_ref_t PBS_ifl_Spawn_create(flatbuffers_builder_t *B __PBS_ifl_Spawn_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_Spawn, PBS_ifl_Spawn_file_identifier, PBS_ifl_Spawn_type_identifier)

#define __PBS_ifl_CopyHook_formal_args , int16_t v0, int64_t v1, flatbuffers_string_ref_t v2, flatbuffers_string_ref_t v3
#define __PBS_ifl_CopyHook_call_args , v0, v1, v2, v3
static inline PBS_ifl_CopyHook_ref_t PBS_ifl_CopyHook_create(flatbuffers_builder_t *B __PBS_ifl_CopyHook_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_CopyHook, PBS_ifl_CopyHook_file_identifier, PBS_ifl_CopyHook_type_identifier)

#define __PBS_ifl_RelNodes_formal_args , flatbuffers_string_ref_t v0, flatbuffers_string_ref_t v1
#define __PBS_ifl_RelNodes_call_args , v0, v1
static inline PBS_ifl_RelNodes_ref_t PBS_ifl_RelNodes_create(flatbuffers_builder_t *B __PBS_ifl_RelNodes_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_RelNodes, PBS_ifl_RelNodes_file_identifier, PBS_ifl_RelNodes_type_identifier)

#define __PBS_ifl_PreemptJob_formal_args , flatbuffers_string_ref_t v0, flatbuffers_string_ref_t v1
#define __PBS_ifl_PreemptJob_call_args , v0, v1
static inline PBS_ifl_PreemptJob_ref_t PBS_ifl_PreemptJob_create(flatbuffers_builder_t *B __PBS_ifl_PreemptJob_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_PreemptJob, PBS_ifl_PreemptJob_file_identifier, PBS_ifl_PreemptJob_type_identifier)

#define __PBS_ifl_Preempt_formal_args , PBS_ifl_PreemptJob_vec_ref_t v0
#define __PBS_ifl_Preempt_call_args , v0
static inline PBS_ifl_Preempt_ref_t PBS_ifl_Preempt_create(flatbuffers_builder_t *B __PBS_ifl_Preempt_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_Preempt, PBS_ifl_Preempt_file_identifier, PBS_ifl_Preempt_type_identifier)

#define __PBS_ifl_Auth_formal_args , flatbuffers_string_ref_t v0, flatbuffers_string_ref_t v1, uint16_t v2, uint16_t v3
#define __PBS_ifl_Auth_call_args , v0, v1, v2, v3
static inline PBS_ifl_Auth_ref_t PBS_ifl_Auth_create(flatbuffers_builder_t *B __PBS_ifl_Auth_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_Auth, PBS_ifl_Auth_file_identifier, PBS_ifl_Auth_type_identifier)

#define __PBS_ifl_Req_formal_args , PBS_ifl_Header_ref_t v0, PBS_ifl_ReqBody_union_ref_t v2, flatbuffers_string_ref_t v3
#define __PBS_ifl_Req_call_args , v0, v2, v3
static inline PBS_ifl_Req_ref_t PBS_ifl_Req_create(flatbuffers_builder_t *B __PBS_ifl_Req_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_Req, PBS_ifl_Req_file_identifier, PBS_ifl_Req_type_identifier)

#define __PBS_ifl_StatRespStat_formal_args , int16_t v0, flatbuffers_string_ref_t v1, PBS_ifl_Attribute_vec_ref_t v2
#define __PBS_ifl_StatRespStat_call_args , v0, v1, v2
static inline PBS_ifl_StatRespStat_ref_t PBS_ifl_StatRespStat_create(flatbuffers_builder_t *B __PBS_ifl_StatRespStat_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_StatRespStat, PBS_ifl_StatRespStat_file_identifier, PBS_ifl_StatRespStat_type_identifier)

#define __PBS_ifl_StatResp_formal_args , PBS_ifl_StatRespStat_vec_ref_t v0
#define __PBS_ifl_StatResp_call_args , v0
static inline PBS_ifl_StatResp_ref_t PBS_ifl_StatResp_create(flatbuffers_builder_t *B __PBS_ifl_StatResp_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_StatResp, PBS_ifl_StatResp_file_identifier, PBS_ifl_StatResp_type_identifier)

#define __PBS_ifl_SelectResp_formal_args , flatbuffers_string_vec_ref_t v0
#define __PBS_ifl_SelectResp_call_args , v0
static inline PBS_ifl_SelectResp_ref_t PBS_ifl_SelectResp_create(flatbuffers_builder_t *B __PBS_ifl_SelectResp_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_SelectResp, PBS_ifl_SelectResp_file_identifier, PBS_ifl_SelectResp_type_identifier)

#define __PBS_ifl_RescQueryResp_formal_args , flatbuffers_int16_vec_ref_t v0, flatbuffers_int16_vec_ref_t v1, flatbuffers_int16_vec_ref_t v2, flatbuffers_int16_vec_ref_t v3
#define __PBS_ifl_RescQueryResp_call_args , v0, v1, v2, v3
static inline PBS_ifl_RescQueryResp_ref_t PBS_ifl_RescQueryResp_create(flatbuffers_builder_t *B __PBS_ifl_RescQueryResp_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_RescQueryResp, PBS_ifl_RescQueryResp_file_identifier, PBS_ifl_RescQueryResp_type_identifier)

#define __PBS_ifl_TextResp_formal_args , flatbuffers_string_ref_t v0
#define __PBS_ifl_TextResp_call_args , v0
static inline PBS_ifl_TextResp_ref_t PBS_ifl_TextResp_create(flatbuffers_builder_t *B __PBS_ifl_TextResp_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_TextResp, PBS_ifl_TextResp_file_identifier, PBS_ifl_TextResp_type_identifier)

#define __PBS_ifl_Resp_formal_args , int16_t v0, int16_t v1, int16_t v2, PBS_ifl_RespBody_union_ref_t v4
#define __PBS_ifl_Resp_call_args , v0, v1, v2, v4
static inline PBS_ifl_Resp_ref_t PBS_ifl_Resp_create(flatbuffers_builder_t *B __PBS_ifl_Resp_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_Resp, PBS_ifl_Resp_file_identifier, PBS_ifl_Resp_type_identifier)

#define __PBS_ifl_RmReq_formal_args , PBS_ifl_Header_ref_t v0, flatbuffers_string_vec_ref_t v1
#define __PBS_ifl_RmReq_call_args , v0, v1
static inline PBS_ifl_RmReq_ref_t PBS_ifl_RmReq_create(flatbuffers_builder_t *B __PBS_ifl_RmReq_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_RmReq, PBS_ifl_RmReq_file_identifier, PBS_ifl_RmReq_type_identifier)

#define __PBS_ifl_RmResp_formal_args , int16_t v0, flatbuffers_string_vec_ref_t v1
#define __PBS_ifl_RmResp_call_args , v0, v1
static inline PBS_ifl_RmResp_ref_t PBS_ifl_RmResp_create(flatbuffers_builder_t *B __PBS_ifl_RmResp_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_RmResp, PBS_ifl_RmResp_file_identifier, PBS_ifl_RmResp_type_identifier)

#define __PBS_ifl_TmAttach_formal_args , flatbuffers_string_ref_t v0, int16_t v1, int16_t v2
#define __PBS_ifl_TmAttach_call_args , v0, v1, v2
static inline PBS_ifl_TmAttach_ref_t PBS_ifl_TmAttach_create(flatbuffers_builder_t *B __PBS_ifl_TmAttach_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_TmAttach, PBS_ifl_TmAttach_file_identifier, PBS_ifl_TmAttach_type_identifier)

#define __PBS_ifl_TmSpawn_formal_args , int16_t v0, flatbuffers_string_vec_ref_t v1, flatbuffers_string_vec_ref_t v2
#define __PBS_ifl_TmSpawn_call_args , v0, v1, v2
static inline PBS_ifl_TmSpawn_ref_t PBS_ifl_TmSpawn_create(flatbuffers_builder_t *B __PBS_ifl_TmSpawn_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_TmSpawn, PBS_ifl_TmSpawn_file_identifier, PBS_ifl_TmSpawn_type_identifier)

#define __PBS_ifl_TmSignal_formal_args , int16_t v0, int16_t v1, int16_t v2
#define __PBS_ifl_TmSignal_call_args , v0, v1, v2
static inline PBS_ifl_TmSignal_ref_t PBS_ifl_TmSignal_create(flatbuffers_builder_t *B __PBS_ifl_TmSignal_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_TmSignal, PBS_ifl_TmSignal_file_identifier, PBS_ifl_TmSignal_type_identifier)

#define __PBS_ifl_TmObit_formal_args , int16_t v0, int16_t v1
#define __PBS_ifl_TmObit_call_args , v0, v1
static inline PBS_ifl_TmObit_ref_t PBS_ifl_TmObit_create(flatbuffers_builder_t *B __PBS_ifl_TmObit_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_TmObit, PBS_ifl_TmObit_file_identifier, PBS_ifl_TmObit_type_identifier)

#define __PBS_ifl_TmInfo_formal_args , int16_t v0
#define __PBS_ifl_TmInfo_call_args , v0
static inline PBS_ifl_TmInfo_ref_t PBS_ifl_TmInfo_create(flatbuffers_builder_t *B __PBS_ifl_TmInfo_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_TmInfo, PBS_ifl_TmInfo_file_identifier, PBS_ifl_TmInfo_type_identifier)

#define __PBS_ifl_TmPublish_formal_args , flatbuffers_string_ref_t v0, flatbuffers_string_ref_t v1
#define __PBS_ifl_TmPublish_call_args , v0, v1
static inline PBS_ifl_TmPublish_ref_t PBS_ifl_TmPublish_create(flatbuffers_builder_t *B __PBS_ifl_TmPublish_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_TmPublish, PBS_ifl_TmPublish_file_identifier, PBS_ifl_TmPublish_type_identifier)

#define __PBS_ifl_TmSubscribe_formal_args , int16_t v0, int16_t v1, flatbuffers_string_ref_t v2
#define __PBS_ifl_TmSubscribe_call_args , v0, v1, v2
static inline PBS_ifl_TmSubscribe_ref_t PBS_ifl_TmSubscribe_create(flatbuffers_builder_t *B __PBS_ifl_TmSubscribe_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_TmSubscribe, PBS_ifl_TmSubscribe_file_identifier, PBS_ifl_TmSubscribe_type_identifier)

#define __PBS_ifl_TmReq_formal_args ,\
  PBS_ifl_Header_ref_t v0, flatbuffers_string_ref_t v1, flatbuffers_string_ref_t v2, int16_t v3, int16_t v4, PBS_ifl_TmBody_union_ref_t v6
#define __PBS_ifl_TmReq_call_args ,\
  v0, v1, v2, v3, v4, v6
static inline PBS_ifl_TmReq_ref_t PBS_ifl_TmReq_create(flatbuffers_builder_t *B __PBS_ifl_TmReq_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PBS_ifl_TmReq, PBS_ifl_TmReq_file_identifier, PBS_ifl_TmReq_type_identifier)

static inline PBS_ifl_ReqBody_union_ref_t PBS_ifl_ReqBody_as_NONE()
{ PBS_ifl_ReqBody_union_ref_t uref; uref.type = PBS_ifl_ReqBody_NONE; uref.value = 0; return uref; }
static inline PBS_ifl_ReqBody_union_ref_t PBS_ifl_ReqBody_as_Qjob(PBS_ifl_Qjob_ref_t ref)
{ PBS_ifl_ReqBody_union_ref_t uref; uref.type = PBS_ifl_ReqBody_Qjob; uref.value = ref; return uref; }
static inline PBS_ifl_ReqBody_union_ref_t PBS_ifl_ReqBody_as_JobFile(PBS_ifl_JobFile_ref_t ref)
{ PBS_ifl_ReqBody_union_ref_t uref; uref.type = PBS_ifl_ReqBody_JobFile; uref.value = ref; return uref; }
static inline PBS_ifl_ReqBody_union_ref_t PBS_ifl_ReqBody_as_JobId(PBS_ifl_JobId_ref_t ref)
{ PBS_ifl_ReqBody_union_ref_t uref; uref.type = PBS_ifl_ReqBody_JobId; uref.value = ref; return uref; }
static inline PBS_ifl_ReqBody_union_ref_t PBS_ifl_ReqBody_as_Manage(PBS_ifl_Manage_ref_t ref)
{ PBS_ifl_ReqBody_union_ref_t uref; uref.type = PBS_ifl_ReqBody_Manage; uref.value = ref; return uref; }
static inline PBS_ifl_ReqBody_union_ref_t PBS_ifl_ReqBody_as_Msg(PBS_ifl_Msg_ref_t ref)
{ PBS_ifl_ReqBody_union_ref_t uref; uref.type = PBS_ifl_ReqBody_Msg; uref.value = ref; return uref; }
static inline PBS_ifl_ReqBody_union_ref_t PBS_ifl_ReqBody_as_Move(PBS_ifl_Move_ref_t ref)
{ PBS_ifl_ReqBody_union_ref_t uref; uref.type = PBS_ifl_ReqBody_Move; uref.value = ref; return uref; }
static inline PBS_ifl_ReqBody_union_ref_t PBS_ifl_ReqBody_as_Run(PBS_ifl_Run_ref_t ref)
{ PBS_ifl_ReqBody_union_ref_t uref; uref.type = PBS_ifl_ReqBody_Run; uref.value = ref; return uref; }
static inline PBS_ifl_ReqBody_union_ref_t PBS_ifl_ReqBody_as_Select(PBS_ifl_Select_ref_t ref)
{ PBS_ifl_ReqBody_union_ref_t uref; uref.type = PBS_ifl_ReqBody_Select; uref.value = ref; return uref; }
static inline PBS_ifl_ReqBody_union_ref_t PBS_ifl_ReqBody_as_DmnCmd(PBS_ifl_DmnCmd_ref_t ref)
{ PBS_ifl_ReqBody_union_ref_t uref; uref.type = PBS_ifl_ReqBody_DmnCmd; uref.value = ref; return uref; }
static inline PBS_ifl_ReqBody_union_ref_t PBS_ifl_ReqBody_as_Signal(PBS_ifl_Signal_ref_t ref)
{ PBS_ifl_ReqBody_union_ref_t uref; uref.type = PBS_ifl_ReqBody_Signal; uref.value = ref; return uref; }
static inline PBS_ifl_ReqBody_union_ref_t PBS_ifl_ReqBody_as_Stat(PBS_ifl_Stat_ref_t ref)
{ PBS_ifl_ReqBody_union_ref_t uref; uref.type = PBS_ifl_ReqBody_Stat; uref.value = ref; return uref; }
static inline PBS_ifl_ReqBody_union_ref_t PBS_ifl_ReqBody_as_Track(PBS_ifl_Track_ref_t ref)
{ PBS_ifl_ReqBody_union_ref_t uref; uref.type = PBS_ifl_ReqBody_Track; uref.value = ref; return uref; }
static inline PBS_ifl_ReqBody_union_ref_t PBS_ifl_ReqBody_as_RescQuery(PBS_ifl_RescQuery_ref_t ref)
{ PBS_ifl_ReqBody_union_ref_t uref; uref.type = PBS_ifl_ReqBody_RescQuery; uref.value = ref; return uref; }
static inline PBS_ifl_ReqBody_union_ref_t PBS_ifl_ReqBody_as_Register(PBS_ifl_Register_ref_t ref)
{ PBS_ifl_ReqBody_union_ref_t uref; uref.type = PBS_ifl_ReqBody_Register; uref.value = ref; return uref; }
static inline PBS_ifl_ReqBody_union_ref_t PBS_ifl_ReqBody_as_CopyFile(PBS_ifl_CopyFile_ref_t ref)
{ PBS_ifl_ReqBody_union_ref_t uref; uref.type = PBS_ifl_ReqBody_CopyFile; uref.value = ref; return uref; }
static inline PBS_ifl_ReqBody_union_ref_t PBS_ifl_ReqBody_as_Cred(PBS_ifl_Cred_ref_t ref)
{ PBS_ifl_ReqBody_union_ref_t uref; uref.type = PBS_ifl_ReqBody_Cred; uref.value = ref; return uref; }
static inline PBS_ifl_ReqBody_union_ref_t PBS_ifl_ReqBody_as_CopyFileCred(PBS_ifl_CopyFileCred_ref_t ref)
{ PBS_ifl_ReqBody_union_ref_t uref; uref.type = PBS_ifl_ReqBody_CopyFileCred; uref.value = ref; return uref; }
static inline PBS_ifl_ReqBody_union_ref_t PBS_ifl_ReqBody_as_UserMigrate(PBS_ifl_UserMigrate_ref_t ref)
{ PBS_ifl_ReqBody_union_ref_t uref; uref.type = PBS_ifl_ReqBody_UserMigrate; uref.value = ref; return uref; }
static inline PBS_ifl_ReqBody_union_ref_t PBS_ifl_ReqBody_as_SchedDefRep(PBS_ifl_SchedDefRep_ref_t ref)
{ PBS_ifl_ReqBody_union_ref_t uref; uref.type = PBS_ifl_ReqBody_SchedDefRep; uref.value = ref; return uref; }
static inline PBS_ifl_ReqBody_union_ref_t PBS_ifl_ReqBody_as_Spawn(PBS_ifl_Spawn_ref_t ref)
{ PBS_ifl_ReqBody_union_ref_t uref; uref.type = PBS_ifl_ReqBody_Spawn; uref.value = ref; return uref; }
static inline PBS_ifl_ReqBody_union_ref_t PBS_ifl_ReqBody_as_CopyHook(PBS_ifl_CopyHook_ref_t ref)
{ PBS_ifl_ReqBody_union_ref_t uref; uref.type = PBS_ifl_ReqBody_CopyHook; uref.value = ref; return uref; }
static inline PBS_ifl_ReqBody_union_ref_t PBS_ifl_ReqBody_as_RelNodes(PBS_ifl_RelNodes_ref_t ref)
{ PBS_ifl_ReqBody_union_ref_t uref; uref.type = PBS_ifl_ReqBody_RelNodes; uref.value = ref; return uref; }
static inline PBS_ifl_ReqBody_union_ref_t PBS_ifl_ReqBody_as_Preempt(PBS_ifl_Preempt_ref_t ref)
{ PBS_ifl_ReqBody_union_ref_t uref; uref.type = PBS_ifl_ReqBody_Preempt; uref.value = ref; return uref; }
static inline PBS_ifl_ReqBody_union_ref_t PBS_ifl_ReqBody_as_Auth(PBS_ifl_Auth_ref_t ref)
{ PBS_ifl_ReqBody_union_ref_t uref; uref.type = PBS_ifl_ReqBody_Auth; uref.value = ref; return uref; }
__flatbuffers_build_union_vector(flatbuffers_, PBS_ifl_ReqBody)

static PBS_ifl_ReqBody_union_ref_t PBS_ifl_ReqBody_clone(flatbuffers_builder_t *B, PBS_ifl_ReqBody_union_t u)
{
    switch (u.type) {
    case 1: return PBS_ifl_ReqBody_as_Qjob(PBS_ifl_Qjob_clone(B, (PBS_ifl_Qjob_table_t)u.value));
    case 2: return PBS_ifl_ReqBody_as_JobFile(PBS_ifl_JobFile_clone(B, (PBS_ifl_JobFile_table_t)u.value));
    case 3: return PBS_ifl_ReqBody_as_JobId(PBS_ifl_JobId_clone(B, (PBS_ifl_JobId_table_t)u.value));
    case 4: return PBS_ifl_ReqBody_as_Manage(PBS_ifl_Manage_clone(B, (PBS_ifl_Manage_table_t)u.value));
    case 5: return PBS_ifl_ReqBody_as_Msg(PBS_ifl_Msg_clone(B, (PBS_ifl_Msg_table_t)u.value));
    case 6: return PBS_ifl_ReqBody_as_Move(PBS_ifl_Move_clone(B, (PBS_ifl_Move_table_t)u.value));
    case 7: return PBS_ifl_ReqBody_as_Run(PBS_ifl_Run_clone(B, (PBS_ifl_Run_table_t)u.value));
    case 8: return PBS_ifl_ReqBody_as_Select(PBS_ifl_Select_clone(B, (PBS_ifl_Select_table_t)u.value));
    case 9: return PBS_ifl_ReqBody_as_DmnCmd(PBS_ifl_DmnCmd_clone(B, (PBS_ifl_DmnCmd_table_t)u.value));
    case 10: return PBS_ifl_ReqBody_as_Signal(PBS_ifl_Signal_clone(B, (PBS_ifl_Signal_table_t)u.value));
    case 11: return PBS_ifl_ReqBody_as_Stat(PBS_ifl_Stat_clone(B, (PBS_ifl_Stat_table_t)u.value));
    case 12: return PBS_ifl_ReqBody_as_Track(PBS_ifl_Track_clone(B, (PBS_ifl_Track_table_t)u.value));
    case 13: return PBS_ifl_ReqBody_as_RescQuery(PBS_ifl_RescQuery_clone(B, (PBS_ifl_RescQuery_table_t)u.value));
    case 14: return PBS_ifl_ReqBody_as_Register(PBS_ifl_Register_clone(B, (PBS_ifl_Register_table_t)u.value));
    case 15: return PBS_ifl_ReqBody_as_CopyFile(PBS_ifl_CopyFile_clone(B, (PBS_ifl_CopyFile_table_t)u.value));
    case 16: return PBS_ifl_ReqBody_as_Cred(PBS_ifl_Cred_clone(B, (PBS_ifl_Cred_table_t)u.value));
    case 17: return PBS_ifl_ReqBody_as_CopyFileCred(PBS_ifl_CopyFileCred_clone(B, (PBS_ifl_CopyFileCred_table_t)u.value));
    case 18: return PBS_ifl_ReqBody_as_UserMigrate(PBS_ifl_UserMigrate_clone(B, (PBS_ifl_UserMigrate_table_t)u.value));
    case 19: return PBS_ifl_ReqBody_as_SchedDefRep(PBS_ifl_SchedDefRep_clone(B, (PBS_ifl_SchedDefRep_table_t)u.value));
    case 20: return PBS_ifl_ReqBody_as_Spawn(PBS_ifl_Spawn_clone(B, (PBS_ifl_Spawn_table_t)u.value));
    case 21: return PBS_ifl_ReqBody_as_CopyHook(PBS_ifl_CopyHook_clone(B, (PBS_ifl_CopyHook_table_t)u.value));
    case 22: return PBS_ifl_ReqBody_as_RelNodes(PBS_ifl_RelNodes_clone(B, (PBS_ifl_RelNodes_table_t)u.value));
    case 23: return PBS_ifl_ReqBody_as_Preempt(PBS_ifl_Preempt_clone(B, (PBS_ifl_Preempt_table_t)u.value));
    case 24: return PBS_ifl_ReqBody_as_Auth(PBS_ifl_Auth_clone(B, (PBS_ifl_Auth_table_t)u.value));
    default: return PBS_ifl_ReqBody_as_NONE();
    }
}

static inline PBS_ifl_RespBody_union_ref_t PBS_ifl_RespBody_as_NONE()
{ PBS_ifl_RespBody_union_ref_t uref; uref.type = PBS_ifl_RespBody_NONE; uref.value = 0; return uref; }
static inline PBS_ifl_RespBody_union_ref_t PBS_ifl_RespBody_as_TextResp(PBS_ifl_TextResp_ref_t ref)
{ PBS_ifl_RespBody_union_ref_t uref; uref.type = PBS_ifl_RespBody_TextResp; uref.value = ref; return uref; }
static inline PBS_ifl_RespBody_union_ref_t PBS_ifl_RespBody_as_SelectResp(PBS_ifl_SelectResp_ref_t ref)
{ PBS_ifl_RespBody_union_ref_t uref; uref.type = PBS_ifl_RespBody_SelectResp; uref.value = ref; return uref; }
static inline PBS_ifl_RespBody_union_ref_t PBS_ifl_RespBody_as_StatResp(PBS_ifl_StatResp_ref_t ref)
{ PBS_ifl_RespBody_union_ref_t uref; uref.type = PBS_ifl_RespBody_StatResp; uref.value = ref; return uref; }
static inline PBS_ifl_RespBody_union_ref_t PBS_ifl_RespBody_as_RescQueryResp(PBS_ifl_RescQueryResp_ref_t ref)
{ PBS_ifl_RespBody_union_ref_t uref; uref.type = PBS_ifl_RespBody_RescQueryResp; uref.value = ref; return uref; }
static inline PBS_ifl_RespBody_union_ref_t PBS_ifl_RespBody_as_Preempt(PBS_ifl_Preempt_ref_t ref)
{ PBS_ifl_RespBody_union_ref_t uref; uref.type = PBS_ifl_RespBody_Preempt; uref.value = ref; return uref; }
__flatbuffers_build_union_vector(flatbuffers_, PBS_ifl_RespBody)

static PBS_ifl_RespBody_union_ref_t PBS_ifl_RespBody_clone(flatbuffers_builder_t *B, PBS_ifl_RespBody_union_t u)
{
    switch (u.type) {
    case 1: return PBS_ifl_RespBody_as_TextResp(PBS_ifl_TextResp_clone(B, (PBS_ifl_TextResp_table_t)u.value));
    case 2: return PBS_ifl_RespBody_as_SelectResp(PBS_ifl_SelectResp_clone(B, (PBS_ifl_SelectResp_table_t)u.value));
    case 3: return PBS_ifl_RespBody_as_StatResp(PBS_ifl_StatResp_clone(B, (PBS_ifl_StatResp_table_t)u.value));
    case 4: return PBS_ifl_RespBody_as_RescQueryResp(PBS_ifl_RescQueryResp_clone(B, (PBS_ifl_RescQueryResp_table_t)u.value));
    case 5: return PBS_ifl_RespBody_as_Preempt(PBS_ifl_Preempt_clone(B, (PBS_ifl_Preempt_table_t)u.value));
    default: return PBS_ifl_RespBody_as_NONE();
    }
}

static inline PBS_ifl_TmBody_union_ref_t PBS_ifl_TmBody_as_NONE()
{ PBS_ifl_TmBody_union_ref_t uref; uref.type = PBS_ifl_TmBody_NONE; uref.value = 0; return uref; }
static inline PBS_ifl_TmBody_union_ref_t PBS_ifl_TmBody_as_TmAttach(PBS_ifl_TmAttach_ref_t ref)
{ PBS_ifl_TmBody_union_ref_t uref; uref.type = PBS_ifl_TmBody_TmAttach; uref.value = ref; return uref; }
static inline PBS_ifl_TmBody_union_ref_t PBS_ifl_TmBody_as_TmSpawn(PBS_ifl_TmSpawn_ref_t ref)
{ PBS_ifl_TmBody_union_ref_t uref; uref.type = PBS_ifl_TmBody_TmSpawn; uref.value = ref; return uref; }
static inline PBS_ifl_TmBody_union_ref_t PBS_ifl_TmBody_as_TmSignal(PBS_ifl_TmSignal_ref_t ref)
{ PBS_ifl_TmBody_union_ref_t uref; uref.type = PBS_ifl_TmBody_TmSignal; uref.value = ref; return uref; }
static inline PBS_ifl_TmBody_union_ref_t PBS_ifl_TmBody_as_TmObit(PBS_ifl_TmObit_ref_t ref)
{ PBS_ifl_TmBody_union_ref_t uref; uref.type = PBS_ifl_TmBody_TmObit; uref.value = ref; return uref; }
static inline PBS_ifl_TmBody_union_ref_t PBS_ifl_TmBody_as_TmInfo(PBS_ifl_TmInfo_ref_t ref)
{ PBS_ifl_TmBody_union_ref_t uref; uref.type = PBS_ifl_TmBody_TmInfo; uref.value = ref; return uref; }
static inline PBS_ifl_TmBody_union_ref_t PBS_ifl_TmBody_as_TmPublish(PBS_ifl_TmPublish_ref_t ref)
{ PBS_ifl_TmBody_union_ref_t uref; uref.type = PBS_ifl_TmBody_TmPublish; uref.value = ref; return uref; }
static inline PBS_ifl_TmBody_union_ref_t PBS_ifl_TmBody_as_TmSubscribe(PBS_ifl_TmSubscribe_ref_t ref)
{ PBS_ifl_TmBody_union_ref_t uref; uref.type = PBS_ifl_TmBody_TmSubscribe; uref.value = ref; return uref; }
__flatbuffers_build_union_vector(flatbuffers_, PBS_ifl_TmBody)

static PBS_ifl_TmBody_union_ref_t PBS_ifl_TmBody_clone(flatbuffers_builder_t *B, PBS_ifl_TmBody_union_t u)
{
    switch (u.type) {
    case 1: return PBS_ifl_TmBody_as_TmAttach(PBS_ifl_TmAttach_clone(B, (PBS_ifl_TmAttach_table_t)u.value));
    case 2: return PBS_ifl_TmBody_as_TmSpawn(PBS_ifl_TmSpawn_clone(B, (PBS_ifl_TmSpawn_table_t)u.value));
    case 3: return PBS_ifl_TmBody_as_TmSignal(PBS_ifl_TmSignal_clone(B, (PBS_ifl_TmSignal_table_t)u.value));
    case 4: return PBS_ifl_TmBody_as_TmObit(PBS_ifl_TmObit_clone(B, (PBS_ifl_TmObit_table_t)u.value));
    case 5: return PBS_ifl_TmBody_as_TmInfo(PBS_ifl_TmInfo_clone(B, (PBS_ifl_TmInfo_table_t)u.value));
    case 6: return PBS_ifl_TmBody_as_TmPublish(PBS_ifl_TmPublish_clone(B, (PBS_ifl_TmPublish_table_t)u.value));
    case 7: return PBS_ifl_TmBody_as_TmSubscribe(PBS_ifl_TmSubscribe_clone(B, (PBS_ifl_TmSubscribe_table_t)u.value));
    default: return PBS_ifl_TmBody_as_NONE();
    }
}

__flatbuffers_build_scalar_field(0, flatbuffers_, PBS_ifl_Header_protType, PBS_ifl_ProtType, PBS_ifl_ProtType_enum_t, 1, 1, INT8_C(0), PBS_ifl_Header)
__flatbuffers_build_scalar_field(1, flatbuffers_, PBS_ifl_Header_version, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_Header)
__flatbuffers_build_scalar_field(2, flatbuffers_, PBS_ifl_Header_reqId, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_Header)
__flatbuffers_build_string_field(3, flatbuffers_, PBS_ifl_Header_user, PBS_ifl_Header)

static inline PBS_ifl_Header_ref_t PBS_ifl_Header_create(flatbuffers_builder_t *B __PBS_ifl_Header_formal_args)
{
    if (PBS_ifl_Header_start(B)
        || PBS_ifl_Header_user_add(B, v3)
        || PBS_ifl_Header_version_add(B, v1)
        || PBS_ifl_Header_reqId_add(B, v2)
        || PBS_ifl_Header_protType_add(B, v0)) {
        return 0;
    }
    return PBS_ifl_Header_end(B);
}

static PBS_ifl_Header_ref_t PBS_ifl_Header_clone(flatbuffers_builder_t *B, PBS_ifl_Header_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_Header_start(B)
        || PBS_ifl_Header_user_pick(B, t)
        || PBS_ifl_Header_version_pick(B, t)
        || PBS_ifl_Header_reqId_pick(B, t)
        || PBS_ifl_Header_protType_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_Header_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, PBS_ifl_Attribute_name, PBS_ifl_Attribute)
__flatbuffers_build_string_field(1, flatbuffers_, PBS_ifl_Attribute_resc, PBS_ifl_Attribute)
__flatbuffers_build_string_field(2, flatbuffers_, PBS_ifl_Attribute_value, PBS_ifl_Attribute)
__flatbuffers_build_scalar_field(3, flatbuffers_, PBS_ifl_Attribute_op, PBS_ifl_batch_op, PBS_ifl_batch_op_enum_t, 1, 1, INT8_C(0), PBS_ifl_Attribute)

static inline PBS_ifl_Attribute_ref_t PBS_ifl_Attribute_create(flatbuffers_builder_t *B __PBS_ifl_Attribute_formal_args)
{
    if (PBS_ifl_Attribute_start(B)
        || PBS_ifl_Attribute_name_add(B, v0)
        || PBS_ifl_Attribute_resc_add(B, v1)
        || PBS_ifl_Attribute_value_add(B, v2)
        || PBS_ifl_Attribute_op_add(B, v3)) {
        return 0;
    }
    return PBS_ifl_Attribute_end(B);
}

static PBS_ifl_Attribute_ref_t PBS_ifl_Attribute_clone(flatbuffers_builder_t *B, PBS_ifl_Attribute_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_Attribute_start(B)
        || PBS_ifl_Attribute_name_pick(B, t)
        || PBS_ifl_Attribute_resc_pick(B, t)
        || PBS_ifl_Attribute_value_pick(B, t)
        || PBS_ifl_Attribute_op_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_Attribute_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, PBS_ifl_Qjob_jobId, PBS_ifl_Qjob)
__flatbuffers_build_string_field(1, flatbuffers_, PBS_ifl_Qjob_destin, PBS_ifl_Qjob)
__flatbuffers_build_table_vector_field(2, flatbuffers_, PBS_ifl_Qjob_attrs, PBS_ifl_Attribute, PBS_ifl_Qjob)

static inline PBS_ifl_Qjob_ref_t PBS_ifl_Qjob_create(flatbuffers_builder_t *B __PBS_ifl_Qjob_formal_args)
{
    if (PBS_ifl_Qjob_start(B)
        || PBS_ifl_Qjob_jobId_add(B, v0)
        || PBS_ifl_Qjob_destin_add(B, v1)
        || PBS_ifl_Qjob_attrs_add(B, v2)) {
        return 0;
    }
    return PBS_ifl_Qjob_end(B);
}

static PBS_ifl_Qjob_ref_t PBS_ifl_Qjob_clone(flatbuffers_builder_t *B, PBS_ifl_Qjob_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_Qjob_start(B)
        || PBS_ifl_Qjob_jobId_pick(B, t)
        || PBS_ifl_Qjob_destin_pick(B, t)
        || PBS_ifl_Qjob_attrs_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_Qjob_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, PBS_ifl_JobFile_seq, flatbuffers_int64, int64_t, 8, 8, INT64_C(0), PBS_ifl_JobFile)
__flatbuffers_build_scalar_field(1, flatbuffers_, PBS_ifl_JobFile_type, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_JobFile)
__flatbuffers_build_scalar_field(2, flatbuffers_, PBS_ifl_JobFile_size, flatbuffers_int64, int64_t, 8, 8, INT64_C(0), PBS_ifl_JobFile)
__flatbuffers_build_string_field(3, flatbuffers_, PBS_ifl_JobFile_jobId, PBS_ifl_JobFile)
__flatbuffers_build_string_field(4, flatbuffers_, PBS_ifl_JobFile_data, PBS_ifl_JobFile)

static inline PBS_ifl_JobFile_ref_t PBS_ifl_JobFile_create(flatbuffers_builder_t *B __PBS_ifl_JobFile_formal_args)
{
    if (PBS_ifl_JobFile_start(B)
        || PBS_ifl_JobFile_seq_add(B, v0)
        || PBS_ifl_JobFile_size_add(B, v2)
        || PBS_ifl_JobFile_jobId_add(B, v3)
        || PBS_ifl_JobFile_data_add(B, v4)
        || PBS_ifl_JobFile_type_add(B, v1)) {
        return 0;
    }
    return PBS_ifl_JobFile_end(B);
}

static PBS_ifl_JobFile_ref_t PBS_ifl_JobFile_clone(flatbuffers_builder_t *B, PBS_ifl_JobFile_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_JobFile_start(B)
        || PBS_ifl_JobFile_seq_pick(B, t)
        || PBS_ifl_JobFile_size_pick(B, t)
        || PBS_ifl_JobFile_jobId_pick(B, t)
        || PBS_ifl_JobFile_data_pick(B, t)
        || PBS_ifl_JobFile_type_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_JobFile_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, PBS_ifl_JobId_jobId, PBS_ifl_JobId)

static inline PBS_ifl_JobId_ref_t PBS_ifl_JobId_create(flatbuffers_builder_t *B __PBS_ifl_JobId_formal_args)
{
    if (PBS_ifl_JobId_start(B)
        || PBS_ifl_JobId_jobId_add(B, v0)) {
        return 0;
    }
    return PBS_ifl_JobId_end(B);
}

static PBS_ifl_JobId_ref_t PBS_ifl_JobId_clone(flatbuffers_builder_t *B, PBS_ifl_JobId_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_JobId_start(B)
        || PBS_ifl_JobId_jobId_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_JobId_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, PBS_ifl_Manage_cmd, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_Manage)
__flatbuffers_build_scalar_field(1, flatbuffers_, PBS_ifl_Manage_objType, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_Manage)
__flatbuffers_build_string_field(2, flatbuffers_, PBS_ifl_Manage_objName, PBS_ifl_Manage)
__flatbuffers_build_table_vector_field(3, flatbuffers_, PBS_ifl_Manage_attrs, PBS_ifl_Attribute, PBS_ifl_Manage)

static inline PBS_ifl_Manage_ref_t PBS_ifl_Manage_create(flatbuffers_builder_t *B __PBS_ifl_Manage_formal_args)
{
    if (PBS_ifl_Manage_start(B)
        || PBS_ifl_Manage_objName_add(B, v2)
        || PBS_ifl_Manage_attrs_add(B, v3)
        || PBS_ifl_Manage_cmd_add(B, v0)
        || PBS_ifl_Manage_objType_add(B, v1)) {
        return 0;
    }
    return PBS_ifl_Manage_end(B);
}

static PBS_ifl_Manage_ref_t PBS_ifl_Manage_clone(flatbuffers_builder_t *B, PBS_ifl_Manage_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_Manage_start(B)
        || PBS_ifl_Manage_objName_pick(B, t)
        || PBS_ifl_Manage_attrs_pick(B, t)
        || PBS_ifl_Manage_cmd_pick(B, t)
        || PBS_ifl_Manage_objType_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_Manage_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, PBS_ifl_Msg_fileInd, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_Msg)
__flatbuffers_build_string_field(1, flatbuffers_, PBS_ifl_Msg_jobId, PBS_ifl_Msg)
__flatbuffers_build_string_field(2, flatbuffers_, PBS_ifl_Msg_text, PBS_ifl_Msg)

static inline PBS_ifl_Msg_ref_t PBS_ifl_Msg_create(flatbuffers_builder_t *B __PBS_ifl_Msg_formal_args)
{
    if (PBS_ifl_Msg_start(B)
        || PBS_ifl_Msg_jobId_add(B, v1)
        || PBS_ifl_Msg_text_add(B, v2)
        || PBS_ifl_Msg_fileInd_add(B, v0)) {
        return 0;
    }
    return PBS_ifl_Msg_end(B);
}

static PBS_ifl_Msg_ref_t PBS_ifl_Msg_clone(flatbuffers_builder_t *B, PBS_ifl_Msg_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_Msg_start(B)
        || PBS_ifl_Msg_jobId_pick(B, t)
        || PBS_ifl_Msg_text_pick(B, t)
        || PBS_ifl_Msg_fileInd_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_Msg_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, PBS_ifl_Move_jobId, PBS_ifl_Move)
__flatbuffers_build_string_field(1, flatbuffers_, PBS_ifl_Move_dest, PBS_ifl_Move)

static inline PBS_ifl_Move_ref_t PBS_ifl_Move_create(flatbuffers_builder_t *B __PBS_ifl_Move_formal_args)
{
    if (PBS_ifl_Move_start(B)
        || PBS_ifl_Move_jobId_add(B, v0)
        || PBS_ifl_Move_dest_add(B, v1)) {
        return 0;
    }
    return PBS_ifl_Move_end(B);
}

static PBS_ifl_Move_ref_t PBS_ifl_Move_clone(flatbuffers_builder_t *B, PBS_ifl_Move_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_Move_start(B)
        || PBS_ifl_Move_jobId_pick(B, t)
        || PBS_ifl_Move_dest_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_Move_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, PBS_ifl_Run_jobId, PBS_ifl_Run)
__flatbuffers_build_string_field(1, flatbuffers_, PBS_ifl_Run_dest, PBS_ifl_Run)
__flatbuffers_build_scalar_field(2, flatbuffers_, PBS_ifl_Run_resch, flatbuffers_int64, int64_t, 8, 8, INT64_C(0), PBS_ifl_Run)

static inline PBS_ifl_Run_ref_t PBS_ifl_Run_create(flatbuffers_builder_t *B __PBS_ifl_Run_formal_args)
{
    if (PBS_ifl_Run_start(B)
        || PBS_ifl_Run_resch_add(B, v2)
        || PBS_ifl_Run_jobId_add(B, v0)
        || PBS_ifl_Run_dest_add(B, v1)) {
        return 0;
    }
    return PBS_ifl_Run_end(B);
}

static PBS_ifl_Run_ref_t PBS_ifl_Run_clone(flatbuffers_builder_t *B, PBS_ifl_Run_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_Run_start(B)
        || PBS_ifl_Run_resch_pick(B, t)
        || PBS_ifl_Run_jobId_pick(B, t)
        || PBS_ifl_Run_dest_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_Run_end(B));
}

__flatbuffers_build_table_vector_field(0, flatbuffers_, PBS_ifl_Select_selAttrs, PBS_ifl_Attribute, PBS_ifl_Select)
__flatbuffers_build_table_vector_field(1, flatbuffers_, PBS_ifl_Select_rtnAttrs, PBS_ifl_Attribute, PBS_ifl_Select)

static inline PBS_ifl_Select_ref_t PBS_ifl_Select_create(flatbuffers_builder_t *B __PBS_ifl_Select_formal_args)
{
    if (PBS_ifl_Select_start(B)
        || PBS_ifl_Select_selAttrs_add(B, v0)
        || PBS_ifl_Select_rtnAttrs_add(B, v1)) {
        return 0;
    }
    return PBS_ifl_Select_end(B);
}

static PBS_ifl_Select_ref_t PBS_ifl_Select_clone(flatbuffers_builder_t *B, PBS_ifl_Select_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_Select_start(B)
        || PBS_ifl_Select_selAttrs_pick(B, t)
        || PBS_ifl_Select_rtnAttrs_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_Select_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, PBS_ifl_DmnCmd_cmd, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_DmnCmd)

static inline PBS_ifl_DmnCmd_ref_t PBS_ifl_DmnCmd_create(flatbuffers_builder_t *B __PBS_ifl_DmnCmd_formal_args)
{
    if (PBS_ifl_DmnCmd_start(B)
        || PBS_ifl_DmnCmd_cmd_add(B, v0)) {
        return 0;
    }
    return PBS_ifl_DmnCmd_end(B);
}

static PBS_ifl_DmnCmd_ref_t PBS_ifl_DmnCmd_clone(flatbuffers_builder_t *B, PBS_ifl_DmnCmd_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_DmnCmd_start(B)
        || PBS_ifl_DmnCmd_cmd_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_DmnCmd_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, PBS_ifl_Signal_jobId, PBS_ifl_Signal)
__flatbuffers_build_string_field(1, flatbuffers_, PBS_ifl_Signal_sigName, PBS_ifl_Signal)

static inline PBS_ifl_Signal_ref_t PBS_ifl_Signal_create(flatbuffers_builder_t *B __PBS_ifl_Signal_formal_args)
{
    if (PBS_ifl_Signal_start(B)
        || PBS_ifl_Signal_jobId_add(B, v0)
        || PBS_ifl_Signal_sigName_add(B, v1)) {
        return 0;
    }
    return PBS_ifl_Signal_end(B);
}

static PBS_ifl_Signal_ref_t PBS_ifl_Signal_clone(flatbuffers_builder_t *B, PBS_ifl_Signal_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_Signal_start(B)
        || PBS_ifl_Signal_jobId_pick(B, t)
        || PBS_ifl_Signal_sigName_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_Signal_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, PBS_ifl_Stat_jobIds, PBS_ifl_Stat)
__flatbuffers_build_table_vector_field(1, flatbuffers_, PBS_ifl_Stat_attrs, PBS_ifl_Attribute, PBS_ifl_Stat)

static inline PBS_ifl_Stat_ref_t PBS_ifl_Stat_create(flatbuffers_builder_t *B __PBS_ifl_Stat_formal_args)
{
    if (PBS_ifl_Stat_start(B)
        || PBS_ifl_Stat_jobIds_add(B, v0)
        || PBS_ifl_Stat_attrs_add(B, v1)) {
        return 0;
    }
    return PBS_ifl_Stat_end(B);
}

static PBS_ifl_Stat_ref_t PBS_ifl_Stat_clone(flatbuffers_builder_t *B, PBS_ifl_Stat_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_Stat_start(B)
        || PBS_ifl_Stat_jobIds_pick(B, t)
        || PBS_ifl_Stat_attrs_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_Stat_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, PBS_ifl_Track_hops, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_Track)
__flatbuffers_build_string_field(1, flatbuffers_, PBS_ifl_Track_jobId, PBS_ifl_Track)
__flatbuffers_build_string_field(2, flatbuffers_, PBS_ifl_Track_location, PBS_ifl_Track)
__flatbuffers_build_scalar_field(3, flatbuffers_, PBS_ifl_Track_state, flatbuffers_int8, int8_t, 1, 1, INT8_C(0), PBS_ifl_Track)

static inline PBS_ifl_Track_ref_t PBS_ifl_Track_create(flatbuffers_builder_t *B __PBS_ifl_Track_formal_args)
{
    if (PBS_ifl_Track_start(B)
        || PBS_ifl_Track_jobId_add(B, v1)
        || PBS_ifl_Track_location_add(B, v2)
        || PBS_ifl_Track_hops_add(B, v0)
        || PBS_ifl_Track_state_add(B, v3)) {
        return 0;
    }
    return PBS_ifl_Track_end(B);
}

static PBS_ifl_Track_ref_t PBS_ifl_Track_clone(flatbuffers_builder_t *B, PBS_ifl_Track_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_Track_start(B)
        || PBS_ifl_Track_jobId_pick(B, t)
        || PBS_ifl_Track_location_pick(B, t)
        || PBS_ifl_Track_hops_pick(B, t)
        || PBS_ifl_Track_state_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_Track_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, PBS_ifl_RescQuery_handle, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_RescQuery)
__flatbuffers_build_string_vector_field(1, flatbuffers_, PBS_ifl_RescQuery_queries, PBS_ifl_RescQuery)

static inline PBS_ifl_RescQuery_ref_t PBS_ifl_RescQuery_create(flatbuffers_builder_t *B __PBS_ifl_RescQuery_formal_args)
{
    if (PBS_ifl_RescQuery_start(B)
        || PBS_ifl_RescQuery_queries_add(B, v1)
        || PBS_ifl_RescQuery_handle_add(B, v0)) {
        return 0;
    }
    return PBS_ifl_RescQuery_end(B);
}

static PBS_ifl_RescQuery_ref_t PBS_ifl_RescQuery_clone(flatbuffers_builder_t *B, PBS_ifl_RescQuery_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_RescQuery_start(B)
        || PBS_ifl_RescQuery_queries_pick(B, t)
        || PBS_ifl_RescQuery_handle_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_RescQuery_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, PBS_ifl_Register_owner, PBS_ifl_Register)
__flatbuffers_build_string_field(1, flatbuffers_, PBS_ifl_Register_parent, PBS_ifl_Register)
__flatbuffers_build_string_field(2, flatbuffers_, PBS_ifl_Register_child, PBS_ifl_Register)
__flatbuffers_build_scalar_field(3, flatbuffers_, PBS_ifl_Register_type, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_Register)
__flatbuffers_build_scalar_field(4, flatbuffers_, PBS_ifl_Register_op, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_Register)
__flatbuffers_build_scalar_field(5, flatbuffers_, PBS_ifl_Register_cost, flatbuffers_int64, int64_t, 8, 8, INT64_C(0), PBS_ifl_Register)

static inline PBS_ifl_Register_ref_t PBS_ifl_Register_create(flatbuffers_builder_t *B __PBS_ifl_Register_formal_args)
{
    if (PBS_ifl_Register_start(B)
        || PBS_ifl_Register_cost_add(B, v5)
        || PBS_ifl_Register_owner_add(B, v0)
        || PBS_ifl_Register_parent_add(B, v1)
        || PBS_ifl_Register_child_add(B, v2)
        || PBS_ifl_Register_type_add(B, v3)
        || PBS_ifl_Register_op_add(B, v4)) {
        return 0;
    }
    return PBS_ifl_Register_end(B);
}

static PBS_ifl_Register_ref_t PBS_ifl_Register_clone(flatbuffers_builder_t *B, PBS_ifl_Register_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_Register_start(B)
        || PBS_ifl_Register_cost_pick(B, t)
        || PBS_ifl_Register_owner_pick(B, t)
        || PBS_ifl_Register_parent_pick(B, t)
        || PBS_ifl_Register_child_pick(B, t)
        || PBS_ifl_Register_type_pick(B, t)
        || PBS_ifl_Register_op_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_Register_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, PBS_ifl_FilePair_local, PBS_ifl_FilePair)
__flatbuffers_build_string_field(1, flatbuffers_, PBS_ifl_FilePair_remote, PBS_ifl_FilePair)
__flatbuffers_build_scalar_field(2, flatbuffers_, PBS_ifl_FilePair_flag, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_FilePair)

static inline PBS_ifl_FilePair_ref_t PBS_ifl_FilePair_create(flatbuffers_builder_t *B __PBS_ifl_FilePair_formal_args)
{
    if (PBS_ifl_FilePair_start(B)
        || PBS_ifl_FilePair_local_add(B, v0)
        || PBS_ifl_FilePair_remote_add(B, v1)
        || PBS_ifl_FilePair_flag_add(B, v2)) {
        return 0;
    }
    return PBS_ifl_FilePair_end(B);
}

static PBS_ifl_FilePair_ref_t PBS_ifl_FilePair_clone(flatbuffers_builder_t *B, PBS_ifl_FilePair_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_FilePair_start(B)
        || PBS_ifl_FilePair_local_pick(B, t)
        || PBS_ifl_FilePair_remote_pick(B, t)
        || PBS_ifl_FilePair_flag_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_FilePair_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, PBS_ifl_CopyFile_jobId, PBS_ifl_CopyFile)
__flatbuffers_build_string_field(1, flatbuffers_, PBS_ifl_CopyFile_owner, PBS_ifl_CopyFile)
__flatbuffers_build_string_field(2, flatbuffers_, PBS_ifl_CopyFile_user, PBS_ifl_CopyFile)
__flatbuffers_build_string_field(3, flatbuffers_, PBS_ifl_CopyFile_group, PBS_ifl_CopyFile)
__flatbuffers_build_scalar_field(4, flatbuffers_, PBS_ifl_CopyFile_flags, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_CopyFile)
__flatbuffers_build_table_vector_field(5, flatbuffers_, PBS_ifl_CopyFile_pairs, PBS_ifl_FilePair, PBS_ifl_CopyFile)

static inline PBS_ifl_CopyFile_ref_t PBS_ifl_CopyFile_create(flatbuffers_builder_t *B __PBS_ifl_CopyFile_formal_args)
{
    if (PBS_ifl_CopyFile_start(B)
        || PBS_ifl_CopyFile_jobId_add(B, v0)
        || PBS_ifl_CopyFile_owner_add(B, v1)
        || PBS_ifl_CopyFile_user_add(B, v2)
        || PBS_ifl_CopyFile_group_add(B, v3)
        || PBS_ifl_CopyFile_pairs_add(B, v5)
        || PBS_ifl_CopyFile_flags_add(B, v4)) {
        return 0;
    }
    return PBS_ifl_CopyFile_end(B);
}

static PBS_ifl_CopyFile_ref_t PBS_ifl_CopyFile_clone(flatbuffers_builder_t *B, PBS_ifl_CopyFile_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_CopyFile_start(B)
        || PBS_ifl_CopyFile_jobId_pick(B, t)
        || PBS_ifl_CopyFile_owner_pick(B, t)
        || PBS_ifl_CopyFile_user_pick(B, t)
        || PBS_ifl_CopyFile_group_pick(B, t)
        || PBS_ifl_CopyFile_pairs_pick(B, t)
        || PBS_ifl_CopyFile_flags_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_CopyFile_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, PBS_ifl_Cred_jobId, PBS_ifl_Cred)
__flatbuffers_build_string_field(1, flatbuffers_, PBS_ifl_Cred_user, PBS_ifl_Cred)
__flatbuffers_build_scalar_field(2, flatbuffers_, PBS_ifl_Cred_validity, flatbuffers_int64, int64_t, 8, 8, INT64_C(0), PBS_ifl_Cred)
__flatbuffers_build_scalar_field(3, flatbuffers_, PBS_ifl_Cred_type, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_Cred)
__flatbuffers_build_scalar_field(4, flatbuffers_, PBS_ifl_Cred_size, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_Cred)
__flatbuffers_build_string_field(5, flatbuffers_, PBS_ifl_Cred_data, PBS_ifl_Cred)

static inline PBS_ifl_Cred_ref_t PBS_ifl_Cred_create(flatbuffers_builder_t *B __PBS_ifl_Cred_formal_args)
{
    if (PBS_ifl_Cred_start(B)
        || PBS_ifl_Cred_validity_add(B, v2)
        || PBS_ifl_Cred_jobId_add(B, v0)
        || PBS_ifl_Cred_user_add(B, v1)
        || PBS_ifl_Cred_data_add(B, v5)
        || PBS_ifl_Cred_type_add(B, v3)
        || PBS_ifl_Cred_size_add(B, v4)) {
        return 0;
    }
    return PBS_ifl_Cred_end(B);
}

static PBS_ifl_Cred_ref_t PBS_ifl_Cred_clone(flatbuffers_builder_t *B, PBS_ifl_Cred_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_Cred_start(B)
        || PBS_ifl_Cred_validity_pick(B, t)
        || PBS_ifl_Cred_jobId_pick(B, t)
        || PBS_ifl_Cred_user_pick(B, t)
        || PBS_ifl_Cred_data_pick(B, t)
        || PBS_ifl_Cred_type_pick(B, t)
        || PBS_ifl_Cred_size_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_Cred_end(B));
}

__flatbuffers_build_table_field(0, flatbuffers_, PBS_ifl_CopyFileCred_files, PBS_ifl_CopyFile, PBS_ifl_CopyFileCred)
__flatbuffers_build_scalar_field(1, flatbuffers_, PBS_ifl_CopyFileCred_type, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_CopyFileCred)
__flatbuffers_build_string_field(2, flatbuffers_, PBS_ifl_CopyFileCred_cred, PBS_ifl_CopyFileCred)

static inline PBS_ifl_CopyFileCred_ref_t PBS_ifl_CopyFileCred_create(flatbuffers_builder_t *B __PBS_ifl_CopyFileCred_formal_args)
{
    if (PBS_ifl_CopyFileCred_start(B)
        || PBS_ifl_CopyFileCred_files_add(B, v0)
        || PBS_ifl_CopyFileCred_cred_add(B, v2)
        || PBS_ifl_CopyFileCred_type_add(B, v1)) {
        return 0;
    }
    return PBS_ifl_CopyFileCred_end(B);
}

static PBS_ifl_CopyFileCred_ref_t PBS_ifl_CopyFileCred_clone(flatbuffers_builder_t *B, PBS_ifl_CopyFileCred_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_CopyFileCred_start(B)
        || PBS_ifl_CopyFileCred_files_pick(B, t)
        || PBS_ifl_CopyFileCred_cred_pick(B, t)
        || PBS_ifl_CopyFileCred_type_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_CopyFileCred_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, PBS_ifl_UserMigrate_tohost, PBS_ifl_UserMigrate)

static inline PBS_ifl_UserMigrate_ref_t PBS_ifl_UserMigrate_create(flatbuffers_builder_t *B __PBS_ifl_UserMigrate_formal_args)
{
    if (PBS_ifl_UserMigrate_start(B)
        || PBS_ifl_UserMigrate_tohost_add(B, v0)) {
        return 0;
    }
    return PBS_ifl_UserMigrate_end(B);
}

static PBS_ifl_UserMigrate_ref_t PBS_ifl_UserMigrate_clone(flatbuffers_builder_t *B, PBS_ifl_UserMigrate_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_UserMigrate_start(B)
        || PBS_ifl_UserMigrate_tohost_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_UserMigrate_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, PBS_ifl_SchedDefRep_cmd, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_SchedDefRep)
__flatbuffers_build_string_field(1, flatbuffers_, PBS_ifl_SchedDefRep_id, PBS_ifl_SchedDefRep)
__flatbuffers_build_scalar_field(2, flatbuffers_, PBS_ifl_SchedDefRep_err, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_SchedDefRep)
__flatbuffers_build_string_field(3, flatbuffers_, PBS_ifl_SchedDefRep_text, PBS_ifl_SchedDefRep)

static inline PBS_ifl_SchedDefRep_ref_t PBS_ifl_SchedDefRep_create(flatbuffers_builder_t *B __PBS_ifl_SchedDefRep_formal_args)
{
    if (PBS_ifl_SchedDefRep_start(B)
        || PBS_ifl_SchedDefRep_id_add(B, v1)
        || PBS_ifl_SchedDefRep_text_add(B, v3)
        || PBS_ifl_SchedDefRep_cmd_add(B, v0)
        || PBS_ifl_SchedDefRep_err_add(B, v2)) {
        return 0;
    }
    return PBS_ifl_SchedDefRep_end(B);
}

static PBS_ifl_SchedDefRep_ref_t PBS_ifl_SchedDefRep_clone(flatbuffers_builder_t *B, PBS_ifl_SchedDefRep_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_SchedDefRep_start(B)
        || PBS_ifl_SchedDefRep_id_pick(B, t)
        || PBS_ifl_SchedDefRep_text_pick(B, t)
        || PBS_ifl_SchedDefRep_cmd_pick(B, t)
        || PBS_ifl_SchedDefRep_err_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_SchedDefRep_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, PBS_ifl_Spawn_jobId, PBS_ifl_Spawn)
__flatbuffers_build_string_vector_field(1, flatbuffers_, PBS_ifl_Spawn_argv, PBS_ifl_Spawn)
__flatbuffers_build_string_vector_field(2, flatbuffers_, PBS_ifl_Spawn_envp, PBS_ifl_Spawn)

static inline PBS_ifl_Spawn_ref_t PBS_ifl_Spawn_create(flatbuffers_builder_t *B __PBS_ifl_Spawn_formal_args)
{
    if (PBS_ifl_Spawn_start(B)
        || PBS_ifl_Spawn_jobId_add(B, v0)
        || PBS_ifl_Spawn_argv_add(B, v1)
        || PBS_ifl_Spawn_envp_add(B, v2)) {
        return 0;
    }
    return PBS_ifl_Spawn_end(B);
}

static PBS_ifl_Spawn_ref_t PBS_ifl_Spawn_clone(flatbuffers_builder_t *B, PBS_ifl_Spawn_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_Spawn_start(B)
        || PBS_ifl_Spawn_jobId_pick(B, t)
        || PBS_ifl_Spawn_argv_pick(B, t)
        || PBS_ifl_Spawn_envp_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_Spawn_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, PBS_ifl_CopyHook_seq, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_CopyHook)
__flatbuffers_build_scalar_field(1, flatbuffers_, PBS_ifl_CopyHook_size, flatbuffers_int64, int64_t, 8, 8, INT64_C(0), PBS_ifl_CopyHook)
__flatbuffers_build_string_field(2, flatbuffers_, PBS_ifl_CopyHook_filename, PBS_ifl_CopyHook)
__flatbuffers_build_string_field(3, flatbuffers_, PBS_ifl_CopyHook_data, PBS_ifl_CopyHook)

static inline PBS_ifl_CopyHook_ref_t PBS_ifl_CopyHook_create(flatbuffers_builder_t *B __PBS_ifl_CopyHook_formal_args)
{
    if (PBS_ifl_CopyHook_start(B)
        || PBS_ifl_CopyHook_size_add(B, v1)
        || PBS_ifl_CopyHook_filename_add(B, v2)
        || PBS_ifl_CopyHook_data_add(B, v3)
        || PBS_ifl_CopyHook_seq_add(B, v0)) {
        return 0;
    }
    return PBS_ifl_CopyHook_end(B);
}

static PBS_ifl_CopyHook_ref_t PBS_ifl_CopyHook_clone(flatbuffers_builder_t *B, PBS_ifl_CopyHook_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_CopyHook_start(B)
        || PBS_ifl_CopyHook_size_pick(B, t)
        || PBS_ifl_CopyHook_filename_pick(B, t)
        || PBS_ifl_CopyHook_data_pick(B, t)
        || PBS_ifl_CopyHook_seq_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_CopyHook_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, PBS_ifl_RelNodes_jobId, PBS_ifl_RelNodes)
__flatbuffers_build_string_field(1, flatbuffers_, PBS_ifl_RelNodes_nodes, PBS_ifl_RelNodes)

static inline PBS_ifl_RelNodes_ref_t PBS_ifl_RelNodes_create(flatbuffers_builder_t *B __PBS_ifl_RelNodes_formal_args)
{
    if (PBS_ifl_RelNodes_start(B)
        || PBS_ifl_RelNodes_jobId_add(B, v0)
        || PBS_ifl_RelNodes_nodes_add(B, v1)) {
        return 0;
    }
    return PBS_ifl_RelNodes_end(B);
}

static PBS_ifl_RelNodes_ref_t PBS_ifl_RelNodes_clone(flatbuffers_builder_t *B, PBS_ifl_RelNodes_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_RelNodes_start(B)
        || PBS_ifl_RelNodes_jobId_pick(B, t)
        || PBS_ifl_RelNodes_nodes_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_RelNodes_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, PBS_ifl_PreemptJob_jid, PBS_ifl_PreemptJob)
__flatbuffers_build_string_field(1, flatbuffers_, PBS_ifl_PreemptJob_order, PBS_ifl_PreemptJob)

static inline PBS_ifl_PreemptJob_ref_t PBS_ifl_PreemptJob_create(flatbuffers_builder_t *B __PBS_ifl_PreemptJob_formal_args)
{
    if (PBS_ifl_PreemptJob_start(B)
        || PBS_ifl_PreemptJob_jid_add(B, v0)
        || PBS_ifl_PreemptJob_order_add(B, v1)) {
        return 0;
    }
    return PBS_ifl_PreemptJob_end(B);
}

static PBS_ifl_PreemptJob_ref_t PBS_ifl_PreemptJob_clone(flatbuffers_builder_t *B, PBS_ifl_PreemptJob_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_PreemptJob_start(B)
        || PBS_ifl_PreemptJob_jid_pick(B, t)
        || PBS_ifl_PreemptJob_order_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_PreemptJob_end(B));
}

__flatbuffers_build_table_vector_field(0, flatbuffers_, PBS_ifl_Preempt_infos, PBS_ifl_PreemptJob, PBS_ifl_Preempt)

static inline PBS_ifl_Preempt_ref_t PBS_ifl_Preempt_create(flatbuffers_builder_t *B __PBS_ifl_Preempt_formal_args)
{
    if (PBS_ifl_Preempt_start(B)
        || PBS_ifl_Preempt_infos_add(B, v0)) {
        return 0;
    }
    return PBS_ifl_Preempt_end(B);
}

static PBS_ifl_Preempt_ref_t PBS_ifl_Preempt_clone(flatbuffers_builder_t *B, PBS_ifl_Preempt_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_Preempt_start(B)
        || PBS_ifl_Preempt_infos_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_Preempt_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, PBS_ifl_Auth_authMethod, PBS_ifl_Auth)
__flatbuffers_build_string_field(1, flatbuffers_, PBS_ifl_Auth_encryptMethod, PBS_ifl_Auth)
__flatbuffers_build_scalar_field(2, flatbuffers_, PBS_ifl_Auth_encryptMode, flatbuffers_uint16, uint16_t, 2, 2, UINT16_C(0), PBS_ifl_Auth)
__flatbuffers_build_scalar_field(3, flatbuffers_, PBS_ifl_Auth_port, flatbuffers_uint16, uint16_t, 2, 2, UINT16_C(0), PBS_ifl_Auth)

static inline PBS_ifl_Auth_ref_t PBS_ifl_Auth_create(flatbuffers_builder_t *B __PBS_ifl_Auth_formal_args)
{
    if (PBS_ifl_Auth_start(B)
        || PBS_ifl_Auth_authMethod_add(B, v0)
        || PBS_ifl_Auth_encryptMethod_add(B, v1)
        || PBS_ifl_Auth_encryptMode_add(B, v2)
        || PBS_ifl_Auth_port_add(B, v3)) {
        return 0;
    }
    return PBS_ifl_Auth_end(B);
}

static PBS_ifl_Auth_ref_t PBS_ifl_Auth_clone(flatbuffers_builder_t *B, PBS_ifl_Auth_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_Auth_start(B)
        || PBS_ifl_Auth_authMethod_pick(B, t)
        || PBS_ifl_Auth_encryptMethod_pick(B, t)
        || PBS_ifl_Auth_encryptMode_pick(B, t)
        || PBS_ifl_Auth_port_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_Auth_end(B));
}

__flatbuffers_build_table_field(0, flatbuffers_, PBS_ifl_Req_hdr, PBS_ifl_Header, PBS_ifl_Req)
__flatbuffers_build_union_field(2, flatbuffers_, PBS_ifl_Req_body, PBS_ifl_ReqBody, PBS_ifl_Req)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_Req_body, PBS_ifl_ReqBody, Qjob, PBS_ifl_Qjob)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_Req_body, PBS_ifl_ReqBody, JobFile, PBS_ifl_JobFile)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_Req_body, PBS_ifl_ReqBody, JobId, PBS_ifl_JobId)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_Req_body, PBS_ifl_ReqBody, Manage, PBS_ifl_Manage)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_Req_body, PBS_ifl_ReqBody, Msg, PBS_ifl_Msg)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_Req_body, PBS_ifl_ReqBody, Move, PBS_ifl_Move)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_Req_body, PBS_ifl_ReqBody, Run, PBS_ifl_Run)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_Req_body, PBS_ifl_ReqBody, Select, PBS_ifl_Select)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_Req_body, PBS_ifl_ReqBody, DmnCmd, PBS_ifl_DmnCmd)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_Req_body, PBS_ifl_ReqBody, Signal, PBS_ifl_Signal)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_Req_body, PBS_ifl_ReqBody, Stat, PBS_ifl_Stat)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_Req_body, PBS_ifl_ReqBody, Track, PBS_ifl_Track)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_Req_body, PBS_ifl_ReqBody, RescQuery, PBS_ifl_RescQuery)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_Req_body, PBS_ifl_ReqBody, Register, PBS_ifl_Register)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_Req_body, PBS_ifl_ReqBody, CopyFile, PBS_ifl_CopyFile)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_Req_body, PBS_ifl_ReqBody, Cred, PBS_ifl_Cred)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_Req_body, PBS_ifl_ReqBody, CopyFileCred, PBS_ifl_CopyFileCred)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_Req_body, PBS_ifl_ReqBody, UserMigrate, PBS_ifl_UserMigrate)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_Req_body, PBS_ifl_ReqBody, SchedDefRep, PBS_ifl_SchedDefRep)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_Req_body, PBS_ifl_ReqBody, Spawn, PBS_ifl_Spawn)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_Req_body, PBS_ifl_ReqBody, CopyHook, PBS_ifl_CopyHook)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_Req_body, PBS_ifl_ReqBody, RelNodes, PBS_ifl_RelNodes)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_Req_body, PBS_ifl_ReqBody, Preempt, PBS_ifl_Preempt)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_Req_body, PBS_ifl_ReqBody, Auth, PBS_ifl_Auth)
__flatbuffers_build_string_field(3, flatbuffers_, PBS_ifl_Req_extend, PBS_ifl_Req)

static inline PBS_ifl_Req_ref_t PBS_ifl_Req_create(flatbuffers_builder_t *B __PBS_ifl_Req_formal_args)
{
    if (PBS_ifl_Req_start(B)
        || PBS_ifl_Req_hdr_add(B, v0)
        || PBS_ifl_Req_body_add_value(B, v2)
        || PBS_ifl_Req_extend_add(B, v3)
        || PBS_ifl_Req_body_add_type(B, v2.type)) {
        return 0;
    }
    return PBS_ifl_Req_end(B);
}

static PBS_ifl_Req_ref_t PBS_ifl_Req_clone(flatbuffers_builder_t *B, PBS_ifl_Req_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_Req_start(B)
        || PBS_ifl_Req_hdr_pick(B, t)
        || PBS_ifl_Req_body_pick(B, t)
        || PBS_ifl_Req_extend_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_Req_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, PBS_ifl_StatRespStat_type, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_StatRespStat)
__flatbuffers_build_string_field(1, flatbuffers_, PBS_ifl_StatRespStat_name, PBS_ifl_StatRespStat)
__flatbuffers_build_table_vector_field(2, flatbuffers_, PBS_ifl_StatRespStat_attrs, PBS_ifl_Attribute, PBS_ifl_StatRespStat)

static inline PBS_ifl_StatRespStat_ref_t PBS_ifl_StatRespStat_create(flatbuffers_builder_t *B __PBS_ifl_StatRespStat_formal_args)
{
    if (PBS_ifl_StatRespStat_start(B)
        || PBS_ifl_StatRespStat_name_add(B, v1)
        || PBS_ifl_StatRespStat_attrs_add(B, v2)
        || PBS_ifl_StatRespStat_type_add(B, v0)) {
        return 0;
    }
    return PBS_ifl_StatRespStat_end(B);
}

static PBS_ifl_StatRespStat_ref_t PBS_ifl_StatRespStat_clone(flatbuffers_builder_t *B, PBS_ifl_StatRespStat_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_StatRespStat_start(B)
        || PBS_ifl_StatRespStat_name_pick(B, t)
        || PBS_ifl_StatRespStat_attrs_pick(B, t)
        || PBS_ifl_StatRespStat_type_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_StatRespStat_end(B));
}

__flatbuffers_build_table_vector_field(0, flatbuffers_, PBS_ifl_StatResp_stats, PBS_ifl_StatRespStat, PBS_ifl_StatResp)

static inline PBS_ifl_StatResp_ref_t PBS_ifl_StatResp_create(flatbuffers_builder_t *B __PBS_ifl_StatResp_formal_args)
{
    if (PBS_ifl_StatResp_start(B)
        || PBS_ifl_StatResp_stats_add(B, v0)) {
        return 0;
    }
    return PBS_ifl_StatResp_end(B);
}

static PBS_ifl_StatResp_ref_t PBS_ifl_StatResp_clone(flatbuffers_builder_t *B, PBS_ifl_StatResp_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_StatResp_start(B)
        || PBS_ifl_StatResp_stats_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_StatResp_end(B));
}

__flatbuffers_build_string_vector_field(0, flatbuffers_, PBS_ifl_SelectResp_ids, PBS_ifl_SelectResp)

static inline PBS_ifl_SelectResp_ref_t PBS_ifl_SelectResp_create(flatbuffers_builder_t *B __PBS_ifl_SelectResp_formal_args)
{
    if (PBS_ifl_SelectResp_start(B)
        || PBS_ifl_SelectResp_ids_add(B, v0)) {
        return 0;
    }
    return PBS_ifl_SelectResp_end(B);
}

static PBS_ifl_SelectResp_ref_t PBS_ifl_SelectResp_clone(flatbuffers_builder_t *B, PBS_ifl_SelectResp_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_SelectResp_start(B)
        || PBS_ifl_SelectResp_ids_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_SelectResp_end(B));
}

__flatbuffers_build_vector_field(0, flatbuffers_, PBS_ifl_RescQueryResp_avail, flatbuffers_int16, int16_t, PBS_ifl_RescQueryResp)
__flatbuffers_build_vector_field(1, flatbuffers_, PBS_ifl_RescQueryResp_alloc, flatbuffers_int16, int16_t, PBS_ifl_RescQueryResp)
__flatbuffers_build_vector_field(2, flatbuffers_, PBS_ifl_RescQueryResp_resvd, flatbuffers_int16, int16_t, PBS_ifl_RescQueryResp)
__flatbuffers_build_vector_field(3, flatbuffers_, PBS_ifl_RescQueryResp_down, flatbuffers_int16, int16_t, PBS_ifl_RescQueryResp)

static inline PBS_ifl_RescQueryResp_ref_t PBS_ifl_RescQueryResp_create(flatbuffers_builder_t *B __PBS_ifl_RescQueryResp_formal_args)
{
    if (PBS_ifl_RescQueryResp_start(B)
        || PBS_ifl_RescQueryResp_avail_add(B, v0)
        || PBS_ifl_RescQueryResp_alloc_add(B, v1)
        || PBS_ifl_RescQueryResp_resvd_add(B, v2)
        || PBS_ifl_RescQueryResp_down_add(B, v3)) {
        return 0;
    }
    return PBS_ifl_RescQueryResp_end(B);
}

static PBS_ifl_RescQueryResp_ref_t PBS_ifl_RescQueryResp_clone(flatbuffers_builder_t *B, PBS_ifl_RescQueryResp_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_RescQueryResp_start(B)
        || PBS_ifl_RescQueryResp_avail_pick(B, t)
        || PBS_ifl_RescQueryResp_alloc_pick(B, t)
        || PBS_ifl_RescQueryResp_resvd_pick(B, t)
        || PBS_ifl_RescQueryResp_down_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_RescQueryResp_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, PBS_ifl_TextResp_txt, PBS_ifl_TextResp)

static inline PBS_ifl_TextResp_ref_t PBS_ifl_TextResp_create(flatbuffers_builder_t *B __PBS_ifl_TextResp_formal_args)
{
    if (PBS_ifl_TextResp_start(B)
        || PBS_ifl_TextResp_txt_add(B, v0)) {
        return 0;
    }
    return PBS_ifl_TextResp_end(B);
}

static PBS_ifl_TextResp_ref_t PBS_ifl_TextResp_clone(flatbuffers_builder_t *B, PBS_ifl_TextResp_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_TextResp_start(B)
        || PBS_ifl_TextResp_txt_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_TextResp_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, PBS_ifl_Resp_code, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_Resp)
__flatbuffers_build_scalar_field(1, flatbuffers_, PBS_ifl_Resp_auxCode, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_Resp)
__flatbuffers_build_scalar_field(2, flatbuffers_, PBS_ifl_Resp_choice, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_Resp)
__flatbuffers_build_union_field(4, flatbuffers_, PBS_ifl_Resp_body, PBS_ifl_RespBody, PBS_ifl_Resp)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_Resp_body, PBS_ifl_RespBody, TextResp, PBS_ifl_TextResp)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_Resp_body, PBS_ifl_RespBody, SelectResp, PBS_ifl_SelectResp)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_Resp_body, PBS_ifl_RespBody, StatResp, PBS_ifl_StatResp)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_Resp_body, PBS_ifl_RespBody, RescQueryResp, PBS_ifl_RescQueryResp)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_Resp_body, PBS_ifl_RespBody, Preempt, PBS_ifl_Preempt)

static inline PBS_ifl_Resp_ref_t PBS_ifl_Resp_create(flatbuffers_builder_t *B __PBS_ifl_Resp_formal_args)
{
    if (PBS_ifl_Resp_start(B)
        || PBS_ifl_Resp_body_add_value(B, v4)
        || PBS_ifl_Resp_code_add(B, v0)
        || PBS_ifl_Resp_auxCode_add(B, v1)
        || PBS_ifl_Resp_choice_add(B, v2)
        || PBS_ifl_Resp_body_add_type(B, v4.type)) {
        return 0;
    }
    return PBS_ifl_Resp_end(B);
}

static PBS_ifl_Resp_ref_t PBS_ifl_Resp_clone(flatbuffers_builder_t *B, PBS_ifl_Resp_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_Resp_start(B)
        || PBS_ifl_Resp_body_pick(B, t)
        || PBS_ifl_Resp_code_pick(B, t)
        || PBS_ifl_Resp_auxCode_pick(B, t)
        || PBS_ifl_Resp_choice_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_Resp_end(B));
}

__flatbuffers_build_table_field(0, flatbuffers_, PBS_ifl_RmReq_hdr, PBS_ifl_Header, PBS_ifl_RmReq)
__flatbuffers_build_string_vector_field(1, flatbuffers_, PBS_ifl_RmReq_data, PBS_ifl_RmReq)

static inline PBS_ifl_RmReq_ref_t PBS_ifl_RmReq_create(flatbuffers_builder_t *B __PBS_ifl_RmReq_formal_args)
{
    if (PBS_ifl_RmReq_start(B)
        || PBS_ifl_RmReq_hdr_add(B, v0)
        || PBS_ifl_RmReq_data_add(B, v1)) {
        return 0;
    }
    return PBS_ifl_RmReq_end(B);
}

static PBS_ifl_RmReq_ref_t PBS_ifl_RmReq_clone(flatbuffers_builder_t *B, PBS_ifl_RmReq_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_RmReq_start(B)
        || PBS_ifl_RmReq_hdr_pick(B, t)
        || PBS_ifl_RmReq_data_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_RmReq_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, PBS_ifl_RmResp_code, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_RmResp)
__flatbuffers_build_string_vector_field(1, flatbuffers_, PBS_ifl_RmResp_data, PBS_ifl_RmResp)

static inline PBS_ifl_RmResp_ref_t PBS_ifl_RmResp_create(flatbuffers_builder_t *B __PBS_ifl_RmResp_formal_args)
{
    if (PBS_ifl_RmResp_start(B)
        || PBS_ifl_RmResp_data_add(B, v1)
        || PBS_ifl_RmResp_code_add(B, v0)) {
        return 0;
    }
    return PBS_ifl_RmResp_end(B);
}

static PBS_ifl_RmResp_ref_t PBS_ifl_RmResp_clone(flatbuffers_builder_t *B, PBS_ifl_RmResp_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_RmResp_start(B)
        || PBS_ifl_RmResp_data_pick(B, t)
        || PBS_ifl_RmResp_code_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_RmResp_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, PBS_ifl_TmAttach_user, PBS_ifl_TmAttach)
__flatbuffers_build_scalar_field(1, flatbuffers_, PBS_ifl_TmAttach_uid, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_TmAttach)
__flatbuffers_build_scalar_field(2, flatbuffers_, PBS_ifl_TmAttach_pid, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_TmAttach)

static inline PBS_ifl_TmAttach_ref_t PBS_ifl_TmAttach_create(flatbuffers_builder_t *B __PBS_ifl_TmAttach_formal_args)
{
    if (PBS_ifl_TmAttach_start(B)
        || PBS_ifl_TmAttach_user_add(B, v0)
        || PBS_ifl_TmAttach_uid_add(B, v1)
        || PBS_ifl_TmAttach_pid_add(B, v2)) {
        return 0;
    }
    return PBS_ifl_TmAttach_end(B);
}

static PBS_ifl_TmAttach_ref_t PBS_ifl_TmAttach_clone(flatbuffers_builder_t *B, PBS_ifl_TmAttach_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_TmAttach_start(B)
        || PBS_ifl_TmAttach_user_pick(B, t)
        || PBS_ifl_TmAttach_uid_pick(B, t)
        || PBS_ifl_TmAttach_pid_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_TmAttach_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, PBS_ifl_TmSpawn_where, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_TmSpawn)
__flatbuffers_build_string_vector_field(1, flatbuffers_, PBS_ifl_TmSpawn_argv, PBS_ifl_TmSpawn)
__flatbuffers_build_string_vector_field(2, flatbuffers_, PBS_ifl_TmSpawn_envp, PBS_ifl_TmSpawn)

static inline PBS_ifl_TmSpawn_ref_t PBS_ifl_TmSpawn_create(flatbuffers_builder_t *B __PBS_ifl_TmSpawn_formal_args)
{
    if (PBS_ifl_TmSpawn_start(B)
        || PBS_ifl_TmSpawn_argv_add(B, v1)
        || PBS_ifl_TmSpawn_envp_add(B, v2)
        || PBS_ifl_TmSpawn_where_add(B, v0)) {
        return 0;
    }
    return PBS_ifl_TmSpawn_end(B);
}

static PBS_ifl_TmSpawn_ref_t PBS_ifl_TmSpawn_clone(flatbuffers_builder_t *B, PBS_ifl_TmSpawn_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_TmSpawn_start(B)
        || PBS_ifl_TmSpawn_argv_pick(B, t)
        || PBS_ifl_TmSpawn_envp_pick(B, t)
        || PBS_ifl_TmSpawn_where_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_TmSpawn_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, PBS_ifl_TmSignal_nid, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_TmSignal)
__flatbuffers_build_scalar_field(1, flatbuffers_, PBS_ifl_TmSignal_tid, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_TmSignal)
__flatbuffers_build_scalar_field(2, flatbuffers_, PBS_ifl_TmSignal_sig, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_TmSignal)

static inline PBS_ifl_TmSignal_ref_t PBS_ifl_TmSignal_create(flatbuffers_builder_t *B __PBS_ifl_TmSignal_formal_args)
{
    if (PBS_ifl_TmSignal_start(B)
        || PBS_ifl_TmSignal_nid_add(B, v0)
        || PBS_ifl_TmSignal_tid_add(B, v1)
        || PBS_ifl_TmSignal_sig_add(B, v2)) {
        return 0;
    }
    return PBS_ifl_TmSignal_end(B);
}

static PBS_ifl_TmSignal_ref_t PBS_ifl_TmSignal_clone(flatbuffers_builder_t *B, PBS_ifl_TmSignal_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_TmSignal_start(B)
        || PBS_ifl_TmSignal_nid_pick(B, t)
        || PBS_ifl_TmSignal_tid_pick(B, t)
        || PBS_ifl_TmSignal_sig_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_TmSignal_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, PBS_ifl_TmObit_nid, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_TmObit)
__flatbuffers_build_scalar_field(1, flatbuffers_, PBS_ifl_TmObit_tid, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_TmObit)

static inline PBS_ifl_TmObit_ref_t PBS_ifl_TmObit_create(flatbuffers_builder_t *B __PBS_ifl_TmObit_formal_args)
{
    if (PBS_ifl_TmObit_start(B)
        || PBS_ifl_TmObit_nid_add(B, v0)
        || PBS_ifl_TmObit_tid_add(B, v1)) {
        return 0;
    }
    return PBS_ifl_TmObit_end(B);
}

static PBS_ifl_TmObit_ref_t PBS_ifl_TmObit_clone(flatbuffers_builder_t *B, PBS_ifl_TmObit_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_TmObit_start(B)
        || PBS_ifl_TmObit_nid_pick(B, t)
        || PBS_ifl_TmObit_tid_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_TmObit_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, PBS_ifl_TmInfo_nid, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_TmInfo)

static inline PBS_ifl_TmInfo_ref_t PBS_ifl_TmInfo_create(flatbuffers_builder_t *B __PBS_ifl_TmInfo_formal_args)
{
    if (PBS_ifl_TmInfo_start(B)
        || PBS_ifl_TmInfo_nid_add(B, v0)) {
        return 0;
    }
    return PBS_ifl_TmInfo_end(B);
}

static PBS_ifl_TmInfo_ref_t PBS_ifl_TmInfo_clone(flatbuffers_builder_t *B, PBS_ifl_TmInfo_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_TmInfo_start(B)
        || PBS_ifl_TmInfo_nid_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_TmInfo_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, PBS_ifl_TmPublish_name, PBS_ifl_TmPublish)
__flatbuffers_build_string_field(1, flatbuffers_, PBS_ifl_TmPublish_info, PBS_ifl_TmPublish)

static inline PBS_ifl_TmPublish_ref_t PBS_ifl_TmPublish_create(flatbuffers_builder_t *B __PBS_ifl_TmPublish_formal_args)
{
    if (PBS_ifl_TmPublish_start(B)
        || PBS_ifl_TmPublish_name_add(B, v0)
        || PBS_ifl_TmPublish_info_add(B, v1)) {
        return 0;
    }
    return PBS_ifl_TmPublish_end(B);
}

static PBS_ifl_TmPublish_ref_t PBS_ifl_TmPublish_clone(flatbuffers_builder_t *B, PBS_ifl_TmPublish_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_TmPublish_start(B)
        || PBS_ifl_TmPublish_name_pick(B, t)
        || PBS_ifl_TmPublish_info_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_TmPublish_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, PBS_ifl_TmSubscribe_nid, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_TmSubscribe)
__flatbuffers_build_scalar_field(1, flatbuffers_, PBS_ifl_TmSubscribe_tid, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_TmSubscribe)
__flatbuffers_build_string_field(2, flatbuffers_, PBS_ifl_TmSubscribe_name, PBS_ifl_TmSubscribe)

static inline PBS_ifl_TmSubscribe_ref_t PBS_ifl_TmSubscribe_create(flatbuffers_builder_t *B __PBS_ifl_TmSubscribe_formal_args)
{
    if (PBS_ifl_TmSubscribe_start(B)
        || PBS_ifl_TmSubscribe_name_add(B, v2)
        || PBS_ifl_TmSubscribe_nid_add(B, v0)
        || PBS_ifl_TmSubscribe_tid_add(B, v1)) {
        return 0;
    }
    return PBS_ifl_TmSubscribe_end(B);
}

static PBS_ifl_TmSubscribe_ref_t PBS_ifl_TmSubscribe_clone(flatbuffers_builder_t *B, PBS_ifl_TmSubscribe_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_TmSubscribe_start(B)
        || PBS_ifl_TmSubscribe_name_pick(B, t)
        || PBS_ifl_TmSubscribe_nid_pick(B, t)
        || PBS_ifl_TmSubscribe_tid_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_TmSubscribe_end(B));
}

__flatbuffers_build_table_field(0, flatbuffers_, PBS_ifl_TmReq_hdr, PBS_ifl_Header, PBS_ifl_TmReq)
__flatbuffers_build_string_field(1, flatbuffers_, PBS_ifl_TmReq_jobId, PBS_ifl_TmReq)
__flatbuffers_build_string_field(2, flatbuffers_, PBS_ifl_TmReq_cookie, PBS_ifl_TmReq)
__flatbuffers_build_scalar_field(3, flatbuffers_, PBS_ifl_TmReq_event, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_TmReq)
__flatbuffers_build_scalar_field(4, flatbuffers_, PBS_ifl_TmReq_jobTid, flatbuffers_int16, int16_t, 2, 2, INT16_C(0), PBS_ifl_TmReq)
__flatbuffers_build_union_field(6, flatbuffers_, PBS_ifl_TmReq_body, PBS_ifl_TmBody, PBS_ifl_TmReq)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_TmReq_body, PBS_ifl_TmBody, TmAttach, PBS_ifl_TmAttach)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_TmReq_body, PBS_ifl_TmBody, TmSpawn, PBS_ifl_TmSpawn)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_TmReq_body, PBS_ifl_TmBody, TmSignal, PBS_ifl_TmSignal)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_TmReq_body, PBS_ifl_TmBody, TmObit, PBS_ifl_TmObit)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_TmReq_body, PBS_ifl_TmBody, TmInfo, PBS_ifl_TmInfo)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_TmReq_body, PBS_ifl_TmBody, TmPublish, PBS_ifl_TmPublish)
__flatbuffers_build_union_table_value_field(flatbuffers_, PBS_ifl_TmReq_body, PBS_ifl_TmBody, TmSubscribe, PBS_ifl_TmSubscribe)

static inline PBS_ifl_TmReq_ref_t PBS_ifl_TmReq_create(flatbuffers_builder_t *B __PBS_ifl_TmReq_formal_args)
{
    if (PBS_ifl_TmReq_start(B)
        || PBS_ifl_TmReq_hdr_add(B, v0)
        || PBS_ifl_TmReq_jobId_add(B, v1)
        || PBS_ifl_TmReq_cookie_add(B, v2)
        || PBS_ifl_TmReq_body_add_value(B, v6)
        || PBS_ifl_TmReq_event_add(B, v3)
        || PBS_ifl_TmReq_jobTid_add(B, v4)
        || PBS_ifl_TmReq_body_add_type(B, v6.type)) {
        return 0;
    }
    return PBS_ifl_TmReq_end(B);
}

static PBS_ifl_TmReq_ref_t PBS_ifl_TmReq_clone(flatbuffers_builder_t *B, PBS_ifl_TmReq_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PBS_ifl_TmReq_start(B)
        || PBS_ifl_TmReq_hdr_pick(B, t)
        || PBS_ifl_TmReq_jobId_pick(B, t)
        || PBS_ifl_TmReq_cookie_pick(B, t)
        || PBS_ifl_TmReq_body_pick(B, t)
        || PBS_ifl_TmReq_event_pick(B, t)
        || PBS_ifl_TmReq_jobTid_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PBS_ifl_TmReq_end(B));
}

#include "flatcc/flatcc_epilogue.h"
#endif /* PBS_IFL_BUILDER_H */
