#ifndef PBS_IFL_READER_H
#define PBS_IFL_READER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension ".bin"
#endif


typedef const struct PBS_ifl_Header_table *PBS_ifl_Header_table_t;
typedef struct PBS_ifl_Header_table *PBS_ifl_Header_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_Header_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_Header_mutable_vec_t;
typedef const struct PBS_ifl_Attribute_table *PBS_ifl_Attribute_table_t;
typedef struct PBS_ifl_Attribute_table *PBS_ifl_Attribute_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_Attribute_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_Attribute_mutable_vec_t;
typedef const struct PBS_ifl_Qjob_table *PBS_ifl_Qjob_table_t;
typedef struct PBS_ifl_Qjob_table *PBS_ifl_Qjob_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_Qjob_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_Qjob_mutable_vec_t;
typedef const struct PBS_ifl_JobFile_table *PBS_ifl_JobFile_table_t;
typedef struct PBS_ifl_JobFile_table *PBS_ifl_JobFile_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_JobFile_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_JobFile_mutable_vec_t;
typedef const struct PBS_ifl_JobId_table *PBS_ifl_JobId_table_t;
typedef struct PBS_ifl_JobId_table *PBS_ifl_JobId_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_JobId_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_JobId_mutable_vec_t;
typedef const struct PBS_ifl_Manage_table *PBS_ifl_Manage_table_t;
typedef struct PBS_ifl_Manage_table *PBS_ifl_Manage_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_Manage_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_Manage_mutable_vec_t;
typedef const struct PBS_ifl_Msg_table *PBS_ifl_Msg_table_t;
typedef struct PBS_ifl_Msg_table *PBS_ifl_Msg_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_Msg_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_Msg_mutable_vec_t;
typedef const struct PBS_ifl_Move_table *PBS_ifl_Move_table_t;
typedef struct PBS_ifl_Move_table *PBS_ifl_Move_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_Move_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_Move_mutable_vec_t;
typedef const struct PBS_ifl_Run_table *PBS_ifl_Run_table_t;
typedef struct PBS_ifl_Run_table *PBS_ifl_Run_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_Run_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_Run_mutable_vec_t;
typedef const struct PBS_ifl_Select_table *PBS_ifl_Select_table_t;
typedef struct PBS_ifl_Select_table *PBS_ifl_Select_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_Select_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_Select_mutable_vec_t;
typedef const struct PBS_ifl_DmnCmd_table *PBS_ifl_DmnCmd_table_t;
typedef struct PBS_ifl_DmnCmd_table *PBS_ifl_DmnCmd_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_DmnCmd_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_DmnCmd_mutable_vec_t;
typedef const struct PBS_ifl_Signal_table *PBS_ifl_Signal_table_t;
typedef struct PBS_ifl_Signal_table *PBS_ifl_Signal_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_Signal_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_Signal_mutable_vec_t;
typedef const struct PBS_ifl_Stat_table *PBS_ifl_Stat_table_t;
typedef struct PBS_ifl_Stat_table *PBS_ifl_Stat_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_Stat_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_Stat_mutable_vec_t;
typedef const struct PBS_ifl_Track_table *PBS_ifl_Track_table_t;
typedef struct PBS_ifl_Track_table *PBS_ifl_Track_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_Track_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_Track_mutable_vec_t;
typedef const struct PBS_ifl_RescQuery_table *PBS_ifl_RescQuery_table_t;
typedef struct PBS_ifl_RescQuery_table *PBS_ifl_RescQuery_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_RescQuery_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_RescQuery_mutable_vec_t;
typedef const struct PBS_ifl_Register_table *PBS_ifl_Register_table_t;
typedef struct PBS_ifl_Register_table *PBS_ifl_Register_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_Register_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_Register_mutable_vec_t;
typedef const struct PBS_ifl_FilePair_table *PBS_ifl_FilePair_table_t;
typedef struct PBS_ifl_FilePair_table *PBS_ifl_FilePair_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_FilePair_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_FilePair_mutable_vec_t;
typedef const struct PBS_ifl_CopyFile_table *PBS_ifl_CopyFile_table_t;
typedef struct PBS_ifl_CopyFile_table *PBS_ifl_CopyFile_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_CopyFile_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_CopyFile_mutable_vec_t;
typedef const struct PBS_ifl_Cred_table *PBS_ifl_Cred_table_t;
typedef struct PBS_ifl_Cred_table *PBS_ifl_Cred_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_Cred_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_Cred_mutable_vec_t;
typedef const struct PBS_ifl_CopyFileCred_table *PBS_ifl_CopyFileCred_table_t;
typedef struct PBS_ifl_CopyFileCred_table *PBS_ifl_CopyFileCred_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_CopyFileCred_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_CopyFileCred_mutable_vec_t;
typedef const struct PBS_ifl_UserMigrate_table *PBS_ifl_UserMigrate_table_t;
typedef struct PBS_ifl_UserMigrate_table *PBS_ifl_UserMigrate_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_UserMigrate_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_UserMigrate_mutable_vec_t;
typedef const struct PBS_ifl_SchedDefRep_table *PBS_ifl_SchedDefRep_table_t;
typedef struct PBS_ifl_SchedDefRep_table *PBS_ifl_SchedDefRep_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_SchedDefRep_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_SchedDefRep_mutable_vec_t;
typedef const struct PBS_ifl_Spawn_table *PBS_ifl_Spawn_table_t;
typedef struct PBS_ifl_Spawn_table *PBS_ifl_Spawn_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_Spawn_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_Spawn_mutable_vec_t;
typedef const struct PBS_ifl_CopyHook_table *PBS_ifl_CopyHook_table_t;
typedef struct PBS_ifl_CopyHook_table *PBS_ifl_CopyHook_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_CopyHook_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_CopyHook_mutable_vec_t;
typedef const struct PBS_ifl_RelNodes_table *PBS_ifl_RelNodes_table_t;
typedef struct PBS_ifl_RelNodes_table *PBS_ifl_RelNodes_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_RelNodes_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_RelNodes_mutable_vec_t;
typedef const struct PBS_ifl_PreemptJob_table *PBS_ifl_PreemptJob_table_t;
typedef struct PBS_ifl_PreemptJob_table *PBS_ifl_PreemptJob_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_PreemptJob_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_PreemptJob_mutable_vec_t;
typedef const struct PBS_ifl_Preempt_table *PBS_ifl_Preempt_table_t;
typedef struct PBS_ifl_Preempt_table *PBS_ifl_Preempt_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_Preempt_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_Preempt_mutable_vec_t;
typedef const struct PBS_ifl_Auth_table *PBS_ifl_Auth_table_t;
typedef struct PBS_ifl_Auth_table *PBS_ifl_Auth_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_Auth_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_Auth_mutable_vec_t;
typedef const struct PBS_ifl_Req_table *PBS_ifl_Req_table_t;
typedef struct PBS_ifl_Req_table *PBS_ifl_Req_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_Req_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_Req_mutable_vec_t;
typedef const struct PBS_ifl_TextResp_table *PBS_ifl_TextResp_table_t;
typedef struct PBS_ifl_TextResp_table *PBS_ifl_TextResp_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_TextResp_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_TextResp_mutable_vec_t;
typedef const struct PBS_ifl_SelectResp_table *PBS_ifl_SelectResp_table_t;
typedef struct PBS_ifl_SelectResp_table *PBS_ifl_SelectResp_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_SelectResp_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_SelectResp_mutable_vec_t;
typedef const struct PBS_ifl_StatRespStat_table *PBS_ifl_StatRespStat_table_t;
typedef struct PBS_ifl_StatRespStat_table *PBS_ifl_StatRespStat_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_StatRespStat_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_StatRespStat_mutable_vec_t;
typedef const struct PBS_ifl_StatResp_table *PBS_ifl_StatResp_table_t;
typedef struct PBS_ifl_StatResp_table *PBS_ifl_StatResp_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_StatResp_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_StatResp_mutable_vec_t;
typedef const struct PBS_ifl_RescQueryRespInfo_table *PBS_ifl_RescQueryRespInfo_table_t;
typedef struct PBS_ifl_RescQueryRespInfo_table *PBS_ifl_RescQueryRespInfo_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_RescQueryRespInfo_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_RescQueryRespInfo_mutable_vec_t;
typedef const struct PBS_ifl_RescQueryResp_table *PBS_ifl_RescQueryResp_table_t;
typedef struct PBS_ifl_RescQueryResp_table *PBS_ifl_RescQueryResp_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_RescQueryResp_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_RescQueryResp_mutable_vec_t;
typedef const struct PBS_ifl_Resp_table *PBS_ifl_Resp_table_t;
typedef struct PBS_ifl_Resp_table *PBS_ifl_Resp_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_Resp_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_Resp_mutable_vec_t;
typedef const struct PBS_ifl_RmReq_table *PBS_ifl_RmReq_table_t;
typedef struct PBS_ifl_RmReq_table *PBS_ifl_RmReq_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_RmReq_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_RmReq_mutable_vec_t;
typedef const struct PBS_ifl_RmResp_table *PBS_ifl_RmResp_table_t;
typedef struct PBS_ifl_RmResp_table *PBS_ifl_RmResp_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_RmResp_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_RmResp_mutable_vec_t;
typedef const struct PBS_ifl_TmAttach_table *PBS_ifl_TmAttach_table_t;
typedef struct PBS_ifl_TmAttach_table *PBS_ifl_TmAttach_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_TmAttach_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_TmAttach_mutable_vec_t;
typedef const struct PBS_ifl_TmSpawn_table *PBS_ifl_TmSpawn_table_t;
typedef struct PBS_ifl_TmSpawn_table *PBS_ifl_TmSpawn_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_TmSpawn_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_TmSpawn_mutable_vec_t;
typedef const struct PBS_ifl_TmSignal_table *PBS_ifl_TmSignal_table_t;
typedef struct PBS_ifl_TmSignal_table *PBS_ifl_TmSignal_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_TmSignal_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_TmSignal_mutable_vec_t;
typedef const struct PBS_ifl_TmObit_table *PBS_ifl_TmObit_table_t;
typedef struct PBS_ifl_TmObit_table *PBS_ifl_TmObit_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_TmObit_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_TmObit_mutable_vec_t;
typedef const struct PBS_ifl_TmInfo_table *PBS_ifl_TmInfo_table_t;
typedef struct PBS_ifl_TmInfo_table *PBS_ifl_TmInfo_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_TmInfo_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_TmInfo_mutable_vec_t;
typedef const struct PBS_ifl_TmPublish_table *PBS_ifl_TmPublish_table_t;
typedef struct PBS_ifl_TmPublish_table *PBS_ifl_TmPublish_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_TmPublish_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_TmPublish_mutable_vec_t;
typedef const struct PBS_ifl_TmSubscribe_table *PBS_ifl_TmSubscribe_table_t;
typedef struct PBS_ifl_TmSubscribe_table *PBS_ifl_TmSubscribe_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_TmSubscribe_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_TmSubscribe_mutable_vec_t;
typedef const struct PBS_ifl_TmReq_table *PBS_ifl_TmReq_table_t;
typedef struct PBS_ifl_TmReq_table *PBS_ifl_TmReq_mutable_table_t;
typedef const flatbuffers_uoffset_t *PBS_ifl_TmReq_vec_t;
typedef flatbuffers_uoffset_t *PBS_ifl_TmReq_mutable_vec_t;
#ifndef PBS_ifl_Header_file_identifier
#define PBS_ifl_Header_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_Header_file_identifier */
#ifndef PBS_ifl_Header_identifier
#define PBS_ifl_Header_identifier flatbuffers_identifier
#endif
#define PBS_ifl_Header_type_hash ((flatbuffers_thash_t)0x41d7cb9a)
#define PBS_ifl_Header_type_identifier "\x9a\xcb\xd7\x41"
#ifndef PBS_ifl_Attribute_file_identifier
#define PBS_ifl_Attribute_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_Attribute_file_identifier */
#ifndef PBS_ifl_Attribute_identifier
#define PBS_ifl_Attribute_identifier flatbuffers_identifier
#endif
#define PBS_ifl_Attribute_type_hash ((flatbuffers_thash_t)0x794a60c1)
#define PBS_ifl_Attribute_type_identifier "\xc1\x60\x4a\x79"
#ifndef PBS_ifl_Qjob_file_identifier
#define PBS_ifl_Qjob_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_Qjob_file_identifier */
#ifndef PBS_ifl_Qjob_identifier
#define PBS_ifl_Qjob_identifier flatbuffers_identifier
#endif
#define PBS_ifl_Qjob_type_hash ((flatbuffers_thash_t)0x59286611)
#define PBS_ifl_Qjob_type_identifier "\x11\x66\x28\x59"
#ifndef PBS_ifl_JobFile_file_identifier
#define PBS_ifl_JobFile_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_JobFile_file_identifier */
#ifndef PBS_ifl_JobFile_identifier
#define PBS_ifl_JobFile_identifier flatbuffers_identifier
#endif
#define PBS_ifl_JobFile_type_hash ((flatbuffers_thash_t)0x9e7715f4)
#define PBS_ifl_JobFile_type_identifier "\xf4\x15\x77\x9e"
#ifndef PBS_ifl_JobId_file_identifier
#define PBS_ifl_JobId_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_JobId_file_identifier */
#ifndef PBS_ifl_JobId_identifier
#define PBS_ifl_JobId_identifier flatbuffers_identifier
#endif
#define PBS_ifl_JobId_type_hash ((flatbuffers_thash_t)0x69c57d7f)
#define PBS_ifl_JobId_type_identifier "\x7f\x7d\xc5\x69"
#ifndef PBS_ifl_Manage_file_identifier
#define PBS_ifl_Manage_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_Manage_file_identifier */
#ifndef PBS_ifl_Manage_identifier
#define PBS_ifl_Manage_identifier flatbuffers_identifier
#endif
#define PBS_ifl_Manage_type_hash ((flatbuffers_thash_t)0xdd3e682c)
#define PBS_ifl_Manage_type_identifier "\x2c\x68\x3e\xdd"
#ifndef PBS_ifl_Msg_file_identifier
#define PBS_ifl_Msg_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_Msg_file_identifier */
#ifndef PBS_ifl_Msg_identifier
#define PBS_ifl_Msg_identifier flatbuffers_identifier
#endif
#define PBS_ifl_Msg_type_hash ((flatbuffers_thash_t)0x60fd206c)
#define PBS_ifl_Msg_type_identifier "\x6c\x20\xfd\x60"
#ifndef PBS_ifl_Move_file_identifier
#define PBS_ifl_Move_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_Move_file_identifier */
#ifndef PBS_ifl_Move_identifier
#define PBS_ifl_Move_identifier flatbuffers_identifier
#endif
#define PBS_ifl_Move_type_hash ((flatbuffers_thash_t)0x17077582)
#define PBS_ifl_Move_type_identifier "\x82\x75\x07\x17"
#ifndef PBS_ifl_Run_file_identifier
#define PBS_ifl_Run_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_Run_file_identifier */
#ifndef PBS_ifl_Run_identifier
#define PBS_ifl_Run_identifier flatbuffers_identifier
#endif
#define PBS_ifl_Run_type_hash ((flatbuffers_thash_t)0x4eb5fc)
#define PBS_ifl_Run_type_identifier "\xfc\xb5\x4e\x00"
#ifndef PBS_ifl_Select_file_identifier
#define PBS_ifl_Select_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_Select_file_identifier */
#ifndef PBS_ifl_Select_identifier
#define PBS_ifl_Select_identifier flatbuffers_identifier
#endif
#define PBS_ifl_Select_type_hash ((flatbuffers_thash_t)0xddb8b57b)
#define PBS_ifl_Select_type_identifier "\x7b\xb5\xb8\xdd"
#ifndef PBS_ifl_DmnCmd_file_identifier
#define PBS_ifl_DmnCmd_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_DmnCmd_file_identifier */
#ifndef PBS_ifl_DmnCmd_identifier
#define PBS_ifl_DmnCmd_identifier flatbuffers_identifier
#endif
#define PBS_ifl_DmnCmd_type_hash ((flatbuffers_thash_t)0x3c9f1ba2)
#define PBS_ifl_DmnCmd_type_identifier "\xa2\x1b\x9f\x3c"
#ifndef PBS_ifl_Signal_file_identifier
#define PBS_ifl_Signal_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_Signal_file_identifier */
#ifndef PBS_ifl_Signal_identifier
#define PBS_ifl_Signal_identifier flatbuffers_identifier
#endif
#define PBS_ifl_Signal_type_hash ((flatbuffers_thash_t)0x93821d6b)
#define PBS_ifl_Signal_type_identifier "\x6b\x1d\x82\x93"
#ifndef PBS_ifl_Stat_file_identifier
#define PBS_ifl_Stat_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_Stat_file_identifier */
#ifndef PBS_ifl_Stat_identifier
#define PBS_ifl_Stat_identifier flatbuffers_identifier
#endif
#define PBS_ifl_Stat_type_hash ((flatbuffers_thash_t)0x5b65ca51)
#define PBS_ifl_Stat_type_identifier "\x51\xca\x65\x5b"
#ifndef PBS_ifl_Track_file_identifier
#define PBS_ifl_Track_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_Track_file_identifier */
#ifndef PBS_ifl_Track_identifier
#define PBS_ifl_Track_identifier flatbuffers_identifier
#endif
#define PBS_ifl_Track_type_hash ((flatbuffers_thash_t)0x9cd5fb5a)
#define PBS_ifl_Track_type_identifier "\x5a\xfb\xd5\x9c"
#ifndef PBS_ifl_RescQuery_file_identifier
#define PBS_ifl_RescQuery_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_RescQuery_file_identifier */
#ifndef PBS_ifl_RescQuery_identifier
#define PBS_ifl_RescQuery_identifier flatbuffers_identifier
#endif
#define PBS_ifl_RescQuery_type_hash ((flatbuffers_thash_t)0xfdfb7e4c)
#define PBS_ifl_RescQuery_type_identifier "\x4c\x7e\xfb\xfd"
#ifndef PBS_ifl_Register_file_identifier
#define PBS_ifl_Register_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_Register_file_identifier */
#ifndef PBS_ifl_Register_identifier
#define PBS_ifl_Register_identifier flatbuffers_identifier
#endif
#define PBS_ifl_Register_type_hash ((flatbuffers_thash_t)0x17c3169e)
#define PBS_ifl_Register_type_identifier "\x9e\x16\xc3\x17"
#ifndef PBS_ifl_FilePair_file_identifier
#define PBS_ifl_FilePair_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_FilePair_file_identifier */
#ifndef PBS_ifl_FilePair_identifier
#define PBS_ifl_FilePair_identifier flatbuffers_identifier
#endif
#define PBS_ifl_FilePair_type_hash ((flatbuffers_thash_t)0xa9799261)
#define PBS_ifl_FilePair_type_identifier "\x61\x92\x79\xa9"
#ifndef PBS_ifl_CopyFile_file_identifier
#define PBS_ifl_CopyFile_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_CopyFile_file_identifier */
#ifndef PBS_ifl_CopyFile_identifier
#define PBS_ifl_CopyFile_identifier flatbuffers_identifier
#endif
#define PBS_ifl_CopyFile_type_hash ((flatbuffers_thash_t)0x3489f324)
#define PBS_ifl_CopyFile_type_identifier "\x24\xf3\x89\x34"
#ifndef PBS_ifl_Cred_file_identifier
#define PBS_ifl_Cred_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_Cred_file_identifier */
#ifndef PBS_ifl_Cred_identifier
#define PBS_ifl_Cred_identifier flatbuffers_identifier
#endif
#define PBS_ifl_Cred_type_hash ((flatbuffers_thash_t)0x4892e9cf)
#define PBS_ifl_Cred_type_identifier "\xcf\xe9\x92\x48"
#ifndef PBS_ifl_CopyFileCred_file_identifier
#define PBS_ifl_CopyFileCred_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_CopyFileCred_file_identifier */
#ifndef PBS_ifl_CopyFileCred_identifier
#define PBS_ifl_CopyFileCred_identifier flatbuffers_identifier
#endif
#define PBS_ifl_CopyFileCred_type_hash ((flatbuffers_thash_t)0xe3d874bc)
#define PBS_ifl_CopyFileCred_type_identifier "\xbc\x74\xd8\xe3"
#ifndef PBS_ifl_UserMigrate_file_identifier
#define PBS_ifl_UserMigrate_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_UserMigrate_file_identifier */
#ifndef PBS_ifl_UserMigrate_identifier
#define PBS_ifl_UserMigrate_identifier flatbuffers_identifier
#endif
#define PBS_ifl_UserMigrate_type_hash ((flatbuffers_thash_t)0xd85f38b5)
#define PBS_ifl_UserMigrate_type_identifier "\xb5\x38\x5f\xd8"
#ifndef PBS_ifl_SchedDefRep_file_identifier
#define PBS_ifl_SchedDefRep_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_SchedDefRep_file_identifier */
#ifndef PBS_ifl_SchedDefRep_identifier
#define PBS_ifl_SchedDefRep_identifier flatbuffers_identifier
#endif
#define PBS_ifl_SchedDefRep_type_hash ((flatbuffers_thash_t)0x59a739dc)
#define PBS_ifl_SchedDefRep_type_identifier "\xdc\x39\xa7\x59"
#ifndef PBS_ifl_Spawn_file_identifier
#define PBS_ifl_Spawn_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_Spawn_file_identifier */
#ifndef PBS_ifl_Spawn_identifier
#define PBS_ifl_Spawn_identifier flatbuffers_identifier
#endif
#define PBS_ifl_Spawn_type_hash ((flatbuffers_thash_t)0xddc881de)
#define PBS_ifl_Spawn_type_identifier "\xde\x81\xc8\xdd"
#ifndef PBS_ifl_CopyHook_file_identifier
#define PBS_ifl_CopyHook_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_CopyHook_file_identifier */
#ifndef PBS_ifl_CopyHook_identifier
#define PBS_ifl_CopyHook_identifier flatbuffers_identifier
#endif
#define PBS_ifl_CopyHook_type_hash ((flatbuffers_thash_t)0x3cab22bd)
#define PBS_ifl_CopyHook_type_identifier "\xbd\x22\xab\x3c"
#ifndef PBS_ifl_RelNodes_file_identifier
#define PBS_ifl_RelNodes_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_RelNodes_file_identifier */
#ifndef PBS_ifl_RelNodes_identifier
#define PBS_ifl_RelNodes_identifier flatbuffers_identifier
#endif
#define PBS_ifl_RelNodes_type_hash ((flatbuffers_thash_t)0x9d7d46c7)
#define PBS_ifl_RelNodes_type_identifier "\xc7\x46\x7d\x9d"
#ifndef PBS_ifl_PreemptJob_file_identifier
#define PBS_ifl_PreemptJob_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_PreemptJob_file_identifier */
#ifndef PBS_ifl_PreemptJob_identifier
#define PBS_ifl_PreemptJob_identifier flatbuffers_identifier
#endif
#define PBS_ifl_PreemptJob_type_hash ((flatbuffers_thash_t)0xd5695b41)
#define PBS_ifl_PreemptJob_type_identifier "\x41\x5b\x69\xd5"
#ifndef PBS_ifl_Preempt_file_identifier
#define PBS_ifl_Preempt_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_Preempt_file_identifier */
#ifndef PBS_ifl_Preempt_identifier
#define PBS_ifl_Preempt_identifier flatbuffers_identifier
#endif
#define PBS_ifl_Preempt_type_hash ((flatbuffers_thash_t)0x5ca984ae)
#define PBS_ifl_Preempt_type_identifier "\xae\x84\xa9\x5c"
#ifndef PBS_ifl_Auth_file_identifier
#define PBS_ifl_Auth_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_Auth_file_identifier */
#ifndef PBS_ifl_Auth_identifier
#define PBS_ifl_Auth_identifier flatbuffers_identifier
#endif
#define PBS_ifl_Auth_type_hash ((flatbuffers_thash_t)0x543335c5)
#define PBS_ifl_Auth_type_identifier "\xc5\x35\x33\x54"
#ifndef PBS_ifl_Req_file_identifier
#define PBS_ifl_Req_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_Req_file_identifier */
#ifndef PBS_ifl_Req_identifier
#define PBS_ifl_Req_identifier flatbuffers_identifier
#endif
#define PBS_ifl_Req_type_hash ((flatbuffers_thash_t)0xf7279861)
#define PBS_ifl_Req_type_identifier "\x61\x98\x27\xf7"
#ifndef PBS_ifl_TextResp_file_identifier
#define PBS_ifl_TextResp_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_TextResp_file_identifier */
#ifndef PBS_ifl_TextResp_identifier
#define PBS_ifl_TextResp_identifier flatbuffers_identifier
#endif
#define PBS_ifl_TextResp_type_hash ((flatbuffers_thash_t)0xc73b395e)
#define PBS_ifl_TextResp_type_identifier "\x5e\x39\x3b\xc7"
#ifndef PBS_ifl_SelectResp_file_identifier
#define PBS_ifl_SelectResp_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_SelectResp_file_identifier */
#ifndef PBS_ifl_SelectResp_identifier
#define PBS_ifl_SelectResp_identifier flatbuffers_identifier
#endif
#define PBS_ifl_SelectResp_type_hash ((flatbuffers_thash_t)0xbe916bf1)
#define PBS_ifl_SelectResp_type_identifier "\xf1\x6b\x91\xbe"
#ifndef PBS_ifl_StatRespStat_file_identifier
#define PBS_ifl_StatRespStat_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_StatRespStat_file_identifier */
#ifndef PBS_ifl_StatRespStat_identifier
#define PBS_ifl_StatRespStat_identifier flatbuffers_identifier
#endif
#define PBS_ifl_StatRespStat_type_hash ((flatbuffers_thash_t)0x78097e25)
#define PBS_ifl_StatRespStat_type_identifier "\x25\x7e\x09\x78"
#ifndef PBS_ifl_StatResp_file_identifier
#define PBS_ifl_StatResp_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_StatResp_file_identifier */
#ifndef PBS_ifl_StatResp_identifier
#define PBS_ifl_StatResp_identifier flatbuffers_identifier
#endif
#define PBS_ifl_StatResp_type_hash ((flatbuffers_thash_t)0x6217a80f)
#define PBS_ifl_StatResp_type_identifier "\x0f\xa8\x17\x62"
#ifndef PBS_ifl_RescQueryRespInfo_file_identifier
#define PBS_ifl_RescQueryRespInfo_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_RescQueryRespInfo_file_identifier */
#ifndef PBS_ifl_RescQueryRespInfo_identifier
#define PBS_ifl_RescQueryRespInfo_identifier flatbuffers_identifier
#endif
#define PBS_ifl_RescQueryRespInfo_type_hash ((flatbuffers_thash_t)0x7a3dd6fe)
#define PBS_ifl_RescQueryRespInfo_type_identifier "\xfe\xd6\x3d\x7a"
#ifndef PBS_ifl_RescQueryResp_file_identifier
#define PBS_ifl_RescQueryResp_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_RescQueryResp_file_identifier */
#ifndef PBS_ifl_RescQueryResp_identifier
#define PBS_ifl_RescQueryResp_identifier flatbuffers_identifier
#endif
#define PBS_ifl_RescQueryResp_type_hash ((flatbuffers_thash_t)0x7d54689e)
#define PBS_ifl_RescQueryResp_type_identifier "\x9e\x68\x54\x7d"
#ifndef PBS_ifl_Resp_file_identifier
#define PBS_ifl_Resp_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_Resp_file_identifier */
#ifndef PBS_ifl_Resp_identifier
#define PBS_ifl_Resp_identifier flatbuffers_identifier
#endif
#define PBS_ifl_Resp_type_hash ((flatbuffers_thash_t)0x38500511)
#define PBS_ifl_Resp_type_identifier "\x11\x05\x50\x38"
#ifndef PBS_ifl_RmReq_file_identifier
#define PBS_ifl_RmReq_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_RmReq_file_identifier */
#ifndef PBS_ifl_RmReq_identifier
#define PBS_ifl_RmReq_identifier flatbuffers_identifier
#endif
#define PBS_ifl_RmReq_type_hash ((flatbuffers_thash_t)0x1d90a7aa)
#define PBS_ifl_RmReq_type_identifier "\xaa\xa7\x90\x1d"
#ifndef PBS_ifl_RmResp_file_identifier
#define PBS_ifl_RmResp_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_RmResp_file_identifier */
#ifndef PBS_ifl_RmResp_identifier
#define PBS_ifl_RmResp_identifier flatbuffers_identifier
#endif
#define PBS_ifl_RmResp_type_hash ((flatbuffers_thash_t)0x58b3ac1c)
#define PBS_ifl_RmResp_type_identifier "\x1c\xac\xb3\x58"
#ifndef PBS_ifl_TmAttach_file_identifier
#define PBS_ifl_TmAttach_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_TmAttach_file_identifier */
#ifndef PBS_ifl_TmAttach_identifier
#define PBS_ifl_TmAttach_identifier flatbuffers_identifier
#endif
#define PBS_ifl_TmAttach_type_hash ((flatbuffers_thash_t)0x2a04c8c5)
#define PBS_ifl_TmAttach_type_identifier "\xc5\xc8\x04\x2a"
#ifndef PBS_ifl_TmSpawn_file_identifier
#define PBS_ifl_TmSpawn_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_TmSpawn_file_identifier */
#ifndef PBS_ifl_TmSpawn_identifier
#define PBS_ifl_TmSpawn_identifier flatbuffers_identifier
#endif
#define PBS_ifl_TmSpawn_type_hash ((flatbuffers_thash_t)0x7fdcec5f)
#define PBS_ifl_TmSpawn_type_identifier "\x5f\xec\xdc\x7f"
#ifndef PBS_ifl_TmSignal_file_identifier
#define PBS_ifl_TmSignal_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_TmSignal_file_identifier */
#ifndef PBS_ifl_TmSignal_identifier
#define PBS_ifl_TmSignal_identifier flatbuffers_identifier
#endif
#define PBS_ifl_TmSignal_type_hash ((flatbuffers_thash_t)0xa4bc6b64)
#define PBS_ifl_TmSignal_type_identifier "\x64\x6b\xbc\xa4"
#ifndef PBS_ifl_TmObit_file_identifier
#define PBS_ifl_TmObit_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_TmObit_file_identifier */
#ifndef PBS_ifl_TmObit_identifier
#define PBS_ifl_TmObit_identifier flatbuffers_identifier
#endif
#define PBS_ifl_TmObit_type_hash ((flatbuffers_thash_t)0x96be6d18)
#define PBS_ifl_TmObit_type_identifier "\x18\x6d\xbe\x96"
#ifndef PBS_ifl_TmInfo_file_identifier
#define PBS_ifl_TmInfo_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_TmInfo_file_identifier */
#ifndef PBS_ifl_TmInfo_identifier
#define PBS_ifl_TmInfo_identifier flatbuffers_identifier
#endif
#define PBS_ifl_TmInfo_type_hash ((flatbuffers_thash_t)0xbd87a58c)
#define PBS_ifl_TmInfo_type_identifier "\x8c\xa5\x87\xbd"
#ifndef PBS_ifl_TmPublish_file_identifier
#define PBS_ifl_TmPublish_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_TmPublish_file_identifier */
#ifndef PBS_ifl_TmPublish_identifier
#define PBS_ifl_TmPublish_identifier flatbuffers_identifier
#endif
#define PBS_ifl_TmPublish_type_hash ((flatbuffers_thash_t)0x238f62bb)
#define PBS_ifl_TmPublish_type_identifier "\xbb\x62\x8f\x23"
#ifndef PBS_ifl_TmSubscribe_file_identifier
#define PBS_ifl_TmSubscribe_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_TmSubscribe_file_identifier */
#ifndef PBS_ifl_TmSubscribe_identifier
#define PBS_ifl_TmSubscribe_identifier flatbuffers_identifier
#endif
#define PBS_ifl_TmSubscribe_type_hash ((flatbuffers_thash_t)0x68a657f8)
#define PBS_ifl_TmSubscribe_type_identifier "\xf8\x57\xa6\x68"
#ifndef PBS_ifl_TmReq_file_identifier
#define PBS_ifl_TmReq_file_identifier flatbuffers_identifier
#endif
/* deprecated, use PBS_ifl_TmReq_file_identifier */
#ifndef PBS_ifl_TmReq_identifier
#define PBS_ifl_TmReq_identifier flatbuffers_identifier
#endif
#define PBS_ifl_TmReq_type_hash ((flatbuffers_thash_t)0xe7564818)
#define PBS_ifl_TmReq_type_identifier "\x18\x48\x56\xe7"

typedef int8_t PBS_ifl_ProtType_enum_t;
__flatbuffers_define_integer_type(PBS_ifl_ProtType, PBS_ifl_ProtType_enum_t, 8)
#define PBS_ifl_ProtType_Batch ((PBS_ifl_ProtType_enum_t)INT8_C(0))
#define PBS_ifl_ProtType_TaskManager ((PBS_ifl_ProtType_enum_t)INT8_C(1))
#define PBS_ifl_ProtType_RescManager ((PBS_ifl_ProtType_enum_t)INT8_C(2))
#define PBS_ifl_ProtType_InterMoM ((PBS_ifl_ProtType_enum_t)INT8_C(3))
#define PBS_ifl_ProtType_InterSvr ((PBS_ifl_ProtType_enum_t)INT8_C(4))

static inline const char *PBS_ifl_ProtType_name(PBS_ifl_ProtType_enum_t value)
{
    switch (value) {
    case PBS_ifl_ProtType_Batch: return "Batch";
    case PBS_ifl_ProtType_TaskManager: return "TaskManager";
    case PBS_ifl_ProtType_RescManager: return "RescManager";
    case PBS_ifl_ProtType_InterMoM: return "InterMoM";
    case PBS_ifl_ProtType_InterSvr: return "InterSvr";
    default: return "";
    }
}

static inline int PBS_ifl_ProtType_is_known_value(PBS_ifl_ProtType_enum_t value)
{
    switch (value) {
    case PBS_ifl_ProtType_Batch: return 1;
    case PBS_ifl_ProtType_TaskManager: return 1;
    case PBS_ifl_ProtType_RescManager: return 1;
    case PBS_ifl_ProtType_InterMoM: return 1;
    case PBS_ifl_ProtType_InterSvr: return 1;
    default: return 0;
    }
}

typedef int8_t PBS_ifl_batch_op_enum_t;
__flatbuffers_define_integer_type(PBS_ifl_batch_op, PBS_ifl_batch_op_enum_t, 8)
#define PBS_ifl_batch_op_SET ((PBS_ifl_batch_op_enum_t)INT8_C(0))
#define PBS_ifl_batch_op_UNSET ((PBS_ifl_batch_op_enum_t)INT8_C(1))
#define PBS_ifl_batch_op_INCR ((PBS_ifl_batch_op_enum_t)INT8_C(2))
#define PBS_ifl_batch_op_DECR ((PBS_ifl_batch_op_enum_t)INT8_C(3))
#define PBS_ifl_batch_op_EQ ((PBS_ifl_batch_op_enum_t)INT8_C(4))
#define PBS_ifl_batch_op_NE ((PBS_ifl_batch_op_enum_t)INT8_C(5))
#define PBS_ifl_batch_op_GE ((PBS_ifl_batch_op_enum_t)INT8_C(6))
#define PBS_ifl_batch_op_GT ((PBS_ifl_batch_op_enum_t)INT8_C(7))
#define PBS_ifl_batch_op_LE ((PBS_ifl_batch_op_enum_t)INT8_C(8))
#define PBS_ifl_batch_op_LT ((PBS_ifl_batch_op_enum_t)INT8_C(9))
#define PBS_ifl_batch_op_DFLT ((PBS_ifl_batch_op_enum_t)INT8_C(10))

static inline const char *PBS_ifl_batch_op_name(PBS_ifl_batch_op_enum_t value)
{
    switch (value) {
    case PBS_ifl_batch_op_SET: return "SET";
    case PBS_ifl_batch_op_UNSET: return "UNSET";
    case PBS_ifl_batch_op_INCR: return "INCR";
    case PBS_ifl_batch_op_DECR: return "DECR";
    case PBS_ifl_batch_op_EQ: return "EQ";
    case PBS_ifl_batch_op_NE: return "NE";
    case PBS_ifl_batch_op_GE: return "GE";
    case PBS_ifl_batch_op_GT: return "GT";
    case PBS_ifl_batch_op_LE: return "LE";
    case PBS_ifl_batch_op_LT: return "LT";
    case PBS_ifl_batch_op_DFLT: return "DFLT";
    default: return "";
    }
}

static inline int PBS_ifl_batch_op_is_known_value(PBS_ifl_batch_op_enum_t value)
{
    switch (value) {
    case PBS_ifl_batch_op_SET: return 1;
    case PBS_ifl_batch_op_UNSET: return 1;
    case PBS_ifl_batch_op_INCR: return 1;
    case PBS_ifl_batch_op_DECR: return 1;
    case PBS_ifl_batch_op_EQ: return 1;
    case PBS_ifl_batch_op_NE: return 1;
    case PBS_ifl_batch_op_GE: return 1;
    case PBS_ifl_batch_op_GT: return 1;
    case PBS_ifl_batch_op_LE: return 1;
    case PBS_ifl_batch_op_LT: return 1;
    case PBS_ifl_batch_op_DFLT: return 1;
    default: return 0;
    }
}



struct PBS_ifl_Header_table { uint8_t unused__; };

static inline size_t PBS_ifl_Header_vec_len(PBS_ifl_Header_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_Header_table_t PBS_ifl_Header_vec_at(PBS_ifl_Header_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_Header_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_Header)

__flatbuffers_define_scalar_field(0, PBS_ifl_Header, protType, PBS_ifl_ProtType, PBS_ifl_ProtType_enum_t, INT8_C(0))
__flatbuffers_define_scalar_field(1, PBS_ifl_Header, version, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_scalar_field(2, PBS_ifl_Header, reqId, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_string_field(3, PBS_ifl_Header, user, 0)

struct PBS_ifl_Attribute_table { uint8_t unused__; };

static inline size_t PBS_ifl_Attribute_vec_len(PBS_ifl_Attribute_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_Attribute_table_t PBS_ifl_Attribute_vec_at(PBS_ifl_Attribute_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_Attribute_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_Attribute)

__flatbuffers_define_string_field(0, PBS_ifl_Attribute, name, 0)
__flatbuffers_define_string_field(1, PBS_ifl_Attribute, resc, 0)
__flatbuffers_define_string_field(2, PBS_ifl_Attribute, value, 0)
__flatbuffers_define_scalar_field(3, PBS_ifl_Attribute, op, PBS_ifl_batch_op, PBS_ifl_batch_op_enum_t, INT8_C(0))

struct PBS_ifl_Qjob_table { uint8_t unused__; };

static inline size_t PBS_ifl_Qjob_vec_len(PBS_ifl_Qjob_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_Qjob_table_t PBS_ifl_Qjob_vec_at(PBS_ifl_Qjob_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_Qjob_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_Qjob)

__flatbuffers_define_string_field(0, PBS_ifl_Qjob, jobId, 0)
__flatbuffers_define_string_field(1, PBS_ifl_Qjob, destin, 0)
__flatbuffers_define_vector_field(2, PBS_ifl_Qjob, attrs, PBS_ifl_Attribute_vec_t, 0)

struct PBS_ifl_JobFile_table { uint8_t unused__; };

static inline size_t PBS_ifl_JobFile_vec_len(PBS_ifl_JobFile_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_JobFile_table_t PBS_ifl_JobFile_vec_at(PBS_ifl_JobFile_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_JobFile_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_JobFile)

__flatbuffers_define_scalar_field(0, PBS_ifl_JobFile, seq, flatbuffers_int64, int64_t, INT64_C(0))
__flatbuffers_define_scalar_field(1, PBS_ifl_JobFile, type, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_scalar_field(2, PBS_ifl_JobFile, size, flatbuffers_int64, int64_t, INT64_C(0))
__flatbuffers_define_string_field(3, PBS_ifl_JobFile, jobId, 0)
__flatbuffers_define_string_field(4, PBS_ifl_JobFile, data, 0)

struct PBS_ifl_JobId_table { uint8_t unused__; };

static inline size_t PBS_ifl_JobId_vec_len(PBS_ifl_JobId_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_JobId_table_t PBS_ifl_JobId_vec_at(PBS_ifl_JobId_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_JobId_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_JobId)

__flatbuffers_define_string_field(0, PBS_ifl_JobId, jobId, 0)

struct PBS_ifl_Manage_table { uint8_t unused__; };

static inline size_t PBS_ifl_Manage_vec_len(PBS_ifl_Manage_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_Manage_table_t PBS_ifl_Manage_vec_at(PBS_ifl_Manage_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_Manage_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_Manage)

__flatbuffers_define_scalar_field(0, PBS_ifl_Manage, cmd, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_scalar_field(1, PBS_ifl_Manage, objType, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_string_field(2, PBS_ifl_Manage, objName, 0)
__flatbuffers_define_vector_field(3, PBS_ifl_Manage, attrs, PBS_ifl_Attribute_vec_t, 0)

struct PBS_ifl_Msg_table { uint8_t unused__; };

static inline size_t PBS_ifl_Msg_vec_len(PBS_ifl_Msg_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_Msg_table_t PBS_ifl_Msg_vec_at(PBS_ifl_Msg_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_Msg_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_Msg)

__flatbuffers_define_scalar_field(0, PBS_ifl_Msg, fileInd, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_string_field(1, PBS_ifl_Msg, jobId, 0)
__flatbuffers_define_string_field(2, PBS_ifl_Msg, text, 0)

struct PBS_ifl_Move_table { uint8_t unused__; };

static inline size_t PBS_ifl_Move_vec_len(PBS_ifl_Move_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_Move_table_t PBS_ifl_Move_vec_at(PBS_ifl_Move_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_Move_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_Move)

__flatbuffers_define_string_field(0, PBS_ifl_Move, jobId, 0)
__flatbuffers_define_string_field(1, PBS_ifl_Move, dest, 0)

struct PBS_ifl_Run_table { uint8_t unused__; };

static inline size_t PBS_ifl_Run_vec_len(PBS_ifl_Run_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_Run_table_t PBS_ifl_Run_vec_at(PBS_ifl_Run_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_Run_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_Run)

__flatbuffers_define_string_field(0, PBS_ifl_Run, jobId, 0)
__flatbuffers_define_string_field(1, PBS_ifl_Run, dest, 0)
__flatbuffers_define_scalar_field(2, PBS_ifl_Run, resch, flatbuffers_int64, int64_t, INT64_C(0))

struct PBS_ifl_Select_table { uint8_t unused__; };

static inline size_t PBS_ifl_Select_vec_len(PBS_ifl_Select_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_Select_table_t PBS_ifl_Select_vec_at(PBS_ifl_Select_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_Select_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_Select)

__flatbuffers_define_vector_field(0, PBS_ifl_Select, selAttrs, PBS_ifl_Attribute_vec_t, 0)
__flatbuffers_define_vector_field(1, PBS_ifl_Select, rtnAttrs, PBS_ifl_Attribute_vec_t, 0)

struct PBS_ifl_DmnCmd_table { uint8_t unused__; };

static inline size_t PBS_ifl_DmnCmd_vec_len(PBS_ifl_DmnCmd_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_DmnCmd_table_t PBS_ifl_DmnCmd_vec_at(PBS_ifl_DmnCmd_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_DmnCmd_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_DmnCmd)

__flatbuffers_define_scalar_field(0, PBS_ifl_DmnCmd, cmd, flatbuffers_int16, int16_t, INT16_C(0))

struct PBS_ifl_Signal_table { uint8_t unused__; };

static inline size_t PBS_ifl_Signal_vec_len(PBS_ifl_Signal_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_Signal_table_t PBS_ifl_Signal_vec_at(PBS_ifl_Signal_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_Signal_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_Signal)

__flatbuffers_define_string_field(0, PBS_ifl_Signal, jobId, 0)
__flatbuffers_define_string_field(1, PBS_ifl_Signal, sigName, 0)

struct PBS_ifl_Stat_table { uint8_t unused__; };

static inline size_t PBS_ifl_Stat_vec_len(PBS_ifl_Stat_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_Stat_table_t PBS_ifl_Stat_vec_at(PBS_ifl_Stat_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_Stat_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_Stat)

__flatbuffers_define_string_field(0, PBS_ifl_Stat, jobIds, 0)
__flatbuffers_define_vector_field(1, PBS_ifl_Stat, attrs, PBS_ifl_Attribute_vec_t, 0)

struct PBS_ifl_Track_table { uint8_t unused__; };

static inline size_t PBS_ifl_Track_vec_len(PBS_ifl_Track_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_Track_table_t PBS_ifl_Track_vec_at(PBS_ifl_Track_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_Track_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_Track)

__flatbuffers_define_scalar_field(0, PBS_ifl_Track, hops, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_string_field(1, PBS_ifl_Track, jobId, 0)
__flatbuffers_define_string_field(2, PBS_ifl_Track, location, 0)
__flatbuffers_define_scalar_field(3, PBS_ifl_Track, state, flatbuffers_int8, int8_t, INT8_C(0))

struct PBS_ifl_RescQuery_table { uint8_t unused__; };

static inline size_t PBS_ifl_RescQuery_vec_len(PBS_ifl_RescQuery_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_RescQuery_table_t PBS_ifl_RescQuery_vec_at(PBS_ifl_RescQuery_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_RescQuery_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_RescQuery)

__flatbuffers_define_scalar_field(0, PBS_ifl_RescQuery, handle, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_vector_field(1, PBS_ifl_RescQuery, queries, flatbuffers_string_vec_t, 0)

struct PBS_ifl_Register_table { uint8_t unused__; };

static inline size_t PBS_ifl_Register_vec_len(PBS_ifl_Register_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_Register_table_t PBS_ifl_Register_vec_at(PBS_ifl_Register_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_Register_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_Register)

__flatbuffers_define_string_field(0, PBS_ifl_Register, owner, 0)
__flatbuffers_define_string_field(1, PBS_ifl_Register, parent, 0)
__flatbuffers_define_string_field(2, PBS_ifl_Register, child, 0)
__flatbuffers_define_scalar_field(3, PBS_ifl_Register, type, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_scalar_field(4, PBS_ifl_Register, op, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_scalar_field(5, PBS_ifl_Register, cost, flatbuffers_int64, int64_t, INT64_C(0))

struct PBS_ifl_FilePair_table { uint8_t unused__; };

static inline size_t PBS_ifl_FilePair_vec_len(PBS_ifl_FilePair_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_FilePair_table_t PBS_ifl_FilePair_vec_at(PBS_ifl_FilePair_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_FilePair_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_FilePair)

__flatbuffers_define_string_field(0, PBS_ifl_FilePair, local, 0)
__flatbuffers_define_string_field(1, PBS_ifl_FilePair, remote, 0)
__flatbuffers_define_scalar_field(2, PBS_ifl_FilePair, flag, flatbuffers_int16, int16_t, INT16_C(0))

struct PBS_ifl_CopyFile_table { uint8_t unused__; };

static inline size_t PBS_ifl_CopyFile_vec_len(PBS_ifl_CopyFile_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_CopyFile_table_t PBS_ifl_CopyFile_vec_at(PBS_ifl_CopyFile_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_CopyFile_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_CopyFile)

__flatbuffers_define_string_field(0, PBS_ifl_CopyFile, jobId, 0)
__flatbuffers_define_string_field(1, PBS_ifl_CopyFile, owner, 0)
__flatbuffers_define_string_field(2, PBS_ifl_CopyFile, user, 0)
__flatbuffers_define_string_field(3, PBS_ifl_CopyFile, group, 0)
__flatbuffers_define_scalar_field(4, PBS_ifl_CopyFile, flags, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_vector_field(5, PBS_ifl_CopyFile, pairs, PBS_ifl_FilePair_vec_t, 0)

struct PBS_ifl_Cred_table { uint8_t unused__; };

static inline size_t PBS_ifl_Cred_vec_len(PBS_ifl_Cred_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_Cred_table_t PBS_ifl_Cred_vec_at(PBS_ifl_Cred_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_Cred_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_Cred)

__flatbuffers_define_string_field(0, PBS_ifl_Cred, jobId, 0)
__flatbuffers_define_string_field(1, PBS_ifl_Cred, user, 0)
__flatbuffers_define_scalar_field(2, PBS_ifl_Cred, validity, flatbuffers_int64, int64_t, INT64_C(0))
__flatbuffers_define_scalar_field(3, PBS_ifl_Cred, type, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_scalar_field(4, PBS_ifl_Cred, size, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_string_field(5, PBS_ifl_Cred, data, 0)

struct PBS_ifl_CopyFileCred_table { uint8_t unused__; };

static inline size_t PBS_ifl_CopyFileCred_vec_len(PBS_ifl_CopyFileCred_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_CopyFileCred_table_t PBS_ifl_CopyFileCred_vec_at(PBS_ifl_CopyFileCred_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_CopyFileCred_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_CopyFileCred)

__flatbuffers_define_table_field(0, PBS_ifl_CopyFileCred, files, PBS_ifl_CopyFile_table_t, 0)
__flatbuffers_define_scalar_field(1, PBS_ifl_CopyFileCred, type, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_string_field(2, PBS_ifl_CopyFileCred, cred, 0)

struct PBS_ifl_UserMigrate_table { uint8_t unused__; };

static inline size_t PBS_ifl_UserMigrate_vec_len(PBS_ifl_UserMigrate_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_UserMigrate_table_t PBS_ifl_UserMigrate_vec_at(PBS_ifl_UserMigrate_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_UserMigrate_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_UserMigrate)

__flatbuffers_define_string_field(0, PBS_ifl_UserMigrate, tohost, 0)

struct PBS_ifl_SchedDefRep_table { uint8_t unused__; };

static inline size_t PBS_ifl_SchedDefRep_vec_len(PBS_ifl_SchedDefRep_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_SchedDefRep_table_t PBS_ifl_SchedDefRep_vec_at(PBS_ifl_SchedDefRep_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_SchedDefRep_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_SchedDefRep)

__flatbuffers_define_scalar_field(0, PBS_ifl_SchedDefRep, cmd, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_string_field(1, PBS_ifl_SchedDefRep, id, 0)
__flatbuffers_define_scalar_field(2, PBS_ifl_SchedDefRep, err, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_string_field(3, PBS_ifl_SchedDefRep, text, 0)

struct PBS_ifl_Spawn_table { uint8_t unused__; };

static inline size_t PBS_ifl_Spawn_vec_len(PBS_ifl_Spawn_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_Spawn_table_t PBS_ifl_Spawn_vec_at(PBS_ifl_Spawn_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_Spawn_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_Spawn)

__flatbuffers_define_string_field(0, PBS_ifl_Spawn, jobId, 0)
__flatbuffers_define_vector_field(1, PBS_ifl_Spawn, argv, flatbuffers_string_vec_t, 0)
__flatbuffers_define_vector_field(2, PBS_ifl_Spawn, envp, flatbuffers_string_vec_t, 0)

struct PBS_ifl_CopyHook_table { uint8_t unused__; };

static inline size_t PBS_ifl_CopyHook_vec_len(PBS_ifl_CopyHook_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_CopyHook_table_t PBS_ifl_CopyHook_vec_at(PBS_ifl_CopyHook_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_CopyHook_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_CopyHook)

__flatbuffers_define_scalar_field(0, PBS_ifl_CopyHook, seq, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_scalar_field(1, PBS_ifl_CopyHook, size, flatbuffers_int64, int64_t, INT64_C(0))
__flatbuffers_define_string_field(2, PBS_ifl_CopyHook, filename, 0)
__flatbuffers_define_string_field(3, PBS_ifl_CopyHook, data, 0)

struct PBS_ifl_RelNodes_table { uint8_t unused__; };

static inline size_t PBS_ifl_RelNodes_vec_len(PBS_ifl_RelNodes_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_RelNodes_table_t PBS_ifl_RelNodes_vec_at(PBS_ifl_RelNodes_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_RelNodes_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_RelNodes)

__flatbuffers_define_string_field(0, PBS_ifl_RelNodes, jobId, 0)
__flatbuffers_define_string_field(1, PBS_ifl_RelNodes, nodes, 0)

struct PBS_ifl_PreemptJob_table { uint8_t unused__; };

static inline size_t PBS_ifl_PreemptJob_vec_len(PBS_ifl_PreemptJob_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_PreemptJob_table_t PBS_ifl_PreemptJob_vec_at(PBS_ifl_PreemptJob_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_PreemptJob_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_PreemptJob)

__flatbuffers_define_string_field(0, PBS_ifl_PreemptJob, jid, 0)
__flatbuffers_define_string_field(1, PBS_ifl_PreemptJob, order, 0)

struct PBS_ifl_Preempt_table { uint8_t unused__; };

static inline size_t PBS_ifl_Preempt_vec_len(PBS_ifl_Preempt_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_Preempt_table_t PBS_ifl_Preempt_vec_at(PBS_ifl_Preempt_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_Preempt_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_Preempt)

__flatbuffers_define_vector_field(0, PBS_ifl_Preempt, infos, PBS_ifl_PreemptJob_vec_t, 0)

struct PBS_ifl_Auth_table { uint8_t unused__; };

static inline size_t PBS_ifl_Auth_vec_len(PBS_ifl_Auth_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_Auth_table_t PBS_ifl_Auth_vec_at(PBS_ifl_Auth_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_Auth_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_Auth)

__flatbuffers_define_string_field(0, PBS_ifl_Auth, authMethod, 0)
__flatbuffers_define_string_field(1, PBS_ifl_Auth, encryptMethod, 0)
__flatbuffers_define_scalar_field(2, PBS_ifl_Auth, encryptMode, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_scalar_field(3, PBS_ifl_Auth, port, flatbuffers_uint16, uint16_t, UINT16_C(0))
typedef uint8_t PBS_ifl_ReqBody_union_type_t;
__flatbuffers_define_integer_type(PBS_ifl_ReqBody, PBS_ifl_ReqBody_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, PBS_ifl_ReqBody)
#define PBS_ifl_ReqBody_NONE ((PBS_ifl_ReqBody_union_type_t)UINT8_C(0))
#define PBS_ifl_ReqBody_Qjob ((PBS_ifl_ReqBody_union_type_t)UINT8_C(1))
#define PBS_ifl_ReqBody_JobFile ((PBS_ifl_ReqBody_union_type_t)UINT8_C(2))
#define PBS_ifl_ReqBody_JobId ((PBS_ifl_ReqBody_union_type_t)UINT8_C(3))
#define PBS_ifl_ReqBody_Manage ((PBS_ifl_ReqBody_union_type_t)UINT8_C(4))
#define PBS_ifl_ReqBody_Msg ((PBS_ifl_ReqBody_union_type_t)UINT8_C(5))
#define PBS_ifl_ReqBody_Move ((PBS_ifl_ReqBody_union_type_t)UINT8_C(6))
#define PBS_ifl_ReqBody_Run ((PBS_ifl_ReqBody_union_type_t)UINT8_C(7))
#define PBS_ifl_ReqBody_Select ((PBS_ifl_ReqBody_union_type_t)UINT8_C(8))
#define PBS_ifl_ReqBody_DmnCmd ((PBS_ifl_ReqBody_union_type_t)UINT8_C(9))
#define PBS_ifl_ReqBody_Signal ((PBS_ifl_ReqBody_union_type_t)UINT8_C(10))
#define PBS_ifl_ReqBody_Stat ((PBS_ifl_ReqBody_union_type_t)UINT8_C(11))
#define PBS_ifl_ReqBody_Track ((PBS_ifl_ReqBody_union_type_t)UINT8_C(12))
#define PBS_ifl_ReqBody_RescQuery ((PBS_ifl_ReqBody_union_type_t)UINT8_C(13))
#define PBS_ifl_ReqBody_Register ((PBS_ifl_ReqBody_union_type_t)UINT8_C(14))
#define PBS_ifl_ReqBody_CopyFile ((PBS_ifl_ReqBody_union_type_t)UINT8_C(15))
#define PBS_ifl_ReqBody_Cred ((PBS_ifl_ReqBody_union_type_t)UINT8_C(16))
#define PBS_ifl_ReqBody_CopyFileCred ((PBS_ifl_ReqBody_union_type_t)UINT8_C(17))
#define PBS_ifl_ReqBody_UserMigrate ((PBS_ifl_ReqBody_union_type_t)UINT8_C(18))
#define PBS_ifl_ReqBody_SchedDefRep ((PBS_ifl_ReqBody_union_type_t)UINT8_C(19))
#define PBS_ifl_ReqBody_Spawn ((PBS_ifl_ReqBody_union_type_t)UINT8_C(20))
#define PBS_ifl_ReqBody_CopyHook ((PBS_ifl_ReqBody_union_type_t)UINT8_C(21))
#define PBS_ifl_ReqBody_RelNodes ((PBS_ifl_ReqBody_union_type_t)UINT8_C(22))
#define PBS_ifl_ReqBody_Preempt ((PBS_ifl_ReqBody_union_type_t)UINT8_C(23))
#define PBS_ifl_ReqBody_Auth ((PBS_ifl_ReqBody_union_type_t)UINT8_C(24))

static inline const char *PBS_ifl_ReqBody_type_name(PBS_ifl_ReqBody_union_type_t type)
{
    switch (type) {
    case PBS_ifl_ReqBody_NONE: return "NONE";
    case PBS_ifl_ReqBody_Qjob: return "Qjob";
    case PBS_ifl_ReqBody_JobFile: return "JobFile";
    case PBS_ifl_ReqBody_JobId: return "JobId";
    case PBS_ifl_ReqBody_Manage: return "Manage";
    case PBS_ifl_ReqBody_Msg: return "Msg";
    case PBS_ifl_ReqBody_Move: return "Move";
    case PBS_ifl_ReqBody_Run: return "Run";
    case PBS_ifl_ReqBody_Select: return "Select";
    case PBS_ifl_ReqBody_DmnCmd: return "DmnCmd";
    case PBS_ifl_ReqBody_Signal: return "Signal";
    case PBS_ifl_ReqBody_Stat: return "Stat";
    case PBS_ifl_ReqBody_Track: return "Track";
    case PBS_ifl_ReqBody_RescQuery: return "RescQuery";
    case PBS_ifl_ReqBody_Register: return "Register";
    case PBS_ifl_ReqBody_CopyFile: return "CopyFile";
    case PBS_ifl_ReqBody_Cred: return "Cred";
    case PBS_ifl_ReqBody_CopyFileCred: return "CopyFileCred";
    case PBS_ifl_ReqBody_UserMigrate: return "UserMigrate";
    case PBS_ifl_ReqBody_SchedDefRep: return "SchedDefRep";
    case PBS_ifl_ReqBody_Spawn: return "Spawn";
    case PBS_ifl_ReqBody_CopyHook: return "CopyHook";
    case PBS_ifl_ReqBody_RelNodes: return "RelNodes";
    case PBS_ifl_ReqBody_Preempt: return "Preempt";
    case PBS_ifl_ReqBody_Auth: return "Auth";
    default: return "";
    }
}

static inline int PBS_ifl_ReqBody_is_known_type(PBS_ifl_ReqBody_union_type_t type)
{
    switch (type) {
    case PBS_ifl_ReqBody_NONE: return 1;
    case PBS_ifl_ReqBody_Qjob: return 1;
    case PBS_ifl_ReqBody_JobFile: return 1;
    case PBS_ifl_ReqBody_JobId: return 1;
    case PBS_ifl_ReqBody_Manage: return 1;
    case PBS_ifl_ReqBody_Msg: return 1;
    case PBS_ifl_ReqBody_Move: return 1;
    case PBS_ifl_ReqBody_Run: return 1;
    case PBS_ifl_ReqBody_Select: return 1;
    case PBS_ifl_ReqBody_DmnCmd: return 1;
    case PBS_ifl_ReqBody_Signal: return 1;
    case PBS_ifl_ReqBody_Stat: return 1;
    case PBS_ifl_ReqBody_Track: return 1;
    case PBS_ifl_ReqBody_RescQuery: return 1;
    case PBS_ifl_ReqBody_Register: return 1;
    case PBS_ifl_ReqBody_CopyFile: return 1;
    case PBS_ifl_ReqBody_Cred: return 1;
    case PBS_ifl_ReqBody_CopyFileCred: return 1;
    case PBS_ifl_ReqBody_UserMigrate: return 1;
    case PBS_ifl_ReqBody_SchedDefRep: return 1;
    case PBS_ifl_ReqBody_Spawn: return 1;
    case PBS_ifl_ReqBody_CopyHook: return 1;
    case PBS_ifl_ReqBody_RelNodes: return 1;
    case PBS_ifl_ReqBody_Preempt: return 1;
    case PBS_ifl_ReqBody_Auth: return 1;
    default: return 0;
    }
}


struct PBS_ifl_Req_table { uint8_t unused__; };

static inline size_t PBS_ifl_Req_vec_len(PBS_ifl_Req_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_Req_table_t PBS_ifl_Req_vec_at(PBS_ifl_Req_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_Req_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_Req)

__flatbuffers_define_table_field(0, PBS_ifl_Req, hdr, PBS_ifl_Header_table_t, 0)
__flatbuffers_define_union_field(flatbuffers_, 2, PBS_ifl_Req, body, PBS_ifl_ReqBody, 0)
__flatbuffers_define_string_field(3, PBS_ifl_Req, extend, 0)

struct PBS_ifl_TextResp_table { uint8_t unused__; };

static inline size_t PBS_ifl_TextResp_vec_len(PBS_ifl_TextResp_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_TextResp_table_t PBS_ifl_TextResp_vec_at(PBS_ifl_TextResp_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_TextResp_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_TextResp)

__flatbuffers_define_string_field(0, PBS_ifl_TextResp, txt, 0)

struct PBS_ifl_SelectResp_table { uint8_t unused__; };

static inline size_t PBS_ifl_SelectResp_vec_len(PBS_ifl_SelectResp_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_SelectResp_table_t PBS_ifl_SelectResp_vec_at(PBS_ifl_SelectResp_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_SelectResp_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_SelectResp)

__flatbuffers_define_vector_field(0, PBS_ifl_SelectResp, ids, flatbuffers_string_vec_t, 0)

struct PBS_ifl_StatRespStat_table { uint8_t unused__; };

static inline size_t PBS_ifl_StatRespStat_vec_len(PBS_ifl_StatRespStat_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_StatRespStat_table_t PBS_ifl_StatRespStat_vec_at(PBS_ifl_StatRespStat_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_StatRespStat_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_StatRespStat)

__flatbuffers_define_scalar_field(0, PBS_ifl_StatRespStat, type, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_string_field(1, PBS_ifl_StatRespStat, name, 0)
__flatbuffers_define_vector_field(2, PBS_ifl_StatRespStat, attrs, PBS_ifl_Attribute_vec_t, 0)

struct PBS_ifl_StatResp_table { uint8_t unused__; };

static inline size_t PBS_ifl_StatResp_vec_len(PBS_ifl_StatResp_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_StatResp_table_t PBS_ifl_StatResp_vec_at(PBS_ifl_StatResp_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_StatResp_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_StatResp)

__flatbuffers_define_vector_field(0, PBS_ifl_StatResp, stats, PBS_ifl_StatRespStat_vec_t, 0)

struct PBS_ifl_RescQueryRespInfo_table { uint8_t unused__; };

static inline size_t PBS_ifl_RescQueryRespInfo_vec_len(PBS_ifl_RescQueryRespInfo_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_RescQueryRespInfo_table_t PBS_ifl_RescQueryRespInfo_vec_at(PBS_ifl_RescQueryRespInfo_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_RescQueryRespInfo_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_RescQueryRespInfo)

__flatbuffers_define_scalar_field(0, PBS_ifl_RescQueryRespInfo, avail, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_scalar_field(1, PBS_ifl_RescQueryRespInfo, alloc, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_scalar_field(2, PBS_ifl_RescQueryRespInfo, resvd, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_scalar_field(3, PBS_ifl_RescQueryRespInfo, down, flatbuffers_int16, int16_t, INT16_C(0))

struct PBS_ifl_RescQueryResp_table { uint8_t unused__; };

static inline size_t PBS_ifl_RescQueryResp_vec_len(PBS_ifl_RescQueryResp_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_RescQueryResp_table_t PBS_ifl_RescQueryResp_vec_at(PBS_ifl_RescQueryResp_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_RescQueryResp_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_RescQueryResp)

__flatbuffers_define_vector_field(0, PBS_ifl_RescQueryResp, infos, PBS_ifl_RescQueryRespInfo_vec_t, 0)
typedef uint8_t PBS_ifl_RespBody_union_type_t;
__flatbuffers_define_integer_type(PBS_ifl_RespBody, PBS_ifl_RespBody_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, PBS_ifl_RespBody)
#define PBS_ifl_RespBody_NONE ((PBS_ifl_RespBody_union_type_t)UINT8_C(0))
#define PBS_ifl_RespBody_TextResp ((PBS_ifl_RespBody_union_type_t)UINT8_C(1))
#define PBS_ifl_RespBody_SelectResp ((PBS_ifl_RespBody_union_type_t)UINT8_C(2))
#define PBS_ifl_RespBody_StatResp ((PBS_ifl_RespBody_union_type_t)UINT8_C(3))
#define PBS_ifl_RespBody_RescQueryResp ((PBS_ifl_RespBody_union_type_t)UINT8_C(4))
#define PBS_ifl_RespBody_Preempt ((PBS_ifl_RespBody_union_type_t)UINT8_C(5))

static inline const char *PBS_ifl_RespBody_type_name(PBS_ifl_RespBody_union_type_t type)
{
    switch (type) {
    case PBS_ifl_RespBody_NONE: return "NONE";
    case PBS_ifl_RespBody_TextResp: return "TextResp";
    case PBS_ifl_RespBody_SelectResp: return "SelectResp";
    case PBS_ifl_RespBody_StatResp: return "StatResp";
    case PBS_ifl_RespBody_RescQueryResp: return "RescQueryResp";
    case PBS_ifl_RespBody_Preempt: return "Preempt";
    default: return "";
    }
}

static inline int PBS_ifl_RespBody_is_known_type(PBS_ifl_RespBody_union_type_t type)
{
    switch (type) {
    case PBS_ifl_RespBody_NONE: return 1;
    case PBS_ifl_RespBody_TextResp: return 1;
    case PBS_ifl_RespBody_SelectResp: return 1;
    case PBS_ifl_RespBody_StatResp: return 1;
    case PBS_ifl_RespBody_RescQueryResp: return 1;
    case PBS_ifl_RespBody_Preempt: return 1;
    default: return 0;
    }
}


struct PBS_ifl_Resp_table { uint8_t unused__; };

static inline size_t PBS_ifl_Resp_vec_len(PBS_ifl_Resp_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_Resp_table_t PBS_ifl_Resp_vec_at(PBS_ifl_Resp_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_Resp_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_Resp)

__flatbuffers_define_scalar_field(0, PBS_ifl_Resp, code, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_scalar_field(1, PBS_ifl_Resp, auxCode, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_scalar_field(2, PBS_ifl_Resp, choice, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_union_field(flatbuffers_, 4, PBS_ifl_Resp, body, PBS_ifl_RespBody, 0)

struct PBS_ifl_RmReq_table { uint8_t unused__; };

static inline size_t PBS_ifl_RmReq_vec_len(PBS_ifl_RmReq_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_RmReq_table_t PBS_ifl_RmReq_vec_at(PBS_ifl_RmReq_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_RmReq_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_RmReq)

__flatbuffers_define_table_field(0, PBS_ifl_RmReq, hdr, PBS_ifl_Header_table_t, 0)
__flatbuffers_define_vector_field(1, PBS_ifl_RmReq, data, flatbuffers_string_vec_t, 0)

struct PBS_ifl_RmResp_table { uint8_t unused__; };

static inline size_t PBS_ifl_RmResp_vec_len(PBS_ifl_RmResp_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_RmResp_table_t PBS_ifl_RmResp_vec_at(PBS_ifl_RmResp_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_RmResp_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_RmResp)

__flatbuffers_define_scalar_field(0, PBS_ifl_RmResp, code, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_vector_field(1, PBS_ifl_RmResp, data, flatbuffers_string_vec_t, 0)

struct PBS_ifl_TmAttach_table { uint8_t unused__; };

static inline size_t PBS_ifl_TmAttach_vec_len(PBS_ifl_TmAttach_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_TmAttach_table_t PBS_ifl_TmAttach_vec_at(PBS_ifl_TmAttach_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_TmAttach_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_TmAttach)

__flatbuffers_define_string_field(0, PBS_ifl_TmAttach, user, 0)
__flatbuffers_define_scalar_field(1, PBS_ifl_TmAttach, uid, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_scalar_field(2, PBS_ifl_TmAttach, pid, flatbuffers_int16, int16_t, INT16_C(0))

struct PBS_ifl_TmSpawn_table { uint8_t unused__; };

static inline size_t PBS_ifl_TmSpawn_vec_len(PBS_ifl_TmSpawn_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_TmSpawn_table_t PBS_ifl_TmSpawn_vec_at(PBS_ifl_TmSpawn_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_TmSpawn_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_TmSpawn)

__flatbuffers_define_scalar_field(0, PBS_ifl_TmSpawn, where, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_vector_field(1, PBS_ifl_TmSpawn, argv, flatbuffers_string_vec_t, 0)
__flatbuffers_define_vector_field(2, PBS_ifl_TmSpawn, envp, flatbuffers_string_vec_t, 0)

struct PBS_ifl_TmSignal_table { uint8_t unused__; };

static inline size_t PBS_ifl_TmSignal_vec_len(PBS_ifl_TmSignal_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_TmSignal_table_t PBS_ifl_TmSignal_vec_at(PBS_ifl_TmSignal_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_TmSignal_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_TmSignal)

__flatbuffers_define_scalar_field(0, PBS_ifl_TmSignal, nid, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_scalar_field(1, PBS_ifl_TmSignal, tid, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_scalar_field(2, PBS_ifl_TmSignal, sig, flatbuffers_int16, int16_t, INT16_C(0))

struct PBS_ifl_TmObit_table { uint8_t unused__; };

static inline size_t PBS_ifl_TmObit_vec_len(PBS_ifl_TmObit_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_TmObit_table_t PBS_ifl_TmObit_vec_at(PBS_ifl_TmObit_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_TmObit_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_TmObit)

__flatbuffers_define_scalar_field(0, PBS_ifl_TmObit, nid, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_scalar_field(1, PBS_ifl_TmObit, tid, flatbuffers_int16, int16_t, INT16_C(0))

struct PBS_ifl_TmInfo_table { uint8_t unused__; };

static inline size_t PBS_ifl_TmInfo_vec_len(PBS_ifl_TmInfo_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_TmInfo_table_t PBS_ifl_TmInfo_vec_at(PBS_ifl_TmInfo_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_TmInfo_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_TmInfo)

__flatbuffers_define_scalar_field(0, PBS_ifl_TmInfo, nid, flatbuffers_int16, int16_t, INT16_C(0))

struct PBS_ifl_TmPublish_table { uint8_t unused__; };

static inline size_t PBS_ifl_TmPublish_vec_len(PBS_ifl_TmPublish_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_TmPublish_table_t PBS_ifl_TmPublish_vec_at(PBS_ifl_TmPublish_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_TmPublish_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_TmPublish)

__flatbuffers_define_string_field(0, PBS_ifl_TmPublish, name, 0)
__flatbuffers_define_string_field(1, PBS_ifl_TmPublish, info, 0)

struct PBS_ifl_TmSubscribe_table { uint8_t unused__; };

static inline size_t PBS_ifl_TmSubscribe_vec_len(PBS_ifl_TmSubscribe_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_TmSubscribe_table_t PBS_ifl_TmSubscribe_vec_at(PBS_ifl_TmSubscribe_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_TmSubscribe_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_TmSubscribe)

__flatbuffers_define_scalar_field(0, PBS_ifl_TmSubscribe, nid, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_scalar_field(1, PBS_ifl_TmSubscribe, tid, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_string_field(2, PBS_ifl_TmSubscribe, name, 0)
typedef uint8_t PBS_ifl_TmBody_union_type_t;
__flatbuffers_define_integer_type(PBS_ifl_TmBody, PBS_ifl_TmBody_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, PBS_ifl_TmBody)
#define PBS_ifl_TmBody_NONE ((PBS_ifl_TmBody_union_type_t)UINT8_C(0))
#define PBS_ifl_TmBody_TmAttach ((PBS_ifl_TmBody_union_type_t)UINT8_C(1))
#define PBS_ifl_TmBody_TmSpawn ((PBS_ifl_TmBody_union_type_t)UINT8_C(2))
#define PBS_ifl_TmBody_TmSignal ((PBS_ifl_TmBody_union_type_t)UINT8_C(3))
#define PBS_ifl_TmBody_TmObit ((PBS_ifl_TmBody_union_type_t)UINT8_C(4))
#define PBS_ifl_TmBody_TmInfo ((PBS_ifl_TmBody_union_type_t)UINT8_C(5))
#define PBS_ifl_TmBody_TmPublish ((PBS_ifl_TmBody_union_type_t)UINT8_C(6))
#define PBS_ifl_TmBody_TmSubscribe ((PBS_ifl_TmBody_union_type_t)UINT8_C(7))

static inline const char *PBS_ifl_TmBody_type_name(PBS_ifl_TmBody_union_type_t type)
{
    switch (type) {
    case PBS_ifl_TmBody_NONE: return "NONE";
    case PBS_ifl_TmBody_TmAttach: return "TmAttach";
    case PBS_ifl_TmBody_TmSpawn: return "TmSpawn";
    case PBS_ifl_TmBody_TmSignal: return "TmSignal";
    case PBS_ifl_TmBody_TmObit: return "TmObit";
    case PBS_ifl_TmBody_TmInfo: return "TmInfo";
    case PBS_ifl_TmBody_TmPublish: return "TmPublish";
    case PBS_ifl_TmBody_TmSubscribe: return "TmSubscribe";
    default: return "";
    }
}

static inline int PBS_ifl_TmBody_is_known_type(PBS_ifl_TmBody_union_type_t type)
{
    switch (type) {
    case PBS_ifl_TmBody_NONE: return 1;
    case PBS_ifl_TmBody_TmAttach: return 1;
    case PBS_ifl_TmBody_TmSpawn: return 1;
    case PBS_ifl_TmBody_TmSignal: return 1;
    case PBS_ifl_TmBody_TmObit: return 1;
    case PBS_ifl_TmBody_TmInfo: return 1;
    case PBS_ifl_TmBody_TmPublish: return 1;
    case PBS_ifl_TmBody_TmSubscribe: return 1;
    default: return 0;
    }
}


struct PBS_ifl_TmReq_table { uint8_t unused__; };

static inline size_t PBS_ifl_TmReq_vec_len(PBS_ifl_TmReq_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PBS_ifl_TmReq_table_t PBS_ifl_TmReq_vec_at(PBS_ifl_TmReq_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PBS_ifl_TmReq_table_t, vec, i, 0)
__flatbuffers_table_as_root(PBS_ifl_TmReq)

__flatbuffers_define_table_field(0, PBS_ifl_TmReq, hdr, PBS_ifl_Header_table_t, 0)
__flatbuffers_define_string_field(1, PBS_ifl_TmReq, jobId, 0)
__flatbuffers_define_string_field(2, PBS_ifl_TmReq, cookie, 0)
__flatbuffers_define_scalar_field(3, PBS_ifl_TmReq, event, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_scalar_field(4, PBS_ifl_TmReq, jobTid, flatbuffers_int16, int16_t, INT16_C(0))
__flatbuffers_define_union_field(flatbuffers_, 6, PBS_ifl_TmReq, body, PBS_ifl_TmBody, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* PBS_IFL_READER_H */
