#ifndef PBS_IFL_VERIFIER_H
#define PBS_IFL_VERIFIER_H

/* Generated by flatcc 0.6.1-dev FlatBuffers schema compiler for C by dvide.com */

#ifndef PBS_IFL_READER_H
#include "pbs_ifl_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int PBS_ifl_Header_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Attribute_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Qjob_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_JobFile_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_JobId_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Manage_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Msg_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Move_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Run_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Select_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_DmnCmd_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Signal_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Stat_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Track_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_RescQuery_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Register_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_FilePair_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_CopyFile_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Cred_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_CopyFileCred_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_UserMigrate_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_SchedDefRep_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Spawn_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_CopyHook_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_RelNodes_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_PreemptJob_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Preempt_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Auth_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Req_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_TextResp_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_SelectResp_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_StatRespStat_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_StatResp_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_RescQueryRespInfo_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_RescQueryResp_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_Resp_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_IMJoin_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_IMSpawn_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_IMTasks_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_IMSignal_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_IMObit_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_IMInfo_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_IMGResc_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_IMSResc_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_IMUpdate_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_IMCred_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_IMRErr_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_IMRKill_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_IMRSpawn_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_IMRTasks_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_IMRObit_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_IMRInfo_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_IMRResc_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_IMRPoll_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_InterMoM_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_RmReq_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_RmResp_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_TmAttach_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_TmSpawn_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_TmSignal_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_TmObit_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_TmInfo_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_TmPublish_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_TmSubscribe_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PBS_ifl_TmReq_verify_table(flatcc_table_verifier_descriptor_t *td);

static int PBS_ifl_ReqBody_union_verifier(flatcc_union_verifier_descriptor_t *ud)
{
    switch (ud->type) {
    case 1: return flatcc_verify_union_table(ud, PBS_ifl_Qjob_verify_table); /* Qjob */
    case 2: return flatcc_verify_union_table(ud, PBS_ifl_JobFile_verify_table); /* JobFile */
    case 3: return flatcc_verify_union_table(ud, PBS_ifl_JobId_verify_table); /* JobId */
    case 4: return flatcc_verify_union_table(ud, PBS_ifl_Manage_verify_table); /* Manage */
    case 5: return flatcc_verify_union_table(ud, PBS_ifl_Msg_verify_table); /* Msg */
    case 6: return flatcc_verify_union_table(ud, PBS_ifl_Move_verify_table); /* Move */
    case 7: return flatcc_verify_union_table(ud, PBS_ifl_Run_verify_table); /* Run */
    case 8: return flatcc_verify_union_table(ud, PBS_ifl_Select_verify_table); /* Select */
    case 9: return flatcc_verify_union_table(ud, PBS_ifl_DmnCmd_verify_table); /* DmnCmd */
    case 10: return flatcc_verify_union_table(ud, PBS_ifl_Signal_verify_table); /* Signal */
    case 11: return flatcc_verify_union_table(ud, PBS_ifl_Stat_verify_table); /* Stat */
    case 12: return flatcc_verify_union_table(ud, PBS_ifl_Track_verify_table); /* Track */
    case 13: return flatcc_verify_union_table(ud, PBS_ifl_RescQuery_verify_table); /* RescQuery */
    case 14: return flatcc_verify_union_table(ud, PBS_ifl_Register_verify_table); /* Register */
    case 15: return flatcc_verify_union_table(ud, PBS_ifl_CopyFile_verify_table); /* CopyFile */
    case 16: return flatcc_verify_union_table(ud, PBS_ifl_Cred_verify_table); /* Cred */
    case 17: return flatcc_verify_union_table(ud, PBS_ifl_CopyFileCred_verify_table); /* CopyFileCred */
    case 18: return flatcc_verify_union_table(ud, PBS_ifl_UserMigrate_verify_table); /* UserMigrate */
    case 19: return flatcc_verify_union_table(ud, PBS_ifl_SchedDefRep_verify_table); /* SchedDefRep */
    case 20: return flatcc_verify_union_table(ud, PBS_ifl_Spawn_verify_table); /* Spawn */
    case 21: return flatcc_verify_union_table(ud, PBS_ifl_CopyHook_verify_table); /* CopyHook */
    case 22: return flatcc_verify_union_table(ud, PBS_ifl_RelNodes_verify_table); /* RelNodes */
    case 23: return flatcc_verify_union_table(ud, PBS_ifl_Preempt_verify_table); /* Preempt */
    case 24: return flatcc_verify_union_table(ud, PBS_ifl_Auth_verify_table); /* Auth */
    default: return flatcc_verify_ok;
    }
}

static int PBS_ifl_RespBody_union_verifier(flatcc_union_verifier_descriptor_t *ud)
{
    switch (ud->type) {
    case 1: return flatcc_verify_union_table(ud, PBS_ifl_TextResp_verify_table); /* TextResp */
    case 2: return flatcc_verify_union_table(ud, PBS_ifl_SelectResp_verify_table); /* SelectResp */
    case 3: return flatcc_verify_union_table(ud, PBS_ifl_StatResp_verify_table); /* StatResp */
    case 4: return flatcc_verify_union_table(ud, PBS_ifl_RescQueryResp_verify_table); /* RescQueryResp */
    case 5: return flatcc_verify_union_table(ud, PBS_ifl_Preempt_verify_table); /* Preempt */
    default: return flatcc_verify_ok;
    }
}

static int PBS_ifl_IMReq_union_verifier(flatcc_union_verifier_descriptor_t *ud)
{
    switch (ud->type) {
    case 1: return flatcc_verify_union_table(ud, PBS_ifl_IMJoin_verify_table); /* IMJoin */
    case 2: return flatcc_verify_union_table(ud, PBS_ifl_IMSpawn_verify_table); /* IMSpawn */
    case 3: return flatcc_verify_union_table(ud, PBS_ifl_IMTasks_verify_table); /* IMTasks */
    case 4: return flatcc_verify_union_table(ud, PBS_ifl_IMSignal_verify_table); /* IMSignal */
    case 5: return flatcc_verify_union_table(ud, PBS_ifl_IMObit_verify_table); /* IMObit */
    case 6: return flatcc_verify_union_table(ud, PBS_ifl_IMInfo_verify_table); /* IMInfo */
    case 7: return flatcc_verify_union_table(ud, PBS_ifl_IMGResc_verify_table); /* IMGResc */
    case 8: return flatcc_verify_union_table(ud, PBS_ifl_IMSResc_verify_table); /* IMSResc */
    case 9: return flatcc_verify_union_table(ud, PBS_ifl_IMUpdate_verify_table); /* IMUpdate */
    case 10: return flatcc_verify_union_table(ud, PBS_ifl_IMCred_verify_table); /* IMCred */
    default: return flatcc_verify_ok;
    }
}

static int PBS_ifl_IMReply_union_verifier(flatcc_union_verifier_descriptor_t *ud)
{
    switch (ud->type) {
    case 1: return flatcc_verify_union_table(ud, PBS_ifl_IMRErr_verify_table); /* IMRErr */
    case 2: return flatcc_verify_union_table(ud, PBS_ifl_IMRKill_verify_table); /* IMRKill */
    case 3: return flatcc_verify_union_table(ud, PBS_ifl_IMRSpawn_verify_table); /* IMRSpawn */
    case 4: return flatcc_verify_union_table(ud, PBS_ifl_IMRTasks_verify_table); /* IMRTasks */
    case 5: return flatcc_verify_union_table(ud, PBS_ifl_IMRObit_verify_table); /* IMRObit */
    case 6: return flatcc_verify_union_table(ud, PBS_ifl_IMRInfo_verify_table); /* IMRInfo */
    case 7: return flatcc_verify_union_table(ud, PBS_ifl_IMRResc_verify_table); /* IMRResc */
    case 8: return flatcc_verify_union_table(ud, PBS_ifl_IMRPoll_verify_table); /* IMRPoll */
    default: return flatcc_verify_ok;
    }
}

static int PBS_ifl_TmBody_union_verifier(flatcc_union_verifier_descriptor_t *ud)
{
    switch (ud->type) {
    case 1: return flatcc_verify_union_table(ud, PBS_ifl_TmAttach_verify_table); /* TmAttach */
    case 2: return flatcc_verify_union_table(ud, PBS_ifl_TmSpawn_verify_table); /* TmSpawn */
    case 3: return flatcc_verify_union_table(ud, PBS_ifl_TmSignal_verify_table); /* TmSignal */
    case 4: return flatcc_verify_union_table(ud, PBS_ifl_TmObit_verify_table); /* TmObit */
    case 5: return flatcc_verify_union_table(ud, PBS_ifl_TmInfo_verify_table); /* TmInfo */
    case 6: return flatcc_verify_union_table(ud, PBS_ifl_TmPublish_verify_table); /* TmPublish */
    case 7: return flatcc_verify_union_table(ud, PBS_ifl_TmSubscribe_verify_table); /* TmSubscribe */
    default: return flatcc_verify_ok;
    }
}

static int PBS_ifl_Header_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* protType */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 2, 2) /* version */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 2, 2) /* reqId */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 3, 0) /* user */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Header_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Header_identifier, &PBS_ifl_Header_verify_table);
}

static inline int PBS_ifl_Header_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Header_type_identifier, &PBS_ifl_Header_verify_table);
}

static inline int PBS_ifl_Header_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Header_verify_table);
}

static inline int PBS_ifl_Header_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Header_verify_table);
}

static int PBS_ifl_Attribute_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* name */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* resc */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* value */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 1, 1) /* op */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Attribute_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Attribute_identifier, &PBS_ifl_Attribute_verify_table);
}

static inline int PBS_ifl_Attribute_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Attribute_type_identifier, &PBS_ifl_Attribute_verify_table);
}

static inline int PBS_ifl_Attribute_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Attribute_verify_table);
}

static inline int PBS_ifl_Attribute_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Attribute_verify_table);
}

static int PBS_ifl_Qjob_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* jobId */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* destin */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 2, 0, &PBS_ifl_Attribute_verify_table) /* attrs */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Qjob_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Qjob_identifier, &PBS_ifl_Qjob_verify_table);
}

static inline int PBS_ifl_Qjob_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Qjob_type_identifier, &PBS_ifl_Qjob_verify_table);
}

static inline int PBS_ifl_Qjob_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Qjob_verify_table);
}

static inline int PBS_ifl_Qjob_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Qjob_verify_table);
}

static int PBS_ifl_JobFile_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 8, 8) /* seq */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 2, 2) /* type */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 8, 8) /* size */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 3, 0) /* jobId */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 4, 0) /* data */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_JobFile_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_JobFile_identifier, &PBS_ifl_JobFile_verify_table);
}

static inline int PBS_ifl_JobFile_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_JobFile_type_identifier, &PBS_ifl_JobFile_verify_table);
}

static inline int PBS_ifl_JobFile_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_JobFile_verify_table);
}

static inline int PBS_ifl_JobFile_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_JobFile_verify_table);
}

static int PBS_ifl_JobId_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* jobId */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_JobId_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_JobId_identifier, &PBS_ifl_JobId_verify_table);
}

static inline int PBS_ifl_JobId_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_JobId_type_identifier, &PBS_ifl_JobId_verify_table);
}

static inline int PBS_ifl_JobId_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_JobId_verify_table);
}

static inline int PBS_ifl_JobId_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_JobId_verify_table);
}

static int PBS_ifl_Manage_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* cmd */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 2, 2) /* objType */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* objName */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 3, 0, &PBS_ifl_Attribute_verify_table) /* attrs */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Manage_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Manage_identifier, &PBS_ifl_Manage_verify_table);
}

static inline int PBS_ifl_Manage_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Manage_type_identifier, &PBS_ifl_Manage_verify_table);
}

static inline int PBS_ifl_Manage_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Manage_verify_table);
}

static inline int PBS_ifl_Manage_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Manage_verify_table);
}

static int PBS_ifl_Msg_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* fileInd */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* jobId */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* text */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Msg_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Msg_identifier, &PBS_ifl_Msg_verify_table);
}

static inline int PBS_ifl_Msg_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Msg_type_identifier, &PBS_ifl_Msg_verify_table);
}

static inline int PBS_ifl_Msg_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Msg_verify_table);
}

static inline int PBS_ifl_Msg_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Msg_verify_table);
}

static int PBS_ifl_Move_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* jobId */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* dest */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Move_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Move_identifier, &PBS_ifl_Move_verify_table);
}

static inline int PBS_ifl_Move_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Move_type_identifier, &PBS_ifl_Move_verify_table);
}

static inline int PBS_ifl_Move_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Move_verify_table);
}

static inline int PBS_ifl_Move_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Move_verify_table);
}

static int PBS_ifl_Run_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* jobId */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* dest */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 8, 8) /* resch */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Run_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Run_identifier, &PBS_ifl_Run_verify_table);
}

static inline int PBS_ifl_Run_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Run_type_identifier, &PBS_ifl_Run_verify_table);
}

static inline int PBS_ifl_Run_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Run_verify_table);
}

static inline int PBS_ifl_Run_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Run_verify_table);
}

static int PBS_ifl_Select_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_vector_field(td, 0, 0, &PBS_ifl_Attribute_verify_table) /* selAttrs */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 1, 0, &PBS_ifl_Attribute_verify_table) /* rtnAttrs */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Select_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Select_identifier, &PBS_ifl_Select_verify_table);
}

static inline int PBS_ifl_Select_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Select_type_identifier, &PBS_ifl_Select_verify_table);
}

static inline int PBS_ifl_Select_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Select_verify_table);
}

static inline int PBS_ifl_Select_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Select_verify_table);
}

static int PBS_ifl_DmnCmd_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* cmd */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_DmnCmd_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_DmnCmd_identifier, &PBS_ifl_DmnCmd_verify_table);
}

static inline int PBS_ifl_DmnCmd_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_DmnCmd_type_identifier, &PBS_ifl_DmnCmd_verify_table);
}

static inline int PBS_ifl_DmnCmd_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_DmnCmd_verify_table);
}

static inline int PBS_ifl_DmnCmd_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_DmnCmd_verify_table);
}

static int PBS_ifl_Signal_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* jobId */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* sigName */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Signal_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Signal_identifier, &PBS_ifl_Signal_verify_table);
}

static inline int PBS_ifl_Signal_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Signal_type_identifier, &PBS_ifl_Signal_verify_table);
}

static inline int PBS_ifl_Signal_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Signal_verify_table);
}

static inline int PBS_ifl_Signal_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Signal_verify_table);
}

static int PBS_ifl_Stat_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* jobIds */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 1, 0, &PBS_ifl_Attribute_verify_table) /* attrs */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Stat_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Stat_identifier, &PBS_ifl_Stat_verify_table);
}

static inline int PBS_ifl_Stat_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Stat_type_identifier, &PBS_ifl_Stat_verify_table);
}

static inline int PBS_ifl_Stat_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Stat_verify_table);
}

static inline int PBS_ifl_Stat_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Stat_verify_table);
}

static int PBS_ifl_Track_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* hops */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* jobId */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* location */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 1, 1) /* state */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Track_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Track_identifier, &PBS_ifl_Track_verify_table);
}

static inline int PBS_ifl_Track_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Track_type_identifier, &PBS_ifl_Track_verify_table);
}

static inline int PBS_ifl_Track_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Track_verify_table);
}

static inline int PBS_ifl_Track_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Track_verify_table);
}

static int PBS_ifl_RescQuery_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* handle */)) return ret;
    if ((ret = flatcc_verify_string_vector_field(td, 1, 0) /* queries */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_RescQuery_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_RescQuery_identifier, &PBS_ifl_RescQuery_verify_table);
}

static inline int PBS_ifl_RescQuery_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_RescQuery_type_identifier, &PBS_ifl_RescQuery_verify_table);
}

static inline int PBS_ifl_RescQuery_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_RescQuery_verify_table);
}

static inline int PBS_ifl_RescQuery_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_RescQuery_verify_table);
}

static int PBS_ifl_Register_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* owner */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* parent */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* child */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 2, 2) /* type */)) return ret;
    if ((ret = flatcc_verify_field(td, 4, 2, 2) /* op */)) return ret;
    if ((ret = flatcc_verify_field(td, 5, 8, 8) /* cost */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Register_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Register_identifier, &PBS_ifl_Register_verify_table);
}

static inline int PBS_ifl_Register_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Register_type_identifier, &PBS_ifl_Register_verify_table);
}

static inline int PBS_ifl_Register_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Register_verify_table);
}

static inline int PBS_ifl_Register_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Register_verify_table);
}

static int PBS_ifl_FilePair_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* local */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* remote */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 2, 2) /* flag */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_FilePair_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_FilePair_identifier, &PBS_ifl_FilePair_verify_table);
}

static inline int PBS_ifl_FilePair_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_FilePair_type_identifier, &PBS_ifl_FilePair_verify_table);
}

static inline int PBS_ifl_FilePair_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_FilePair_verify_table);
}

static inline int PBS_ifl_FilePair_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_FilePair_verify_table);
}

static int PBS_ifl_CopyFile_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* jobId */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* owner */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* user */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 3, 0) /* group */)) return ret;
    if ((ret = flatcc_verify_field(td, 4, 2, 2) /* flags */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 5, 0, &PBS_ifl_FilePair_verify_table) /* pairs */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_CopyFile_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_CopyFile_identifier, &PBS_ifl_CopyFile_verify_table);
}

static inline int PBS_ifl_CopyFile_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_CopyFile_type_identifier, &PBS_ifl_CopyFile_verify_table);
}

static inline int PBS_ifl_CopyFile_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_CopyFile_verify_table);
}

static inline int PBS_ifl_CopyFile_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_CopyFile_verify_table);
}

static int PBS_ifl_Cred_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* jobId */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* user */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 8, 8) /* validity */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 2, 2) /* type */)) return ret;
    if ((ret = flatcc_verify_field(td, 4, 2, 2) /* size */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 5, 0) /* data */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Cred_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Cred_identifier, &PBS_ifl_Cred_verify_table);
}

static inline int PBS_ifl_Cred_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Cred_type_identifier, &PBS_ifl_Cred_verify_table);
}

static inline int PBS_ifl_Cred_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Cred_verify_table);
}

static inline int PBS_ifl_Cred_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Cred_verify_table);
}

static int PBS_ifl_CopyFileCred_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_field(td, 0, 0, &PBS_ifl_CopyFile_verify_table) /* files */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 2, 2) /* type */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* cred */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_CopyFileCred_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_CopyFileCred_identifier, &PBS_ifl_CopyFileCred_verify_table);
}

static inline int PBS_ifl_CopyFileCred_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_CopyFileCred_type_identifier, &PBS_ifl_CopyFileCred_verify_table);
}

static inline int PBS_ifl_CopyFileCred_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_CopyFileCred_verify_table);
}

static inline int PBS_ifl_CopyFileCred_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_CopyFileCred_verify_table);
}

static int PBS_ifl_UserMigrate_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* tohost */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_UserMigrate_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_UserMigrate_identifier, &PBS_ifl_UserMigrate_verify_table);
}

static inline int PBS_ifl_UserMigrate_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_UserMigrate_type_identifier, &PBS_ifl_UserMigrate_verify_table);
}

static inline int PBS_ifl_UserMigrate_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_UserMigrate_verify_table);
}

static inline int PBS_ifl_UserMigrate_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_UserMigrate_verify_table);
}

static int PBS_ifl_SchedDefRep_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* cmd */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* id */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 2, 2) /* err */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 3, 0) /* text */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_SchedDefRep_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_SchedDefRep_identifier, &PBS_ifl_SchedDefRep_verify_table);
}

static inline int PBS_ifl_SchedDefRep_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_SchedDefRep_type_identifier, &PBS_ifl_SchedDefRep_verify_table);
}

static inline int PBS_ifl_SchedDefRep_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_SchedDefRep_verify_table);
}

static inline int PBS_ifl_SchedDefRep_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_SchedDefRep_verify_table);
}

static int PBS_ifl_Spawn_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* jobId */)) return ret;
    if ((ret = flatcc_verify_string_vector_field(td, 1, 0) /* argv */)) return ret;
    if ((ret = flatcc_verify_string_vector_field(td, 2, 0) /* envp */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Spawn_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Spawn_identifier, &PBS_ifl_Spawn_verify_table);
}

static inline int PBS_ifl_Spawn_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Spawn_type_identifier, &PBS_ifl_Spawn_verify_table);
}

static inline int PBS_ifl_Spawn_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Spawn_verify_table);
}

static inline int PBS_ifl_Spawn_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Spawn_verify_table);
}

static int PBS_ifl_CopyHook_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* seq */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 8, 8) /* size */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* filename */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 3, 0) /* data */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_CopyHook_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_CopyHook_identifier, &PBS_ifl_CopyHook_verify_table);
}

static inline int PBS_ifl_CopyHook_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_CopyHook_type_identifier, &PBS_ifl_CopyHook_verify_table);
}

static inline int PBS_ifl_CopyHook_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_CopyHook_verify_table);
}

static inline int PBS_ifl_CopyHook_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_CopyHook_verify_table);
}

static int PBS_ifl_RelNodes_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* jobId */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* nodes */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_RelNodes_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_RelNodes_identifier, &PBS_ifl_RelNodes_verify_table);
}

static inline int PBS_ifl_RelNodes_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_RelNodes_type_identifier, &PBS_ifl_RelNodes_verify_table);
}

static inline int PBS_ifl_RelNodes_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_RelNodes_verify_table);
}

static inline int PBS_ifl_RelNodes_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_RelNodes_verify_table);
}

static int PBS_ifl_PreemptJob_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* jid */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* order */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_PreemptJob_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_PreemptJob_identifier, &PBS_ifl_PreemptJob_verify_table);
}

static inline int PBS_ifl_PreemptJob_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_PreemptJob_type_identifier, &PBS_ifl_PreemptJob_verify_table);
}

static inline int PBS_ifl_PreemptJob_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_PreemptJob_verify_table);
}

static inline int PBS_ifl_PreemptJob_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_PreemptJob_verify_table);
}

static int PBS_ifl_Preempt_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_vector_field(td, 0, 0, &PBS_ifl_PreemptJob_verify_table) /* infos */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Preempt_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Preempt_identifier, &PBS_ifl_Preempt_verify_table);
}

static inline int PBS_ifl_Preempt_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Preempt_type_identifier, &PBS_ifl_Preempt_verify_table);
}

static inline int PBS_ifl_Preempt_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Preempt_verify_table);
}

static inline int PBS_ifl_Preempt_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Preempt_verify_table);
}

static int PBS_ifl_Auth_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* authMethod */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* encryptMethod */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 2, 2) /* encryptMode */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 2, 2) /* port */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Auth_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Auth_identifier, &PBS_ifl_Auth_verify_table);
}

static inline int PBS_ifl_Auth_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Auth_type_identifier, &PBS_ifl_Auth_verify_table);
}

static inline int PBS_ifl_Auth_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Auth_verify_table);
}

static inline int PBS_ifl_Auth_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Auth_verify_table);
}

static int PBS_ifl_Req_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_field(td, 0, 0, &PBS_ifl_Header_verify_table) /* hdr */)) return ret;
    if ((ret = flatcc_verify_union_field(td, 2, 0, &PBS_ifl_ReqBody_union_verifier) /* body */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 3, 0) /* extend */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Req_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Req_identifier, &PBS_ifl_Req_verify_table);
}

static inline int PBS_ifl_Req_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Req_type_identifier, &PBS_ifl_Req_verify_table);
}

static inline int PBS_ifl_Req_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Req_verify_table);
}

static inline int PBS_ifl_Req_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Req_verify_table);
}

static int PBS_ifl_TextResp_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* txt */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_TextResp_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_TextResp_identifier, &PBS_ifl_TextResp_verify_table);
}

static inline int PBS_ifl_TextResp_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_TextResp_type_identifier, &PBS_ifl_TextResp_verify_table);
}

static inline int PBS_ifl_TextResp_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_TextResp_verify_table);
}

static inline int PBS_ifl_TextResp_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_TextResp_verify_table);
}

static int PBS_ifl_SelectResp_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_vector_field(td, 0, 0) /* ids */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_SelectResp_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_SelectResp_identifier, &PBS_ifl_SelectResp_verify_table);
}

static inline int PBS_ifl_SelectResp_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_SelectResp_type_identifier, &PBS_ifl_SelectResp_verify_table);
}

static inline int PBS_ifl_SelectResp_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_SelectResp_verify_table);
}

static inline int PBS_ifl_SelectResp_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_SelectResp_verify_table);
}

static int PBS_ifl_StatRespStat_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* type */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* name */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 2, 0, &PBS_ifl_Attribute_verify_table) /* attrs */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_StatRespStat_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_StatRespStat_identifier, &PBS_ifl_StatRespStat_verify_table);
}

static inline int PBS_ifl_StatRespStat_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_StatRespStat_type_identifier, &PBS_ifl_StatRespStat_verify_table);
}

static inline int PBS_ifl_StatRespStat_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_StatRespStat_verify_table);
}

static inline int PBS_ifl_StatRespStat_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_StatRespStat_verify_table);
}

static int PBS_ifl_StatResp_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_vector_field(td, 0, 0, &PBS_ifl_StatRespStat_verify_table) /* stats */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_StatResp_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_StatResp_identifier, &PBS_ifl_StatResp_verify_table);
}

static inline int PBS_ifl_StatResp_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_StatResp_type_identifier, &PBS_ifl_StatResp_verify_table);
}

static inline int PBS_ifl_StatResp_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_StatResp_verify_table);
}

static inline int PBS_ifl_StatResp_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_StatResp_verify_table);
}

static int PBS_ifl_RescQueryRespInfo_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* avail */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 2, 2) /* alloc */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 2, 2) /* resvd */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 2, 2) /* down */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_RescQueryRespInfo_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_RescQueryRespInfo_identifier, &PBS_ifl_RescQueryRespInfo_verify_table);
}

static inline int PBS_ifl_RescQueryRespInfo_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_RescQueryRespInfo_type_identifier, &PBS_ifl_RescQueryRespInfo_verify_table);
}

static inline int PBS_ifl_RescQueryRespInfo_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_RescQueryRespInfo_verify_table);
}

static inline int PBS_ifl_RescQueryRespInfo_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_RescQueryRespInfo_verify_table);
}

static int PBS_ifl_RescQueryResp_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_vector_field(td, 0, 0, &PBS_ifl_RescQueryRespInfo_verify_table) /* infos */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_RescQueryResp_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_RescQueryResp_identifier, &PBS_ifl_RescQueryResp_verify_table);
}

static inline int PBS_ifl_RescQueryResp_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_RescQueryResp_type_identifier, &PBS_ifl_RescQueryResp_verify_table);
}

static inline int PBS_ifl_RescQueryResp_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_RescQueryResp_verify_table);
}

static inline int PBS_ifl_RescQueryResp_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_RescQueryResp_verify_table);
}

static int PBS_ifl_Resp_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* code */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 2, 2) /* auxCode */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 2, 2) /* choice */)) return ret;
    if ((ret = flatcc_verify_union_field(td, 4, 0, &PBS_ifl_RespBody_union_verifier) /* body */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_Resp_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Resp_identifier, &PBS_ifl_Resp_verify_table);
}

static inline int PBS_ifl_Resp_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_Resp_type_identifier, &PBS_ifl_Resp_verify_table);
}

static inline int PBS_ifl_Resp_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_Resp_verify_table);
}

static inline int PBS_ifl_Resp_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_Resp_verify_table);
}

static int PBS_ifl_IMJoin_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* nodeNum */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 2, 2) /* stdOut */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 2, 2) /* stdErr */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 2, 2) /* credType */)) return ret;
    if ((ret = flatcc_verify_field(td, 4, 2, 2) /* credLen */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 5, 0) /* cred */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 6, 0, &PBS_ifl_Attribute_verify_table) /* attrs */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_IMJoin_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMJoin_identifier, &PBS_ifl_IMJoin_verify_table);
}

static inline int PBS_ifl_IMJoin_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMJoin_type_identifier, &PBS_ifl_IMJoin_verify_table);
}

static inline int PBS_ifl_IMJoin_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_IMJoin_verify_table);
}

static inline int PBS_ifl_IMJoin_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_IMJoin_verify_table);
}

static int PBS_ifl_IMSpawn_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* pvnodeId */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 2, 2) /* tvnodeId */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 2, 2) /* taskId */)) return ret;
    if ((ret = flatcc_verify_string_vector_field(td, 3, 0) /* argv */)) return ret;
    if ((ret = flatcc_verify_string_vector_field(td, 4, 0) /* envp */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_IMSpawn_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMSpawn_identifier, &PBS_ifl_IMSpawn_verify_table);
}

static inline int PBS_ifl_IMSpawn_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMSpawn_type_identifier, &PBS_ifl_IMSpawn_verify_table);
}

static inline int PBS_ifl_IMSpawn_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_IMSpawn_verify_table);
}

static inline int PBS_ifl_IMSpawn_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_IMSpawn_verify_table);
}

static int PBS_ifl_IMTasks_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* pvnodeId */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 2, 2) /* tvnodeId */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_IMTasks_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMTasks_identifier, &PBS_ifl_IMTasks_verify_table);
}

static inline int PBS_ifl_IMTasks_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMTasks_type_identifier, &PBS_ifl_IMTasks_verify_table);
}

static inline int PBS_ifl_IMTasks_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_IMTasks_verify_table);
}

static inline int PBS_ifl_IMTasks_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_IMTasks_verify_table);
}

static int PBS_ifl_IMSignal_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* pvnodeId */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 2, 2) /* taskId */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 2, 2) /* sigNum */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_IMSignal_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMSignal_identifier, &PBS_ifl_IMSignal_verify_table);
}

static inline int PBS_ifl_IMSignal_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMSignal_type_identifier, &PBS_ifl_IMSignal_verify_table);
}

static inline int PBS_ifl_IMSignal_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_IMSignal_verify_table);
}

static inline int PBS_ifl_IMSignal_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_IMSignal_verify_table);
}

static int PBS_ifl_IMObit_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* pvnodeId */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 2, 2) /* taskId */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_IMObit_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMObit_identifier, &PBS_ifl_IMObit_verify_table);
}

static inline int PBS_ifl_IMObit_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMObit_type_identifier, &PBS_ifl_IMObit_verify_table);
}

static inline int PBS_ifl_IMObit_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_IMObit_verify_table);
}

static inline int PBS_ifl_IMObit_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_IMObit_verify_table);
}

static int PBS_ifl_IMInfo_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* pvnodeId */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 2, 2) /* taskId */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* name */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_IMInfo_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMInfo_identifier, &PBS_ifl_IMInfo_verify_table);
}

static inline int PBS_ifl_IMInfo_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMInfo_type_identifier, &PBS_ifl_IMInfo_verify_table);
}

static inline int PBS_ifl_IMInfo_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_IMInfo_verify_table);
}

static inline int PBS_ifl_IMInfo_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_IMInfo_verify_table);
}

static int PBS_ifl_IMGResc_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* pvnodeId */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_IMGResc_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMGResc_identifier, &PBS_ifl_IMGResc_verify_table);
}

static inline int PBS_ifl_IMGResc_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMGResc_type_identifier, &PBS_ifl_IMGResc_verify_table);
}

static inline int PBS_ifl_IMGResc_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_IMGResc_verify_table);
}

static inline int PBS_ifl_IMGResc_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_IMGResc_verify_table);
}

static int PBS_ifl_IMSResc_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* node */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 8, 8) /* cput */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 8, 8) /* mem */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 8, 8) /* cpupercent */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_IMSResc_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMSResc_identifier, &PBS_ifl_IMSResc_verify_table);
}

static inline int PBS_ifl_IMSResc_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMSResc_type_identifier, &PBS_ifl_IMSResc_verify_table);
}

static inline int PBS_ifl_IMSResc_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_IMSResc_verify_table);
}

static inline int PBS_ifl_IMSResc_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_IMSResc_verify_table);
}

static int PBS_ifl_IMUpdate_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_vector_field(td, 0, 0, &PBS_ifl_Attribute_verify_table) /* attrs */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_IMUpdate_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMUpdate_identifier, &PBS_ifl_IMUpdate_verify_table);
}

static inline int PBS_ifl_IMUpdate_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMUpdate_type_identifier, &PBS_ifl_IMUpdate_verify_table);
}

static inline int PBS_ifl_IMUpdate_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_IMUpdate_verify_table);
}

static inline int PBS_ifl_IMUpdate_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_IMUpdate_verify_table);
}

static int PBS_ifl_IMCred_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* type */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* cred */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 8, 8) /* validity */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_IMCred_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMCred_identifier, &PBS_ifl_IMCred_verify_table);
}

static inline int PBS_ifl_IMCred_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMCred_type_identifier, &PBS_ifl_IMCred_verify_table);
}

static inline int PBS_ifl_IMCred_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_IMCred_verify_table);
}

static inline int PBS_ifl_IMCred_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_IMCred_verify_table);
}

static int PBS_ifl_IMRErr_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* errcode */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* errmsg */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_IMRErr_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMRErr_identifier, &PBS_ifl_IMRErr_verify_table);
}

static inline int PBS_ifl_IMRErr_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMRErr_type_identifier, &PBS_ifl_IMRErr_verify_table);
}

static inline int PBS_ifl_IMRErr_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_IMRErr_verify_table);
}

static inline int PBS_ifl_IMRErr_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_IMRErr_verify_table);
}

static int PBS_ifl_IMRKill_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 8, 8) /* cput */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 8, 8) /* mem */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 8, 8) /* cpupercent */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 3, 0, &PBS_ifl_Attribute_verify_table) /* attrs */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_IMRKill_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMRKill_identifier, &PBS_ifl_IMRKill_verify_table);
}

static inline int PBS_ifl_IMRKill_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMRKill_type_identifier, &PBS_ifl_IMRKill_verify_table);
}

static inline int PBS_ifl_IMRKill_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_IMRKill_verify_table);
}

static inline int PBS_ifl_IMRKill_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_IMRKill_verify_table);
}

static int PBS_ifl_IMRSpawn_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* taskId */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_IMRSpawn_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMRSpawn_identifier, &PBS_ifl_IMRSpawn_verify_table);
}

static inline int PBS_ifl_IMRSpawn_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMRSpawn_type_identifier, &PBS_ifl_IMRSpawn_verify_table);
}

static inline int PBS_ifl_IMRSpawn_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_IMRSpawn_verify_table);
}

static inline int PBS_ifl_IMRSpawn_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_IMRSpawn_verify_table);
}

static int PBS_ifl_IMRTasks_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_vector_field(td, 0, 0, 2, 2, INT64_C(2147483647)) /* taskIds */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_IMRTasks_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMRTasks_identifier, &PBS_ifl_IMRTasks_verify_table);
}

static inline int PBS_ifl_IMRTasks_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMRTasks_type_identifier, &PBS_ifl_IMRTasks_verify_table);
}

static inline int PBS_ifl_IMRTasks_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_IMRTasks_verify_table);
}

static inline int PBS_ifl_IMRTasks_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_IMRTasks_verify_table);
}

static int PBS_ifl_IMRObit_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* exitval */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_IMRObit_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMRObit_identifier, &PBS_ifl_IMRObit_verify_table);
}

static inline int PBS_ifl_IMRObit_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMRObit_type_identifier, &PBS_ifl_IMRObit_verify_table);
}

static inline int PBS_ifl_IMRObit_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_IMRObit_verify_table);
}

static inline int PBS_ifl_IMRObit_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_IMRObit_verify_table);
}

static int PBS_ifl_IMRInfo_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_vector_field(td, 0, 0) /* infos */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_IMRInfo_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMRInfo_identifier, &PBS_ifl_IMRInfo_verify_table);
}

static inline int PBS_ifl_IMRInfo_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMRInfo_type_identifier, &PBS_ifl_IMRInfo_verify_table);
}

static inline int PBS_ifl_IMRInfo_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_IMRInfo_verify_table);
}

static inline int PBS_ifl_IMRInfo_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_IMRInfo_verify_table);
}

static int PBS_ifl_IMRResc_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* info */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_IMRResc_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMRResc_identifier, &PBS_ifl_IMRResc_verify_table);
}

static inline int PBS_ifl_IMRResc_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMRResc_type_identifier, &PBS_ifl_IMRResc_verify_table);
}

static inline int PBS_ifl_IMRResc_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_IMRResc_verify_table);
}

static inline int PBS_ifl_IMRResc_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_IMRResc_verify_table);
}

static int PBS_ifl_IMRPoll_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* exitval */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 8, 8) /* cput */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 8, 8) /* mem */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 8, 8) /* cpupercent */)) return ret;
    if ((ret = flatcc_verify_table_vector_field(td, 4, 0, &PBS_ifl_Attribute_verify_table) /* attrs */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_IMRPoll_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMRPoll_identifier, &PBS_ifl_IMRPoll_verify_table);
}

static inline int PBS_ifl_IMRPoll_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_IMRPoll_type_identifier, &PBS_ifl_IMRPoll_verify_table);
}

static inline int PBS_ifl_IMRPoll_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_IMRPoll_verify_table);
}

static inline int PBS_ifl_IMRPoll_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_IMRPoll_verify_table);
}

static int PBS_ifl_InterMoM_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* jobId */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* cookie */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 2, 2) /* cmd */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 2, 2) /* event */)) return ret;
    if ((ret = flatcc_verify_field(td, 4, 2, 2) /* fromTask */)) return ret;
    if ((ret = flatcc_verify_union_field(td, 6, 0, &PBS_ifl_IMReq_union_verifier) /* req */)) return ret;
    if ((ret = flatcc_verify_union_field(td, 8, 0, &PBS_ifl_IMReply_union_verifier) /* reply */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_InterMoM_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_InterMoM_identifier, &PBS_ifl_InterMoM_verify_table);
}

static inline int PBS_ifl_InterMoM_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_InterMoM_type_identifier, &PBS_ifl_InterMoM_verify_table);
}

static inline int PBS_ifl_InterMoM_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_InterMoM_verify_table);
}

static inline int PBS_ifl_InterMoM_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_InterMoM_verify_table);
}

static int PBS_ifl_RmReq_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_field(td, 0, 0, &PBS_ifl_Header_verify_table) /* hdr */)) return ret;
    if ((ret = flatcc_verify_string_vector_field(td, 1, 0) /* data */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_RmReq_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_RmReq_identifier, &PBS_ifl_RmReq_verify_table);
}

static inline int PBS_ifl_RmReq_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_RmReq_type_identifier, &PBS_ifl_RmReq_verify_table);
}

static inline int PBS_ifl_RmReq_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_RmReq_verify_table);
}

static inline int PBS_ifl_RmReq_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_RmReq_verify_table);
}

static int PBS_ifl_RmResp_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* code */)) return ret;
    if ((ret = flatcc_verify_string_vector_field(td, 1, 0) /* data */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_RmResp_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_RmResp_identifier, &PBS_ifl_RmResp_verify_table);
}

static inline int PBS_ifl_RmResp_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_RmResp_type_identifier, &PBS_ifl_RmResp_verify_table);
}

static inline int PBS_ifl_RmResp_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_RmResp_verify_table);
}

static inline int PBS_ifl_RmResp_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_RmResp_verify_table);
}

static int PBS_ifl_TmAttach_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* user */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 2, 2) /* uid */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 2, 2) /* pid */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_TmAttach_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_TmAttach_identifier, &PBS_ifl_TmAttach_verify_table);
}

static inline int PBS_ifl_TmAttach_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_TmAttach_type_identifier, &PBS_ifl_TmAttach_verify_table);
}

static inline int PBS_ifl_TmAttach_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_TmAttach_verify_table);
}

static inline int PBS_ifl_TmAttach_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_TmAttach_verify_table);
}

static int PBS_ifl_TmSpawn_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* where */)) return ret;
    if ((ret = flatcc_verify_string_vector_field(td, 1, 0) /* argv */)) return ret;
    if ((ret = flatcc_verify_string_vector_field(td, 2, 0) /* envp */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_TmSpawn_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_TmSpawn_identifier, &PBS_ifl_TmSpawn_verify_table);
}

static inline int PBS_ifl_TmSpawn_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_TmSpawn_type_identifier, &PBS_ifl_TmSpawn_verify_table);
}

static inline int PBS_ifl_TmSpawn_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_TmSpawn_verify_table);
}

static inline int PBS_ifl_TmSpawn_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_TmSpawn_verify_table);
}

static int PBS_ifl_TmSignal_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* nid */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 2, 2) /* tid */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 2, 2) /* sig */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_TmSignal_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_TmSignal_identifier, &PBS_ifl_TmSignal_verify_table);
}

static inline int PBS_ifl_TmSignal_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_TmSignal_type_identifier, &PBS_ifl_TmSignal_verify_table);
}

static inline int PBS_ifl_TmSignal_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_TmSignal_verify_table);
}

static inline int PBS_ifl_TmSignal_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_TmSignal_verify_table);
}

static int PBS_ifl_TmObit_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* nid */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 2, 2) /* tid */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_TmObit_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_TmObit_identifier, &PBS_ifl_TmObit_verify_table);
}

static inline int PBS_ifl_TmObit_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_TmObit_type_identifier, &PBS_ifl_TmObit_verify_table);
}

static inline int PBS_ifl_TmObit_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_TmObit_verify_table);
}

static inline int PBS_ifl_TmObit_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_TmObit_verify_table);
}

static int PBS_ifl_TmInfo_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* nid */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_TmInfo_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_TmInfo_identifier, &PBS_ifl_TmInfo_verify_table);
}

static inline int PBS_ifl_TmInfo_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_TmInfo_type_identifier, &PBS_ifl_TmInfo_verify_table);
}

static inline int PBS_ifl_TmInfo_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_TmInfo_verify_table);
}

static inline int PBS_ifl_TmInfo_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_TmInfo_verify_table);
}

static int PBS_ifl_TmPublish_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* name */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* info */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_TmPublish_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_TmPublish_identifier, &PBS_ifl_TmPublish_verify_table);
}

static inline int PBS_ifl_TmPublish_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_TmPublish_type_identifier, &PBS_ifl_TmPublish_verify_table);
}

static inline int PBS_ifl_TmPublish_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_TmPublish_verify_table);
}

static inline int PBS_ifl_TmPublish_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_TmPublish_verify_table);
}

static int PBS_ifl_TmSubscribe_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 2, 2) /* nid */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 2, 2) /* tid */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* name */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_TmSubscribe_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_TmSubscribe_identifier, &PBS_ifl_TmSubscribe_verify_table);
}

static inline int PBS_ifl_TmSubscribe_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_TmSubscribe_type_identifier, &PBS_ifl_TmSubscribe_verify_table);
}

static inline int PBS_ifl_TmSubscribe_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_TmSubscribe_verify_table);
}

static inline int PBS_ifl_TmSubscribe_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_TmSubscribe_verify_table);
}

static int PBS_ifl_TmReq_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_field(td, 0, 0, &PBS_ifl_Header_verify_table) /* hdr */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* jobId */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* cookie */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 2, 2) /* event */)) return ret;
    if ((ret = flatcc_verify_field(td, 4, 2, 2) /* jobTid */)) return ret;
    if ((ret = flatcc_verify_union_field(td, 6, 0, &PBS_ifl_TmBody_union_verifier) /* body */)) return ret;
    return flatcc_verify_ok;
}

static inline int PBS_ifl_TmReq_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_TmReq_identifier, &PBS_ifl_TmReq_verify_table);
}

static inline int PBS_ifl_TmReq_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PBS_ifl_TmReq_type_identifier, &PBS_ifl_TmReq_verify_table);
}

static inline int PBS_ifl_TmReq_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PBS_ifl_TmReq_verify_table);
}

static inline int PBS_ifl_TmReq_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PBS_ifl_TmReq_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* PBS_IFL_VERIFIER_H */
